<h1>Datenbestand Bücher &amp; mehr</h1>
<p>Ausführlichere Informationen im <a
			href="http://swissbib-baselbern.blogspot.com/2012/05/bucher-mehr-zwischen-ids-basel-bern-und.html">Blog</a>.
</p>
<h3>Basel</h3>
<ul class="list">
	<li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken">Verbundbibliotheken
			IDS</a></li>
	<li><a href="http://www.fhnw.ch/bibliothek">Fachhochschule Nordwestschweiz</a></li>
</ul>
<h3>Bern</h3>
<ul class="list">
	<li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken">Verbundbibliotheken
			IDS</a></li>
	<li><a href="http://www.nb.admin.ch">Schweizerische Nationalbibliothek</a>
	</li>
	<li><a href="http://www.bewi.unibe.ch">Bibliothek exakte Wissenschaften Bern</a></li>
	<li><a href="http://www.bfh.ch/service/bibliotheken.html">Berner Fachhochschule</a></li>
	<li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries">Schweizerische Nationalbank,
			Bibliothek Bern</a></li>
</ul>

<h3>Volltext online</h3>
<ul class="list">
	<li><a href="http://retro.seals.ch">RetroSeals</a>: <a
				href="http://baselbern.swissbib.ch/TouchPoint/start.do?Language=de&amp;View=bb&amp;Query=1810=%22retros%22 ">über
			200'000 Artikel</a> aus digitalisierten Zeitschriften
	</li>
	<!--
	<li><<a href="http://www.helveticarchives.ch">HelveticArchives</a></li>
	-->
</ul>

<h2>Datenbestand Artikel &amp; mehr</h2>
<ul class="list">
	<li><a href="http://www.oclc.org/worldcatlocal">WorldCat Local</a>, gefiltert auf Artikel und Kapitel.
		<br>Wenn Sie nicht im Netz der Universität Basel oder Bern angemeldet sind, werden Ihnen davon nur die open
		access Inhalte angezeigt.
	</li>
</ul>