<h1>My swissbib</h1>
<h2>Login</h2>
<p>Melden Sie sich mit Ihrer <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis">IDS-Kennung</a> an, die Sie auch bisher bereits für Bestellungen aus dem Katalog benutzen.</p>
<p>Passwort vergessen? Bitte von <a href="http://www.swissbib.ch/libraries/index.html">Ihrer Bibliothek</a> zurücksetzen lassen (Link <i>Bibliotheksinfo</i>).</p>

<!--
<p>Wenn Sie sich anmelden, können Sie eigene <strong>Merklisten</strong> anlegen und Ihre <strong>Sucheinstellungen</strong> speichern.</p>
 
<p><strong>Suchhistorie</strong>
	<br />Wenn Sie angemeldet sind, werden Ihre letzten 50 Abfragen gespeichert. Sie können diese nochmals ausführen oder
	via <i>In die Suche übernehmen</i> mit geänderten Parametern nochmals ausführen.</p>
-->

<h2>Favoriten</h2>
<p>Um eine Bibliothek als Favorit zu markieren, gehen Sie entweder über <i>My swissbib - Favoriten</i> oder
    Sie klicken in einer Aufnahme auf das <img
            src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"
            alt="in meinen Favoriten anzeigen">.
    <!--
	<br />In der Trefferliste sind die Titel dieser Bibliotheken mit einem <img
			src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"> markiert, kommen bei
	der Sortierung nach Relevanz zuoberst und können als Facette ausgewählt werden.
	-->

</p>