<h1>My swissbib</h1>
<h2>Login</h2>
<p>Melden Sie sich mit Ihrer <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis">IDS-Kennung</a> an, die Sie auch bisher bereits für Bestellungen aus dem Katalog benutzen.</p>

<h3>Wozu anmelden?</h3>
<p>Ausleihfunktionen, Favoritbibliotheken, Merklisten, gespeicherte Suchen und gespeicherte Sucheinstellungen stehen Ihnen nur zur Verfügung, wenn Sie sich anmelden.</p>

<h3>Wozu abmelden?</h3>
<p>An öffentlichen Computern sollten Sie sich abmelden, bevor Sie gehen, damit ausser Ihnen niemand Ihr Konto benutzen kann.</p>


<h3>Passwort vergessen?</h3>
<p>Bitte von <a href="http://www.swissbib.ch/libraries/index.html">Ihrer Bibliothek</a> zurücksetzen lassen.</p>


<h2>Favoriten</h2>
<p>Um eine Bibliothek als Favorit zu markieren, gehen Sie entweder über <i>My swissbib - Favoriten</i> oder
    Sie klicken in einer Aufnahme auf das <img
            src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"
            alt="in meinen Favoriten anzeigen">.
    <!--
	<br>In der Trefferliste sind die Titel dieser Bibliotheken mit einem <img
			src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"> markiert, kommen bei
	der Sortierung nach Relevanz zuoberst und können als Facette ausgewählt werden.
	-->

</p>