<h1>Speichern</h1>

<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="in die Merkliste"></td>
		<td>Titel in einer Ihrer <strong>Merklisten</strong> speichern.</td>
	</tr>
		<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>" alt="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"></td>
		<td>Neue Einträge zu Ihrer Suche per <strong>Feed</strong> gemeldet bekommen.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>" alt="Drucken"></td>
		<td>Treffer in verschiedenen Formaten <strong>drucken</strong>.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>" alt="per Email versenden"></td>
		<td>Treffer in verschiedenen Formaten als <strong>Email</strong> versenden.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>" alt="Exportieren nach ..."></td>
		<td>Treffer in verschiedenen Formaten <strong>exportieren</strong>.</td>
	</tr>
	</tbody>
</table>

<h2>Bestellen</h2>
<h3>Bücher &amp; mehr</h3>
<ul class="list">
	<li>Klicken Sie auf den Titel</li>
	<li>Wählen Sie unter <i>Exemplare</i> eine Bibliothek aus</li>
	<li>Klicken Sie <i>Anmelden</i> unter dem Bibliotheksnamen</li>
	<li>Klicken Sie <i>Ausleihen</i>, <i>Buchung</i>, oder <i>Kopie bestellen</i></li>
	<li>Wenn keine der genannten Optionen angezeigt wird, kann das Werk nicht online bestellt werden, z.B. weil es im Freihandbereich steht. Klick auf das <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>" alt="Bibliotheksinformation"> neben der Signatur zeigt Öffnungszeiten und Adresse der Bibliothek.</li>
</ul>
<h3>Artikel &amp; mehr</h3>
<ul class="list">
	<li><i>get it</i> = Link zum Volltext</li>
	<li><img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>" alt="Link zu SFX Services"> = Link zum Volltext, Artikelbestellung, Bestandesnachweis Schweiz</li>
</ul>



