<h1>Speichern</h1>

<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="in die Merkliste"></td>
		<td>Titel aus der Trefferliste in der <strong>Merkliste</strong> speichern, die oben rechts angezeigt
			wird.<br><br>
			Wenn Sie angemeldet sind, können Sie zusätzlich zur temporären Merkliste eigene Merklisten anlegen. Die
			Listen bleiben verfügbar bis zu einem Neuaufbau der Datenbank; Sie sollten sie daher nicht als einziges
			Speichermedium benutzen.<br><br>
			<i>Artikel &amp; mehr:</i> eigene Merklisten funktionieren noch nicht.<br><br></td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>" alt="Einträge lokal speichern"></td>
		<td>Treffer in verschiedenen Formaten als <strong>Datei</strong> speichern.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>" alt="Einträge versenden"></td>
		<td>Treffer in verschiedenen Formaten als <strong>Email</strong> versenden.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>" alt="Einträge drucken"></td>
		<td>Treffer in verschiedenen Formaten <strong>drucken</strong>.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_perma.gif') ?>" alt="Permanenter Link"></td>
		<td>Link <strong>teilen</strong>: facebook, Twitter etc.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>" alt="Atom Feed abonnieren"></td>
		<td>Neue Werke zu einer Suche per <strong>Atom-Feed</strong> gemeldet bekommen.</td>
	</tr>
	</tbody>
</table>

<h2>Bestellen</h2>
<h3>Bücher &amp; mehr</h3>
<ul class="list">
	<li>Klicken Sie auf den Titel</li>
	<li>Wählen Sie unter Bibliotheken eine aus</li>
	<li><i>zum Bestand</i> führt Sie zu den Ausleihfunktionen dieser Bibliothek<br></li>
	<li><i>retro.seals</i> = Link zum Volltext</li>
</ul>
<h3>Artikel &amp; mehr</h3>
<ul class="list">
	<li><i>get it</i> = Link zum Volltext</li>
	<li><i>get it - sfx</i> = Link zum Volltext, Artikelbestellung, Bestandesnachweis Schweiz</li>
</ul>



