<h1>Speichern</h1>

<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="in die Merkliste"></td>
		<td>Titel aus der Trefferliste auf einer <strong>Merkliste</strong> speichern.<br /><br />
			Sie können mehrere Merklisten anlegen, ein Titel kann auf mehr als einer Merkliste gespeichert sein, jede Merkliste kann als öffentlich oder als privat definiert sein [Präziserer Hilfetext folgt.]</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>" alt="Einträge lokal speichern"></td>
		<td>Treffer in verschiedenen Formaten <strong>exportieren</strong>.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>" alt="Einträge versenden"></td>
		<td>Link auf Treffer als <strong>Email</strong> versenden.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>" alt="Einträge drucken"></td>
		<td>Treffer <strong>drucken</strong>.</td>
	</tr>
	
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>" alt="Atom Feed abonnieren"></td>
		<td>Neue Werke zu einer Suche per <strong>Feed</strong> gemeldet bekommen.</td>
	</tr>
	</tbody>
</table>

<h2>Bestellen</h2>
<h3>Bücher &amp; mehr</h3>
<ul class="list">
	<li>Klicken Sie auf <strong>ausleihen</strong></li>
	<li>[Präziserer Hilfetext folgt.]</li>
	<li><i>retro.seals</i> = Link zum Volltext</li>
</ul>
<h3>Artikel &amp; mehr</h3>
<ul class="list">
	<li><i>get it</i> = Link zum Volltext</li>
	<li><i>sfx</i> = Link zum Volltext, Artikelbestellung, Bestandesnachweis Schweiz</li>
</ul>



