<h1>Suche</h1>

<h3>Kombinieren</h3>
<p>AND, OR, NOT. Bsp.: <i>art* OR kunst*</i>
    <br>Die Operatoren müssen in Grossbuchstaben geschrieben werden, Default ist AND
</p>

<h3>Phrasensuche mit Anführungszeichen</h3>
<p>
    <i>"street art"</i> = die beiden Wörter müssen direkt hintereinander stehen
    <br><i>"street art"~5</i> = die beiden Wörter müssen innerhalb von 5 Wörtern Abstand vorkommen</p>
<p>Anführungszeichen ebenfalls benutzen für:
    <br>- ISBN, ISSN
    <br>- Bindestrich-Wortkombinationen
</p>

<h3>Suche mit Platzhaltern, innerhalb oder am Ende eines Wortes</h3>
<table>
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">ersetzt beliebig viele Zeichen</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>


    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">ersetzt genau ein Zeichen</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc. **</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist etc. **</td>
    </tr>



    <tr>
        <td>~</td>
        <td>wenn Sie die genaue Schreibweise nicht kennen</td>
        <td><i>Copenhagen~</i></td>
        <td>Copenhagen, København, Kopenhagen etc. **</td>
    </tr>
    </tbody>

</table>


<h3>Bereichssuche **</h3>
<p><i>Wetter [2010 TO 2013]</i>
    <br>
    <br>** nur für <i>Bücher & mehr</i>
</p>

<h2>Zu viel gefunden?</h2>
<p>Benutzen Sie die Facetten in der linken Spalte und/oder die <a href="../vufind/Search/Advanced">erweiterte Suche.</a></p>

<h2>Zu wenig gefunden?</h2>
<ul class="list">
    <li>Klick auf <i>Artikel & mehr</i> führt Ihre Suche im Bestand von <a href="http://www.serialssolutions.com/en/services/summon/content">Summon</a> aus.</li>
    <li><a href="http://www.swissbib.ch">swissbib.ch</a> Metakatalog der Schweizer Hochschulbibliotheken und der Schweizerischen Nationalbibliothek</li>
    <li>Wenden Sie sich an die Info/Fernleihe <a href="http://www.swissbib.ch/libraries/index.html">Ihrer Bibliothek.</a></li>
</ul>

<h2>Sie wissen nicht, wo anfangen?</h2>
<ul class="list">
    <li>
        Klicken Sie auf <i>Suchen</i>, ohne einen Suchbegriff einzugeben und benutzen Sie die Facetten, um die Resultate zu filtern.
    </li>
</ul>
 