<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?=$this->layout()->userLang?>" xml:lang="en">
	<head>
		<?=$this->partial('global/head.phtml')?>
	</head>
	<body>
		<div class="page_margins">
			<div class="page <?=(isset($pageClass)?$pageClass:'')?>">
				<?=$this->render('global/header.phtml')?>
				<?=$this->render('global/searchbox.phtml')?>
				<div id="main">
					<?=$this->layout()->content?>
				</div>
			</div>
		</div>
        <?=$this->render('global/footer.phtml')?>
	</body>
</html>
