<?php $this->headThemeResources(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?=$this->partial('global/head.phtml')?>
	</head>
	<body>
		<div class="page_margins">
			<div class="page <?=(isset($pageClass)?$pageClass:'')?>">
				<?=$this->render('global/header.phtml')?>
				<?=$this->render('global/searchbox.phtml')?>
				<div id="main">
					<?=$this->layout()->content?>
				</div>
			</div>
		</div>
		<div class="footer buildnum"><?=$this->latestGitTag()?></div>
	</body>
</html>