<?php $this->headThemeResources(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?=$this->partial('global/head.phtml')?>
	</head>
	<body>
		<!-- begin: page -->
		<div class="page_margins">
			<div class="page template_home">
				<!-- begin: header -->
				<?=$this->partial('global/header.phtml')?>
				<!-- end: header -->
				<!-- begin: search -->
				<?=$this->partial('global/searchbox.phtml')?>
				<!-- end: search -->
				<!-- begin: main  -->
				<div id="main">
					<!-- begin: col3 (content) -->
					<?=$this->layout()->content?>
					<!-- end: col3 (content) -->
				</div>
				<!-- end: main -->
			</div>
		</div>
		<!-- end: page -->
	</body>
</html>