

<?= $this->ScriptMarker()->headline("keyNavigation.phtml", true)?>
      <div id="access" class="hidden">
        <h3>Sprungnavigation</h3>
        <ul>
          <li><a accesskey="0" title="Startseite" href="#">zur Zeit nicht benutzt</a></li>
          <li><a accesskey="1" title="Navigation" href="#">zur Zeit nicht benutzt</a></li>
        </ul>
      </div>

<?= $this->ScriptMarker()->footline("keyNavigation.phtml", true)?>
