<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $basicSearch = $options->getSearchAction();
    $searchHome = $basicSearch;
    $searchHome['action'] = 'Home';
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>

<div id="search">

<form method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="AdvancedSearchForm" class="search">

  <h3><label for="searchForm_lookfor">Suchen nach</label></h3>


    <input id="searchForm_lookfor" type="text" name="lookfor" size="40" class="text" value=""/>
    <select name="searchForm_libraries" size="1" id="selectNetworks" class="select dropdown">
        <option value="">alle Bibliotheken</option>
        <option value="17">IDS - Informationsverbund Deutschschweiz</option>
        <option value="18">RERO - Westschweizer Bibliotheken</option>
        <option value="20">Nationalbibliothek</option>
        <option value="21">IDS Basel/Bern</option>
        <option value="22">NEBIS</option>
        <option value="23">IDS Zürich Universität</option>
        <option value="24">IDS Luzern</option>
        <option value="25">IDS St. Gallen</option>
        <option value="26">RERO Genève</option>
        <option value="27">RERO Vaud</option>
        <option value="28">RERO Fribourg</option>
        <option value="29">RERO Neuchâtel/Jura</option>
        <option value="30">RERO Wallis</option>
        <option value="31">Bundesinstitutionen</option>
        <option value="32">St. Galler Bibliotheksnetz</option>
        <option value="19">Sistema Bibliotecario Ticinese</option>
        <option value="33">Bibliotheken Graubünden</option>
        <option value="41">Aargauer Bibliotheksnetz</option>
        <option value="34">Schweizer Plakatsammlung</option>
        <option value="35">Helvetic Archives</option>
        <option value="36">RetroSEALS</option>
        <option value="37">ZORA</option>
        <option value="38">swissbib Zürich</option>
    </select>
  <input type="submit"  class="submit primary" name="submit" value="<?=$this->transEsc("Suchen")?>"/>


    <? if ($advSearch): ?>
        <a  id="search_extended" title="Erweiterte Suche"  href="<?=$this->url($advSearch)?>" class="small">Erweiterte Suche</a>
    <? endif; ?>

</form>
<script type="text/javascript">$("#searchForm_lookfor").focus()</script>

</div>