<?
// Set page title.
//$this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

// Grab clean ISBN for convenience:
//$isbn = $this->driver->getCleanISBN();

// Activate Syndetics Plus if necessary:
//if ($this->syndeticsPlus()->isActive()) {
//    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
//}


/** @var    VuFind\View\Helper\Root\Record $viewRecord */
/** @var    Swissbib\RecordDriver\SolrMarc $resultItem */
$resultItem = $this->driver;
$viewRecord = $this->record($resultItem);


$subjectVocabularies = $resultItem->getAllSubjectVocabularies(true);

/* Display Standard-IDs */
$isbns  = $this->driver->getISBNs();
$issns  = $this->driver->getISSNs();
$ismns  = $this->driver->getISMNs();
$dois   = $this->driver->getDOIs();
$urns   = $this->driver->getURNs();

?>
    <!-- Tab-Inhalte gemaess TP detailstab -->

<?
$series = $this->driver->getSeries();
$recordLinks = $this->driver->getAllRecordLinks();
?>

<? if (!empty($isbns) or !empty($issns) or !empty($ismns) or !empty($dois) or !empty($urns)): ?>
    <? $contentDisplayed = true; ?>
    <div class="details">
        <? if (!empty($isbns)): ?>
            <h4><?= $this->transEsc('ISBN') ?>: </h4>
            <p>
                <? foreach ($isbns as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? if (!empty($issns)): ?>
            <h4><?= $this->transEsc('ISSN') ?>: </h4>
            <p>
                <? foreach ($issns as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? if (!empty($ismns)): ?>
            <h4><?= $this->transEsc('ISMN') ?>: </h4>
            <p>
                <? foreach ($ismns as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? if (!empty($dois)): ?>
            <h4><?= $this->transEsc('DOI') ?>: </h4>
            <p>
                <? foreach ($dois as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? if (!empty($urns)): ?>
            <h4><?= $this->transEsc('URN') ?>: </h4>
            <p>
                <? foreach ($urns as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
    </div>
<? endif; ?>

<? /* Display alternative title */ ?>
<? $alttitle = $this->driver->getAltTitle();
if (!empty($alttitle)): ?>
    <div class="details">
        <h4><?= $this->transEsc('Other_Title') ?>: </h4>
        <p>
            <? foreach ($alttitle as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
        </p>
    </div>
<? endif; ?>

<? /* Display series section if at least one series exists. */ ?>
<? $series = $this->driver->getSeries();
if (!empty($series)): ?>
    <div class="details">
        <h4><?= $this->transEsc('Series') ?>: </h4>
        <? foreach ($series as $field): ?>
            <? if (is_array($field)): ?>
                <? if (!empty($field['name'])): ?>
                    <p><?= $this->escapeHtml($field['name']) ?>
                        <? if (!empty($field['number'])): ?>
                            <?= $this->escapeHtml($field['number']) ?>
                        <? endif; ?>
                        <br/>
                    </p>
                <? endif; ?>
            <? else: ?>
                <p>
                    <?= $this->escapeHtml($field) ?> <br/>
                </p>
            <? endif; ?>
        <? endforeach; ?>
    </div>
<? endif; ?>

<? /* Display and link to related items (field configured in config_base.ini -> marc_links) */ ?>
<? $recordLinks = $this->driver->getAllRecordLinks(); ?>
<? if (!empty($recordLinks)): ?>
    <? $contentDisplayed = true; ?>
    <div class="details">
        <h4><?= $this->transEsc('Related Items') ?></h4>

        <p>
            <? foreach ($recordLinks as $recordLink): ?>
                <?= $this->transEsc($recordLink['title']) ?>:
                <a href="<?= $this->recordLink()->related($recordLink['link']) ?>"><?= $this->escapeHtml($recordLink['value']) ?></a>
                <br/>
            <? endforeach; ?>
        </p>
    </div>
<? endif; ?>

<? /* This section is only valid when the above links do not exist */ ?>
<? $nextTitles = $this->driver->getNewerTitles();
$prevTitles = $this->driver->getPreviousTitles(); ?>
<? if (!empty($nextTitles) or !empty($prevTitles)): ?>
    <div class="details">
        <? if (!empty($nextTitles)): ?>
            <h4><?= $this->transEsc('New Title') ?>: </h4>
            <p>
                <? foreach ($nextTitles as $field): ?>
                    <a href="<?= $this->record($this->driver)->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                    <br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? if (!empty($prevTitles)): ?>
            <h4><?= $this->transEsc('Previous Title') ?>: </h4>
            <p>
                <? foreach ($prevTitles as $field): ?>
                    <a href="<?= $this->record($this->driver)->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                    <br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
    </div>
<? endif; ?>

<? /* div-box for all notes */ ?>

<?
$notes      = $resultItem->getGeneralNotes();
$freq       = $resultItem->getPublicationFrequency();
$contDates  = $resultItem->getContResourceDates();
$diss       = $resultItem->getDissertationNotes();
$bib        = $resultItem->getBibliographyNotes();
$access     = $resultItem->getAccessRestrictions();
$credits    = $resultItem->getProductionCredits();
$origtitle  = $resultItem->getOriginalTitle();
$perfomer   = $resultItem->getPerformerNote();
$awards     = $resultItem->getAwards();
$citenotes  = $resultItem->getCitationNotes();
$orignotes  = $resultItem->getOriginalVersionNotes();
$copynotes  = $resultItem->getCopyNotes();
$system     = $resultItem->getSystemDetails();
?>
<? if (!empty($notes) or !empty($freq) or !empty($contDates) or !empty($diss) or
    !empty($bib) or !empty($access) or !empty($credits) or !empty($awards) or
    !empty($citenotes) or !empty($orignotes) or !empty($copynotes) or
    !empty($origtitle) or !empty($perfomer) or !empty($system)
): ?>
    <? $contentDisplayed = true; ?>
    <div class="details">
        <? /* Display general notes (field 500) */ ?>
        <? if (!empty($notes)): ?>
            <h4><?= $this->transEsc('Item Description') ?>: </h4>
            <p>
                <? foreach ($notes as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>

        <? /* Display publication frequency (field 310) */ ?>
        <? if (!empty($freq)): ?>
            <h4><?= $this->transEsc('Publication Frequency') ?>: </h4>
            <p>
                <? foreach ($freq as $field): ?>
                    <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>

        <? /* Display Dates of Publication and/or Sequential Designation (field 362) */ ?>
        <? if (!empty($contDates)): ?>
            <h4><?= $this->transEsc('Numeration') ?>: </h4>
            <p>
                <? foreach ($contDates as $field): ?>
                    <?= $this->escapeHtml($field)?><br>
                <? endforeach; ?>
            </p>
        <? endif; ?>

        <? /* Display dissertation notes (field 502) */ ?>
        <? if (!empty($diss)): ?>
            <h4><?= $this->transEsc('Dissertation_Note') ?>: </h4>
            <p>
                <? foreach ($diss as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display bibliography notes (field 504) */ ?>
        <? if (!empty($bib)): ?>
            <h4><?= $this->transEsc('Bibliography') ?>: </h4>
            <p>
                <? foreach ($bib as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display access restriction notes (field 506) */ ?>
        <? if (!empty($access)): ?>
            <h4><?= $this->transEsc('Access') ?>: </h4>
            <p>
                <? foreach ($access as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display production credit notes (field 508) */ ?>
        <? if (!empty($credits)): ?>
            <h4><?= $this->transEsc('Production Credits') ?>: </h4>
            <p>
                <? foreach ($credits as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display original title (field 509) */ ?>
        <? if (!empty($origtitle)): ?>
            <h4><?= $this->transEsc('Original_Title') ?>: </h4>
            <p>
                <? foreach ($origtitle as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display citation / reference note (field 510) */ ?>
        <? if (!empty($citenotes)): ?>
            <h4><?= $this->transEsc('Citation_Note') ?>: </h4>
            <p>
                <? foreach ($citenotes as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display participant / performers note */ ?>
        <? if (!empty($perfomer)): ?>
            <h4><?= $this->transEsc('Performer') ?>: </h4>
            <p>
                <? foreach ($perfomer as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display original version note (field 534) */ ?>
        <? if (!empty($orignotes)): ?>
            <h4><?= $this->transEsc('Original_Version_Note') ?>: </h4>
            <p>
                <? foreach ($orignotes as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display copy and version identification note (fields 562 or 590) */ ?>
        <? if (!empty($copynotes)): ?>
            <h4><?= $this->transEsc('Copy_Note') ?>: </h4>
            <p>
                <? foreach ($copynotes as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display system information note (field 538) */ ?>
        <? if (!empty($system)): ?>
            <h4><?= $this->transEsc('Format') ?>: </h4>
            <p>
                <? foreach ($system as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
        <? /* Display award notes (field 586) */ ?>
        <? if (!empty($awards)): ?>
            <h4><?= $this->transEsc('Awards') ?>: </h4>
            <p>
                <? foreach ($awards as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </p>
        <? endif; ?>
    </div>
<? endif; ?>


<?
/** ==Subject Headings== */
?>
<? if (sizeof($subjectVocabularies)): ?>
    <div class="subjectVocabularies">
        <h4><?= $this->transEsc('Subjects') ?>: </h4>
        <? foreach ($subjectVocabularies as $vocabulary => $fieldsData): ?>
            <h4 class="vocabularyTitle"><?= $this->transEsc('vocabulary.' . $vocabulary, array(), $vocabulary) ?></h4>
            <ul class="vocabularyList vocabulary<?= ucfirst($vocabulary) ?>">
                <? foreach ($fieldsData as $fieldIndex => $fieldData): ?>
                    <? foreach ($fieldData as $fieldValues): ?>
<?
//								// Optional: Filter out numeric fields directly here in template
//							$fieldValues = array_filter($fieldValues, function($value) {
//																			return !is_numeric($value);
//																		});
                        ?>
                        <li class="type<?= $fieldIndex ?>"><?= $this->escapeHtml(implode(' > ', $fieldValues)) ?></li>
                    <? endforeach; ?>
                <? endforeach; ?>
            </ul>
        <? endforeach; ?>
    </div>
<? endif; ?>