<?
	// Set page title.
$this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

// Grab clean ISBN for convenience:
$isbn = $this->driver->getCleanISBN();

// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

?>


<!-- Tab-Inhalte gemaess TP detailstab -->

<h1>hallo</h1>


<h4>Alternativtitel</h4>
<p>hier 240 etc.</p>

<h4>Reihe</h4>
<p>490 etc.</p>

<h4>diverse 500</h4>
<p>diverse 500</p>

    <? $subjectHeadings = $this->driver->getAllSubjectHeadings(true) ?>
    <? if (sizeof($subjectHeadings) > 0) :?>
    <? foreach ($subjectHeadings as $heading): ?>
        <? if ($heading['@ind2'] === '0') :?>
        <h4>LCSH</h4>
        <p><?=$this->escapeHtml($heading['600a'])?></p>
        <? endif; ?>
        <? if ($topic['@ind2'] === '7' && $topic['6500'] === 'gnd') :?>
        <h4>GND-Schlagworte</h4>
        <p><?=$this->escapeHtml($topic['6500'])?></p>
        <? endif; ?>
    <? endforeach; ?>
    <? endif; ?>

<? $topics = $this->driver->getTopicalTerms() ?>
<? if (sizeof($topics) > 0) :?>
<? foreach ($topics as $topic): ?>
    <? if ($topic['@ind2'] === '7' && $topic['source_heading'] === 'gnd') :?>
        <h4>GND-Schlagworte</h4>
        <p><?=$this->escapeHtml($topic['a'])?>, <?=$this->escapeHtml($topic['authority_record_control_numer'][0])?></p>
        <? endif; ?>
    <? endforeach; ?>
<? endif; ?>


