<?php
// Set page title.
$this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

// Grab clean ISBN for convenience:
$isbn = $this->driver->getCleanISBN();

// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

$resultItem	= $this->driver;
$subjectVocabularies	= $resultItem->getAllSubjectVocabularies();
$subjects = $this->driver->getAllSubjectHeadings();
?>


<!-- Tab-Inhalte gemaess TP detailstab -->

<?/* Display ISBN */?>
<? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('ISBN')?>: </h4>
    <p>
        <? foreach ($isbns as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<?/* Display ISSN */?>
<? $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('ISSN')?>: </h4>
    <p>
        <? foreach ($issns as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<?/* Display ISMN */?>
<? $ismns = $this->driver->getISMNs(); if (!empty($ismns)): ?>
<? $contentDisplayed = true; ?>
<h4><?=$this->transEsc('ISMN')?>: </h4>
<p>
    <? foreach ($ismns as $field): ?>
    <?=$this->escapeHtml($field)?><br />
    <? endforeach; ?>
</p>
<? endif; ?>

<?/* Display DOI */?>
<? $dois = $this->driver->getDOIs(); if (!empty($dois)): ?>
<? $contentDisplayed = true; ?>
<h4><?=$this->transEsc('DOI')?>: </h4>
<p>
    <? foreach ($dois as $field): ?>
    <?=$this->escapeHtml($field)?><br />
    <? endforeach; ?>
</p>
<? endif; ?>

<?/* Display URN */?>
<? $urns = $this->driver->getURNs(); if (!empty($urns)): ?>
<? $contentDisplayed = true; ?>
<h4><?=$this->transEsc('URN')?>: </h4>
<p>
    <? foreach ($urns as $field): ?>
    <?=$this->escapeHtml($field)?><br />
    <? endforeach; ?>
</p>
<? endif; ?>

<?/* Display alternative title */?>
<? $alttitle = $this->driver->getAltTitle(); if (!empty($alttitle)): ?>
    <h4><?=$this->transEsc('Other_Title')?></h4>
    <p>
        <? foreach ($alttitle as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<?/* Display series section if at least one series exists. */?>
<? $series = $this->driver->getSeries(); if (!empty($series)): ?>
    <h4><?=$this->transEsc('Series')?>: </h4>
        <? foreach ($series as $field): ?>
        <? if (is_array($field)): ?>
            <? if (!empty($field['name'])): ?>
                <p><?=$this->escapeHtml($field['name'])?>
                    <? if (!empty($field['number'])): ?>
                        <?=$this->escapeHtml($field['number'])?>
                    <? endif; ?>
                    <br />
                </p>
            <? endif; ?>
            <? else: ?>
            <p>
                <?=$this->escapeHtml($field)?> <br />
            </p>
        <? endif; ?>
        <? endforeach; ?>
<? endif; ?>

<? $notes = $this->driver->getGeneralNotes(); if (!empty($notes)): ?>
    <h4><?=$this->transEsc('Item Description')?>: </h4>
    <p>
        <? foreach ($notes as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<?php endif; ?>

<? $awards = $this->driver->getAwards(); if (!empty($awards)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('Awards')?>: </h4>
    <p>
        <? foreach ($awards as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<? $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('Production Credits')?>: </h4>
    <p>
        <? foreach ($credits as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<? $bib = $this->driver->getBibliographyNotes(); if (!empty($bib)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('Bibliography')?>: </h4>
    <p>
        <? foreach ($bib as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<? $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
<? $contentDisplayed = true; ?>
    <h4><?=$this->transEsc('Access')?>: </h4>
    <p>
        <? foreach ($access as $field): ?>
        <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
    </p>
<? endif; ?>

<?php if(sizeof($subjectVocabularies)): ?>
    <?=$this->subjectVocabularies($subjectVocabularies)?>
<?php endif; ?>

<? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>

<h4><?=$this->transEsc('Subjects')?>: </h4>
<? foreach ($subjects as $field): ?>
    <? $subject = ''; ?>
    <p>
    <? $i = 0; foreach ($field as $subfield): ?>
            <?=($i++ == 0) ? '' : ' &gt; '?>
        <? $subject = trim($subject . ' ' . $subfield); ?>
        <?=$this->escapeHtml($subfield)?>
        <? endforeach; ?>
    </p>
    <? endforeach; ?>

<? endif; ?>
