<?
// Set page title.
//$this->headTitle($this->translate('Series') . ': ' . $this->driver->getBreadcrumb());
$hierarchyTreeList = $this->tab->getTreeList();
$activeTree = $this->tab->getActiveTree();

$this->inlineScript(
    \Zend\View\Helper\HeadScript::SCRIPT,
    "var hierarchySettings = {\n"
    . "    lightboxMode: " . ($this->layout()->getTemplate() == 'layout/lightbox' ? 'true' : 'false') . ",\n"
    . "    fullHierarchy: " . ($this->tab->isFullHierarchyVisible() ? 'true' : 'false') . "\n"
    . "};\n"
    . "vufindString.showTree = \"" . $this->transEsc('hierarchy_show_tree') . "\";\n"
    . "vufindString.hideTree = \"" . $this->transEsc('hierarchy_hide_tree') . "\";\n"
);
$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'jsTree/jquery.jstree.js');
$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'hierarchyTree_JSTree.js');
echo $this->inlineScript();
?>
<div<?= isset($this->mainTreeClass) ? ' class="' . $this->mainTreeClass . '"' : '' ?>>
    <? if (count($hierarchyTreeList) > 1): ?>
        <div id="treeSelector">
            <? foreach ($hierarchyTreeList as $hierarchy => $hierarchyTitle): ?>
                <a class="tree<?= ($activeTree == $hierarchy) ? ' currentTree' : '' ?>" href="<?= $this->recordLink()->getTabUrl($this->driver, 'HierarchyTree') ?>?hierarchy=<?= urlencode($hierarchy) ?>"><?= $this->escapeHtml($hierarchyTitle) ?></a>
            <? endforeach; ?>
        </div>
    <? endif; ?>
    <? if ($activeTree): ?>
        <div id="hierarchyTreeHolder">

            <div id="hierarchyTree">
                <input type="hidden" value="<?= $this->escapeHtml($this->driver->getUniqueId()) ?>" class="hiddenRecordId"/>
                <input type="hidden" value="<?= $this->escapeHtml($activeTree) ?>" class="hiddenHierarchyId"/>
                <input type="hidden" value="<?= isset($this->treeContext) ? $this->treeContext : 'Record' ?>" class="hiddenContext"/>
                <? if ($this->layout()->getTemplate() != 'layout/lightbox'): ?>
                    <noscript>
                        <?php
                        /** We don't want to render the tree while loading the page */
                        /** $this->tab->renderTree($this->url('home'))*/
                        ?>
                    </noscript>
                <? endif; ?>
            </div>
            <?php /** Dummy input to prevent js error when record itself is missing in tree because of limitation */ ?>
            <input type="hidden" class="jsTreeID" value="<?= $this->escapeHtml($this->driver->getUniqueId()) ?>"/>
            <script>
                /** Make sure to open the root node in case not opened because record is missing */
                $("#hierarchyTree").bind("loaded.jstree", function () {
                    setTimeout(function () {
                        $("#hierarchyTree").find('li').eq(0).removeClass("jstree-closed").addClass("jstree-open");
                    }, 100);
                });
            </script>
        </div>
    <? endif; ?>
</div>
