<?php

/** @var	 VuFind\Auth\Manager	$account  */
$account		= $this->auth()->getManager();
/** @var	Boolean|Object			$user  */
$user			= $account->isLoggedIn();
$holdings		= $this->driver->getRealTimeHoldings($account);
/** @var	VuFind\ILS\Connection	$ilsConnection  */
$ilsConnection	= $this->ils();


////var_dump($holdings);
//var_dump(\VuFind\ILS\Connection::getHoldsMode());
////var_dump($ilsConnection->getDriver());
//exit();

?>
<!-- begin: innerbox meine bibliotheken -->
<div class="innerbox grey">
	<h3 class="toggler persist collapsed" id="library_toggler_meine-bibliotheken"><span class="icon_favorit_library">Meine Bibliotheken</span></h3>
	<div class="library_toggler_meine-bibliotheken">

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Historisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_meine-bibliotheken_historisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_remove">
					<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://aleph.unibas.ch" class="externallink" title="Historisches Seminar">http://aleph.unibas.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_meine-bibliotheken_historisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

	</div>
</div><!-- end: innerbox meine bibliotheken -->

<!-- begin: innerbox basel -->
<div class="innerbox grey">
	<h3 class="toggler persist collapsed" id="library_toggler_ids-basel">IDS Basel / Bern</h3>
	<div class="library_toggler_ids-basel">

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Historisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_historisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_remove">
					<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Historisches Seminar">http://aleph.unibas.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-basel_historisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Altägyptisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_aegyptisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_add">
					<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Altägyptisches Seminar">http://aleph.unibas.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-basel_aegyptisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Slavisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_slavisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_add">
					<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Slavisches Seminar">http://aleph.unibas.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-basel_slavisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

	</div>
</div><!-- end: innerbox basel -->

<!-- begin: innerbox basel -->
<div class="innerbox grey">
	<h3 class="toggler persist collapsed" id="library_toggler_ids-zurich">IDS Zürich Universität</h3>
	<div class="library_toggler_ids-zurich">

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Historisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_historisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_add">
					<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Historisches Seminar">http://biblio.unizh.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-zurich_historisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Altägyptisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_aegyptisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_add">
					<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Altägyptisches Seminar">http://biblio.unizh.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-zurich_aegyptisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Slavisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_slavisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_add">
					<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Slavisches Seminar">http://biblio.unizh.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_ids-zurich_slavisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

	</div>
</div>
<!-- end: innerbox basel -->


<?php return; ?>








<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings($account);
    $openUrl = $this->driver->openURLActive('holdings') ? $this->driver->getOpenURL() : false;
    $offlineMode = $this->ils()->getOfflineMode();
    // Account for replace_other_urls setting
    $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if ((\VuFind\ILS\Connection::getHoldsMode() == 'driver' && !empty($holdings)) || \VuFind\ILS\Connection::getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="info">
        <a href="<?=$this->currentPath()?>?login=true&catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->currentPath() . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold', array($account)); if (!empty($holdingTitleHold)): ?>
    <a class="holdPlace" href="<?=$this->recordLink()->getHoldUrl($holdingTitleHold)?>"><?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrl): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrl): ?><?=$this->openUrl($openUrl);?><? endif; ?>
<? endif; ?>
<? foreach ($holdings as $location => $holding): ?>
<h3><?=$this->transEsc($location)?></h3>
<table cellpadding="2" cellspacing="0" border="0" class="citation" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($location)?>">
  <? if (isset($holding['items'][0]['callnumber'])): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td><?=$this->escapeHtml($holding['items'][0]['callnumber'])?></td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['summary'])): ?>
  <tr>
    <th><?=$this->transEsc("Volume Holdings")?>: </th>
    <td>
      <? foreach ($holding['summary'] as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['notes'])): ?>
  <tr>
    <th><?=$this->transEsc("Notes")?>: </th>
    <td>
      <? foreach ($holding['notes'] as $data): ?>
        <?=$this->escapeHtml($data)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? foreach ($holding['items'] as $row): ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr>
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
          <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?>
          <? elseif (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="unknown"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
              <div>
               <span class="available"><?=$this->transEsc("Available")?></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'])?>"><span><?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></span></a>
              <? endif; ?>
              </div>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <div>
              <span class="checkedout"><?=$this->transEsc($row['status'])?></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?> <span class="statusExtra"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                <span class="statusExtra"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'])?>"><span><?=$this->transEsc($check ? "Check Recall" : "Recall This")?></span></a>
              <? endif; ?>
              </div>
            <? endif; ?>
          <? endif; ?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>