<?php

/** @var	 VuFind\Auth\Manager	$account  */
//$account		= $this->auth()->getManager();

/** @var	Boolean|Object			$user  */
//$user			= $account->isLoggedIn();
//$holdings		= $this->driver->getRealTimeHoldings($account);

/** @var	VuFind\ILS\Connection	$ilsConnection  */
//$ilsConnection	= $this->ils();

/** @var	Swissbib\RecordDriver\SolrMarc	$recordDriver  */
$recordDriver	= $this->driver;
$holdings		= $recordDriver->getHoldings();

?>

<?= $this->render('RecordTab\mylibraries.phtml') ?>

<?php foreach($holdings as $networkCode => $network): ?>
	<!-- begin: innerbox <?=$networkCode?> -->
	<div class="innerbox grey">
		<?php
			$expandLib	= isset($_GET['expandlib']) ? $_GET['expandlib'] : '';
			$expandedOrCollapsedClass = 'collapsed';
			$expandOnLoad = '';
			if( array_key_exists('institutions', $network) && count($network['institutions']) > 0 ) {
				foreach($network['institutions'] as $institutionSysCode => $institution) {
					if ($institutionSysCode == $expandLib) {
						$expandedOrCollapsedClass	= 'expanded';
						$expandOnLoad= $networkCode;
					}
				}
			}
		?>

		<? if($expandOnLoad != ''): ?>
<script type="text/javascript">
		// On DOM-ready: expand selected library even if it's collapsed via cookie
	$(document).ready(function() {
		var elItem	= $('.toggler#library_toggler_<?= $expandOnLoad ?>')['0'];
		var cname	= "toggler_" + jQuery(elItem).attr("id");
		cname 		= encodeURI(cname);
		if(jQuery.cookie(cname)) {
			if(jQuery.cookie(cname) != "expanded") {
				expandedLibItem.click();
			}
		}
	});
</script>
		<? endif; ?>

		<h3 class="toggler persist <?= $expandedOrCollapsedClass ?>" id="library_toggler_<?=$networkCode?>">
			<?=$this->escapeHtml($network['label']) /*IDS Basel / Bern*/ ?>
		</h3>
		<div class="library_toggler_<?=$networkCode?>">

			<div class="innerbox">
				<?php foreach($network['institutions'] as $institutionCode => $institution): ?>
					<h4><?=$this->escapeHtml($institution['label'])?></h4>
					<ul class="actions">
						<li>
							<a href="<?=$this->escapeHtml($institution['backlink'])?>" class="linkbutton primary icon_link_primary" title="Zum Bestand" target="_blank"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_<?=$networkCode?>_<?=$institutionCode?>">
								<span>Informationen zum Bestand</span>
							</a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_remove">
							<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
						</li>
						<li class="miniaction_link">
							<a href="<?=$this->escapeHtml($network['link'])?>" class="externallink" title="Bibliothek Historisches Seminar"><?=$this->escapeHtml($network['link'])?></a>
						</li>
					</ul>

					<div class="stock_toggler_<?=$networkCode?>_<?=$institutionCode?>">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Beschreibung</th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
								<?php
										// Items
									if( isset($institution['items'])) {
										foreach($institution['items'] as $item) {
											echo $this->render('record/holdingsils_item.phtml', array(
												'item'	=> $item
											));
										}
									}

										// Holdings
									if( isset($institution['holdings'])) {
										foreach($institution['holdings'] as $holding) {
											echo $this->render('record/holdingsils_holding.phtml', array(
												'holding'	=> $holding
											));
										}
									}
								?>
							</tbody>
						</table>
					</div>
				<?php endforeach; ?>

			</div>
		</div>
	</div>
	<!-- end: innerbox <?=$networkCode?> -->

<?php endforeach; ?>