<?php

/** @var	Swissbib\RecordDriver\SolrMarc	$recordDriver  */
$recordDriver	= $this->driver;
$holdings		= $recordDriver->getHoldings();

?>

<?= $this->render('RecordTab/mylibraries.phtml') ?>

<?php foreach($holdings as $groupCode => $group): ?>
	<!-- begin: innerbox <?=$groupCode?> -->
	<div class="innerbox grey">
		<?php
			$expandLib	= isset($_GET['expandlib']) ? $_GET['expandlib'] : '';
			$expandedOrCollapsedClass = 'collapsed';
			$expandOnLoad = '';
			if (isset($group['institutions']) && sizeof($group['institutions'])) {
				foreach($group['institutions'] as $institutionSysCode => $institution) {
					if ($institutionSysCode == $expandLib) {
						$expandedOrCollapsedClass	= 'expanded';
						$expandOnLoad= $groupCode;
					}
				}
			}
		?>

		<? if($expandOnLoad != ''): ?>
			<script type="text/javascript">
					// On DOM-ready: expand selected library even if it's collapsed via cookie
				$(document).ready(function() {
					var elItem	= $('.toggler#library_toggler_<?= $expandOnLoad ?>')['0'];
					var cname	= "toggler_" + jQuery(elItem).attr("id");
					cname 		= encodeURI(cname);
					if(jQuery.cookie(cname)) {
						if(jQuery.cookie(cname) != "expanded") {
							expandedLibItem.click();
						}
					}
				});
			</script>
		<? endif; ?>

		<h3 class="toggler persist <?= $expandedOrCollapsedClass ?>" id="library_toggler_<?=$groupCode?>">
			<?=$this->zendTranslate($group['label'], 'group')?>
		</h3>
		<div class="library_toggler_<?=$groupCode?>">

			<div class="innerbox">
				<?php foreach($group['institutions'] as $institutionCode => $institution): ?>
					<h4>
						<?=$this->escapeHtml($this->zendTranslate($institution['label'], 'institution'))?>
					</h4>

					<ul class="actions">
						<?php if (isset($institution['backlink'])): ?>
						<li>
							<a href="<?=$this->escapeHtml($institution['backlink'])?>" class="linkbutton primary icon_link_primary" title="Zum Bestand" target="_blank">
								<span>Zum Bestand</span>
							</a>
						</li>
						<?php else: ?>
							<li>Kein Institutions-Backlink.</li>
						<?php endif; ?>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_<?=$groupCode?>_<?=$institutionCode?>">
								<span>Informationen zum Bestand</span>
							</a>
						</li>
					</ul>
<!--					<ul class="miniactions boxed">-->
					<ul class="miniactions">
						<li class="miniaction_favorite_remove">
							<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
						</li>
						<?php if (isset($institution['bibinfolink']) && $institution['bibinfolink']): ?>
							<li class="miniaction_link">
								<a href="<?=$this->escapeHtml($institution['bibinfolink']['url'])?>" class="externallink" title="<?=$this->escapeHtml($this->zendTranslate($institution['label'], 'institution'))?>">
									<?=$this->escapeHtml($institution['bibinfolink']['host'])?>
								</a>
							</li>
						<?php endif; ?>
					</ul>

					<div class="stock_toggler_<?=$groupCode?>_<?=$institutionCode?>">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Beschreibung</th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
								<?php
										// Items
									if( isset($institution['items'])) {
										foreach($institution['items'] as $item) {
											echo $this->render('record/holdingsils_item.phtml', array(
												'item'	=> $item
											));
										}
									}

										// Holdings
									if( isset($institution['holdings'])) {
										foreach($institution['holdings'] as $holding) {
											echo $this->render('record/holdingsils_holding.phtml', array(
												'holding'	=> $holding
											));
										}
									}
								?>
							</tbody>
						</table>
					</div>
				<?php endforeach; ?>

			</div>
		</div>
	</div>
	<!-- end: innerbox <?=$groupCode?> -->

<?php endforeach; ?>