<div class="innerbox grey">
	<h3 class="toggler persist collapsed" id="library_toggler_meine-bibliotheken"><span class="icon_favorit_library">Meine Bibliotheken</span></h3>
	<div class="library_toggler_meine-bibliotheken">

		<!-- begin: innerbox -->
		<div class="innerbox">
			<h4>Historisches Seminar</h4>
			<ul class="actions">
				<li>
					<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
				</li>
				<li>
					<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_meine-bibliotheken_historisches-seminar"><span>Informationen zum Bestand</span></a>
				</li>
			</ul>
			<ul class="miniactions boxed">
				<li class="miniaction_favorite_remove">
					<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
				</li>
				<li class="miniaction_link">
					<a href="http://aleph.unibas.ch" class="externallink" title="Historisches Seminar">http://aleph.unibas.ch</a>
				</li>
			</ul>

			<div class="stock_toggler_meine-bibliotheken_historisches-seminar">
				<table>
					<thead>
						<tr>
							<th>Standort</th>
							<th>Signatur</th>
							<th>Exemplarstatus</th>
							<th>Ausleihstatus</th>
							<th>Bechreibung</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>-</td>
							<td>Gd XIII 3836</td>
							<td>ausleihbar</td>
							<td>erhältlich</td>
							<td>Diest ist ein Beschreibungstext.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div><!-- end: innerbox -->

	</div>
</div>