<?
// Set page title.
$this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

$toc = $this->driver->getTOC();
?>
<? if (!empty($toc)): ?>
    <h4><?=$this->transEsc('Table of Contents')?>: </h4>
    <ul>
        <? foreach ($toc as $line): ?>
            <li><?=$this->escapeHtml($line)?></li>
        <? endforeach; ?>
    </ul>
<? else: ?>
    <?=$this->transEsc("Table of Contents unavailable")?>.
<? endif; ?>