<?php
/** @var    Swissbib\RecordDriver\SolrMarc $record */
$record         = $this->driver;
$tableOfContent = $record->getTableOfContent();
$contentSummary = $record->getContentSummary();

?>
<?php if (empty($tableOfContent) && empty($contentSummary)): ?>

    <p><?= $this->transEsc('Table of Contents unavailable') ?></p>

<?php else: ?>

    <?php if (!empty($tableOfContent)): ?>
        <h4><?= $this->transEsc('toc.content') ?>: </h4>
        <ul id="table-of-content" class="keywordList">
            <?php foreach ($tableOfContent as $line): ?>
                <li><?= $this->escapeHtml($line) ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <?php if (!empty($contentSummary)): ?>
        <h4><?= $this->transEsc('toc.summary') ?>: </h4>
        <div id="content-summary">
            <?php foreach ($contentSummary as $line): ?>
                <p><?= $this->escapeHtml($line) ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

<?php endif; ?>