<?php

$commentCount	= sizeof($this->driver->getComments());

?>

<h3 class="metatitle">
    <?php if( $commentCount == 0 ): ?>
    <?=$this->transEsc('No reviews were found for this record')?>
    <?php else: ?>
    <?=$this->transEsc('Reviews')?>
    <?php endif?>
	<span class="rating rating_3"></span><span class="meta">Durchschnittliche Bewertung</span>
</h3>

<!-- begin: items review -->
<?=$this->render('record/comments-list.phtml')?>
<!-- end: items review -->

<!-- begin: editor_rezensionen -->
<?=$this->render('record/comments-form.phtml')?>
<!-- end: editor_rezensionen -->