<?php

$menuItems = array(
//	'accounts'	=> array(
//		'route'	=> 'myresearch-accounts',
//		'label'	=> 'My Accounts',
//		'sub'	=> array()
//	),
	'favorites'	=> array(
		'route'	=> 'myresearch-favorites',
		'label'	=> 'Favorites',
		'sub'	=> array()
	),
	'checkedout'	=> array(
		'route'	=> 'myresearch-checkedout',
		'label'	=> 'Checked Out Items'
	),
	'holds'	=> array(
		'route'	=> 'myresearch-holds',
		'label'	=> 'Holds and Recalls'
	),
	'fines'	=> array(
		'route'	=> 'myresearch-fines',
		'label'	=> 'Fines'
	),
	'profile'	=> array(
		'route'	=> 'myresearch-profile',
		'label'	=> 'Profile'
	),
	'history'	=> array(
		'route'	=> 'search-history',
		'label'	=> 'history_saved_searches'
	)
);

?>
<h3><?=$this->transEsc('Your Account')?></h3>
<div class="subnavigation">
	<ul>

		<?php foreach($menuItems as $key => $menuItem): ?>
			<?php $activeClass = $this->active == $key ? 'selected' : ''; ?>

			<li class="<?=$activeClass?>">
				<a href="<?=$this->url($menuItem['route'])?>" title="<?=$this->transEsc($menuItem['label'])?>"><?=$this->transEsc($menuItem['label'])?></a>
				<?php if( isset($menuItem['sub']) && is_array($menuItem['sub']) ): ?>
					<ul>

						<?php foreach($menuItem['sub'] as $subMenuItem): ?>

							<li>
								<a href="<?=$this->url($subMenuItem['route'])?>" title="<?=$this->transEsc($subMenuItem['label'])?>"><?=$this->transEsc($subMenuItem['label'])?></a>
							</li>

						<?php endforeach; ?>

					</ul>
				<?php endif; ?>
			</li>

		<?php endforeach; ?>

	</ul>
</div>