<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
	<div id="col1_content" class="clearfix">
		<!-- begin: sidebar -->
		<div id="sidebar">
			<?php /*$this->context($this)->renderInContext("myresearch/sidebar/sidebar.phtml", array('active' => $active))*/ ?>
			<?=$this->render("myresearch/sidebar/sidebar.phtml")?>
		</div>
		<!-- end: sidebar -->
	</div>
</div>
<!-- end: col1 (sidebar) -->