<?
// Set page title
$this->headTitle($this->translate('My Profile'));
// Only display home library form if we have multiple pickup locations
$showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);
$delinquency = $profile['delinq-1'] . $profile['delinq-2'] . $profile['delinq-3'];
$delinq_notes = array(
    'n1' => $profile['delinq-n-1'],
    'n2' => $profile['delinq-n-2'],
    'n3' => $profile['delinq-n-3']
);
?>

<?=$this->myResearchSideBar('profile', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
    <div id="col3_content" class="clearfix">
        <!-- begin: content -->
        <div id="content">
            <h1><?=$this->transEsc('Your Profile')?></h1>
            <?=$this->flashmessages()?>

            <table>
                <tbody>
                <tr>
                    <th width="100"><?=$this->escapeHtml($this->transEsc('User Account'))?></th>
                    <td><?=$this->escapeHtml($this->profile['lastname'])?></td>
                </tr>
                <tr>
                    <th width="100"><?=$this->escapeHtml($this->transEsc('Address'))?></th>
                    <td><?=$this->escapeHtml($this->profile['address1'])?></td>
                </tr>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td><?=$this->escapeHtml($this->profile['address2'])?></td>
                </tr>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td><?=$this->escapeHtml($this->profile['address3'])?></td>
                </tr>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td><?=$this->escapeHtml($this->profile['address4'])?></td>
                </tr>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td><?=$this->escapeHtml($this->profile['address5'])?></td>
                </tr>
                <tr>
                    <th width="100"><?=$this->escapeHtml($this->transEsc('Email'));?></th>
                    <td><?=$this->escapeHtml($this->profile['email'])?></td>
                </tr>
                <tr>
                    <th width="100"><?=$this->escapeHtml($this->transEsc('Phone Number'));?></th>
                    <td><?=$this->escapeHtml($this->profile['phone'])?></td>
                </tr>
                </tbody>
            </table>
            <? if (preg_match('/[1-9]/', $delinquency)): ?>
                <table>
                    <tbody>
                    <tr>
                        <th width="100"><?=$this->escapeHtml($this->transEsc('Account blocked'))?></th>
                        <td>
                            <? foreach ($delinq_notes as $field): ?>
                                <? if (!empty($field)): ?>
                                    <?= $this->transEsc($field) ?><br/>
                                <? endif; ?>
                            <? endforeach; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            <? endif; ?>
            <table>
                <? switch ($_COOKIE['language']) {
                    case 'de':
                        $lang = '=GER';
                        break;
                    case 'fr':
                        $lang = '=FRE';
                        break;
                    case 'en':
                        $lang = '=ENG';
                        break;
                    case 'it':
                        $lang = '=ENG';
                        break;
                } ?>
                <? $loginlink = 'http://aleph.unibas.ch/F/?func=file&file_name=login-session&con_lng' . $lang; ?>
                <tbody>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td>
                        <a href="<?=$loginlink?>" target="_blank"><?=$this->transEsc('changeaddress')?></a>
                    </td>
                </tr>
                <tr>
                    <th width="100">&nbsp;</th>
                    <td>
                        <a href="<?=$loginlink?>" target="_blank"><?=$this->transEsc('changepassword')?></a>
                    </td>
                </tr>
                </tbody>
            </table>

            <?php
            if( $showHomeLibForm ) {
                echo $this->render('myresearch/profile/pickupform.phtml', array(
                        'pickup'				=> $this->pickup,
                        'profile'				=> $this->profile,
                        'defaultPickupLocation'	=> $this->defaultPickupLocation
                    ));
            }
            ?>

        </div>
        <!-- end: content -->
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>
<!-- end: col3 (content) -->