<div class="footer buildnum"><?= $this->getVersion() ?></div>

<!-- swissmetrix.ch -->
<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(["trackPageView"]);
    _paq.push(["enableLinkTracking"]);

    (function () {
        var u = (("https:" == document.location.protocol) ? "https" : "http") + "://www.swissmetrix.ch/analytics/";
        _paq.push(["setTrackerUrl", u + "smx.php"]);
        _paq.push(["setSiteId", "23"]);
        var d = document, g = d.createElement("script"), s = d.getElementsByTagName("script")[0];
        g.type = "text/javascript";
        g.defer = true;
        g.async = true;
        g.src = u + "smx.js";
        s.parentNode.insertBefore(g, s);
    })();
</script>
<!-- End swissmetrix.ch -->