<?php

/** @var    VuFind\View\Helper\Root\Record $viewRecord */
/** @var    Swissbib\RecordDriver\SolrMarc $record */

$record = $this->driver;
$viewRecord = $this->record($record);
$theme = $this->configAccess()->Site->theme;
$showFRBR = $this->configAccess()->Site->displayFrbr;

//$authors	= $this->Authors($resultItem->getDeduplicatedAuthors());

//$thumbnail		= $viewRecord->getThumbnail('medium');
$thumbnail = $viewRecord->getThumbnail('large');
$thumbnailSrc = $thumbnail ? $thumbnail : $this->url('cover-unavailable');

$titleStatement       = $record->getTitleStatement(true);
$shortTitle           = $record->getShortTitle();
$subtitle             = $viewRecord->getSubtitle($titleStatement);
$responsible          = $viewRecord->getResponsible($titleStatement, $record);
$publishers           = $record->getPublishers(true);
$physicalDescriptions = $record->getPhysicalDescriptions(false);
$edition              = $record->getEdition();
$cartMathData         = $record->getCartMathData();
$summary              = trim(implode($record->getSummary()));
$groupID              = $record->getGroup(true);
$uniqueID             = $record->getUniqueID();

$publicationDate = $this->publicationDateMarc($record->getPublicationDates());
$hostitems = $record->getHostItemEntry();
// prepared to activate openURL-display in solr-Tab, openURL switched of @todo analyse later
//$openUrl				= $record->openURLActive('record') ? $record->getOpenURL() : false;
//$urls                   = ($openUrl && $record->replaceURLsWithOpenURL()) ? array() : $viewRecord->getLinkDetails();


/*
todo: erste Implementierung gezielt links generieren zu lassen (GH)
zufrieden bin ich damit noch nicht richtig - eventuell kann man noch gezielter konfigurieren, welche links man einsetzen möchte
aktueller Status:
1) $viewRecord->getExtendedLinkDetails()
-> sucht nach allen links lokal (Tag 950) sowie 856 und 956 des bibliographischen Satzes
2) $urls = $viewRecord->getExtendedLinkDetails($params,false);
sucht gezielt nach links in den lokalen 950 Tags. Folgende Einschränkungen sind möglich
$allParams = array('unions' => array(), 'localtags'  => array(), 'indicators' => array(), 'subfields' => array());
unions -> Verbunde
localtags -> gezielt nach localtags abfragen
indicators -> Einschraenkung auf bestimmte Indikatoren
subfields -> Einschraenkung nach subfields
Die Methode verwendet die allgemeine Methode getLocalValues, die auch für das Auslesen anderen lokaler tags als fuer links verwendet werden kann
erweitertes Beispiel:
    $unions = array('IDSBB','SNL');
    $localtags = array('956','856);
    indicators = array('7','-')
    subfields = array('a','b','C')
    $params = compact('unions','localtags','indicators','subfields');

man muss noch schauen, ob diese Form der Implementierung fuer die anderen use cases ausreichend und sinnvoll ist

*/
$currentView = $this->configAccess()->Site->theme;
if (strcmp(strtolower($currentView),'swissbibmulti') != 0) {

    $urls = $viewRecord->getExtendedLinkDetails();


} else {
    $localunions = array('IDSBB','SNL', 'RETROS');
    $localtags = array('856');
    $localRestrictions = compact('localunions','localtags');

    $globalunions = array('IDSBB','SNL');
    $tags = array('956');
    $globalRestrictions = compact('globalunions','tags');


    $urls = $viewRecord->getExtendedLinkDetails($localRestrictions,$globalRestrictions);

}





$memorizeLink = $this->recordLink()->getActionUrl($record, 'Save');
$highlightedFulltext = $record->getHighlightedFulltext();

?>
<? /* Common parts of recordDriver's core.phtml templates*/ ?>
<!-- col -->
<div class="c25l">
    <a title="<?= $this->transEsc('memorizelistadd') ?>" class="memorize" href="<?= $memorizeLink ?>">
        <img src="<?= $this->basePath('themes/' . urlencode($theme) . '/images/icon_notepad_add.gif') ?>">
    </a>
    <p class="preview">
        <img class="dropshadow" src="<?= $thumbnailSrc ?>"/>
    </p>
</div>

<!-- col -->
<div class="c75r">
    <!-- title section -->
    <h2><?= $this->escapeHtml($shortTitle) ?></h2>
    <? if (isset($subtitle)): ?>
        <p><?= $this->escapeHtml($subtitle) ?></p>
    <? endif ?>

    <!-- details -->
    <div class="details">

        <?php if ($responsible): ?>
            <h4><?= $this->transEsc('Author') ?>:</h4>
                <p><?=$this->escapeHtml($responsible)?></p>
        <?php endif; ?>

        <? if ($hostitems): ?>
            <? foreach ($hostitems as $hostitem): ?>
                <h4><?= $this->transEsc('note_773') ?>: </h4>
                <? $text = array_key_exists('related', $hostitem) ? $hostitem['title'] . ', ' . $hostitem['related'] : $hostitem['title'] ?>
                <p><?= $this->escapeHtml($text) ?></p>
            <? endforeach; ?>
        <? endif; ?>

        <? if ($publishers): ?>
            <h4><?= $this->transEsc('Publication') ?>:</h4>
            <p><?= $this->escapeHtml(implode(' | ', $publishers)) ?>, <?= $this->escapeHtml($publicationDate) ?></p>
        <? elseif ($publicationDate): ?>
            <h4><?= $this->transEsc('Year') ?>:</h4>
            <p><?= $this->escapeHtml($publicationDate) ?></p>
        <? endif; ?>

        <?php if ($edition): ?>
            <h4><?= $this->transEsc('Edition') ?>:</h4>
            <p><?= $this->escapeHtml($edition) ?></p>
        <?php endif; ?>

        <?php if ($cartMathData): ?>
            <h4><?= $this->transEsc('Map_Scale') ?>:</h4>
            <p><?= $this->escapeHtml($cartMathData) ?></p>
        <?php endif; ?>

        <?php if ($physicalDescriptions): ?>
            <h4><?= $this->transEsc('Physical Description') ?>:</h4>
            <p><?= $this->physicalDescription($physicalDescriptions) ?></p>
        <?php endif; ?>

        <h4><?= $this->transEsc('Format') ?>:</h4>
        <p><?=$viewRecord->getFormatList()?></p>

        <? if ($urls): ?>
            <? foreach ($urls as $current): ?>
            <h4><?= $this->transEsc('Online Access') ?>: </h4>
                <p>
                    <?php  $wrappedURL = $this->redirectProtocolWrapper()->getWrappedURL($current['url']) ?>
                    <a href="<?= $this->escapeHtml($this->proxyUrl($wrappedURL)) ?>"
                       target="_blank"><?= $this->escapeHtml($current['desc']) ?></a><br/>
                </p>
            <? endforeach; ?>
        <?php endif; ?>

        <?php if (!empty($showFRBR) && $showFRBR && !empty($groupID)) : ?>
            <div class="no-print">
                <a href="<?=
                $this->url('search-results') . '?lookfor=' . $groupID . "&type=FRBR"
                . "&sort=publishDateSort+desc" ?>"
                   class="linkbutton icon_show" title="<?= $this->transEsc('FRBR_Button') ?>">
                    <span><?= $this->transEsc('FRBR_Button') ?></span>
                </a>
            </div>
        <?php endif; ?>

        <?php if ($highlightedFulltext): ?>
            <div class="no-print">
                <h4><?= $this->transEsc('fulltexthighlight') ?>: </h4>

                <p><?= $this->highlight($highlightedFulltext) ?></p>
            </div>
        <?php endif; ?>

        <?php if (!empty($uniqueID)): ?>
            <div class="print">
                <h4><?= $this->transEsc('Item_ID') ?>:</h4>

                <p><?= $uniqueID ?></p>
            </div>
        <?php endif; ?>

    </div>

</div>