<?php
/** @var	Swissbib\RecordDriver\SbSolrMarc	$resultItem  */
$resultItem	= $this->driver;
/** @var	VuFind\View\Helper\Root\Record		$record  */
$viewRecord	= $this->record($resultItem);

//$authors	= $this->Authors($resultItem->getDeduplicatedAuthors());

$mediumThumb= $viewRecord->getThumbnail('medium');
//$largeThumb	= $viewRecord->getThumbnail('large');
$thumbUrl	= $mediumThumb ? $mediumThumb : $this->url('cover-unavailable');

$primaryAuthor		= $resultItem->getTitleStatement(true);
$secondaryAuthors	= $resultItem->getSecondaryAuthors();
$publisher			= $resultItem->getPublisher(true);
$edition			= $resultItem->getEdition();
$summary			= trim(implode($resultItem->getSummary()));

?>
<!-- col -->
<div class="c25l">
	<a title="Zur Merkliste hinzufügen" class="icon_notepad_add_link" href="#">
		<img src="<?=$thumbUrl?>" class="dropshadow"/>
	</a>
</div>

<!-- col -->
<div class="c75l">
	<h2><?=$this->escapeHtml($resultItem->getShortTitle())?></h2>
	<p><?=$this->escapeHtml($resultItem->getSubtitle())?></p>
	<!-- details -->
	<div class="details">

		<?php if($primaryAuthor): ?>
		<h4>Verfasser:</h4>
		<p><?=$this->escapeHtml($primaryAuthor)?></p>
		<?php endif; ?>

		<?php if($publisher): ?>
		<h4>Verlag:</h4>
		<p><?=$this->escapeHtml($publisher)?></p>
		<?php endif; ?>

		<h4>Jahr:</h4>
		<p><?=$this->publicationDate($resultItem->getPublicationDates())?></p>

		<h4>Format:</h4>
		<p>
		<?php foreach($resultItem->getFormats() as $format): ?>
			<span class="icon_format_book"><?=$this->escapeHtml($format)?></span>
		<?php endforeach; ?>
		</p>

		<?php if($edition): ?>
		<h4>Auflage:</h4>
		<p><?=$this->escapeHtml($edition)?></p>
		<?php endif; ?>

		<?php if(!empty($summary)): ?>
		<h4>Inhalt:</h4>
		<p><?$this->escapeHtml($summary)?></p>
		<?php endif; ?>

	</div>

	<a href="frbr.html" class="linkbutton icon_show" title="Weitere Ausgaben und Formate anzeigen"><span>Weitere Ausgaben und Formate</span></a>

</div>