<?
    // Set up some convenience variables:
    $id = $this->driver->getUniqueId();
    $source = $this->driver->getResourceSource();
    if (isset($this->list) && is_object($this->list)) {
        $list_id = $this->list->id;
        $user_id = $this->list->user_id;
    } else {
        $list_id = null;
        $user_id = $this->user ? $this->user->id : null;
    }

	$listThumb		= $this->record($this->driver)->getThumbnail();
	$thumbSrc		= $listThumb ? $this->escapeHtml($listThumb) : $this->url('cover-unavailable');
	$thumbAlt		= $listThumb ? 'Cover Image' : 'No Cover Image';
	$title			= $this->driver->getTitle();
	$listTitle		= empty($title) ? $this->transEsc('Title not available') : $title;
	$description	= $this->driver->getSummary();
	$isEditAllowed	= (isset($list) && $list->editAllowed($this->user)) || (!isset($list) && $this->user);

?>
<tr>
	<td class="small center nodivider">
		<?=$this->driver->position?>
	</td>
	<td class="nodivider">
		<div>
			<?= $this->record($driver)->getCheckbox() ?>
		</div>

	</td>
	<td class="nodivider right">
		<a href="#" >
			<img src="<?=$thumbSrc?>" alt="<?=$thumbAlt?>" class="dropshadow"/>
		</a>
	</td>
	<td>
		<h3>
			<a href="<?=$this->recordLink()->getUrl($this->driver)?>" title="<?=$this->escapeHtml($listTitle)?>" class="color">
				<?=$this->escapeHtml($this->truncate($listTitle, 180))?>
			</a>
		</h3>
		<?php if(sizeof($description)): ?>
			<p><?=$description[0]?></p>
		<?php endif; ?>
		<!-- meta -->
		<div class="meta">
			
			<?php
			$listTags = $this->driver->getTags($list_id, $user_id, 'tag');
			$tagLinks = array();
			$listNotes= $this->driver->getListNotes($list_id, $user_id);
			$listLinks= array();

			foreach ($listTags as $tag) {
				$tagLinks[] = '<a href="' . $this->url('tag-home') . '?lookfor=' . urlencode($tag->tag) . '">' . $this->escapeHtml($tag->tag) . '</a>';
			}
			if (isset($this->lists) && is_array($this->lists)) {
				foreach ($this->lists as $current) {
					$listLinks[] = '<a href="' . $this->url('userList', array('id' => $current->id)) . '">' . $this->escapeHtml($current->title) . '</a>';
				}
			}
			?>
			<?php if (count($tagLinks)): ?>
				<h6><?= $this->transEsc('Your Tags') ?>:</h6>
				<span>
					<?=implode(', ', $tagLinks)?>
				</span>
				<br/>
			<?php endif; ?>

			<?php if (count($listNotes)): ?>
				<h6><?= $this->transEsc('Notes') ?>:</h6>
				<span>
					<?=implode('<br /> ', $listNotes)?>
				</span>
				<br/>
			<?php endif; ?>

			<?php if (count($listLinks)): ?>
				<h6><?= $this->transEsc('Saved in') ?>:</h6>
				<span>
					<?=implode(', ', $listLinks)?>
				</span>
				<br/>
			<?php endif; ?>

			<h6>Autor:</h6>
			<span><?=$this->driver->getTitleStatement()?></span>
		</div>
		<!-- format -->
		<div class="format">
			<h6 class="icon_format_book">Buch</h6>
		</div>
	</td>
	<td class="right">
		<?php if ($isEditAllowed): ?>
			<?php
				$editLink	= $this->url('myresearch-edit') . '?id=' . urlencode($id) . '&amp;source=' . urlencode($source) . (!is_null($list_id)?'&amp;list_id=' . urlencode($list_id) : '');
				$deleteLink = (is_null($list_id) ? $this->url('myresearch-favorites') : $this->url('userList', array('id' => $list_id))) . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
			?>
			<ul class="editing">
				<li>
					<a href="<?=$editLink?>" class="edit tool"><?=$this->transEsc('Edit')?></a>
				</li>
				<li>
					<a href="<?=$deleteLink?>" title="<?=$this->transEsc('confirm_delete_brief')?>" class="delete tool source<?=$this->escapeHtml($source)?>"><?=$this->transEsc('Delete')?></a>
				</li>
			</ul>
		<?php endif; ?>
	</td>
</tr>