<?
    // Set up some convenience variables:
    $id = $this->driver->getUniqueId();
    $source = $this->driver->getResourceSource();
    if (isset($this->list) && is_object($this->list)) {
        $list_id = $this->list->id;
        $user_id = $this->list->user_id;
    } else {
        $list_id = null;
        $user_id = $this->user ? $this->user->id : null;
    }

    $record               = $this->driver;
    if ($record instanceof \Swissbib\RecordDriver\Missing) {
        $thumbnailSrc         = $this->url('cover-unavailable');
        $shortTitle           = '[Titel fehlt]';
        $subtitle             = '[Aufnahme im Index gelöscht]';
        $publicationDate      = '0000';
    }
    elseif ($record instanceof \Swissbib\RecordDriver\SolrMarc) {
        $viewRecord           = $this->record($record);
        $thumbnail            = $viewRecord->getThumbnail('small');
        $thumbnailSrc         = $thumbnail ? $thumbnail : $this->url('cover-unavailable');
        $titleStatement       = $record->getTitleStatement(true);
        $shortTitle           = $record->getShortTitle();
        $subtitle             = $viewRecord->getSubtitle($titleStatement);
        $responsible          = $viewRecord->getResponsible($titleStatement, $record);
        $publishers           = $record->getPublishers(true);
        $publicationDate      = $this->publicationDateMarc($record->getPublicationDates());
        $hostitems            = $record->getHostItemEntry();
        $format               = $viewRecord->getFormatList();
        $isEditAllowed	      = (isset($list) && $list->editAllowed($this->user)) || (!isset($list) && $this->user);
    }
    elseif ($record instanceof \VuFind\RecordDriver\Summon) {
        $viewRecord           = $this->record($record);
        $thumbnail            = $viewRecord->getThumbnail('small');
        $thumbnailSrc         = $thumbnail ? $thumbnail : $this->url('cover-unavailable');
        $shortTitle           = $record->getShortTitle();
        $responsible          = $record->getAuthor();
        $publishers           = $record->getPublishers(true);
        $publicationDate      = $this->publicationDateSummon($record->getPublicationDates());
        $hostitem             = $record->getContainerTitle();
        if ($hostitem) {
            $hostitem = '. - ' .$record->getContainerReference();
        }
        $format               = $viewRecord->getFormatList();
        $isEditAllowed	      = (isset($list) && $list->editAllowed($this->user)) || (!isset($list) && $this->user);

    }

    // get user generated content (tags and notes)
    $listTags = $this->driver->getTags($list_id, $user_id, 'tag');
    $tags     = array();
    $listNotes= $this->driver->getListNotes($list_id, $user_id);
    $listLinks= array();

    foreach ($listTags as $tag) {
        $tags[] = $this->escapeHtml($tag->tag);
    }
    if (isset($this->lists) && is_array($this->lists)) {
        foreach ($this->lists as $current) {
            $listLinks[] = '<a href="' . $this->url('userList', array('id' => $current->id)) . '">' . $this->escapeHtml($current->title) . '</a>';
        }
    }
?>
<tr>
    <!-- Column 1: Index -->
    <td class="col-1 small center nodivider">
        <?=$this->driver->position?>
	</td>
    <!-- Colum 2: Checkbox -->
    <td class="col-2 nodivider">
        <div>
			<?= $this->record($driver)->getCheckbox() ?>
		</div>
	</td>
    <!-- Column 3: Teaser-image / Thumbnail -->
    <td class="col-3 nodivider right">
        <div class="ie8buster">
        <a class="preview" href="<?= $this->recordLink()->getUrl($record) ?>"
           title="<?= $this->escapeHtml($shortTitle) ?>">
        <img src="<?=$thumbnailSrc?>" class="dropshadow"/>
		</a>
        </div>
    </td>
    <!-- Column 4: bibliographic information -->
    <td class="col-4">
        <!-- Title and author details => links to full-view -->
        <h3>
			<a href="<?=$this->recordLink()->getUrl($record)?>" title="<?=$this->escapeHtml($shortTitle)?>" class="color">
				<?=$this->escapeHtml($this->truncate($shortTitle, 180))?>
			</a>
		</h3>
        <!-- Untertitel und Verfasserangabe -->
        <div class="meta">
            <? if (isset($subtitle)): ?>
                <p>
                    <?= $this->escapeHtml($subtitle) ?>
                </p>
            <? endif; ?>
            <? if ($responsible): ?>
                <h6><?= $this->transEsc('Author') ?>: </h6>
                <span>
                    <?= $this->escapeHtml($responsible) ?>
                </span>
            <? endif; ?>
        </div>
        <!-- Host Item & Jahr -->
        <div class="meta">
            <? if ($hostitems): ?>
                <? foreach ($hostitems as $hostitem): ?>
                    <h6><?= $this->transEsc('note_773') ?>: </h6>
                    <? $text = array_key_exists('related', $hostitem) ? $hostitem['title'] . ', ' . $hostitem['related'] : $hostitem['title'] ?>
                    <span><?= $this->escapeHtml($text) ?></span><br/>
                <? endforeach; ?>
            <? endif; ?>
            <h6><?= $this->transEsc('Year') ?>:</h6>
            <span><?= $this->escapeHtml($publicationDate) ?></span>
            <? if ($edition): ?>
                <h6><?= $this->transEsc('Edition') ?>:</h6>
                <span><?= $this->escapeHtml($edition) ?></span>
            <? endif; ?>
        </div>
		<!-- format -->
		<div class="format">
            <p><?= $format ?></p>
		</div>
        <!-- user content (tags, notes -->
        <div class="meta">
            <?php if (count($tags)): ?>
                <h6><?= $this->transEsc('Your Tags') ?>:</h6>
                <span><?=implode(', ', $tags)?></span>
                <br/>
            <?php endif; ?>
            <?php if (count($listNotes)): ?>
                <h6><?= $this->transEsc('Notes') ?>:</h6>
                <span><?=implode('<br /> ', $listNotes)?></span>
                <br/>
            <?php endif; ?>
            <?php if (count($listLinks)): ?>
                <h6><?= $this->transEsc('Saved in') ?>:</h6>
                <span><?=implode(', ', $listLinks)?></span>
                <br/>
            <?php endif; ?>
        </div>
        <!-- COINS -->
        <span class="Z3988" title="<?= $this->escapeHtml($this->driver->getOpenURL($this)) ?>"></span>
		<? if (!empty($id)): ?>
			<div class="print">
				<h6><?=$this->transEsc('Item_ID')?>:</h6> <span><?=$id ?> </span>
			</div>
		<? endif; ?>
	</td>
    <!-- Column 5: edit and delete actions -->
	<td class="col-5 right">
		<?php if ($isEditAllowed): ?>
			<?php
				$editLink	= $this->url('myresearch-edit') . '?id=' . urlencode($id) . '&amp;source=' . urlencode($source) . (!is_null($list_id)?'&amp;list_id=' . urlencode($list_id) : '');
				$deleteLink = (is_null($list_id) ? $this->url('myresearch-favorites') : $this->url('userList', array('id' => $list_id))) . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
			?>
			<ul class="editing">
				<li>
					<a href="<?=$editLink?>" class="edit tool"><?=$this->transEsc('Edit')?></a>
				</li>
                <?php if (!is_null($list_id)): ?>
                    <li>
                    <a href="<?=$deleteLink?>" title="<?=$this->transEsc('confirm_delete_brief')?>" class="delete tool source<?=$this->escapeHtml($source)?>"><?=$this->transEsc('Delete')?></a>
				</li>
                <?php endif; ?>
            </ul>
		<?php endif; ?>
	</td>
</tr>