<?php
/** @var    Swissbib\RecordDriver\Summon $resultItem */
/** @var    Swissbib\View\Helper\Record $record */

$resultItem = $this->driver;
$viewRecord = $this->record($resultItem);
$memorizeLink = $this->escapeHtml($this->recordLink()->getActionUrl($this->driver, 'Save'));
$theme = $this->configAccess()->Site->theme;

// do *not* use Summon's thumbnails ...
$thumbnail = $this->escapeHtml($viewRecord->getThumbnail('small'));
$thumbnailSrc = $thumbnail ? $thumbnail : $this->url('cover-unavailable');

$TITLE = $resultItem->getTitle();
$AUTHOR = $resultItem->getAuthor();
$IMPRINT = $resultItem->getImprint();
$EDITION = $resultItem->getEdition();
$CONTAINER = $resultItem->getContainerTitle();
if ($CONTAINER) {
    $CONTAINER .= '. - ' . $resultItem->getContainerReference();
}
?>

<!-- col 1 -->
<div class="c25l center">
    <a title="<?= $this->transEsc('memorizelistadd') ?>" class="memorize" href="<?= $memorizeLink ?>">
        <img src="<?= $this->basePath('themes/' . urlencode($theme) . '/images/icon_notepad_add.gif') ?>">
    </a>
    <a class="preview" href="#">
        <img class="dropshadow" src="<?= $thumbnailSrc ?>"/>
    </a>
</div>

<!-- col 2 -->
<div class="c75r">
    <h2><?= $this->escapeHtml($TITLE) ?></h2>

    <div class="details">
        <!-- details -->
        <?php if ($AUTHOR): ?>
            <h4><?= $this->transEsc('Author') ?>:</h4>
            <p><?= $this->escapeHtml($AUTHOR) ?></p>
        <?php endif; ?>
        <?php if ($IMPRINT): ?>
            <h4><?= $this->transEsc('Publication') ?>:</h4>
            <p><?= $this->escapeHtml($IMPRINT) ?></p>
        <?php endif; ?>
        <?php if ($EDITION): ?>
            <h4><?= $this->transEsc('Edition') ?>:</h4>
            <p><?= $this->escapeHtml($EDITION) ?></p>
        <?php endif; ?>
        <?php if ($CONTAINER): ?>
            <h4><?= $this->transEsc('note_773') ?>:</h4>
            <p><?= $this->escapeHtml($CONTAINER) ?></p>
        <?php endif; ?>
        <!-- format -->
        <h4><?= $this->transEsc('Format') ?>:</h4>

        <p>
            <?php foreach ($resultItem->getFormats() as $format): ?>
                <span class="icon_format_book"><?= $this->escapeHtml($format) ?></span>
            <?php endforeach; ?>
        </p>

    </div>
</div>
