<h2>Il progetto Swissbib</h2>
<p>Swissbib è il risultato della cooperazione tra le biblioteche universitarie svizzere e la Biblioteca nazionale. Il
    progetto, coordinato dalla Biblioteca universitaria di Basilea, si inscrive in un programma di innovazione e di
    collaborazione denominato &raquo;E-lib.ch: biblioteca elettronica svizzera&laquo;.</p>

<p>Swissbib beneficia di un sostegno finanziario, per il periodo 2008-2013, da parte della Conferenza universitaria
    svizzera (CUS).</p>

<h2>Cooperazione</h2>
<p>Le biblioteche e i sistemi bibliotecari qui di seguito elencati hanno grandemente contribuito a swissbib, senza il
    loro aiuto, swissbib non avrebbe potuto essere realizzato.</p>

<h3>Messa a disposizione dei dati</h3>
<ul class="list">
    <li>tutti i membri della rete IDS - Informationsverbund Deutschschweiz</li>
    <li>la Biblioteca nazionale svizzera</li>
    <li>RERO - Réseau des bibliothques de Suisse occidentale</li>
    <li>SBT - Sistema bibliotecario ticinese</li>
    <li>Rete di biblioteche Alexandria</li>
</ul>

<h3>Test di funzionalità</h3>
<p>Le prove di funzionalità sono state organizzate e condotte da un gruppo di lavoro della Biblioteca universitaria di
    Basilea. Vi hanno partecipato:</p>
<ul class="list">
    <li>bliotecari dei servizi all’utenza e catalogazione di IDS Lucerna, San Gallo, Basilea/Berna, dell'Università di
        Zurigo e della Zentralbibliothek di Zurigo
    </li>
    <li>bibliotecari dei servizi all’utenza e catalogazione della Biblioteca nazionale svizzera</li>
    <li>membri della COPAC e della Centrale de catalogage di RERO</li>
    <li>bibliotecari della Biblioteca universitaria di Lugano</li>
</ul>

<h3>Test di usabilità</h3>
<p>L’ergonomia dell'interfaccia è stata valutata da due gruppi di utenti e da un gruppo di esperti, nel quadro dei
    progetti <a href="http://www.e-lib.ch/accept.html" target="_blank">ACCEPT</a> e <a
        href="http://www.e-lib.ch/eval.html" target="_blank">ElibEval</a>.</p>

<h3>Traduzione</h3>
<p>Le versioni francese e italiana dell'interfaccia sono state adattate in modo da rispettare un uso proprio della
    terminologia. Egualmente sono state tradotte le pagine che illustrano le diverse funzionalità.</p>

<ul class="list">
    <li>interfaccia in francese: a cura dei membri COPAC di RERO</li>
    <li>pagine di contenuti in francese: Biblioteca universitaria di Basilea</li>
    <li>interfaccia e pagine di contenuti in italiano: Biblioteca universitaria di Lugano</li>
</ul>

<h2>Design del sito web</h2>
<p>Il design del sito è stato realizzato da <a href="http://www.nose.ch" target="_blank">Nose Design AG</a>.</p>

<h2>Software swissbib</h2>
<p>Il software utilizzato da swissbib basandosi su tre componenti:
<ul class="list">
    <li>Preparazione dei dati: <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS - Metadata
            management
            solution</a> di OCLC.
    </li>
    <li>Motore di ricerca: <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr/Lucene</a> (Open Source)
    </li>
    <li>Interfaccia utente: <a href="http://www.vufind.org" target="_blank">vufind</a> (Open Source)</li>
    <li>singoli componenti della soluzione complessiva: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>

</ul>
</p>