<h1>A proposito di swissbib</h1>
<h2>Ricerca centralizzata – richieste locali</h2>
<p>Swissbib permette di effettuare una ricerca simultanea nei cataloghi delle biblioteche universitarie svizzere, delle
    stazioni di ricerca e della Biblioteca nazionale.</p>

<h2>Cosa contiene il catalogo?</h2>
<p>Swissbib comprende attualmente <strong>19.8 milioni di notizie bibliografiche</strong> provenienti da <a
        href="../libraries/index.html"><strong>823 biblioteche</strong></a> e relative a libri a stampa, periodici,
    tesi, libri elettronici, documenti digitali, film (VHS, DVD, Blu-ray), musica (partiture, dischi, CD, DVD),
    audiolibri, foto, diapositive, materiali didattici, corsi di lingua e molto altro ancora ...</p>

<p>In swissbib sono presenti i seguenti cataloghi:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SBT%22') ?>" target="_blank">Sistema
            bibliotecario ticinese (32 biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSBB%22') ?>" target="_blank">IDS Basel/Bern
            (193 biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSLU%22') ?>" target="_blank">IDS Luzern (30
            biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SNL%22') ?>" target="_blank">Biblioteca nazionale
            svizzera (1 biblioteca)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSS*%22') ?>" target="_blank">IDS St. Gallen (36
            biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22NEBIS%22') ?>" target="_blank">NEBIS (172
            biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RERO%22') ?>" target="_blank">RERO (236
            biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SGBN%22') ?>" target="_blank">St. Galler
            Bibliotheksnetz (52 biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22BGR%22') ?>" target="_blank">Bibliotheksverbund
            Graubünden (26 biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ABN%22') ?>" target="_blank">Aargauer
            Bibliotheksnetz (25 biblioteche)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ALEX%22') ?>" target="_blank">Rete di biblioteche
            Alexandria (20 biblioteche)</a></li>
</ul>

<p>Nel corso del 2013, altri se ne aggiungeranno:</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek (25 biblioteche)</li>
</ul>

<p>Si possono altresì contare i depositi istituzionali di alcune università svizzere e numerosi progetti di
    digitalizzazione:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CCSA%22') ?>" target="_blank">Catalogue collectif
            suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH02%22') ?>" target="_blank">Documenti
            dell’Archivio svizzero di letteratura</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH01%22') ?>" target="_blank">Documenti
            dell’Archivio federale dei monumenti storici</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RETROS%22') ?>"
           target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ZORA%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>Cui si sommeranno, sempre nel corso del 2013, le seguenti collezioni:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>serval</li>
</ul>

<h2>Swissbib è aggiornato regolarmente?</h2>
<p>I dati contenuti in swissbib sono aggiornati a cadenza quotidiana.</p>

<h2>Fateci conoscere la vostra opinione</h2>
<p>Swissbib è in continuo miglioramento e sviluppo. Per fare questo abbiamo bisogno delle vostre osservazioni e dei
    vostri commenti. Nel menu di ogni pagina troverete un link al forum degli utenti, dove potete inviarci i vostri
    commenti o votare a sostegno di un’idea precedentemente espressa.</p>

<h2>Quali miglioramenti saranno apportati nel corso del 2013?</h2>
<p>La lista delle modifiche e dei miglioramenti che verranno apportati durante il 2013, senza essere esaustiva,
    comprende:</p>

<ul class="list">
    <li>richiesta e prenotazione di documenti direttamente in swissbib</li>
    <li>gestione di un conto utente</li>
    <li>miglior trattamento dei dati per facilitare la ricerca</li>
    <li>integrazione di nuovi indici per agevolare la ricerca</li>
</ul>

<h2>Il progetto swissbib</h2>
<p>Swissbib è il risultato della cooperazione tra le biblioteche universitarie svizzere e la Biblioteca nazionale. Il
    progetto, coordinato dalla Biblioteca universitaria di Basilea, si inscrive in un programma di innovazione e di
    collaborazione denominato &raquo;E-lib.ch: biblioteca elettronica svizzera&laquo;.</p>
<p>Swissbib beneficia di un sostegno finanziario, per il periodo 2008-2013, da parte della Conferenza universitaria
    svizzera (CUS).</p>