<?
// Set page title.
$this->headTitle($this->translate('Export Record'));

?>

<h1 class="hideinlightbox"><?= $this->transEsc('Export Record') ?></h1>

<?= $this->flashmessages() ?>

<? if (!empty($this->exportOptions)): ?>
	<form class="search data" method="post" action="<?= $this->url('cart-export') ?>" name="exportForm"
		  title="<?= $this->transEsc('Export Items') ?>">

		<fieldset>
			<div class="fieldbox">
				<ul class="list">
					<? foreach ($this->records as $current): ?>
						<li><strong><?= $this->transEsc('Title') ?>
								:</strong> <?= $this->escapeHtml($current->getBreadcrumb()) ?>
							<input type="hidden" name="ids[]"
								   value="<?= $this->escapeHtml($current->getResourceSource() . '|' . $current->getUniqueId()) ?>"/></li>
					<? endforeach; ?>
				</ul>
			</div>
			<div class="fieldbox">
				<label class="label" for="format"><?= $this->transEsc('Format') ?>:</label>
				<select name="format" id="format" class="select">
					<? foreach ($this->exportOptions as $exportOption): ?>
						<option value="<?= $this->escapeHtml($exportOption) ?>"><?= $this->transEsc($exportOption) ?></option>
					<? endforeach; ?>
				</select>
			</div>
		</fieldset>
		<fieldset class="actions">
			<input class="submit primary" type="submit" name="submit" value="<?= $this->transEsc('Export') ?>"/>
			<input class="close reset" type="button" name="close" value="<?= $this->transEsc('Cancel') ?>" />
		</fieldset>
	</form>
<? endif; ?>