<div class="toolbar">
	<ul>
		<li><input type="submit" class="button holdCancel" name="cancelSelected"
				   value="<?=$this->translate("hold_cancel_selected") ?>"
				   onClick="return confirm('<?=$this->translate("confirm_hold_cancel_selected_text") ?>')"/>
		</li>
		<li><input type="submit" class="button holdCancelAll" name="cancelAll"
				   value="<?=$this->translate("hold_cancel_all") ?>"
				   onClick="return confirm('<?=$this->translate("confirm_hold_cancel_all_text") ?>')"/>
		</li>
	</ul>
</div>
<div class="clearer"></div>