<?php
/** @var VuFind\RecordDriver\SolrDefault  $holding */

?>
<table>
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th><?=$this->transEsc('Title')?></th>
        <th><?=$this->transEsc('Created') ?></th>
        <th><?=$this->transEsc("hold_queue_position") ?></th>
        <th><?=$this->transEsc('pick_up_location') ?></th>
        <th><?=$this->transEsc('Status')?></th>
        <th><?=$this->transEsc('Library')?></th>
        <th><?=$this->transEsc('Call Number')?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->recordList as $index => $holding): ?>
        <?php
        echo get_class($holding);
        $ilsDetails			= $holding->getExtraDetail('ils_details');
        //$isNonMissingRecord	= is_a($holding, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($holding, 'VuFind\\RecordDriver\\Missing');
        ?>
    <tr>
        <td><?=$index+1?></td>
        <td><input type="checkbox"></td>
        <td><?=$this->escapeHtml($ilsDetails['title']) ?> + if(exists(z30-description)</td>
        <td><?=$this->escapeHtml($ilsDetails['create']) ?></td>
        <td><?=$this->escapeHtml($ilsDetails['position']) ?></td>
        <td><?=$this->escapeHtml($ilsDetails['location']) ?></td>
        <td><?=$this->escapeHtml($ilsDetails['status']) ?> fällig am: + if(exists(z37-balancer-date)</td>
        <td>Bibliothek (z30-sub-library)</td>
        <td>Signatur (z30-call-no)</td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
