<?php
/** @var VuFind\RecordDriver\SolrDefault  $holding */

?>
<ul class="recordSet">
	<?php foreach($this->recordList as $index => $holding): ?>
		<?php
			echo get_class($holding);
			$ilsDetails			= $holding->getExtraDetail('ils_details');
			$isNonMissingRecord	= is_a($holding, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($holding, 'VuFind\\RecordDriver\\Missing');
		?>
		<li class="result<?php if( ($index % 2) == 0 ): ?> alt<?php endif; ?>">
			<?php if( $this->cancelForm && isset($ilsDetails['cancel_details']) ): ?>
			<?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $holding->getUniqueId()); ?>
			<label for="checkbox_<?=$safeId?>"
				   class="offscreen"><?=$this->transEsc("Select this record")?></label>
			<input type="hidden" name="cancelAllIDS[]"
				   value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>"/>
			<input type="checkbox" name="cancelSelectedIDS[]"
				   value="<?=$this->escapeHtml($ilsDetails['cancel_details']) ?>" class="checkbox"
				   style="margin-left:0;" id="checkbox_<?=$safeId?>"/>
			<?php endif; ?>
			<div id="record<?=$this->escapeHtml($holding->getUniqueId()) ?>">
				<div class="span-2">
					<?php if( $summThumb = $this->record($holding)->getThumbnail() ): ?>
					<img src="<?=$this->escapeHtml($summThumb)?>" class="summcover"
						 alt="<?=$this->transEsc('Cover Image')?>"/>
					<?php else: ?>
					<img src="<?=$this->url('cover-unavailable')?>" class="summcover"
						 alt="<?=$this->transEsc('No Cover Image')?>"/>
					<?php endif; ?>
				</div>
				<div class="span-10">
					<?
					// If this is a non-missing Solr record, we should display a link:
					if( $isNonMissingRecord ) {
						$title = $holding->getTitle() ?: 'Title not available';
						echo '<a href="' . $this->recordLink()->getUrl($holding) . '" class="title">' . $this->escapeHtml($title) . '</a>';
					}
					else if( isset($ilsDetails['title']) && !empty($ilsDetails['title']) ) {
						// If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
						echo $this->escapeHtml($ilsDetails['title']);
					}
					else {
						// Last resort -- indicate that no title could be found.
						echo $this->transEsc('Title not available');
					}
					?><br/>
					<?php $listAuthor = $holding->getPrimaryAuthor(); if( !empty($listAuthor) ): ?>
					<?= $this->transEsc('by') ?>:
					<?php $authorString = implode(', ', $listAuthor) ?>
					<a href="<?=$this->record($holding)->getLink('author', $authorString)?>"><?=$this->escapeHtml($authorString)?></a>
					<br/>
					<?php endif; ?>
					<?php /* TODO: tags
			{if $resource.tags}
			  <?=$this->transEsc('Your Tags')?>:
			  {foreach from=$resource.tags item=tag name=tagLoop}
				<a href="{$url}/Search/Results?tag={$tag->tag|escape:"url"}">{$tag->tag|escape}</a>{if !$smarty.foreach.tagLoop.last},{/if}
			  {/foreach}
			  <br/>
			{/if}
			 */ ?>
					<?php /* TODO: notes
			{if $resource.notes}
			  <?=$this->transEsc('Notes')?>: {$resource.notes|escape}<br/>
			{/if}
			 */ ?>

					<?php $formats = $holding->getFormats(); if( count($formats) > 0 ): ?>
					<?= $this->record($holding)->getFormatList() ?>
					<br/>
					<?php endif; ?>
					<?php if( isset($ilsDetails['volume']) && !empty($ilsDetails['volume']) ): ?>
					<strong><?=$this->transEsc('Volume')?>
						:</strong> <?= $this->escapeHtml($ilsDetails['volume']) ?>
					<br/>
					<?php endif; ?>

					<?php if( isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year']) ): ?>
					<strong><?=$this->transEsc('Year of Publication')?>
						:</strong> <?= $this->escapeHtml($ilsDetails['publication_year']) ?>
					<br/>
					<?php endif; ?>

					<?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
			   value to display... */ ?>
					<?php $pickupDisplay = ''; ?>
					<?php $pickupTranslate = false; ?>
					<?php if( isset($ilsDetails['location']) ): ?>
					<?php if( $this->pickup ): ?>
						<?php foreach($this->pickup as $library): ?>
							<?php if( $library['locationID'] == $ilsDetails['location'] ): ?>
								<?php $pickupDisplay = $library['locationDisplay']; ?>
								<?php $pickupTranslate = true; ?>
								<?php endif; ?>
							<?php endforeach; ?>
						<?php endif; ?>
					<?php if( empty($pickupDisplay) ): ?>
						<?php $pickupDisplay = $ilsDetails['location']; ?>
						<?php endif; ?>
					<?php endif; ?>
					<?php if( !empty($pickupDisplay) ): ?>
					<strong><?=$this->transEsc('pick_up_location') ?>:</strong>
					<?= $pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay) ?>
					<br/>
					<?php endif; ?>

					<strong><?=$this->transEsc('Created') ?>
						:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?> |
					<strong><?=$this->transEsc('Expires') ?>
						:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
					<br/>

					<?php if( isset($this->cancelResults['items']) ): ?>
					<?php foreach($this->cancelResults['items'] as $itemId => $cancelResult): ?>
						<?php if( $itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false ): ?>
							<div class="error"><?=$this->transEsc($cancelResult['status']) ?><?php if( $cancelResult['sysMessage'] ) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
							<?php endif; ?>
						<?php endforeach; ?>
					<?php endif; ?>

					<?php if( isset($ilsDetails['available']) && $ilsDetails['available'] == true ): ?>
					<div class="info"><?=$this->transEsc("hold_available") ?></div>
					<?php elseif( isset($ilsDetails['position']) ): ?>
					<p><strong><?=$this->transEsc("hold_queue_position") ?>
						:</strong> <?=$this->escapeHtml($ilsDetails['position']) ?></p>
					<?php endif; ?>
					<?php if( isset($ilsDetails['cancel_link']) ): ?>
					<p>
						<a href="<?=$this->escapeHtml($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a>
					</p>
					<?php endif; ?>

				</div>
				<div class="clear"></div>
			</div>
		</li>
	<?php endforeach; ?>
</ul>