<table id="photocopies-table">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th><?=$this->transEsc('Title')?></th>
			<th><?=$this->transEsc('Created') ?></th>
            <th><?=$this->transEsc('Status') ?></th>
            <th><?=$this->transEsc('Place of Delivery') ?></th>
			<th><?=$this->transEsc('Library') ?></th>
			<th><?=$this->transEsc('Call Number') ?></th>
			<th><?=$this->transEsc('Note') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->photoCopies as $index => $photoCopy): ?>
			<tr id="photocopy-<?=intval($photoCopy['sequence'])?>" class="link">
				<td>+1</td>
				<td>
                    <?=$this->escapeHtml($photoCopy['title'])?>
                        <? if (!empty($photoCopy['author']) || (!empty($photoCopy['title2'])) || (!empty($photoCopy['pages']))) ?>
                            <? $addtitle = array(
                                $this->escapeHtml($photoCopy['author']),
                                $this->escapeHtml($photoCopy['title2']),
                                $this->escapeHtml($photoCopy['pages']),
                                )
                            ?>
                    <?= implode(', ', $addtitle); ?>
                </td>
                <td><?=date('d/m/y', $photoCopy['dateOpen'])?></td>
                <td><?=$this->escapeHtml($photoCopy['status'])?></td>
                <td><?=$this->escapeHtml($photoCopy['pickup'])?></td>
				<td><?=$this->escapeHtml($photoCopy['library'])?></td>
				<td><?=$this->escapeHtml($photoCopy['callNumber'])?></td>
				<td><?=$this->escapeHtml($photoCopy['note1'] . ' ' . $photoCopy['note2'])?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>