<?php
/** @var VuFind\RecordDriver\SolrDefault $transaction */
?>
<table>
	<thead>
		<tr>
			<th>&nbsp;</th>
            <th>&nbsp;</th>
            <th><?=$this->transEsc('Title')?></th>
			<th><?=$this->transEsc('Checked Out')?></th>
			<th><?=$this->transEsc('Due')?></th>
			<th><?=$this->transEsc('Renewals')?></th>
			<th><?=$this->transEsc('Library')?></th>
			<th><?=$this->transEsc('Call Number')?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->transactions as $index => $transaction): ?>
			<?php
				$ilsDetails 		= $transaction->getExtraDetail('ils_details');
				//$isNonMissingRecord	= is_a($transaction, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($transaction, 'VuFind\\RecordDriver\\Missing');
				$isRenewable		= isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details']);
				$safeId 			= preg_replace('/[^a-zA-Z0-9]/', '', $transaction->getUniqueId());
			?>
			<tr>
				<td><?=$index+1?></td>
                <td>
					<input type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtml($ilsDetails['renew_details'])?>" class="checkbox" style="margin-left: 0" id="checkbox_<?=$safeId?>" />
				</td>
                <td><?=$this->escapeHtml($ilsDetails['title'])?></td>
				<td><?=$this->escapeHtml($ilsDetails['loandate'])?></td>
				<td>
                    <?if ($ilsDetails['status'] == 'Active'): ?>
						<?=$this->escapeHtml($ilsDetails['duedate'])?>
                    <? else: ?>
						<?=$this->escapeHtml($ilsDetails['duedate'])?> (<?=$this->escapeHtml($ilsDetails['status'])?>)
                    <? endif; ?>
                </td>
				<td><?=$this->escapeHtml($ilsDetails['renewals'])?> (<?=$this->transEsc('of')?> 5)</td>
				<td><?=$this->escapeHtml($ilsDetails['library'])?></td>
				<td><?=$this->escapeHtml($ilsDetails['callnum'])?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>