<h2>Le projet swissbib</h2>
<p>Swissbib est le fruit d'une coopération entre les bibliothèques universitaires suisses et la Bibliothèque nationale.
    Coordonné par la Bibliothèque universitaire de Bâle, le projet s'inscrit dans le programme d'innovation et de
    coopération des hautes écoles de Suisse &laquo; E-lib.ch : Bibliothèque électronique suisse &raquo;</p>

<p>Swissbib bénéficie d'un soutien financier de la Conférence universitaire suisse (CUS) pour la période de 2008 à
    2013.</p>

<h2>Coopération</h2>
<p>Les bibliothèques et réseaux suivants ont grandement contribué à swissbib à plusieurs niveaux. Sans leur aide,
    swissbib n’aurait pas pu être réalisé.</p>

<h3>Livraisons des données</h3>

<ul class="list">
    <li>tous les membres du réseau IDS – Informationsverbund Deutschschweiz</li>
    <li>la Bibliothèque nationale suisse</li>
    <li>RERO – Réseau des bibliothèques de Suisse occidentale</li>
    <li>sbt - Sistema bibliotecario ticinese et partenaires IDS</li>
    <li>Réseau de bibliothèques Alexandria/li>
</ul>

<h3>Test des fonctionnalités</h3>
<p>Le test des fonctionnalités a été organisé et dirigé par une équipe de la Bibliothèque universitaire de Bâle. Les
    réseaux et bibliothèques suivants y ont participé :</p>

<ul class="list">
    <li>bibliothécaires des services aux usagers et du catalogage des réseaux IDS de Lucerne, Saint-Gall, Bâle/Berne,
        Université de Zurich ainsi que de la Zentralbibliothek de Zurich
    </li>
    <li>bibliothécaires des services aux usagers et du catalogage de la Bibliothèque nationale suisse</li>
    <li>membres de la COPAC et de la centrale de catalogage de RERO</li>
    <li>la Biblioteca universitaria de Lugano</li>
</ul>

<h3>Tests d’ergonomie</h3>
<p>L’ergonomie (performance d’utilisation) de l’interface a été évaluée par deux groupes d’utilisateurs et par un groupe
    d’experts, dans le cadre des projets de <a href="http://www.e-lib.ch/accept.html" target="_blank">ACCEPT</a> et <a
        href="http://www.e-lib.ch/eval.html" target="_blank">ElibEval</a>.</p>

<h3>Traduction</h3>
<p>Les versions française et italienne de l’interface ont été adaptées à l'usage suisse en la matière. Les pages de
    contenus swissbib ont également été traduites.</p>

<ul class="list">
    <li>interface en français : membres de la COPAC de RERO</li>
    <li>pages de contenus en français : Bibliothèque universitaire de Bâle</li>
    <li>interface et pages de contenus en italien : Biblioteca universitaria de Lugano</li>
</ul>

<h2>Design du site web</h2>
<p>Le design du site web a été réalisé par <a href="http://www.nose.ch" target="_blank">Nose Design AG</a>.</p>

<h2>Logiciel swissbib</h2>
<p>Le logiciel utilisé par swissbib est constitué de trois composantes :
<ul class="list">
    <li>composition des métadonnées : <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS - Metadata
            management
            solution</a> de OCLC.
    </li>
    <li>moteur de recherche: <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr/Lucene</a> (Open
        Source)
    </li>
    <li>interface: <a href="http://www.vufind.org" target="_blank">vufind</a> (Open Source)</li>
    <li>les composants individuels de la solution globale: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>


</ul>
</p>
