<h1>À propos de swissbib</h1>
<h2>Recherche centralisée – commande locale</h2>
<p>Swissbib vous permet d'effectuer une recherche simultanée dans les bibliothèques des universités et hautes écoles de
    Suisse, ainsi qu' aux staions de recherche et à la Bibliothèque nationale.</p>

<p>Vous utilisez swissbib à la fois pour faire une recherche, en afficher les résultats et savoir dans quelles
    bibliothèques se trouvent les documents dont vous avez besoin. La demande ou réservation se fait ensuite directement
    auprès des bibliothèques.</p>


<h2>Que contient le catalogue ?</h2>
<p>Swissbib recense actuellement <b>20 millions de notices</b> provenant de <a href="../Libraries"><b>900
            bibliothèques, médiathèques et archives</b></a> de toutes les régions de Suisse et donnant accès à des
    livres, périodiques, thèses, e-books, documents numérisés, films (VHS, DVD, Blu-ray), musique (partitions, disques,
    CD, DVD), livres audios, photos, diapositives, matériel d'enseignement, cours de langue et bien plus encore ...</p>

<p>Les réseaux de bibliothèques suivants sont rassemblés dans swissbib :</p>
<ul class="list">
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22RERO%22') ?>" target="_blank">RERO</a>
    </li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22SBT%22') ?>" target="_blank">Sistema
        bibliotecario ticinese</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSBB%22') ?>" target="_blank">IDS
        Basel/Bern</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSLU%22') ?>" target="_blank">IDS
        Luzern</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22SNL%22') ?>"
        target="_blank">Bibliothèque nationale suisse</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSS*%22') ?>" target="_blank">IDS
        St.Gallen</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22NEBIS%22') ?>" target="_blank">NEBIS</a>
    </li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22SGBN%22') ?>" target="_blank">St. Galler
        Bibliotheksnetz</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22BGR%22') ?>
        "target="_blank">Bibliotheksverbund Graubünden</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22ABN%22') ?>" target="_blank">Aargauer
        Bibliotheksnetz</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22ALEX%22') ?>" target="_blank">Réseau de
        bibliothèques Alexandria</a></li>
</ul>

<p>À partir de 2014, d'autres réseaux seront disponibles dans swissbib :</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek</li>
</ul>

<p>D'autre sources de données peuvent en outre être consultées à travers swissbib :</p>
<ul class="list">
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22CCSA%22') ?>" target="_blank">Catalogue
        collectif suisse des affiches</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH02%22') ?>"
        target="_blank">Documents numérisés des Archives littéraires suisses</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH01%22') ?>"
        target="_blank">Documents numérisés des Archives fédérales des monuments historiques</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22RETROS%22') ?>"
        target="_blank">retro.seals.ch</a></li>
    <li><a href="<a href="<?= $this->basePath('Search/Results?filter=union%3A%22ZORA%22') ?>" target="_blank">ZORA</a>
    </li>
</ul>

<p>À partir de 2014 viendront s'ajouter les collections numériques suivantes :</p>
<ul class="list">
    <li>RERO DOC</li>
    <li>Alexandria</li>
    <li>SERVAL</li>
</ul>

<h2>Swissbib est-il mis à jour régulièrement ?</h2>
<p>Les données de swissbib sont mises à jour quotidiennement.</p>

<h2>Votre avis nous intéresse</h2>
<p>Swissbib se développe et se perfectionne continuellement. Pour ce faire, nous avons besoin de vos réactions et de vos
    commentaires. Vous trouverez dans le menu de chaque page un lien vers le forum des utilisateurs, dans lequel vous
    pouvez nous faire part de vos commentaires ou voter pour soutenir une idée déjà exprimée.</p>


<h2>Quelles améliorations seront apportées en 2014 ?</h2>
<p>Les domaines suivants seront modifiés et améliorés dans le courant de 2014. Il ne s'agit pas d'une liste exhaustive
    :</p>

<ul class="list">
    <li>commande et réservation directe de documents dans swissbib - en moment il est testé par le team swissbib</li>
    <li>gestion d'un compte pour les usagers d'une bibliothèque - en moment il est testé par le team swissbib</li>
    <li>meilleur traitement des données pour faciliter la recherche</li>
    <li>intégration de nouveaux index pour une recherche plus aisée</li>
</ul>

<h2>Le projet swissbib</h2>
<p>Swissbib est le fruit d'une coopération entre les bibliothèques universitaires suisses et la Bibliothèque nationale.
    Coordonné par la Bibliothèque universitaire de Bâle. De 2008 à 2013 le projet s'inscrit dans le programme
    d'innovation et de
    coopération des hautes écoles de Suisse &laquo; E-lib.ch : Bibliothèque électronique suisse &raquo;, qui était
    terminé à la fin de 2013.</p>

<p>Swissbib bénéficie d'un soutien financier de la Conférence universitaire suisse (CUS) pour la période de 2008 à
    2014.</p>