<h2>Anmelden</h2>
<div class="floatbox">
    <img class="small right"
         src="<?= $this->basePath('themes/swissbibsingle/images/Help/de/myswissbib/switch_Anmelden.png') ?>">

    <p>swissbib ist ein <strong>überregionaler Service</strong> und bietet eine bibliotheksunabhängige
        Anmeldung.</p>

    <p>Es werden zwei Möglichkeiten angeboten:</p>
    <ul class="list">
        <li><strong>switchAAI</strong> für Studierende und Personal von Universitäten, Fachhochschulen und weiteren
            Institutionen. Mehr Informationen bietet <a href="http://www.switch.ch/aai/participants/homeorgs.html"
                                                        target="_blank">switch</a>.
        </li>
        <li>Der Zugang für <strong>Private</strong> steht speziell jenen Nutzerinnen und Nutzern zur Verfügung, die sich
            nicht
            über switchAAI anmelden können. Er wird ebenfalls von switch bereitgestellt.
        </li>
    </ul>
</div>

<h3>Wozu anmelden?</h3>
<p>Die Anmeldung ermöglicht es, swissbib effektiver zu nutzen. Sie können </p>
<ul class="list">
    <li>auf bereits getätigte Suchen zurückgreifen</li>
    <li>Favoritenbibliotheken einmal definieren und dann immer wieder nutzen</li>
    <li>Merklisten über einen längeren Zeitraum speichern</li>
    <li>Die Suchoberfläche konfigurieren</li>
    <!-- <li>Nutzerdaten für die Ausleihe in Bibliotheken hinterlegen</li> -->
</ul>
<p>Wenn Sie sich <strong>nicht</strong> anmelden, verlieren Sie alle Einstellungen, wenn Sie den Browser schliessen.</p>

<h3>Passwort vergessen?</h3>
<ul class="list">
    <li>Nutzen Sie bei <strong>switchAAI</strong> die Rücksetzungsservices Ihrer Organisation.</li>
    <li>Beim <strong>Gastzugang</strong> nutzen Sie den switch-Service zur Passwortrücksetzung.</li>
</ul>

<h3>Wozu abmelden?</h3>
<p>An öffentlichen Computern sollten Sie sich abmelden <strong> und den Browser schliessen</strong>, damit ausser Ihnen
    niemand Ihr Konto benutzen kann.</p>

<!--<h3>Ausleihfunktionen</h3>
<h4>Konto IDS Basel Bern</h4>
<div class="floatbox">
    <img class="small right"
         src="<?= $this->basePath('themes/swissbibsingle/images/Help/de/myswissbib/Anmelden_IDS-BaselBern.png') ?>">

    <p>Online ausleihbare Bestände des IDS Basel/Bern können direkt in swissbib bestellt oder vorgemerkt werden.
        Voraussetzung ist, dass der für die Bestellung benötigte Nutzername und das Passwort im swissbib-Account
        hinterlegt werden.</p>

    <p>Dies geschieht nach der ersten Anmeldung mit switchAAI oder dem switch Gastzugang im <strong>Konto IDS
            Basel/Bern</strong>.</p>

    <p>Die Benutzerdaten werden im swissbib-Account verschlüsselt gespeichert und sicher an das Bibliothekssystem
        übertragen. Schliessen Sie an öffentlichen Stationen nach der Abmeldung immer den Browser, damit niemand
        versehentlich mit Ihren Daten bestellt.</p>
</div> -->