<h2>swissbib adapte les données bibliographiques en changeant le logiciel de recherche</h2>
<h3>Qu’est-ce qui ne fonctionne plus ?</h3>
<p>Il s’agit d’une mise à jour très profonde qui mène à trois adaptions importantes avec des conséquences pour vos
    données personnelles :
</p>
<ol class="list">
    <li>Les alignements de votre compte d’utilisateur ne fonctionnent plus. Les usagers privés sont obligés à refaire un
        compte nouveau.
    </li>
    <li>Les listes de sélection qui font partie de votre compte d’utilisateur sont supprimées.</li>
    <li>Les liens qui réfèrent aux données de swissbib ne sont plus valables.</li>
</ol>
<h3>Qu’est-ce qui change?</h3>
<p>En générale il y a peu de changement – les différences se trouvent en détail :
</p>
<ul class="list">
    <li>Le filtre par réseau de bibliothèque est supprimé à la page d’accueil. Il vient afficher dans la liste &laquo;
        affiner la recherche &raquo; qui se trouve sur la gauche de la liste de vos résultats.
    </li>
    <li>Nouvelle &laquo; recherche étendue &raquo;</li>
    <li>Nouvelle inscription pour usagers privés <a href="<?= $this->url('myresearch-home'); ?>"
                                                    title="<?= $this->transEsc('Your Account') ?>"><img alt="Info"
                                                                                                 src="/themes/swissbib/images/icon_info.gif"></a>
    </li>
    <li>La liste des résultats
        <ul>
            <li>Nouvelle facette pour le filtre par années</li>
            <li>Améliorations pour imprimer et échanger les résultats</li>
        </ul>
    </li>
    <li>Affichage des résultats
        <ul>
            <li>Affichage des bibliothèques adaptés</li>
            <li>Affichage des volumes clair en cas des œuvres en plusieurs volumes <a
                    href="/Record/295089423/HierarchyTree?hierarchy=295089423"><img alt="Info"
                                                                                    src="/themes/swissbib/images/icon_info.gif"></a>
            </li>
            <li>Améliorations pour imprimer et échanger les résultats</li>
            <li>La description des documents est plus détaillée si les données le permettent</li>
        </ul>
    </li>
</ul>

