<h1>A proposito di swissbib</h1>

<h3>Contatto</h3>
<ul class="list">
    <li>Per domande concernenti il tuo conto ti preghiamo di contattare la <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">tua biblioteca</a>.</li>
    <li>Per domande concernenti un determinato documento ti preghiamo di contattare direttamente la <a href="<?= $this->url('libraries-index') ?>">biblioteca</a> che lo possiede.</li>
    <li>Contatto swissbib Basel Bern: inviaci una e-mail a <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oppure scrivi un commento sul nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.</li>
</ul>

<h3>News</h3>
<p>Segui il nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a></p>

<h1>Fonte dei dati</h1>

<h3>Libri &amp; più</h3>
<ul class="list">
<li>Le biblioteche scientifiche di <a href="<?= $this->url('libraries-index') ?>#nav_0">Basilea</a> e <a href="<?= $this->url('libraries-index') ?>#nav_1">Berna</a></li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: riviste scientifiche retrodigitalizzate</li>  
</ul> 
<h3>Articoli &amp; più</h3>
<ul class="list">
    <li>In <i>Articoli &amp; più</i> troverai i contenuti di numerosi periodici elettronici, gli e-book e le banche dati in abbonamento presso le biblioteche universitarie di Basilea e/o Berna. Nella maggior parte dei casi è possibile accedere direttamente al testo integrale in versione elettronica (articolo di rivista, capitolo di e-book, ecc.), se ci si trova in una sede universitaria.</li>
    <li>Il catalogo <i>Articoli &amp; più</i> contiene inoltre risorse elettroniche liberamente accessibili in rete.</li>
    <li>I documenti per i quali non è possibile un accesso diretto al testo integrale possono essere ordinati presso la tua biblioteca universitaria tramite prestito interbibliotecario.</li>
    <li>Per ulteriori informazioni riguardanti le fonti catalogate, vedi <a href="http://www.proquest.com/products-services/The-Summon-Service.html" target="_blank">ProQuest</a>.</li>
</ul>
