<h1>A proposito di swissbib</h1>

<h2>Contatto</h2>
<p>Scrivi un commento sul nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>, inviaci una
    mail a
    <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oppure contattaci via
    <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>
<p>Per domande concernenti il tuo conto ti preghiamo di contattare la <a
        href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">tua biblioteca</a>.</p>
<p>Per domande concernenti un determinato documento ti preghiamo di contattare direttamente la <a
        href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">biblioteca</a> che lo possiede. Link dal
    catalogo: clicca sull'icona <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>"
                                     alt="Library Info"> accanto alla segnatura.</p>


<h2>News</h2>
<p>Segui il nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a> o <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>

<h1>Fonte dei dati</h1>

<h2>Libri &amp; più</h2>
<!--
<p>For more details see <a
href="http://swissbib-baselbern.blogspot.com/2012/05/bucher-mehr-zwischen-ids-basel-bern-und.html">this blog
post</a> (in German).</p>
-->

<p><strong>Regione di Basilea</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, biblioteche a
        Basilea e Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Biblioteche della rete IDS</a></li>
</ul>
<p><strong>Regione di Berna</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Banca nazionale
            svizzera</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Biblioteca nazionale svizzera</a>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Biblioteche
            della rete IDS</a></li>
    </li>
</ul>


<p><strong>retro.seals</strong></p>
<ul class="list">
    <li>Nell'ambito del progetto <a href="http://retro.seals.ch" target="_blank">retro.seals.ch</a>, vengono
        retrodigitalizzate riviste scientifiche e rese accessibili su internet.
    </li>
</ul>

<!--
<h3>IDS-Kurier</h3>
<ul class="list">
    <li><a href="http://www.ub.unibas.ch/ids-basel-bern/ids-kurierbibliotheken">IDS-Kurierbibliotheken</a> in Luzern, St. Gallen und Zürich</li>
  </ul>
-->

<h2>Articoli &amp; più</h2>
<ul class="list">
    <li><a href="http://www.serialssolutions.com/en/services/summon/content-and-coverage" target="_blank">Summon di
            SerialsSolutions</a>
        <!--
<br>If you are not logged in to the university network in Basel or Bern your search is limited to texts with
open access.
-->
    </li>
</ul>