<h1>Ricerca avanzata</h1>
<h2>Libri &amp; più</h2>
<h3>Con tutti i grupi di ricerca</h3>
<div class="floatbox">
    <a href="/themes/swissbibmulti/images/HelpPage/it/advanced1.png" class="help">
        <img class="image magnify" src="/themes/swissbibmulti/images/HelpPage/it/advanced1_small.png"
             alt="Screenshot"/>
    </a>
    <p>
        Migration*/Migrant*/migrazion*<br/><strong>e</strong><br/>Gesundheit*/health/santé/salute<br/><strong>e</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*
    </p>
</div>

<h3>Senza il terzo grupo di ricerca</h3>
<div class="floatbox">
    <a href="/themes/swissbibmulti/images/HelpPage/it/advanced2.png" class="help">
        <img class="image magnify" src="/themes/swissbibmulti/images/HelpPage/it/advanced2_small.png"
             alt="Screenshot"/>
    </a>

    <p>Migration*/Migrant*/migrazion*<br/><strong>e</strong><br/>Gesundheit*/health/santé/salute<br/><strong>ma no</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*</p>
</div>

<h3>Affinare la ricerca: Lingua, Formato, Biblioteca, Anno di pubblicazione</h3>
<p>Invece di scorrere nelle drop-down lists, clicca su un punto qualsiasi della lista e scrivi la parola che desideri selezionare, p.es. <i>Italiano</i> in <i>Lingua</i></p>

<h3>Ripetere la ricerca</h3>
<p><i>Modifica questa ricerca avanzata</i> su la lista di risultati o <i>Il mio swissbib - Ricerche salvate</i>.</p>

<h3>Salvare la ricerca</h3>
<p><i>Il mio swissbib - Ricerche salvate</i>.</p>

<h2>Articoli &amp; più</h2>
<p>As <i>Books &amp; mehr</i>, but some of the fields/facets are different, as <i>Articles &amp; more</i> is a separate catalog.</p>
