<h1>Ricerca avanzata</h1>
<h2>Libri &amp; più</h2>
<h3>Con tutti i gruppi di ricerca</h3>
<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/advanced1.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/advanced1_small.png') ?>" alt="Zoom"> 
     </a>
       <p>
        Migration*/Migrant*/migrazion*<br/><strong>e</strong><br/>Gesundheit*/health/santé/salute<br/><strong>e</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*
    </p>
</div>

<h3>Senza il terzo gruppo di ricerca</h3>
<div class="floatbox">
      <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/advanced2.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/advanced2_small.png') ?>" alt="Zoom"> 
     </a>
    <p>Migration*/Migrant*/migrazion*<br/><strong>e</strong><br/>Gesundheit*/health/santé/salute<br/><strong>ma senza</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*</p>
</div>

<h3>Affinare la ricerca: Lingua, Formato, Biblioteca, Anno di pubblicazione</h3>
<p>Invece di scorrere nelle drop-down lists, clicca su un punto qualsiasi della lista e scrivi la parola che desideri selezionare, p.es. <i>Italiano</i> in <i>Lingua</i></p>

<h3>Rifare una ricerca</h3>
<p>Tramite <i>Modifica questa ricerca avanzata</i> sulla lista dei risultati o sotto <i>Il mio swissbib - Ricerche salvate</i>.</p>

<h3>Salvare una ricerca</h3>
<p>Sotto <i>Il mio swissbib - Ricerche salvate</i>.</p>

<!--
<h3>Ricevere una notifica quando nuovi documenti corrispondono alla tua ricerca</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>" alt="Feed RSS"> Abonnarsi</p> 
-->

<h2>Articoli &amp; più</h2>
<p>Funziona come <i>Libri &amp; più</i>, ma alcuni campi di ricerca e filtri sono diversi, in quanto <i>Articoli &amp; più</i> è un catalogo separato.</p>
