<h1>FAQ</h1>
<h2>Search</h2>
<ul class="list">
    <li><strong>Which fields does the basic search / search in <i>All fields</i> include?</strong>
        <br>... 
    </li>
</ul>

<h2>Display</h2>
<ul class="list">
  <li><strong>What is Sorting by relevancy?</strong>
        <br><i>Books &amp; more:</i><br>Hits in main title, author name and subjects rank higher than hits in other fields. New publications sort before older ones. These settings are tuned by us.<br>
        <i>Articles &amp; more:</i><br>Hits in author names rank highly, some of the full texts are indexed. Here we can't
        influence the order as it is part of the data we get from SerialsSolutions.
    </li>
 </ul>

<h2>Ordinare</h2>
<ul class="list">
        <li><strong>Potete inviarmi il documento xy?</strong>
            <br>Scegli la biblioteca dalla quale desideri ordinare il documento. Clicca su <i>Ordinare</i>. Se è possibile la spedizione postale al tuo recapito, la vedrai quale opzione sotto <i>Punto di ritiro</i>. 
                   </li>
       </ul>

<div class="example">Non trovi risposta alla tua domanda? Scrivicela sul <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, per <a href="mailto:swissbib-baselbern@unibas.ch">email</a> o tramite <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.
</div>