<h1>FAQ</h1>
<h2>Ricerca, Ricerca avanzata</h2>
<ul class="list">
         <li><strong>Can I search within a certain library?</strong>
         <br/>Either mark the library as favorite and filter your search results with <i>Refine search - Favorites</i> or use <i>Advanced search - Refine search - Library</i>.</li>   
     <li><strong>Che cosa significa Ordina per Rilevanza?</strong>
        <br/>I risultati in cui i termini della tua ricerca appaiono nei campi del titolo, dell'autore o del soggetto hanno priorità su quelli in cui i termini appaiono in altri campi bibliografici.</li>
     </ul>

<h2>Ordinare</h2>
<ul class="list">
        <li><strong>Potete inviarmi il documento xy?</strong>
            <br/>Scegli la biblioteca dalla quale desideri ordinare il documento. Clicca su <i>Ordinare</i>. Se è possibile la spedizione postale al tuo recapito privato, la troverai quale opzione sotto <i>Punto di ritiro/invio</i>. 
                   </li>
       </ul>

<h2>My swissbib</h2>
<ul class="list">
        <li><strong>Is there a shortcut to see what I have checked out?</strong>
            <br/><i>Log in</i>, then click on <i>Account: Your name</i>.<br> 
                   </li>
       </ul>       
       
<div class="example">Non trovi risposta alla tua domanda? Scrivicela sul <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, per <a href="mailto:swissbib-baselbern@unibas.ch">e-mail</a> o tramite <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.
</div>