<h1>FAQ</h1>
<h2>Ricerca, Ricerca avanzata</h2>
<ul class="list">
     <!--
     <li><strong>How can I search directly in <i>Articles & more</i>?</strong>
        <br/><a href="http://baselbern.swissbib.ch/Summon/Search" target="_blank">baselbern.swissbib.ch/Summon/Search</a>
    </li>
    -->
    <li><strong>La ricerca con l'uso delle parentesi non fornisce i risultati auspicati</strong>
        <br/>Ricerche del tipo <i>a AND (b OR c)</i> o <i>(a OR b) NOT c</i> non funzionano nel modulo della ricerca semplice. Usa la <i>Ricerca avanzata</i> introducendo le relative combinazioni di termini nei diversi gruppi di ricerca.</li>
    </ul>

<h2>Elenco dei risultati</h2>
<ul class="list">
     <li><strong>Che cosa significa Ordina per Rilevanza?</strong>
        <br/>I risultati in cui i termini della tua ricerca appaiono nei campi del titolo, dell'autore o del soggetto hanno priorità su quelli in cui i termini appaiono in altri campi bibliografici.</li>
          <li><strong>Is <i>Refine search - Subject</i> the same as <i>Advanced search - Subject</i>?</strong>
        <br/>Search for <i>Subject</i> in advanced search includes special subjects of single libraries and classifications.<br/>The facet <i>Subject</i> only shows controlled vocabulary (GND, MeSH, terms BS/BE).</li>
    </ul>

<h2>Ordinare</h2>
<ul class="list">
        <li><strong>Potete inviarmi il documento xy?</strong>
            <br/>Scegli la biblioteca dalla quale desideri ordinare il documento. Clicca su <i>Ordinare</i>. Se è possibile la spedizione postale al tuo recapito privato, la troverai quale opzione sotto <i>Punto di ritiro/invio</i>. 
                   </li>
       </ul>

<div class="example">Non trovi risposta alla tua domanda? Scrivicela sul <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, per <a href="mailto:swissbib-baselbern@unibas.ch">e-mail</a> o tramite <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.
</div>