<h1>Login, Il mio swissbib</h1>
<h2>Login</h2>

<p>Per l'autenticazione inserisci la tua <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis" target="_blank">identificazione IDS</a>, quella che usi anche per le ordinazioni nel catalogo.</p>

<h3>Perché il login?</h3>
<p>Per effettuare dei prestiti, per definire le tue biblioteche preferite, per recuperare liste o ricerche che hai salvato, per modificare le impostazioni.</p>

<h3>Hai dimenticato la password?</h3>
<p>Contatta la <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">tua biblioteca</a>.</p>


<h3>Perché il logout?</h3>
<p>Se stai usando un computer pubblico, effetua il logout per evitare che qualcun altro utilizzi il tuo conto.</p>

<h2>Il mio swissbib</h2>
<h3>Ricerche salvate</h3>
<p>Se non hai effettuato il login, le tue ricerche saranno salvate fino a quando non chiudi il browser. Puoi ripetere una ricerch oppure, dopo il login, salvarla a tempo indeterminato.</p>

<h3>Le mie preferite</h3>
<p>Se vuoi aggiungere una biblioteca a <i>Le mie preferite</i> puoi farlo attraverso <i>Il mio swissbib - Le mie preferite</i> oppure cliccando sull'icona del <img
        src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>" alt="Aggiungi alle mie preferite"> nel catalogo.</p>

<h3>Liste</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="Aggiungi a una lista"> Dopo il login puoi salvare dei titoli nelle tue liste.  <br/>Attenzione: se crei una nuova lista mentre stai salvando un titolo dovrai cliccare due volte su <i>Salva</i>.</p>
            
<h3>Impostazioni</h3>
<p>Lingua dell'interfaccia del catalogo, numero di titoli per pagina</p>

<h3>Conto IDS Basel Bern</h3>
<p>Funzioni di prestito</p>
