<h1>Salvare i risultati della ricerca</h1>

<table>
	<tbody>
	<tr>
        <td><img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
                 alt="<?= $this->transEsc('memorizelistadd')?>"
                 title="<?= $this->transEsc('memorizelistadd')?>">
        </td>
		<td>Aggiungi i risultati a una delle tue <strong>liste</strong></td>
	</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_rss.gif') ?>"
                 alt="<?= $this->transEsc('Get RSS Feed')?>"
                 title="<?= $this->transEsc('Get RSS Feed')?>">
        </td>
		<td>Richiedi di essere notificato via <strong>Feed</strong> quando nuovi documenti corrispondono alla tua ricerca</td>
	</tr>
    <tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_perma.gif') ?>"
                 alt="<?= $this->transEsc('Cite this')?>"
                 title="<?= $this->transEsc('Cite this')?>">
        </td>
        <td><strong>Citare</strong> i risultati</td>
    </tr>

    <tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_print.gif') ?>"
                 alt="<?= $this->transEsc('Print')?>"
                 title="<?= $this->transEsc('Print')?>"">
        </td>
		<td><strong>Stampa</strong> i risultati</td>
	</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_send.gif') ?>"
                 alt="<?= $this->transEsc('Email this')?>"
                 title="<?= $this->transEsc('Email this')?>">
        </td>
		<td>Invia i risultati per <strong>email</strong></td>
		</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_save.gif') ?>"
                 alt="<?= $this->transEsc('Export Items')?>"
                 title="<?= $this->transEsc('Export Items')?>">
        </td>
		<td><strong>Salva</strong> i risultati in vari formati</td>
	</tr>
	</tbody>
</table>

<h2>Ordinare</h2>

<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/order.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/it/order_small.png') ?>" alt="Zoom">
     </a>
    
    <ul class="list">
        <li>Clicca sul titolo.</li>
        <li>Scegli una biblioteca.</li>
        <li>Clicca su <i>Login</i> sotto il nome della biblioteca.</li>
        <li>Clicca su <i>Ordinare</i> o <i>Ordinare una fotocopia</i>.</li>
        <li>Se queste opzioni non sono visibili, significa che il documento non può essere ordinato online. Cliccando sull'icona <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Info biblioteca"> sotto Localizzazione puoi verificare gli orari d'apertura e l'indirizzo della biblioteca.</li>
    </ul>
</div>





