<h1>Salvare i risultati della ricerca</h1>

<table>
	<tbody>
	
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="add to list"></td>
		<td>Aggiungi i risultati a una delle tue <strong>liste</strong>.
		<br/>Attenzione: se crei una nuova lista mentre stai salvando un titolo dovrai cliccare due volte su <i>Salva</i>.
		</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
				 alt="get feed of new items matching this search"></td>
		<td>Richiedi di essere notificato via <strong>Feed</strong> quando nuovi documenti corrispondono alla tua ricerca.</td>
	</tr>
	
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>"
				 alt="Print"></td>
		<td><strong>Stampa</strong> i risultati.</td>
	</tr>
	
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>"
				 alt="Email this"></td>
		<td>Invia i risultati per <strong>email</strong>.</td>
		</tr>
	
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>"
				 alt="Export to ..."></td>
		<td><strong>Salva</strong> i risultati in vari formati.</td>
	</tr>

	</tbody>
</table>

<h2>Ordinare</h2>
<h3>Libri &amp; più</h3>
<ul class="list">
	<li>Clicca sul titolo</li>
	<li>Scegli una biblioteca</li>
	<li>Clicca su <i>Login</i> sotto il nome della biblioteca</li> 
	<li>Clicca su <i>Ordinare</i> o <i>Ordinare una fotocopia</i></li>
	<li>Se queste opzioni non sono visibili, significa che il documento non può essere ordinato online, p.es. perché si trova nella zona a scaffali aperti. Cliccando sull'icona <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>" alt="Info biblioteca"> accanto alla segnatura puoi verificare gli orari d'apertura e l'indirizzo della biblioteca.</li>
</ul>


<h3>Articoli &amp; più</h3>
<ul class="list">
	<li><i>get it</i> = link per visionare il testo integrale</li>
	<li><img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>" alt="SFX Services"> = link per visionare il testo integrale e/o accedere ad altri servizi sfx (ordinare un articolo, verificare la localizzazione del documento in Svizzera).</li>
</ul>