<?php
    // scripts
    $script = 'var vufindString = {};';
    $this->headScript()->prependScript($script);
    $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

    // Set up OpenSearch link:
    $this->headLink(
        array(
            'href' => $this->url('search-opensearch') . '?method=describe',
            'type' => 'application/opensearchdescription+xml',
            'title' => $this->transEsc('Library Catalog Search'),
            'rel' => 'search'
        )
    );
?>
<?=$this->headThemeResources()?>
<?=$this->headTitle()?>
<?=$this->headMeta()?>
<?=$this->headLink()?>
<?=$this->headScript()?>

