<div id="access" class="hidden">
	<h3>Sprungnavigation</h3>
	<ul>
		<li>
			<a accesskey="0" title="Startseite" href="home.html">Startseite Alt+0</a>
		</li>
		<li>
			<a accesskey="1" title="Navigation" href="#nav">Navigation Alt+1</a>
		</li>
		<li>
			<a accesskey="2" title="Inhalt" href="#col1">Inhalt Alt+2</a>
		</li>
		<li>
			<a accesskey="3" title="Kontakt" href="kontakt.html">Kontakt Alt+3</a>
		</li>
	</ul>
</div>