<?php
/** @var String $userLang Currently active user language */
$supportedLanguages = array(
	'de' => 'German',
	'en' => 'English',
	'fr' => 'French',
	'it' => 'Italian'
);
$languages = array();




$hostInfo = "";


$displayTestSystem = $this->configAccess()->Site->displayTestSystem ;
$displayTestSystem = !empty($displayTestSystem) && ($displayTestSystem == "true"  ||  $displayTestSystem == "1") ? "1" : 0;

if ($displayTestSystem) {
    $hostInfo =  '<li class="error">Testsystem!!!</li>';
}


foreach ($supportedLanguages as $langCode => $langName) {
	$languages[] = array(
		'code'     => $langCode,
		'label'    => $this->displayLanguageOption($langName),
		'selected' => $langCode == $userLang
	);
}
	// Replace language parameter
$baseUrl= preg_replace('/[&\?]?lng\=[a-z]+/', '', $this->serverUrl(true));
$baseUrl= preg_replace('/&/','&amp;',$baseUrl);
	// How to add the parameter: ? or &
$glue	= strpos($baseUrl, '?') === false ? '?' : '&amp;';

?>
<div id="meta">
	<h3 class="hidden">Metanavigation</h3>
	<ul>

        <?= $hostInfo ?>

		<?php foreach ($languages as $language): ?>
			<?php
			$class = 'nav_' . $language['code'] . ($language['selected'] ? ' selected' : '');
			$url   = $baseUrl . $glue . 'lng=' . $language['code'];
			?>
			<li class="<?= $class ?>">
				<a href="<?= $url ?>" title="<?= $language['label'] ?>"><?= $language['code'] ?></a>
			</li>
		<?php endforeach; ?>
	</ul>
</div>