<div id="navigation">
	<h3 class="hidden">Hauptnavigation</h3>
	<ul>
		<li class="nav_home">
			<a href="<?=$this->url('search-home');?>">Home</a>
		</li>
		<li>
			<a href="#">My swissbib</a>
			<ul class="subnavigation">
				<li>
					<a href="merklisten.html">Meine Merklisten</a>
				</li>
				<li>
					<a href="#">Meine Suchdienste</a>
				</li>
				<li>
					<a href="#">Meine Bibliotheken</a>
				</li>
				<li>
					<a href="#">Und etwas mehr Text damit es umbricht</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="inhaltsseite.html">Über swissbib</a>
		</li>
		<li>
			<a href="#">Feedback</a>
		</li>
		<li class="nav_help">
			<a href="#">Hilfe</a>
		</li>
	</ul>
</div>