<?php

	$isLoggedIn	= !!$this->auth()->isLoggedIn();

?>

<div id="navigation">
	<h3 class="hidden">Hauptnavigation</h3>
	<ul>
		<li class="nav_home">
			<a href="<?=$this->url('search-home');?>">Home</a>
		</li>
		<li>
			<a href="<?=$this->url('myresearch-home');?>"><?= $this->transEsc('menu.swissbib') ?></a>
			<ul class="subnavigation">
				<li>
					<a href="<?=$this->url('myresearch-favorite-institutions')?>"><?= $this->transEsc('menu.mylibraries') ?></a>
				</li>
				<?if ( $isLoggedIn ): ?>
					<li>
						<a href="<?=$this->url('search-settings');?>"><?=$this->transEsc('My_Search_Settings')?></a>
					</li>
					<li>
						<a href="<?=$this->url('myresearch-favorites');?>"><?=$this->transEsc('dotrans: Merklisten')?></a>
					</li>
					<li>
						<a href="<?=$this->url('search-history')?>"><?=$this->transEsc('history_saved_searches')?></a>
					</li>
					<li>
						<a href="#">Meine Suchdienste</a>
					</li>
				<? endif; ?>
			</ul>
		</li>
		<li>
			<a href="<?=$this->url('help-page',array('topic'=>'About'));?>"><?= $this->transEsc('menu.service.information') ?></a>
		</li>
		<li>
			<a title="Feedback" href="javascript:void(0)" style="cursor:not-allowed;"><?= $this->transEsc('menu.feedback') ?></a>
		</li>
		<li class="nav_help">
			<a href="<?=$this->url('help-page')?>"><?=$this->transEsc('Help')?></a>
		</li>
	</ul>
</div>