<?php
$isLoggedIn	= !!$this->auth()->isLoggedIn();
?>
<div id="navigation">
	<h3 class="hidden">Hauptnavigation</h3>
	<ul>
		<li class="nav_home">
			<a href="<?=$this->url('search-home');?>">Home</a>
		</li>
		<?php if( $isLoggedIn ): ?>
			<li>
				<a href="<?=$this->url('myresearch-home');?>">My swissbib</a>
				<ul class="subnavigation">
					<li>
						<a href="merklisten.html">Meine Merklisten</a>
					</li>
					<li>
						<a href="#">Meine Suchdienste</a>
					</li>
					<li>
						<a href="#">Meine Bibliotheken</a>
					</li>
					<li>
						<a href="#">Und etwas mehr Text damit es umbricht</a>
					</li>
				</ul>
			</li>
		<?php endif; ?>
		<li>
			<a href="inhaltsseite.html">Über swissbib</a>
		</li>
		<li>
			<a href="#">Feedback</a>
		</li>
		<li class="nav_help">
			<a href="#">Hilfe</a>
		</li>
	</ul>
</div>