<div id="pagefunctions" class="<?=$this->boxClass?>">
	<h3 class="hidden">Seitenfunktionen</h3>
	<ul>
		<li id="pagefunction_rss">
			<a href="#" title="<?=$this->transEsc('Get RSS Feed')?>"><?=$this->transEsc('Get RSS Feed')?></a>
		</li>
		<li id="pagefunction_link">
			<a title="Permanenter Link zu diesem/n Treffer(n)" class="modal" href="#display_permalink">permalink</a>
		</li>
		<li id="pagefunction_print">
			<a href="#" title="<?=$this->transEsc('Print')?>"><?=$this->transEsc('Print')?></a>
		</li>
		<li id="pagefunction_send">
			<a href="#" title="<?=$this->transEsc('Email this')?>"><?=$this->transEsc('Email this')?></a>
		</li>
		<?php
			$exportFormats = $this->export()->getFormatsForRecord($this->driver);
		?>
		<?php if (count($exportFormats) > 0): ?>
			<li id="pagefunction_save">
				<a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" title="<?=$this->transEsc('Save')?>"><?=$this->transEsc('Save')?></a>
				<ul class="menu" id="exportMenu">
					<?php foreach ($exportFormats as $exportFormat): ?>
						<?php
							$needsRedirect	= $this->export()->needsRedirect($exportFormat);
							$targetAttr		= $needsRedirect ? 'target=' . $this->escapeHtml($exportFormat) . 'Main' : '';
							$exportLink		= $this->recordLink()->getActionUrl($this->driver, 'Export') . '?style=' . $this->escapeHtml($exportFormat);
						?>
						<li>
							<a <?=$targetAttr?> href="<?=$exportLink?>"><?= $this->transEsc('Export to') ?> <?= $this->escapeHtml($exportFormat) ?></a>
						</li>
					<?php endforeach; ?>
				</ul>
			</li>
		<?php endif; ?>
	</ul>
</div>