<?php $pageFunctionsOffsetClass = isset($this->pageFunctionsOffsetClass) ? $this->pageFunctionsOffsetClass : ''; ?>
<div id="pagefunctions" class="<?=$pageFunctionsOffsetClass?>">
	<h3 class="hidden">Seitenfunktionen</h3>
	<ul>
		<li id="pagefunction_rss">
			<a href="#" title="RSS Feed abonnieren">RSS Feed</a>
		</li>
		<li id="pagefunction_link">
			<a title="Permanenter Link zu diesem/n Treffer(n)" class="modal" href="#display_permalink">permalink</a>
		</li>
		<li id="pagefunction_print">
			<a href="#" title="Seite drucken">Seite drucken</a>
		</li>
		<li id="pagefunction_send">
			<a href="#" title="Link per Email senden">Link per Email senden</a>
		</li>
		<li id="pagefunction_save">
			<a href="#" title="Seite speichern">Seite speichern</a>
		</li>
	</ul>
</div>