<?php

$resultViewParams	= $this->layout()->resultViewParams;
$lookFor			= $resultViewParams ? $resultViewParams->getDisplayQuery() : '';
/** @var VuFind\Search\Solr\Options	 $options  */
$options 			= $this->searchOptions();
$lastSort			= $options->getLastSort();
$lastLimit			= $options->getLastLimit();

?>
<div id="search">
	<form id="form_search" name="form_search" action="<?=$this->url('search-results')?>" method="get">
		<h3><label for="lookfor">Suchen nach</label></h3>
		<input type="text" class="text" name="lookfor" id="lookfor" autocomplete="off" value="<?=$this->escapeHtml($lookFor)?>" />
		<label for="search_submit" class="hidden">Suchanfrage senden</label>
		<input type="submit" class="submit primary" id="search_submit" name="search_submit" value="Suchen"/>
		<label for="search_favorites" class="checker">Nur in Favoriten</label>
		<input type="checkbox" class="hidden" id="search_favorites" name="search_favorites" />
		<a href="<?=$this->url('search-advanced')?>" title="Erweiterte Suche" id="search_extended">Erweiterte&nbsp;Suche</a>

		<?php /* Load hidden limit preference from Session */ ?>
		<?php if( !empty($lastLimit)): ?>
			<input type="hidden" name="limit" value="<?=$this->escapeHtml($lastLimit)?>" />
		<?php endif; ?>

		<?php if( !empty($lastSort)): ?>
			<input type="hidden" name="sort" value="<?=$this->escapeHtml($lastSort)?>" />
		<?php endif; ?>

	</form>
</div>