<?php

$isLoggedIn	= $this->auth()->isLoggedIn();

if( $isLoggedIn ) {
	/** @var VuFind\Db\Row\User $user  */
	$user = $isLoggedIn;
}

?>

<div id="service">
	<h3 class="hidden">Servicenavigation</h3>
	<ul>
        <?php if( $isLoggedIn ): ?>
            <li class="nav_account">
                <a href="<?=$this->url('myresearch-home');?>" title="<?=$this->transEsc('Your Account')?>">
                    <span><?=$this->transEsc('User Account')?></span>: <?=$this->escapeHtml($user->firstname . ' ' . $user->lastname)?>
                </a>
            </li>
            <li class="nav_logout">
                <a href="<?=$this->url('myresearch-logout')?>" title="<?=$this->transEsc('Log Out')?>"><?=$this->transEsc('Log Out')?></a>
            </li>
        <?php else: ?>
            <li class="nav_login">
                <a href="<?=$this->url('myresearch-home');?>" title="<?=$this->transEsc('Login')?>"><?=$this->transEsc('Login')?></a>
            </li>
        <?php endif; ?>
	</ul>
</div>