<?php

use VuFindSearch\Query\QueryGroup;
use VuFindSearch\Query\Query;

// Set page title
$this->headTitle($this->translate('Advanced Search'));

// Set up saved search details:

$jsSearchDetails = array();

if (isset($this->saved) && is_object($this->saved)) {
    /** @var QueryGroup $searchDetails */
    /** @var QueryGroup $searchGroup */
    /** @var Query $searchQuery */
    $searchDetails = $this->saved->getParams()->getQuery();
    $groups = $searchDetails->getQueries();
    $searchFilters = $this->saved->getParams()->getFilterList();

    if (is_object($searchDetails)) {
        foreach ($searchDetails->getQueries() as $searchGroup) {
            $groupData = array();
            foreach ($searchGroup->getQueries() as $searchQuery) {
                $groupData[] = array(
                    'lookfor' => $searchQuery->getString(),
                    'field' => $searchQuery->getHandler(),
                    'bool' => $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator()
                );
            }
            $jsSearchDetails[] = $groupData;
        }
    }
} else {
    $searchDetails = $searchFilters = $groups = false;
}

// Set up Javascript
// Step 1: Define our search arrays so they are usable in javascript

// Step 2: Call the javascript to make use of the above
$this->headScript()->appendFile('advanced_search.js');
$this->headScript()->appendFile('swissbib/AdvancedSearch.js');
$this->headScript()->appendFile('lib/handlebars.js');
// Step 3: Build the page
//    $this->headScript()->appendScript($this->partial('search/advanced/build_page.phtml', array('searchDetails' => $searchDetails)));
// Replace build_page
$this->headScript()->appendScript('swissbib.AdvancedSearch.searchDetails = ' . json_encode($jsSearchDetails) . ';');
$this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));

$lastSort = $this->options->getLastSort();



?>

<?= $this->render('search/advanced/templates-handlebars') ?>

<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
    <div id="col1_content" class="clearfix">
        <!-- begin: sidebar -->
        <?= $this->render('search/advanced/sidebar') ?>
        <!-- end: sidebar -->
    </div>
</div>
<!-- end: col1 (sidebar) -->
<!-- begin: col3 (content) -->
<div id="col3" class="content">
    <div id="col3_content" class="clearfix">
        <!-- begin: content -->
        <div id="content">

            <?php if (sizeof($this->allTabsConfig) > 1): ?>
                <div id="inlay">
                    <div id="tabbed">
                        <ul>
                            <?php foreach ($this->allTabsConfig as $tabKey => $tabConfig): ?>
                                <?php $isSelected = $tabKey === $this->activeTabKey; ?>
                                <li class="<?= $isSelected ? 'selected' : '' ?>">
                                    <a href="<?= $isSelected ? 'javascript:void(0)' : $this->url($tabConfig['advSearch']) ?>">
                                        <span><?= $this->transEsc($tabConfig['label']) ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>

            <h1><?= $this->transEsc('Advanced Search') ?></h1>
            <?= $this->flashmessages() ?>

            <form method="get" action="<?= $this->url($this->options->getSearchAction()) ?>" id="advSearchForm"
                  name="searchForm" class="search data">

                <?php if (!empty($lastSort)): ?>
                    <input type="hidden" name="sort" value="<?= $this->escapeHtml($lastSort) ?>"/>
                <?php endif; ?>
                <h3><?= $this->transEsc("Your search terms") ?></h3>

                <fieldset class="actions">
                    <label for="advancedsearch_submit" class="hidden"><?= $this->transEsc("Find") ?></label>
                    <input id="advancedsearch_submit" type="submit" class="submit primary"
                           value="<?= $this->transEsc("Find") ?>"/>
                    <label for="advancedsearch_reset" class="hidden"><?= $this->transEsc("Reset") ?></label>
                    <input id="advancedsearch_reset" name="advancedsearch_reset" type="reset" class="reset"
                           value="<?= $this->transEsc('Reset') ?>"/>
                </fieldset>

                <fieldset>


                    <div id="groupJoin" class="searchGroups">
                        <div class="searchGroupDetails">
                            <label for="groupJoinOptions"><?= $this->transEsc("search_match") ?>:</label>
                            <select id="groupJoinOptions" name="join">
                                <option value="AND"><?= $this->transEsc("group_AND") ?></option>
                                <option
                                    value="OR"<?= (isset($searchDetails) && is_object($searchDetails) && $searchDetails->getOperator() == 'OR') ? ' selected="selected"' : '' ?>><?= $this->transEsc("group_OR") ?></option>
                            </select>
                        </div>
                        <h4><?= $this->transEsc("search_groups") ?>:</h4>
                    </div>

                    <?php /* An empty div. This is the target for the javascript that builds this screen */ ?>
                    <div id="searchHolder">
                        <?php /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
                        <?php if (false): ?>
                            <noscript><?= $this->render('search/advanced/noscript.phtml') ?></noscript>
                        <?php endif; ?>
                    </div>

                    <div class="fieldbox">
                        <a href="javascript:void(0)" class="linkbutton small icon_add"
                           onclick="swissbib.AdvancedSearch.addNewGroup()"><span><?= $this->transEsc("add_search_group") ?></span></a>
                    </div>

                </fieldset>

                <?php if (isset($this->extraAdvancedControls)): ?>
                    <?= $this->extraAdvancedControls ?>
                <?php endif; ?>

                <fieldset class="actions">
                    <label for="advancedsearch_submit" class="hidden"><?= $this->transEsc("Find") ?></label>
                    <input id="advancedsearch_submit" type="submit" class="submit primary"
                           value="<?= $this->transEsc("Find") ?>"/>
                    <label for="advancedsearch_reset" class="hidden"><?= $this->transEsc("Reset") ?></label>
                    <input id="advancedsearch_reset" name="advancedsearch_reset" type="reset" class="reset"
                           value="<?= $this->transEsc("Reset") ?>"/>
                </fieldset>

            </form>

        </div>
        <!-- end: content -->
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>
<!-- end: col3 (content) -->