<div id="sidebar">

	<?php if( !empty($searchFilters) ): ?>
		<div class="filterList">
			<h3><?=$this->transEsc("adv_search_filters")?>
				<br/><span>(<?=$this->transEsc("adv_search_select_all")?> <input type="checkbox"
																				 checked="checked"
																				 onclick="filterAll(this, 'advSearchForm');"/>)</span>
			</h3>
			<?php foreach($searchFilters as $field => $data): ?>
				<div>
					<h4><?=$this->transEsc($field)?></h4>
					<ul>
						<?php foreach($data as $value): ?>
							<li><input type="checkbox" checked="checked" name="filter[]"
									   value='<?=$this->escapeHtml($value['field'])?>:"<?=$this->escapeHtml($value['value'])?>"'/> <?=$this->escapeHtml($value['displayText'])?>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>

	<!-- begin: subnavigation -->
	<h3>Suche</h3>
	<div class="subnavigation">
		<ul>
			<li class="selected">
				<a href="erweitertesuche.html" title="Erweiterte Suche">Erweiterte Suche</a>
			</li>
			<li>
				<a href="sucheinstellungen.html" title="Sucheinstellungen">Sucheinstellungen</a>
			</li>
			<li>
				<a href="suchhistorie.html" title="Suchhistorie">Suchhistorie</a>
			</li>
			<li>
				<a href="#" title="swissbib Labs">swissbib Labs</a>
				<ul>
					<li>
						<a href="#" title="Graphen Visualisierung">Graphen Visualisierung</a>
					</li>
					<li>
						<a href="#" title="Trends">Trends</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
	<!-- end: subnavigation -->

	<!-- begin: subnavigation -->
	<h3><?=$this->transEsc("Search Tips")?></h3>
	<div class="subnavigation">
		<ul>
			<li>
				<a href="<?=$this->url('help-home')?>?topic=searchadv"><?=$this->transEsc("Help with Advanced Search")?></a>
			</li>
			<li>
				<a href="<?=$this->url('help-home')?>?topic=search"><?=$this->transEsc("Help with Search Operators")?></a>
			</li>
		</ul>
	</div>
	<!-- end: subnavigation -->

</div>