<?php
$advSearch = $this->searchOptions($this->searchClassId)->getAdvancedSearchAction();
?>
<div id="sidebar">

	<?php if( !empty($searchFilters) ): ?>
		<div class="filterList">
			<h3><?=$this->transEsc("adv_search_filters")?>
				<br/><span>(<?=$this->transEsc("adv_search_select_all")?> <input type="checkbox"
																				 checked="checked"
																				 onclick="filterAll(this, 'advSearchForm');"/>)</span>
			</h3>
			<?php foreach($searchFilters as $field => $data): ?>
				<div>
					<h4><?=$this->transEsc($field)?></h4>
					<ul>
						<?php foreach($data as $value): ?>
							<li><input type="checkbox" checked="checked" name="filter[]"
									   value='<?=$this->escapeHtml($value['field'])?>:"<?=$this->escapeHtml($value['value'])?>"'/> <?=$this->escapeHtml($value['displayText'])?>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>

	<!-- begin: subnavigation -->
	<h3><?=$this->transEsc('Search')?></h3>
	<div class="subnavigation">
		<ul>
			<li class="selected">
                <a href="<?=$this->url($advSearch)?>" title="<?=$this->transEsc('Advanced Search')?>" id="search_extended"><?=$this->transEsc('Advanced Search')?></a>
			</li>
            <li>
                <a href="<?=$this->url('search-history')?>"><?=$this->transEsc('history_saved_searches')?></a>
            </li>
			<li>
                <a href="<?=$this->url('myresearch-settings');?>"><?=$this->transEsc('My_Search_Settings')?></a>
			</li>
		</ul>
	</div>
	<!-- end: subnavigation -->

</div>