<div id="sidebar">
	<!-- begin: subnavigation -->
	<h3>Suche</h3>
	<div class="subnavigation">
		<ul>
			<li class="selected">
				<a href="erweitertesuche.html" title="Erweiterte Suche">Erweiterte Suche</a>
			</li>
			<li>
				<a href="sucheinstellungen.html" title="Sucheinstellungen">Sucheinstellungen</a>
			</li>
			<li>
				<a href="suchhistorie.html" title="Suchhistorie">Suchhistorie</a>
			</li>
			<li>
				<a href="#" title="swissbib Labs">swissbib Labs</a>
				<ul>
					<li>
						<a href="#" title="Graphen Visualisierung">Graphen Visualisierung</a>
					</li>
					<li>
						<a href="#" title="Trends">Trends</a>
					</li>
				</ul>
			</li>
		</ul>
	</div><!-- end: subnavigation -->
</div>