<?php

$dateRangeName = isset($this->dateRangeName) ? $this->dateRangeName : 'publishDate';
$startYear = $searchClassId === 'Summon' ? 1980 : 1450;
$counter = 0;
$facetGroups = array();
$favoriteLanguages = array('ger', 'German', 'eng', 'English', 'fre', 'French', 'ita', 'Italian');

foreach ($this->facetList as $field => $list) {
    $groupIndex = (int)floor($counter++ / 2);

    if (!isset($facetGroups[$groupIndex])) {
        $facetGroups[$groupIndex] = array();
    }

    $facetGroups[$groupIndex][] = array(
        'field' => $field,
        'list'  => $list
    );
}

if (isset($this->dateRangeLimit)) {
    $this->headScript()->appendFile('pubdate_slider.js');
}

?>

<fieldset>
    <h3 class="toggler persist collapsed" id="searchoption_toggler_refine">
        <?= $this->transEsc('Limit To') ?>
    </h3>

    <div class="searchoption_toggler_refine">
        <div id="adv_tab" class="tabs">
            <ul>
                <? //@TODO Figure out tab names and translate them ?>
                <li><a href="#tab-1">Facetten</a></li>
                <? if (!empty($this->classificationTree)) : ?>
                <li><a href="#tab-2">Klassifikationsbaum</a></li>
                <? endif; ?>
            </ul>
            <div id="tab-1" class="tab">
                <?php foreach ($facetGroups as $facetGroup): ?>
                    <?php foreach ($facetGroup as $facet): ?>
                        <?php if($facet['field']==='navDrsys') continue; ?>
                        <div class="fieldbox">
                            <?php $fieldKey = str_replace(' ', '', $facet['field']); ?>

                            <label for="limit_<?= $this->escapeHtml($fieldKey) ?>" class="label"><?= $this->transEsc($facet['list']['label']) ?></label>
                            <select id="limit_<?= $this->escapeHtml($fieldKey) ?>" name="filter[]" class="select multiple large" multiple="multiple">

                                <?php
                                // Sort the current facet list alphabetically; we'll use this data
                                // along with the foreach below to display facet options in the
                                // correct order.
                                // These facet items will be translated using the translation mechanism
                                // of ZF2 instead of the translation mechanism of VuFind.
                                $sorted = array();
                                $customTranslate = array(
                                    'institution' => 'institution',
                                    'union'       => 'union'
                                );
                                foreach ($facet['list']['list'] as $index => $value) {
                                    $sorted[$index] = isset($customTranslate[$facet['field']]) ?
                                        $this->zendTranslate($value['displayText'], $customTranslate[$facet['field']])
                                        : $this->translate($value['displayText']);
                                }
                                natcasesort($sorted);
                                ?>

                                <?php if (strtolower($facet['field'])===strtolower("language")) : ?>
                            <?php foreach ($sorted as $index => $display): ?>
                                <?php $value = $facet['list']['list'][$index]; ?>
                                <? if (in_array($value['value'],$favoriteLanguages)) : ?>
                                    <option value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?> title="<?= $this->escapeHtml($display) ?>">
                                        <?= $this->escapeHtml($display) ?>
                                    </option>
                                <? endif; ?>
                            <?php endforeach; ?>
                                <optgroup label="<?= $this->transEsc('all_languages') ?>">
                                    <?php endif; ?>

                                    <?php foreach ($sorted as $index => $display): /* Render options of current facet's selector */ ?>
                                        <?php $value = $facet['list']['list'][$index]; ?>
                                        <option value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?> title="<?= $this->escapeHtml($display) ?>">
                                            <?= $this->escapeHtml($display) ?>
                                        </option>
                                    <?php endforeach; ?>

                                    <?php if ($facet['field']==="language") : ?>
                                </optgroup>
                            <?php endif; ?>

                            </select>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>

                <?= $this->render('search/advanced/limit'); ?>

                <?php
                if (isset($this->dateRangeLimit)) {
                    echo $this->render(
                        'search/advanced/daterange', array(
                                                          'name'           => $dateRangeName,
                                                          'dateRangeLimit' => $this->dateRangeLimit,
                                                          'startYear'      => $startYear
                                                     )
                    );
                }
                ?>
            </div>
            <? if (!empty($this->classificationTree)) : ?>
            <div id="tab-2" class="tab">
                <div class="fieldbox">
                    <div id="classification-tree" class="jstree jstree-default">
                    <? foreach($this->classificationTree as $classification){
                        echo $this->render(
                            'search/advanced/treeItem',
                            array(
                                 'classification' => $classification
                            )
                        );
                    }
                    ?>
                    </div>
                </div>
            </div>
            <? endif; ?>
        </div>
    </div>
    <script>
        $(function(){
            swissbib.AdvancedSearch.initializeTabs("#adv_tab", "#<?=$activeTabId?>");
        });
    </script>
</fieldset>