<?php

$dateRangeName = isset($this->dateRangeName) ? $this->dateRangeName : 'publishDate';
$counter = 0;
$facetGroups = array();
$favoriteLanguages = array('ger', 'German', 'eng', 'English', 'fre', 'French', 'ita', 'Italian');

foreach ($this->facetList as $field => $list) {
    $groupIndex = (int)floor($counter++ / 2);

    if (!isset($facetGroups[$groupIndex])) {
        $facetGroups[$groupIndex] = array();
    }

    $facetGroups[$groupIndex][] = array(
        'field' => $field,
        'list'  => $list
    );
}

if (isset($this->dateRangeLimit)) {
    $this->headScript()->appendFile('pubdate_slider.js');
}

?>

<div class="searchoption_toggler_refine">
    <?php foreach ($facetGroups as $facetGroup): ?>
        <?php foreach ($facetGroup as $facet): ?>
            <?php if($facet['field']==='navDrsys') continue; ?>
            <div class="fieldbox">
                <?php $fieldKey = str_replace(' ', '', $facet['field']); ?>

                <label for="limit_<?= $this->escapeHtml($fieldKey) ?>" class="label"><?= $this->transEsc($facet['list']['label']) ?></label>
                <select id="limit_<?= $this->escapeHtml($fieldKey) ?>" name="filter[]" class="select multiple xlarge" multiple="multiple">

                    <?php
                    // Sort the current facet list alphabetically; we'll use this data
                    // along with the foreach below to display facet options in the
                    // correct order.
                    // These facet items will be translated using the translation mechanism
                    // of ZF2 instead of the translation mechanism of VuFind.
                    $sorted = array();
                    $customTranslate = array(
                        'institution' => 'institution',
                        'union'       => 'union'
                    );
                    foreach ($facet['list']['list'] as $index => $value) {
                        $sorted[$index] = isset($customTranslate[$facet['field']]) ?
                            $this->zendTranslate($value['displayText'], $customTranslate[$facet['field']])
                            : $this->translate($value['displayText']);
                    }
                    natcasesort($sorted);
                    ?>

                    <?php if (strtolower($facet['field'])==="language") : ?>
                <?php foreach ($sorted as $index => $display): ?>
                    <?php $value = $facet['list']['list'][$index]; ?>
                    <? if (in_array($value['value'],$favoriteLanguages)) : ?>
                        <option value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?> title="<?= $this->escapeHtml($display) ?>">
                            <?= $this->escapeHtml($display) ?>
                        </option>
                    <? endif; ?>
                <?php endforeach; ?>
                    <optgroup label="<?= $this->transEsc('all_languages') ?>">
                        <?php endif; ?>

                        <?php foreach ($sorted as $index => $display): /* Render options of current facet's selector */ ?>
                            <?php $value = $facet['list']['list'][$index]; ?>
                            <option value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?> title="<?= $this->escapeHtml($display) ?>">
                                <?= $this->escapeHtml($display) ?>
                            </option>
                        <?php endforeach; ?>

                        <?php if ($facet['field']==="language") : ?>
                    </optgroup>
                <?php endif; ?>

                </select>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>

    <?= $this->render('search/advanced/limit'); ?>

    <?php
    if (isset($this->dateRangeLimit)) {
        echo $this->render(
            'search/advanced/daterange', array(
                                              'name'           => $dateRangeName,
                                              'dateRangeLimit' => $this->dateRangeLimit,
                                              'params'         => $params
                                         )
        );
    }
    ?>

</div>