<?php

$dateRangeName = isset($this->dateRangeName) ? $this->dateRangeName : 'publishDate';
$counter = 0;
$facetGroups = array();
$favoriteLanguages = array('ger', 'German', 'eng', 'English', 'fre', 'French', 'ita', 'Italian');

foreach ($this->facetList as $field => $list) {
    $groupIndex = (int)floor($counter++ / 2);

    if (!isset($facetGroups[$groupIndex])) {
        $facetGroups[$groupIndex] = array();
    }

    $facetGroups[$groupIndex][] = array(
        'field' => $field,
        'list'  => $list
    );
}

if (isset($this->ranges)) {
    $this->headScript()->appendFile('pubdate_slider.js');
}

?>

<div class="searchoption_toggler_refine">
    <?php foreach ($facetGroups as $facetGroup): ?>
        <?php foreach ($facetGroup as $facet): ?>
            <?php
            // GH: Why do we skip userInstitutions?
            // processing of userInstitutions (also called Favorites) is only consistent if the specialized Manger for this purposes
            //(Swissbibib\Favorites\Manager) is used.(see also Swissbib\Controller\FavoritesController - which is used for the route MyResearch/Favorites -
            //for further examples)
            //at initialization of the FavoritesManager (e.g.: conditions if the institutions are already loaded) is partly implemented in the Controller
            //This should be moved behind a Service Facade. The ServiceFacade could then be used by the advanced advanced search functionality
            ?>

            <?php if ($facet['field'] === 'navDrsys_Gen' || $facet['field'] === 'navDrsys_D' || $facet['field'] === 'userInstitutions') continue; ?>
            <div class="fieldbox">
                <?php $fieldKey = str_replace(' ', '', $facet['field']); ?>

                <label for="limit_<?= $this->escapeHtml($fieldKey) ?>" class="label"><?= $this->transEsc($facet['list']['label']) ?></label>
                <select id="limit_<?= $this->escapeHtml($fieldKey) ?>" name="filter[]" class="select multiple xlarge" multiple="multiple">

                    <?php
                    // Sort the current facet list alphabetically; we'll use this data
                    // along with the foreach below to display facet options in the
                    // correct order.
                    // These facet items will be translated using the translation mechanism
                    // of ZF2 instead of the translation mechanism of VuFind.
                    $sorted = array();
                    $customTranslate = array(
                        'institution' => 'institution',
                        'union'       => 'union'
                    );
                    foreach ($facet['list']['list'] as $index => $value) {
                        $sorted[$index] = isset($customTranslate[$facet['field']]) ?
                            $this->zendTranslate($value['displayText'], $customTranslate[$facet['field']])
                            : $this->translate($value['displayText']);
                    }
                    natcasesort($sorted);
                    ?>

                    <?php if (strtolower($facet['field'])==="language") : ?>
                <?php foreach ($sorted as $index => $display): ?>
                    <?php $value = $facet['list']['list'][$index]; ?>
                    <? if (in_array($value['value'], $favoriteLanguages)) : ?>
                        <option
                            value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?>
                            title="<?= $this->escapeHtml($display) ?>">
                            <?= $this->escapeHtml($display) ?>
                        </option>
                    <? endif; ?>
                <?php endforeach; ?>
                    <optgroup label="<?= $this->transEsc('all_languages') ?>">
                        <?php endif; ?>
                        <?php if (strtolower($facet['field']) === "format") : ?>

                        <option value='format:"*K01*"' title="article"><?= $this->transEsc('*K01*') ?></option>
                        <option value='format:"BK02*"' title="book"><?= $this->transEsc('BK02*') ?></option>
                        <option value='format:"*R0*"' title="continuing"><?= $this->transEsc('*R0*') ?></option>
                        <option value='format:"CL0*"' title="collection"><?= $this->transEsc('CL0*') ?></option>
                        <option value='format:"MU01*"' title="sheet_music"><?= $this->transEsc('MU01*') ?></option>
                        <option value='format:"MU03*"' title="sound"><?= $this->transEsc('MU03*') ?></option>
                        <option value='format:"MU04*"' title="music"><?= $this->transEsc('MU04*') ?></option>
                        <option value='format:"MP0*"' title="map"><?= $this->transEsc('MP0*') ?></option>
                        <option value='format:"VM01*"' title="film"><?= $this->transEsc('VM01*') ?></option>
                        <option value='format:"VM02*"' title="picture"><?= $this->transEsc('VM02*') ?></option>
                        <option value='format:"VM03*"' title="mx_game"><?= $this->transEsc('VM03*') ?></option>
                        <option value='format:"VM04*"' title="object"><?= $this->transEsc('VM04*') ?></option>
                        <option value='format:"CF0*"' title="software"><?= $this->transEsc('CF0*') ?></option>

                        <optgroup label="<?= $this->transEsc('all_formats') ?>">
                            <?php endif; ?>

                            <?php foreach ($sorted as $index => $display): /* Render options of current facet's selector */ ?>
                            <?php $value = $facet['list']['list'][$index]; ?>
                            <option value='<?= $this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"') ?>' <?= (isset($value['selected']) && $value['selected']) ? ' selected="selected"' : '' ?> title="<?= $this->escapeHtml($display) ?>">
                                <?= $this->escapeHtml($display) ?>
                            </option>
                        <?php endforeach; ?>

                            <?php if ($facet['field'] === "language") : ?>
                        </optgroup>
                    <?php endif; ?>
                        <?php if ($facet['field'] === "format") : ?>
                    </optgroup>
                <?php endif; ?>

                </select>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>

    <?= $this->render('search/advanced/limit'); ?>

    <?php
    if (isset($this->ranges)) {
        echo $this->render(
            'search/advanced/daterange', array(
                                              'name'           => $dateRangeName,
                                              'dateRangeLimit' => $this->ranges,
                                              'params'         => $params
                                         )
        );
    }
    ?>

</div>