<?php

$dateRangeName	= isset($this->dateRangeName) ? $this->dateRangeName : 'publishDate';
$counter 		= 0;
$facetGroups	= array();

foreach($this->facetList as $field => $list) {
	$groupIndex	= (int)floor($counter++/2);

	if( !isset($facetGroups[$groupIndex]) ) {
		$facetGroups[$groupIndex] = array();
	}

	$facetGroups[$groupIndex][] = array(
		'field'	=> $field,
		'list'	=> $list
	);
}

if( isset($this->dateRangeLimit) ) {
	$this->headScript()->appendFile('pubdate_slider.js');
}

?>

<fieldset>
	<h3 class="toggler persist collapsed" id="searchoption_toggler_refine">
		<?=$this->transEsc('Limit To')?>
	</h3>

	<div class="searchoption_toggler_refine">
		<?php foreach($facetGroups as $facetGroup): ?>
			<div class="fieldbox">

				<?php foreach($facetGroup as $facet): ?>
					<?php $fieldKey	= str_replace(' ', '', $facet['field']); ?>

					<label for="limit_<?=$this->escapeHtml($fieldKey)?>" class="label"><?=$this->transEsc($facet['list']['label'])?></label>
					<select id="limit_<?=$this->escapeHtml($fieldKey)?>" name="filter[]" class="select multiple" multiple="multiple">

						<?php
							// Sort the current facet list alphabetically; we'll use this data
							// along with the foreach below to display facet options in the
							// correct order.
							// These facet items will be translated using the translation mechanism
							// of ZF2 instead of the translation mechanism of VuFind.
							$sorted	= array();
							$customTranslate = array(
								'institution' => 'institution',
								'union'		  => 'union'
							);
							foreach($facet['list']['list'] as $index => $value) {
								$sorted[$index] = isset($customTranslate[$facet['field']]) ?
									$this->zendTranslate($value['displayText'], $customTranslate[$facet['field']])
								:	$this->translate($value['displayText']);
							}
							natcasesort($sorted);
						?>

						<?php foreach($sorted as $index => $display): /* Render options of current facet's selector */ ?>
							<?php $value = $facet['list']['list'][$index]; ?>
							<option value='<?=$this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"')?>' <?=(isset($value['selected']) && $value['selected']) ? ' selected="selected"' : ''?>>
								<?=$this->escapeHtml($display)?>
							</option>
						<?php endforeach; ?>

					</select>
				<?php endforeach; ?>

			</div>
		<?php endforeach; ?>


		<?=$this->render('search/advanced/limit');?>

		<?php
			if( isset($this->dateRangeLimit) ) {
				echo $this->render('search/advanced/daterange', array(
																	 'name'				=> $dateRangeName,
																	 'dateRangeLimit'	=> $this->dateRangeLimit
																));
			}
		?>

	</div>
</fieldset>