<?php

$counter 		= 0;
$facetGroups	= array();

foreach($this->facetList as $field => $list) {
	$index	= floor($counter/2);

	if( !isset($facetGroups[$index]) ) {
		$facetGroups[$index] = array();
	}

	$facetGroups[$index][] = array(
		'field'	=> $field,
		'list'	=> $list
	);

	$counter++;
}

if( isset($this->dateRangeLimit) ) {
	$this->headScript()->appendFile('pubdate_slider.js');
}

?>
<fieldset>

	<h3 class="toggler persist collapsed" id="searchoption_toggler_refine"><?=$this->transEsc('Limit To')?></h3>

	<div class="searchoption_toggler_refine">

		<?php foreach($facetGroups as $facetGroup): ?>
			<div class="fieldbox">

				<?php foreach($facetGroup as $facet): ?>
					<?php
						$fieldKey	= str_replace(' ', '', $facet['field']);
					?>

					<label for="limit_<?=$this->escapeHtml($fieldKey)?>" class="label"><?=$this->transEsc($facet['list']['label'])?></label>
					<select id="limit_<?=$this->escapeHtml($fieldKey)?>" name="filter[]" class="select multiple" multiple="multiple">

						<?php
							// Sort the current facet list alphabetically; we'll use this data
							// along with the foreach below to display facet options in the
							// correct order.
							$sorted = array();
							foreach($facet['list']['list'] as $index => $value) {
								$sorted[$index] = $value['displayText'];
							}
							natcasesort($sorted);
						?>
						<?php foreach($sorted as $index => $display): ?>
							<?php $value = $facet['list']['list'][$index]; ?>
							<option value='<?=$this->escapeHtml($facet['field'] . ':"' . $value['value'] . '"')?>' <?=(isset($value['selected']) && $value['selected']) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($display)?></option>
						<?php endforeach; ?>

					</select>
				<?php endforeach; ?>

			</div>
		<?php endforeach; ?>




		<?php if( isset($this->illustratedLimit) ): ?>

			<div class="fieldbox">
				<label class="label"><?=$this->transEsc("Illustrated")?></label>

				<div class="vertical">
					<?php foreach($this->illustratedLimit as $illustration): ?>
						<input type="radio" <?=$illustration['selected'] ? 'checked="checked"':''?> value="<?=$this->escapeHtml($illustration['value'])?>" class="radio" name="illustration" id="illustrated_<?=$this->escapeHtml($illustration['value'])?>">
						<label class="radiolabel" for="illustrated_<?=$this->escapeHtml($illustration['value'])?>"><?=$this->transEsc($illustration['text'])?></label>
						<br>
					<?php endforeach; ?>
				</div>
			</div>

		<?php endif; ?>



		<?php
		    $limitList		= $this->options->getLimitOptions();
		    $lastLimit		= $this->options->getLastLimit();
		    $selectedLimit	= empty($lastLimit) ? $this->options->getDefaultLimit() : $lastLimit;
		?>
		<?php if( count($limitList) > 1 ): ?>
			<div class="fieldgroup">
				<div class="fieldbox">
					<label class="label" for="limit"><?=$this->transEsc('Results per page')?></label>
					<select class="select tiny" name="limit" id="limit">
						<?php foreach($limitList as $limitVal): ?>
							<option value="<?=$this->escapeHtml($limitVal)?>"<?=($limitVal == $selectedLimit) ? 'selected="selected"' : ''?>><?=$this->escapeHtml($limitVal)?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
		<? endif; ?>



		<?php if( isset($this->dateRangeLimit) ): ?>

			<div class="fieldbox">
				<label class="label"><?=$this->transEsc('adv_search_year')?></label>
				<div class="vertical yearSliderBox">
					<input type="hidden" name="daterange[]" value="publishDate"/>

					<label for="publishDatefrom"><?=$this->transEsc('date_from')?>:</label>
					<input type="text" size="4" maxlength="4" class="yearbox text" name="publishDatefrom" id="publishDatefrom" value="<?=$this->escapeHtml($this->dateRangeLimit[0])?>"/>

					<label for="publishDateto"><?=$this->transEsc('date_to')?>:</label>
					<input type="text" size="4" maxlength="4" class="yearbox text" name="publishDateto" id="publishDateto" value="<?=$this->escapeHtml($this->dateRangeLimit[1])?>"/>

					<br>
					<div id="publishDateSlider" class="dateSlider"></div>
				</div>
			</div>

		<?php endif; ?>

	</div>

</fieldset>
