<script id="adv-search-field" type="text/x-handlebars-template">
	<div class="advRow fieldbox">
		{{{label}}}
		{{{term}}}
		{{{selector}}}
	</div>
</script>

<script id="adv-search-field-label" type="text/x-handlebars-template">
	<div class="label">
		<label for="search_lookfor{{groupIndex}}_{{fieldIndex}}" class="{{classes}}">{{label}}:</label>
		&nbsp;
	</div>
</script>

<script id="adv-search-field-term-text" type="text/x-handlebars-template">
	<div class="terms">
		<input type="text" class="text large" value="{{value}}" size="{{size}}" name="lookfor{{groupIndex}}[]" id="search_lookfor{{groupIndex}}_{{fieldIndex}}">
	</div>
</script>

<script id="adv-search-field-field-selector" type="text/x-handlebars-template">
	<div class="field">
		<label for="search_type{{groupIndex}}_{{fieldIndex}}">{{label}}</label>
		<select class="select" name="type{{groupIndex}}[]" id="search_typ{{groupIndex}}_{{fieldIndex}}">
			{{#each options}}
				<option value="{{name}}" {{#if selected}}selected="selected"{{/if}}>{{label}}</option>
			{{/each}}
		</select>
	</div>
</script>

<script id="adv-search-group" type="text/x-handlebars-template">
	<div id="group{{groupIndex}}" class="group">
		{{{searchDetails}}}
		<div id="group{{groupIndex}}SearchHolder" class="groupSearchHolder"></div>
		{{{addLink}}}
	</div>
</script>

<script id="adv-search-group-searchDetails" type="text/x-handlebars-template">
	<div class="groupSearchDetails">
		<div class="join">
			<label for="search_bool{{groupIndex}}">{{matchLabel}}:</label>
			<select name="bool{{groupIndex}}[]" id="search_bool{{groupIndex}}">
				{{#each joins}}
					<option value="{{name}}" {{#if selected}}selected="selected"{{/if}}>{{label}}</option>
				{{/each}}
			</select>
		</div>
            <a onclick="swissbib.AdvancedSearch.deleteThisGroup(this)" id="delete_link_{{groupIndex}}" class="linkbutton small icon_delete" href="javascript:void(0)" style="display: inline;"><span>{{deleteLabel}}</span></a>
	</div>
</script>

<script id="adv-search-group-addfield" type="text/x-handlebars-template">
	<div class="floatbox">
		<a onclick="swissbib.AdvancedSearch.addFieldToThisGroup(this)" id="add_search_link_{{groupIndex}}" class="linkbutton small icon_add" href="javascript:void(0)"><span>{{addLabel}}</span></a>
	</div>
</script>



