<?php
/** @var Array $autocompleterData */

$this->headTitle($this->translate('mylibraries'));
?>
<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
    <div id="col1_content" class="clearfix">
        <!-- begin: sidebar -->
        <div id="sidebar">

        </div>
        <!-- end: sidebar -->
    </div>
</div>
<!-- end: col1 (sidebar) -->
<!-- begin: col3 (content) -->
<div id="col3" class="content">
    <div id="col3_content" class="clearfix">
        <!-- begin: content -->

        <div id="content">
             <div>
                 <p>&nbsp;</p>
             </div>
			<h2>Zu Favoriten hinzufügen</h2>

                <form class="form">
					<div class="fieldgroup">
                        <fieldset>
                            <div class="fieldbox">
                                <label for="query" class="label"><?=$this->transEsc('Library')?></label>
                                <input type="text" id="query" class="text large" />
                            </div>
                        </fieldset>
					</div>
                </form>

			<div id="user-favorites">
				<?=$this->render('favorites/selectionList')?>
			</div>

        </div>
        <!-- end: content -->
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>
<!-- end: col3 (content) -->

<script type="text/javascript">
	jQuery(function(){
		swissbib.FavoriteInstitutions.init(<?=json_encode($autocompleterData)?>);
	});
</script>


<?php /** $this->inlineScript()->appendFile("sbfavorites.js");*/ ?>