<?php
/** @var Array $availableInstitutions */

?>
<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
    <div id="col1_content" class="clearfix">
        <!-- begin: sidebar -->
        <div id="sidebar">

        </div>
        <!-- end: sidebar -->
    </div>
</div>
<!-- end: col1 (sidebar) -->
<!-- begin: col3 (content) -->
<div id="col3" class="content">
    <div id="col3_content" class="clearfix">
        <!-- begin: content -->

        <div id="content">

            <div id="add-favorites">
                <form   action="#"   onSubmit="return false;" method="get">
                    <h2>Zu Favoriten hinzufügen</h2>

                    <fieldset>
                        <div class="fieldbox">
                            <label for="libraryname" class="label"><strong>Bibliotheksname</strong> (name / code / place)</label>
                            <input  type="text"  id="libraryname" class="text large" />
                        </div>

                    </fieldset>
                </form>
            </div>

			<div id="user-favorites">
				<?=$this->render('favorites/selectionList')?>
			</div>

        </div>
        <!-- end: content -->
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>
<!-- end: col3 (content) -->

<script type="text/javascript">
	jQuery(function(){
		swissbib.FavoriteInstitutions.init(<?=json_encode($availableInstitutions)?>);
	});
</script>


<?php /** $this->inlineScript()->appendFile("sbfavorites.js");*/ ?>