<?php
/** @var Array $userInstitutions */
/** @var Array[] $userInstitutionsList */
?>
<h2>Meine Favoriten</h2>

<table class="data" id="favorites-table">

	<?php foreach ($userInstitutionsList as $groupCode => $groupInstitutions): ?>

		<tr>
			<td colspan="2">
				<strong><?=$this->escapeHtml($this->zendTranslate($groupCode, 'group'))?></strong>
			</td>

		</tr>

		<?php foreach ($groupInstitutions as $institutionCode): ?>

			<tr>
				<td style="padding-left: 2em" class="nodivider">
					<?=$this->escapeHtml($this->zendTranslate($institutionCode, 'institution'))?>

					<a href="http://aleph.unibas.ch/F/?func=library&sub_library=A100" class="externallink" title="Bibliotheksinformation"></a>
				</td>
				<td class="right">
					<a href="#" class="linkbutton icon_delete deleteFavoriteInstitution" title="Favorit löschen" data-institution="<?=$institutionCode?>"><span>löschen</span></a>
				</td>
			</tr>

		<?php endforeach; ?>

	<?php endforeach; ?>

</table>