<?php
/** @var Array $userInstitutions */
/** @var Array[] $userInstitutionsList */
?>
<h2><?= $this->transEsc('mylibraries') ?></h2>

<table class="data" id="favorites-table">

    <?php foreach ($userInstitutionsList as $groupCode => $groupInstitutions): ?>

        <tr>
            <td colspan="2">
                <strong><?= $this->escapeHtml($this->zendTranslate($groupCode, 'group')) ?></strong>
            </td>

        </tr>

        <?php foreach ($groupInstitutions as $institutionCode): ?>

            <tr>
                <td style="padding-left: 2em" class="nodivider">
                    <?= $this->escapeHtml($this->zendTranslate($institutionCode, 'institution')) ?>
                    <a href="<?= $this->escapeHtml($this->zendTranslate($institutionCode, 'bibinfo')) ?>"
                       class="externallink" title="<?= $this->transEsc('Library_Information') ?>" target="_blank"></a>
                </td>
                <td class="right">
                    <a href="#" class="linkbutton icon_delete deleteFavoriteInstitution"
                       title="<?= $this->transEsc('mylibraries.remove') ?>"
                       data-institution="<?= $institutionCode ?>"><span><?= $this->transEsc('Delete') ?></span></a>
                </td>
            </tr>

        <?php endforeach; ?>

    <?php endforeach; ?>

</table>