<h1>About swissbib</h1>

<h2>Contact</h2>
<p>Write a comment in our <a href="http://swissbib-baselbern.blogspot.ch">blog</a>, an email to
    <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> or contact
    <a href="https://twitter.com/swissbibBB">@swissbibBB</a>.</p>
<p>For questions about a certain work please contact the <a href="http://www.swissbib.ch/libraries">owning library</a> directly (link <i>Library Information</i> in the catalog).</p>
<p>For questions about your account please contact <a href="http://www.swissbib.ch/libraries">your library</a>.</p>


<h2>News</h2>
<p>Follow our <a href="http://swissbib-baselbern.blogspot.ch">blog</a> or <a href="https://twitter.com/swissbibBB">@swissbibBB</a>.</p>

<h2>Data in Books &amp; more</h2>
<!--
<p>For more details see <a
href="http://swissbib-baselbern.blogspot.com/2012/05/bucher-mehr-zwischen-ids-basel-bern-und.html">this blog
post</a> (in German).</p>
-->
<h3>Region Basel</h3>
<ul class="list">
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken">Verbundbibliotheken
        IDS</a></li>
    <li><a href="http://www.fhnw.ch/bibliothek">Fachhochschule Nordwestschweiz</a></li>
</ul>
<h3>Region Bern</h3>
<ul class="list">
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken">Verbundbibliotheken
        IDS</a></li>
    <li><a href="http://www.nb.admin.ch">Schweizerische Nationalbibliothek</a>
    </li>
    <li><a href="http://www.bewi.unibe.ch">Bibliothek exakte Wissenschaften Bern</a></li>
    <li><a href="http://www.bfh.ch/service/bibliotheken.html">Berner Fachhochschule</a></li>
    <li><a href="http://www.swissbib.ch/libraries/placelist.html">other libraries in Bern</a></li>
</ul>

<h3>Full text online</h3>
<ul class="list">
    <li><a href="http://retro.seals.ch">RetroSeals</a>: <a
            href="http://baselbern.swissbib.ch/TouchPoint/start.do?Language=de&amp;View=bb&amp;Query=1810=%22retros%22 ">almost
        300'000 articles</a> from retrodigitized scientific journals
    </li>
</ul>

<h3>IDS-Kurier</h3>
<ul class="list">
    <li><a href="http://www.ub.unibas.ch/ids-basel-bern/ids-kurierbibliotheken">IDS-Kurierbibliotheken</a> in Luzern, St. Gallen und Zürich</li>
</ul>


<h2>Data in Articles &amp; more</h2>
<ul class="list">
    <li><a href="http://www.serialssolutions.com/en/services/summon/content">Summon by SerialsSolutions</a>
        <!--
<br>If you are not logged in to the university network in Basel or Bern your search is limited to texts with
open access.
-->
    </li>
</ul>