<h1>FAQ</h1>

<h2>Search</h2>
<ul class="list">
    <!--
       <li><strong><i>Articles &amp; more</i>: no hits for search with ? and ~.</strong>
           <br>? and ~ only wirk in <i>Books &amp; more</i>.
       </li>

       <li><strong>Can I search for "Basel only" or "Bern only"?</strong>
           <br>You can use these search boxes: <a
                   href="http://baselbern.swissbib.ch/TouchPoint/bb/common/sb_bb_search_box_nur_basel.html">nur Basel</a>,
           <a href="http://baselbern.swissbib.ch/TouchPoint/bb/common/sb_bb_search_box_nur_bern.html">nur Bern</a>.
       </li>

       <li><strong>How do I search for the holdings of a certain library?</strong>
           <br>For the moment: add the libraray code as an additional search term or define the library as a favourite.<br>
           <a href="http://m.baselbern.swissbib.ch">Mobile</a>: choose a library via <i>Options</i>: <a
                   href="http://baselbern.swissbib.ch/mobile/data/bibliotheksliste-basel.html">Basel</a>, <a
                   href="http://baselbern.swissbib.ch/mobile/data/bibliotheksliste-bern.html">Bern</a>. Searches only in
           <i>Books &amp; more</i>.
       </li>

       <li><strong>Is there an app? </strong>
           <br>No, but your mobile device should be redirected automatically to <a href="http://m.baselbern.swissbib.ch">m.baselbern.swissbib.ch</a>.
       </li>
     -->
    <li><strong>Searching for hyphenated terms returns too many hits.</strong>
        <br>Put quotation marks around the term.
    </li>

</ul>


<h2>Display</h2>
<ul class="list">
    <li><strong><i>Circulation state</i> is always empty.</strong>
        <br>Some functions need JavaScript, which seems to be disabled on your computer.
    </li>

    <!--
        <li><strong>The QR-Code doesn't work.</strong>
            <br>Click on the icon to make it bigger.
        </li>
    -->
    <li><strong><i>URL: Onlinezugriff</i> doesn't link to the full text.</strong>
        <br>The link only works if you are logged in to the network of a university that has a licence for this title.
    </li>

    <li><strong>What is Sorting by relevancy?</strong>
        <br><i>Books &amp; more:</i> Hits in title fields, especially journal titles, rank higher than hits in author
        names or themes. New publications sort before older ones. These settings are tuned by us.<br>
        <i>Articles &amp; more:</i> Hits in author names rank highly, some of the full texts are indexed. Here we can't
        influence the order as it is part of the data we get from Summon Local.
    </li>

    <li><strong>Why are there titles with the facet <i>Article</i> in <i>Books &amp; more</i>?</strong>
        <br><i>Books &amp; more</i> and <i>Articles &amp; more</i> are two seperate catalogs, see <i><a href="about.phtml">About swissbib</a></i>
    </li>

    <li><strong>Why does it take so many clicks to get to the <i>Informations about holdings</i>?</strong>
        <br>Shortcut: hold the mouse over the <img
                src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_info.gif') ?>"> in the result list,
        then click on the name of the library you are interested in.
    </li>

</ul>

<h2>Order</h2>
<ul class="list">
    <li><strong><i>get it - sfx</i> claims "Full text provided ...", but when I click <i>GO</i>, I get "No results were
        found".</strong>
        <br>Empty some of the fields <i>Year Volume Issue Start Page</i>, for example only leaving the year. Often this
        gets you to an overview from where you then can pick the volume you are looking for.<br>If you are not logged in
        to a university network only the <i>get it</i> link is working.
    </li>
</ul>

<div class="example">Is your question not covered? Ask us in the <a
        href="http://swissbib-baselbern.blogspot.com">blog</a>, by <a href="mailto:swissbib-baselbern@unibas.ch">email</a> or <a href="https://twitter.com/swissbibBB">@swissbibBB</a>.
</div>