<h1>My swissbib</h1>
<h2>Login</h2>

<p>Use your <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis">IDS account</a> for logging in.</p>

<h2>Forgot your password?</h2>
<p>Please contact <a href="http://www.swissbib.ch/libraries/index.html">your library</a>.</p>

<!--
<p>When you are logged in you can create <strong>additional lists</strong> and save your <strong>search
       preferences</strong>.

</p>
<p><strong>Previous searches</strong>
   <br>When you are logged in your last 50 searches are saved. You can <i>execute</i> them again or - via <i>Select for
       search</i> - push them to <i>Advanced search</i> to add more parameters.
</p>

   -->


<h2>Favorites</h2>
<p>To add a library to <i>Favorites</i> either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>" alt="Add to my favourites"> next to <i>Library Information</i>.
    <!--
	<br>Titles in those libraries and are marked with a <img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>">, score
	higher in relevancy and can be used as facets.
	-->
</p>