<h1>Save</h1>
<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>"
				 alt="Add to My list"></td>
		<td>Add result/s to a <strong>list</strong>.<br /><br />
			You can have several lists and you can decide for each list if it should be public or only visible for yourself. [Details to follow.]
		</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>"
				 alt="Save items locally"></td>
		<td><strong>Export</strong> result/s in different formats.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>"
				 alt="Send items"></td>
		<td><strong>Email</strong> a link to result/s.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>"
				 alt="Print items"></td>
		<td><strong>Print</strong> result/s.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
				 alt="subscribe to Atom feed"></td>
		<td><strong>Feed</strong> notification about new titles that match your search.</td>
	</tr>
	</tbody>
</table>

<h2>Order</h2>
<h3>Books &amp; more</h3>
<ul class="list">
	<li>Click on <strong>Loan</strong></li>
	<li>[Details to follow.]</li>
	<li><i>retro.seals</i> = link to full text</li>
</ul>
<h3>Articles &amp; more</h3>
<ul class="list">
	<li><i>get it</i> = link to full text</li>
	<li><i>sfx</i> = link to full text and/or other sfx services</li>
</ul>