<h1>Save</h1>
<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>"
				 alt="Add to My list"></td>
		<td>Add result/s to the <strong>Temporary list</strong>.<br>
			When you are logged in you can create additional lists: <i>My swissbib - My list - New list</i>.
		</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>"
				 alt="Save items locally"></td>
		<td>Different formats to save result/s as a <strong>file</strong>.</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>"
				 alt="Send items"></td>
		<td><strong>Email</strong> result/s in different formats.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>"
				 alt="Print items"></td>
		<td><strong>Print</strong> result/s in different formats.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_perma.gif') ?>"
				 alt="Permanent link"></td>
		<td><strong>Share</strong> link on facebook, Twitter etc.</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
				 alt="subscribe to Atom feed"></td>
		<td><strong>Atom feed</strong> notification about new titles that match your search.</td>
	</tr>
	</tbody>
</table>

<h2>Order</h2>
<h3>Books &amp; more</h3>
<ul class="list">
	<li>Click on the title</li>
	<li>Choose a library</li>
	<li><i>Go to holdings</i> = lending functions of that library</li>
	<li><i>retro.seals</i> = link to full text</li>
</ul>
<h3>Articles &amp; more</h3>
<ul class="list">
	<li><i>get it</i> = link to full text</li>
	<li><i>get it - sfx</i> = link to full text and/or other sfx services</li>
</ul>