<h1>Search</h1>

<p>
    <strong>Combine</strong>
    <br>AND, OR, NOT. Example: <i>art* OR kunst*</i>
    <br>The operators must be written in capital letters, default is AND.
</p>

<p>
    <strong>Phrase search</strong>
    <br><i>"street art"</i> = the words must be adjacent
    <br><i>"street art"~5</i> = must be present within 5 words</p>

<p>
    <strong>Truncation</strong></p>
<table>
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">replaces any number of letters</td>
        <td><i></i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>

    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">replaces exactly one letter</td>
        <td><i>wom?n</i></td>
        <td>woman, women</td>
    </tr>

    <tr>
        <td>~</td>
        <td>fuzzy search</td>
    <tr>
        <td><i>Lindquist~</i></td>
        <td>Lindquist, Lindkvist, Lindqvist</td>
    </tr>
    </tr>
    </tbody>
</table>

<p>
    <strong>ISBN, ISSN etc.</strong>
    <br>Use quotation marks.</p>

<h1>Advanced search</h1>
<p>[Following soon]</p>
	