<h1>Search boxes</h1>
<p>To try the search boxes click <i>To the HTML code</i>.</p>
<p>Saving the code for your own site: hold the mouse over <i>To the HTML code</i> - right click - <i>Download Linked
		File as</i>.</p>
<h3>One library</h3>
<p>Alternatively: type the library code as an additional word in your search.</p>
<p><a href="bb/common/sb_bb_search_box_1_sublib.html">To the HTML code</a></p>
<!-- Start: swissbib Basel Bern search box -->
<!-- by Projekt swissbib (2012) -->
<!-- Hintergrundfarbe -->
<div style="background: #FF9900  bottom no-repeat; width: 430px; height:80px;">
	<script type="text/javascript">
		function search_sbbb() {
			var basic_url = "http://baselbern.swissbib.ch/TouchPoint/start.do";
			<!-- Sprache der Oberflaeche -->
			var first_fix_part = "?Language=de&Query=-1=\"";
			var search_value = encodeURIComponent(document.getElementById('INPUT_SWISSBIB_SEARCH').value.replace(/"/g, "\\\"")) + "\"";
			<!-- fuer anderen Bibliotheksfilter, wechsle den Zweigstellencode und die Bezeichnung im Label unten -->
			<!-- falls ein Filter auf Materialtyp gewuenscht ist, ersetze 1805 mit 330 und dem entsprechenden Materialcode -->
		<
			!--Liste
			der
			Codes: http://www.swissbib.org/wiki/index.php?title=Filtering#format_code (klein schreiben, koennen trunkiert werden) -->
				<!-- Beispiel fuer Comic: filter_restriction = ' AND 330="bk0401*"' -->
					var filter_restriction = "";
			if(document.getElementById("filterMaps").checked) {
				filter_restriction = ' AND 1805="A296"';
			}
			var query_parameter = first_fix_part + search_value + filter_restriction;
			var search_all_url = basic_url + query_parameter;
			window.open(search_all_url);
			return false;
		}
	</script>
	<!-- Hintergrundfarbe des Icon -->
	<div style="margin:5px 0 0 15px; background: #FF9900; height: 5px; padding-left:130px;"></div>
	<div style="margin:0 0 0 15px; background: #FF9900  url(http://baselbern.swissbib.ch/TouchPoint/bb/common/style/css/themes/orange/img/logo_swissbib_bern-basel.gif) no-repeat; height: 65px; padding-left:130px;">
		<form style="padding:10px 0 0 40px; " onsubmit="return search_sbbb();">
			<fieldset style="margin: 0; padding: 0; border: none;">
				<input style="display:block;float:left;width:230px;" name="SEARCH_ALL" id="INPUT_SWISSBIB_SEARCH"
					   type="text">
				<input style="height:25px; width:80px;  margin-top:5px; display:block;float:left;" value="Suchen"
					   type="submit">
				<!--falls checkbox leer sein soll, lass die Option "checked" leer -->
				<input id="filterMaps" style="margin:10px 5px 0 5px; padding-left:10px; display:block; float:left;"
					   value="Search" checked="checked" type="checkbox">
				<!-- Label : Farbe und Text-->
				<label style="margin-top:5px; color:#2F333C;font-family:Arial,Helvetica,sans-serif;font-size:11px;margin:-25px 10px 5px 110px;"
					   for="filtermaps">nur Bibliothek für Gestaltung</label>
			</fieldset>
		</form>
	</div>
</div>
<!-- End: swissbib Basel Bern search box-->

<p><br></p>
<h3>Several libraries</h3>
<p><a href="bb/common/sb_bb_search_box_8_sublibs.html">To the HTML code</a> (8 library codes)</p>

<p><br></p>
<h3>Format code</h3>
<p><a href="http://www.swissbib.org/wiki/index.php?title=Filtering#format_code">List of format codes</a></p>
<p><a href="bb/common/sb_bb_search_box_formatcode.html">To the HTML code</a></p>
<!-- Start: swissbib Basel Bern search box -->
<!-- by Projekt swissbib (2012) -->
<!-- Hintergrundfarbe -->
<div style="background: #FF9900  bottom no-repeat; width: 430px; height:80px;">
	<script type="text/javascript">
		function search_sbbb() {
			var basic_url = "http://baselbern.swissbib.ch/TouchPoint/start.do";
			<!-- Sprache der Oberflaeche -->
			var first_fix_part = "?Language=de&Query=-1=\"";
			var search_value = encodeURIComponent(document.getElementById('INPUT_SWISSBIB_SEARCH').value.replace(/"/g, "\\\"")) + "\"";
			<!-- fuer anderen Bibliotheksfilter, wechsle den Zweigstellencode und die Bezeichnung im Label unten -->
			<!-- falls ein Filter auf Materialtyp gewuenscht ist, ersetze 1805 mit 330 und dem entsprechenden Materialcode -->
		<
			!--Liste
			der
			Codes: http://www.swissbib.org/wiki/index.php?title=Filtering#format_code (klein schreiben, koennen trunkiert werden) -->
				<!-- Beispiel fuer Comic: filter_restriction = ' AND 330="bk0401*"' -->
					var filter_restriction = "";
			if(document.getElementById("filterMaps").checked) {
				filter_restriction = ' AND 330="mp*"';
			}
			var query_parameter = first_fix_part + search_value + filter_restriction;
			var search_all_url = basic_url + query_parameter;
			window.open(search_all_url);
			return false;
		}
	</script>
	<!-- Hintergrundfarbe des Icon -->
	<div style="margin:5px 0 0 15px; background: #FF9900; height: 5px; padding-left:130px;"></div>
	<div style="margin:0 0 0 15px; background: #FF9900 url(http://baselbern.swissbib.ch/TouchPoint/bb/common/style/css/themes/orange/img/logo_swissbib_bern-basel.gif) no-repeat; height: 65px; padding-left:130px;">
		<form style="padding:10px 0 0 40px; " onsubmit="return search_sbbb();">
			<fieldset style="margin: 0; padding: 0; border: none;">
				<input style="display:block;float:left;width:230px;" name="SEARCH_ALL" id="INPUT_SWISSBIB_SEARCH"
					   type="text">
				<input style="height:25px; width:80px;  margin-top:5px; display:block;float:left;" value="Suchen"
					   type="submit">
				<!--falls checkbox leer sein soll, lass die Option "checked" leer -->
				<input id="filterMaps" style="margin:10px 5px 0 10px; padding-left:10px; display:block; float:left;"
					   value="Search" checked="checked" type="checkbox">
				<!-- Label : Farbe und Text-->
				<label style="margin-top:5px; color:#2F333C;font-family:Arial,Helvetica,sans-serif;font-size:12px; margin:10px 10px 5px 5px;"
					   for="filtermaps">nur Kartenmaterial</label>
			</fieldset>
		</form>
	</div>
</div>
<!-- End: swissbib Basel Bern search box-->