<h2>À propos de Jusbib</h2>

<p>Jusbib est un <b>méta-catalogue</b> de données bibliographiques provenant de bibliothèques juridiques suisses et
    d'autres collections <b>de données juridiques</b>. L'interface et les fonctionnalités de recherche correspondent à
    celles de Swissbib.</p>

<p>En outre, les données peuvent être interrogées au moyen d'une classification par domaines du droit; la classification
    choisie est le <a href="http://www.isdc.ch/d2wfiles/document/5440/4018/0/Plan%20syst%20F(ISDC).pdf" target="_blank">plan
        systématique
        multilingue de l'Institut Suisse de droit comparé</a>.</p>

<p>Le projet Jusbib a été lancé par l'<a href="http://www.lawlibraries.ch/" target="_blank">Association des
        bibliothèques juridiques suisses</a> et est réalisé en étroite
    collaboration avec le groupe de projet Swissbib. Il reçoit un appui financier de <a href="http://www.ofj.admin.ch/"
                                                                                        target="_blank">l'Office fédéral
        de la Justice</a> et de l'association <a href="http://www.svri.ch/index.html" target="_blank"> eJustice.CH</a>.
</p>
