<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'VuFindTheme\View\Helper\MobileUrl'          => __DIR__ . '/VuFindTheme/View/Helper/MobileUrl.php',
  'VuFindTheme\View\Helper\HeadThemeResources' => __DIR__ . '/VuFindTheme/View/Helper/HeadThemeResources.php',
  'VuFindTheme\View\Helper\HeadScript'         => __DIR__ . '/VuFindTheme/View/Helper/HeadScript.php',
  'VuFindTheme\View\Helper\HeadLink'           => __DIR__ . '/VuFindTheme/View/Helper/HeadLink.php',
  'VuFindTheme\View\Helper\InlineScript'       => __DIR__ . '/VuFindTheme/View/Helper/InlineScript.php',
  'VuFindTheme\View\Helper\ImageLink'          => __DIR__ . '/VuFindTheme/View/Helper/ImageLink.php',
  'VuFindTheme\Initializer'                    => __DIR__ . '/VuFindTheme/Initializer.php',
  'VuFindTheme\Mobile'                         => __DIR__ . '/VuFindTheme/Mobile.php',
  'VuFindTheme\ThemeInfo'                      => __DIR__ . '/VuFindTheme/ThemeInfo.php',
  'VuFindTheme\ResourceContainer'              => __DIR__ . '/VuFindTheme/ResourceContainer.php',
  'VuFindTheme\InjectTemplateListener'         => __DIR__ . '/VuFindTheme/InjectTemplateListener.php',
);
