<div id="notepad-single">
    <a href="#" id="icon_notepad_addadd" class="linkbutton icon_notepad_addadd"><span>&nbsp;</span></a>

    <form name="MemorizeBean" id="form_notepad" method="get" action="#" class="notepadJQueryMemorizeListGrip" style="background-color: rgb(240, 240, 240); color: rgb(73, 78, 89);">
        <select name="selectedMemorizeList" id="notepad_list" class="select dropdown">
            <option value="3_-1" selected="selected">Temporäre Merkliste</option>
        </select>
    </form>
    <a href="#" class="linkbutton icon_goto" title="Merkliste"><span>Anzeigen</span></a>
</div>