<h3 class="facet_more">
	<a href="#" class="toggler persist collapsed" id="toggler_facet_more"
						  title="Mehr Suchfilter anzeigen $ Weniger Suchfilter anzeigen">Mehr Suchfilter anzeigen</a>
</h3>
<div class="facets toggler_facet_more">
	<!-- facet -->
	<div class="facet" id="facet_country">
		<h5 class="toggler persist collapsed" id="facet_toggler_country">Land</h5>
		<ul class="facet_toggler_country">
			<li><a href="#" title="Schweiz (6)">Schweiz (6)&nbsp;&raquo;</a></li>
			<li><a href="#" title="Rumänien (3)">Rumänien (3)&nbsp;&raquo;</a></li>
		</ul>
	</div>
	<!-- facet -->
	<div class="facet" id="facet_publisher">
		<h5 class="toggler persist collapsed" id="facet_toggler_publisher">Verlag</h5>
		<ul class="facet_toggler_publisher">
			<li><a href="#" title="Diogenes (6)">Diogenes (6)&nbsp;&raquo;</a></li>
			<li><a href="#" title="Rowohlt (6)">Rowohlt (6)&nbsp;&raquo;</a></li>
			<li><a href="#" title="Reclam (1)">Reclam (1)&nbsp;&raquo;</a></li>
			<li class="facet_more">
				<a href="#" title="Mehr anzeigen">Mehr anzeigen</a>
			</li>
		</ul>
	</div>
</div>