<?php
$this->headScript()->appendFile('pubdate_slider.js');
$dateRange          = $params->getDateRange();
$publishDateFrom    = $dateRange['from'];
$publishDateTo      = $dateRange['to'];
?>
<div id="facet_pubdate_slider" class="facet">
    <h5 id="facet_toggler_publishdate" onclick="$('#publishDateForceHeight').toggleClass('publishDateForceHeight')"
        class="toggler persist expanded" title="adv_search_year"><?= $this->transEsc('adv_search_year') ?></h5>

    <form action="" name="publishDateFilter" id="publishDateFilter">
        <?php /* Pass on other filter criteria via hidden fields, remove last publishDate */ ?>
        <?= $results->getUrlQuery()->asHiddenFields(array('filter' => "/publishDate:.*/")) ?>
        <input type="hidden" name="daterange[]" value="publishDate"/>

        <div class="publishDateForceHeight" id="publishDateForceHeight">
            <fieldset class="publishDateLimit facet_toggler_publishdate" id="publishDateSlider">
                <div class="values">
                    <div>
                        <label for="publishDatefrom"><?= $this->transEsc('date_from') ?>:</label>
                        <input type="text" size="4" maxlength="4" class="yearbox" name="publishDatefrom"
                               id="publishDatefrom" value="<?= $publishDateFrom ?>"/>
                    </div>
                    <div>
                        <label for="publishDateto"><?= $this->transEsc('date_to') ?>:</label>
                        <input type="text" size="4" maxlength="4" class="yearbox" name="publishDateto"
                               id="publishDateto" value="<?= $publishDateTo ?>"/>
                    </div>
                </div>
                <div id="publishDateSlider" class="dateSlider"></div>
                <input type="submit" value="<?= $this->transEsc('Set') ?>" id="publishDategoButton"/>
            </fieldset>
        </div>
    </form>
    <script language="javascript">
        $().ready(function () {
            if ($('#facet_toggler_publishdate').hasClass('collapsed')) {
                $('#publishDateForceHeight').hide();
            }
        });
    </script>
</div>