<?php
$facetDefaultLimit = $this->facetConfig->get('facet_limit_default'); // initially shown
?>
<?php foreach ($facetList as $facetGroup => $facetGroupData): /* Iterate over facet groups (topic, author, language, ... */ ?>
	<?php
	$facetId         = strtolower($facetGroup);
	$facetGroupLabel = $facetGroupData['label'];
	$facetGroupItems = $this->SortAndPrepareFacetList($results, $facetGroup, $facetGroupData['list'], $basicSearch, array('tab' => ucfirst($this->activeTabKey)));
	?>
	<!-- facet start: <?=$facetGroup?> -->
	<div class="facet" id="facet_<?= $facetId ?>">
		<h5 class="toggler persist expanded"
			id="facet_toggler_<?= $facetId ?>"><?= $this->escapeHtml($facetGroupLabel) ?></h5>
		<ul class="facet_toggler_<?= $facetId ?>">

			<?php
			// Get limit of initially shown items per facet
			$amountItems = count($facetGroupItems);
			$amountItemsShown = intval($this->facetConfig->get('facet_limit_' . $facetGroup));
			if ($amountItemsShown === 0) {
				$amountItemsShown = $facetDefaultLimit;
			}
			$itemsCount = 0;
			?>
			<?php foreach ($facetGroupItems as $facet): ?>
				<?php if ($itemsCount >= $amountItemsShown) break; /* Limit initially shown items per facet*/ ?>
				<?php $itemsCount++; ?>
				<?= $this->facetItem($facet, $facetGroup) ?>
			<?php endforeach; ?>
			<? if ($amountItems > $amountItemsShown): /* Show "more facets" link if there are more */ ?>
				<?php $amountMore = $amountItems - $amountItemsShown ?>
				<li id="more<?= $facetId ?>" class="facet_more">
					<a href="#" onclick="moreFacets('<?= $facetId ?>'); return false"
					   title="<?= $this->transEsc('more_info_toggle') ?>"><?= $this->transEsc('more_info_toggle') ?>
						(<?= $amountMore ?>)</a>
				</li>
				<div id="narrowGroupHidden_<?= $facetId ?>" class="offscreen">
					<?php while ($itemsCount < $amountItems) {
						$facet = $facetGroupItems[$itemsCount];
						?>
						<?= $this->facetItem($facet, $facetGroup) ?>
						<?php $itemsCount++; ?>
					<?php } ?>
					<li id="less<?= $facetId ?>" class="facet_more">
						<a href="#" onclick="lessFacets('<?= $facetId ?>'); return false"
						   title="<?= $this->transEsc('more_info_toggle') ?>"><?= $this->transEsc('more_info_toggle') ?>
							(<?= $amountMore ?>)</a>
					</li>
				</div>
			<? endif; ?>
		</ul>
	</div>
	<!-- facet -->
<?php endforeach; ?>