<label for="searchresult_displaynb">max. Treffer pro Seite</label>
<select class="select tiny" name="searchresult_displaynb" id="searchresult_displaynb">
	<option value="displaynb_5">5</option>
	<option value="displaynb_10" selected="selected">10</option>
	<option value="displaynb_15">15</option>
	<option value="displaynb_20">20</option>
	<option value="displaynb_30">30</option>
	<option value="displaynb_40">40</option>
	<option value="displaynb_50">50</option>
</select>