<div id="notepad">
	<form id="form_notepad" name="form_notepad" action="#" class="hint">
		<h3 class="hidden"><label for="notepad_list">Merklisten</label></h3>
		<select class="select dropdown" name="notepad_list" id="notepad_list">
			<option value="l01">Amerikanische Autoren</option>
			<option value="l02">Natur</option>
			<option value="default">Default</option>
		</select>
	</form>
	<a href="merkliste.html" class="linkbutton icon_goto" title="Merkliste anzeigen"><span>Anzeigen</span></a>
</div>