<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form action="<?=$this->currentPath() . $this->results->getUrlQuery()->setSort(null)?>" class="sortSelector" method="post">
    <label for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtml($sortType)?>"<?=($this->escapeHtml($sortType) == $_REQUEST['sort'] || $sortData['selected'])?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
