<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?=$this->layout()->userLang?>" xml:lang="en">



  <head>

      <?= $this->ScriptMarker()->headline("layout.home.phtml", true)?>

      <?$this->headThemeResources()?>
      <?=$this->headMeta()?>
      <?=$this->headTitle()?>
      <?=$this->headStyle()?>
      <?
          // Set up OpenSearch link:
          $this->headLink(
              array(
                  'href' => $this->url('search-opensearch') . '?method=describe',
                  'type' => 'application/opensearchdescription+xml',
                  'title' => $this->transEsc('Library Catalog Search'),
                  'rel' => 'search'
              )
          );
      ?>
      <?=$this->headLink()?>
      <?
          // Set global path for Javascript code:
          $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

          // Deal with cart stuff:
          //$cart = \VuFind\Cart::getInstance();
          //if ($cart->isActive()) {
          //    $this->headScript()->appendFile("jquery.cookie.js");
          //    $this->headScript()->appendFile("cart.js");
          //    $script = 'var vufindString = {};'
          //        . 'vufindString.bulk_noitems_advice = "' . $this->transEsc('bulk_noitems_advice') . '";'
          //        . 'vufindString.confirmEmpty = "' . $this->transEsc('bookbag_confirm_empty') . '";'
          //        . 'vufindString.viewBookBag = "' . $this->transEsc('View Book Bag') . '";'
          //        . 'vufindString.addBookBag = "' . $this->transEsc('Add to Book Bag') . '";'
          //        . 'vufindString.removeBookBag = "' . $this->transEsc('Remove from Book Bag') . '";'
          //        . 'vufindString.itemsAddBag = "' . $this->transEsc('items_added_to_bookbag') . '";'
          //        . 'vufindString.itemsInBag = "' . $this->transEsc('items_already_in_bookbag') . '";'
          //        . 'vufindString.bookbagMax = "' . $cart->getMaxSize() . '";'
          //        . 'vufindString.bookbagFull = "' . $this->transEsc('bookbag_full_msg') . '";'
          //        . 'vufindString.bookbagStatusFull = "' . $this->transEsc('bookbag_full') . '";';
          //    $this->headScript()->appendScript($script);
          //}
      ?>
      <?=$this->headScript()?>

  </head>


<body>

<!-- layout 1col home-->

    <div class="page_margins">
        <div class="page template_home">
            <div id="header">

            <?= $this->render('common/logo.phtml') ?>

            <?= $this->render('common/keyNavigation.phtml') ?>
            <?= $this->render('common/serviceNavigation.phtml') ?>

            <?= $this->render('common/navigation.phtml') ?>



            </div>

            <?= $this->render('common/sbSearchbox.phtml') ?>

            <div id="main">
                <div id="col3" class="content">
                    <div id="col3_content" class="clearfix">
                        <div id="content">

                            <?=$this->layout()->content?>


                        </div>

                     </div>

                 </div>
             </div>



        </div>



    </div>





</body>

  <?= $this->ScriptMarker()->footer("layout.home.phtml", true)?>

</html>