<?php
/** @var Array $holding */

$mapLink	= isset($holding['locationMap']) && $holding['locationMap'] ?
				'<a href="' . $holding['locationMap'] . '" class="holdingMapLink">' . $this->transEsc('Show_Location_Map') . '</a>' :
				'';
$moreDetailsLink	= $holding['itemsLink']['count'] ? '<a href="' . $this->url('holdings-holding-items', $holding['itemsLink']['url']) . '" rel="items" title="Holdings Test Title">Enthält ' . $holding['itemsLink']['count'] . ' Items</a>' : 'Keine Items gefunden';

?>
<tr>
	<td><?=$this->holdingActions($holding, 'holdingActionsHolding')?> </td>
    <td><?=$moreDetailsLink?></td>
    <td><?=$this->escapeHtml($holding['locationLabel'])?><?=$mapLink?></td>
	<td><?=$this->escapeHtml($holding['signature'])?></td>
	<td>QR</td>
	<td><?=$this->escapeHtml($holding['holding_information'])?></td>
</tr>