<?php
/** @var Array $item */
/** @var String $record */
/** @var String $recordTitle */

$mapLink	= '';

// Description (last column)
$description = !empty($item['description']) ? $item['description'] . '. ' : '';
if (!empty($item['public_note'])) {
    $description .= $item['public_note'] . '. ';
}
if (!empty($item['opac_note'])) {
    $description .= $item['opac_note'];
}

if (isset($item['locationMap']) && $item['locationMap']) {
	$mapLink = '<a href="' . $item['locationMap'] . '" class="holdingMapLink">' . $this->transEsc('Show_Location_Map') . '</a>';
}

?>
<tr>
	<td><?=$this->holdingActions($item, 'holdingActionsItem')?> </td>
	<td><?=$this->availabilityInfo($item['availability'])?></td>
	<td>
        <?=$this->escapeHtml($item['locationLabel'])?>
        <?=$mapLink?>
        <?php  if (isset($item['institutionUrl'])): ?>
            <?php  $wrappedURL = $this->redirectProtocolWrapper()->getWrappedURL($item['institutionUrl']) ?>
            <a href="<?=$this->escapeHtml($wrappedURL)?>" class="bibinfo" target="_blank" title="<?=$this->transEsc('Library_Information')?>"></a>
        <?php endif; ?>
    </td>
	<td><?=$this->escapeHtml($item['signature'])?></td>
	<td><?=$this->qrCodeHolding($item, $recordTitle)?></td>
	<td><?=$this->escapeHtml($description)?></td>
</tr>