<?php
/** @var Array $item */

$desc		= '';
$mapLink	= '';

	// Temporary usage for error info
if (isset($item['error'])) {
	$desc = $item['error'];
}
if (isset($item['locationMap']) && $item['locationMap']) {
	$mapLink = '<a href="' . $item['locationMap'] . '" class="holdingMapLink">' . $this->transEsc('Show_Location_Map') . '</a>';
}

?>
<tr>
    <td><?=$this->holdingActions($item, 'holdingActionsItem')?> </td>
    <td><?=$this->availabilityInfo($item['availability'])?></td>
	<td><?=$this->escapeHtml($item['locationLabel'])?><?=$mapLink?></td>
	<td><?=$this->escapeHtml($item['signature'])?></td>
    <td>QR</td>
	<td><?=$this->escapeHtml($desc)?></td>
</tr>