<?php
/** @var String $listClass */
/** @var Array[] $actions */
?>
<ul class="holdingActions <?=$listClass?>">

   <?php foreach($actions as $key => $action): ?>

		<li class="<?=$action['class']?>">
			<a href="<?=$action['href']?>" <?php if(isset($action['target'])): ?>target="<?=$action['target']?>"<?php endif; ?> title="<?=$this->escapeHtml($action['label'])?>">
				<span><?=$this->escapeHtml($action['label'])?></span>
			</a>
		</li>

   <?php endforeach; ?>

</ul>