<?php
/** @var Array[] $items */
?>
<table class="holdings-items">
	<thead>
		<tr>
			<th>&nbsp; (Funktionen)</th>
			<th><?=$this->transEsc('Availability')?></th>
			<th><?=$this->transEsc('Location')?></th>
			<th><?=$this->transEsc('Call Number')?></th>
			<th>QR</th>
			<th><?=$this->transEsc('Description')?></th>
		</tr>
	</thead>
	<tbody>
		<?php
			// Items
			foreach($items as $item) {
				echo $this->render('Holdings/holding-item.phtml', array(
					'item'	=> $item
				));
			}
		?>
	</tbody>
</table>