<?php
/** @var Array[] $items */
/** @var String $record */
/** @var String $recordTitle */
?>
<table class="holdings-items holdingTable">
	<thead>
		<tr>
			<th class="actions">&nbsp;</th>
			<th class="availability"><?=$this->transEsc('Availability')?></th>
			<th class="location"><?=$this->transEsc('Location')?></th>
			<th class="callnr"><?=$this->transEsc('Call Number')?></th>
			<th class="qr"><?=$this->transEsc('hold_qr')?></th>
			<th class="description"><?=$this->transEsc('Description')?></th>
		</tr>
	</thead>
	<tbody>
		<?php
			// Items
			foreach($items as $item) {
				echo $this->render('Holdings/holding-item.phtml', array(
					'item'			=> $item,
					'record'		=> $record,
					'recordTitle'	=> $recordTitle
				));
			}
		?>
	</tbody>
</table>