<?php
/** @var Array $item */
/** @var String $url */
/** @var String $text */
	$windowId	= isset($item['bibsysnumber']) ? $item['bibsysnumber'] : md5(time());
?>
<img src="<?= $this->basePath('themes/swissbib/images/qr_code.png') ?>" title="QR-Code" class="qrCodeIcon" onclick="swissbib.Holdings.showQrCode('<?=$windowId?>', '<?=$url?>', '<?=addslashes($text)?>')">
<?php $x = $item; ?>
<div id="qrcode-<?=$windowId?>" style="display: none" class="qrCodePopup">
	<div class="infotext"><?=$this->transEsc('qrcode.info')?></div>
	<img src="" title="QR Code">
	<div class="datatext"><?=$this->transEsc('qrcode.info')?></div>
</div>