<h2>jusbib in three steps</h2>
<p>jusbib offers fast, easy and broad access to scientific information in form of books, journals, newspapers, music,
    pictures, films, maps and electronic resources in Switzerland. At the same time the stock of Swiss university
    libraries and Swiss national libraries are researchable in jusbib.</p>
<p>We will explain how you can search for relevant materials and how to access them.</p>


<ol class="list">
    <li><a href="#search">Search</a></li>
    <li><a href="#refine">Find</a></li>
    <li><a href="#locate">Choose and order</a></li>
</ol>
<h2><a name="search"></a>Search</h2>
<div class="floatbox">
    <img class="small nb" src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/suche_klein.png') ?>"
         alt="Suchen"/>

    <p>Type one or more terms in the seeking slot.</p>

    <p><em>With a star <strong>*</strong> you can replace <strong>any number</strong> of characters, for example to find
            terms with different endings (e.g. Oper* for Opera, Opernhaus, opéra, operas, operate, etc.).</em></p>

    <p><em>The question mark <strong>?</strong> replaces <strong>one</strong> character and allows you to include
            different spellings (e.g. wom?n for woman and women).</em></p>

    <p><em>Putting your search terms in quotation marks <strong>“...“</strong> gives you the option of searching for an
            <strong>exact word order</strong> (e.g. “Don Giovanni”).</em></p>
</div>

<h2><a name="refine"></a>Find</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/anpassung_klein.png') ?>"
         alt="Suche anpassen"/>

    <h3>Filter</h3>

    <p>You can limit your results by using the filters on the left.</p>

    <p>Are you looking for a <strong>specific author</strong>? <br/>Using the simple search for a name, will lead to
        documents by and about the person. To find documents by a certain person, click on the desired name under the
        filter <b>author</b> to limit your results.</p>

    <p>Are you looking for a <strong>topic</strong>? <br/>Under one of the filters for the <strong>content</strong> you
        will find <strong>thematic search terms</strong>to limit your results.</p>
</div>

<h3>Sorting results</h3>
<p>Does sorting by <strong>year (newest first)</strong> not bring the desired document? Try changing the order of the
    results – for example sort by &raquo;relevance&laquo;.</p>

<h3>Where can you order the documents</h3>
<p>The question mark <img src="<?= $this->basePath('themes/jusbib/images/icon_info.gif') ?>" alt="Info"/> on the right
    side of every title, shows you which libraries have a copy of the book. By clicking on the library name, you will
    find more information.</p>

<h2><a name="locate"></a>Choose and order</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/bestellen_klein.png') ?>"
         alt="Hilfe zum Bestellen">

    <p>By clicking on the title in the hit list, you will find the bibliographic information (title, author, place,
        publisher, year of publication, page number, edition etc.). In the lower area you will see which libraries offer
        access to the document. You also have the option, to define your most used libraries as favourites, by clicking
        on the heart symbol<img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_miniaction_favorite_add.gif') ?>"
            alt="add favourite"/>. By adding <strong>favourite</strong> libraries, they will always rank first on your
        searches.</p>

    <p>Clicking on the <strong>library name</strong>, will show you the location of a book and call number. Many
        libraries also let you know, if a document is available <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_online.gif') ?>" alt="Available"/> or
        not <img src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_notavailable.gif') ?>"
                 alt="Not Available"/>.</p>

    <h3>Ausleihe/Bestellung</h3>
    <ul class="list">
        <!-- <li>Dokumente des IDS Basel/Bern können Sie <strong>direkt in jusbib</strong> bestellen oder reservieren.</li> -->
        <li>The documents of a library must be  <!-- aller anderen --> <strong>collected directly at the particular
                library</strong>. To access and accordingly to order / to reserve a document, click on the link <strong>go
                to holdings</strong>. This will take you to the library that owns the document, there you will have to
            sign in again.
        </li>
    </ul>
</div>

<!-- <h2>Brauchen Sie weitere Informationen?</h2>
<p>Ausführlichere Informationen zur Benutzung von jusbib stehen Ihnen auf unserer erweiterten Hilfe-Seite zur
    Verfügung.</p>-->