<h2>jusbib in drei Schritten</h2>
<p>Jusbib bietet einen raschen, einfachen und umfassenden Zugang zu wissenschaftlicher Information in Form von
    Büchern, Zeitschriften, Zeitungen, Musik, Bildern, Filmen, Karten und elektronischen Ressourcen in der Schweiz an.
    In jusbib sind die Bestände aller Schweizer Hochschulbibliotheken und der Schweizerischen Nationalbibliothek
    gleichzeitig recherchierbar.</p>

<p>Wir erklären Ihnen, wie Sie in jusbib relevante Materialien recherchieren und anschliessend darauf zugreifen
    können.</p>

<ol class="list">
    <li><a href="#search">Suchen</a></li>
    <li><a href="#refine">Finden</a></li>
    <li><a href="#locate">Auswählen und Bestellen</a></li>
</ol>
<h2><a name="search"></a>Suchen</h2>
<div class="floatbox">
    <img class="small nb" src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/suche_klein.png') ?>"
         alt="Suchen"/>

    <p>Geben Sie einen oder mehrere Begriffe in den Suchschlitz ein.</p>

    <p><em>Mit einem Stern <strong>*</strong> können Sie <strong>beliebig viele</strong> Zeichen ersetzen, um z.B.
            Begriffe mit unterschiedlicher Endung zu erfassen (Bsp. oper* für 'Oper', 'Opern', 'opéra', 'opéras',
            'opera', 'opere' etc.).</em></p>

    <p><em>Das Fragezeichen <strong>?</strong> ersetzt <strong>ein</strong> Zeichen und erlaubt Ihnen, unterschiedliche
            Schreibweisen zu berücksichtigen (Bsp. wom?n für 'woman' und 'women').</em></p>

    <p><em>Indem Sie Ihre Suchbegriffe in Anführungszeichen <strong>“...“</strong> setzen, haben Sie die Möglichkeit,
            nach einer <strong>genauen Wortabfolge</strong> zu suchen (Bsp. „Don Giovanni“).
        </em></p>
</div>

<h2><a name="refine"></a>Finden</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/anpassung_klein.png') ?>"
         alt="Suche anpassen"/>

    <h3>Filter</h3>

    <p>Sie können Ihre Treffer anhand der Filter auf der linken Seite eingrenzen.</p>

    <p>Suchen Sie nach einem <strong>bestimmten Autor</strong>? <br/>Eine einfache Suche nach dem Namen ergibt Dokumente
        von einer aber auch über eine Person. Um nur Dokumente von einer bestimmten Person zu erhalten, wählen Sie den
        gewünschten Namen beim Filter <strong>Autor</strong> aus und klicken Sie darauf, um die Treffermenge
        einzugrenzen.</p>

    <p>Suchen Sie nach einem <strong>Thema</strong>? <br/>Unter einem der Filter für den <strong>Inhalt</strong> finden
        Sie <strong>thematische Suchbegriffe</strong>, um Ihre Treffer einzuschränken</p>
</div>

<h3>Ergebnisse sortieren</h3>
<p>Liefert die Sortierung nach <strong>Jahr (neuestes zuerst)</strong> nicht das Gewünschte? Ändern Sie die Reihenfolge,
    in der die
    Ergebnisse Ihrer Suche angezeigt werden sollen - z.B. auf &raquo;Relevanz&laquo;.</p>

<h3>Wo können Sie das Gesuchte bestellen?</h3>
<p>Das Fragezeichen <img src="<?= $this->basePath('themes/jusbib/images/icon_info.gif') ?>" alt="Info"/> auf der
    rechten Seite jedes Titels zeigt Ihnen, in welchen Bibliotheken ein Exemplar vorhanden ist. Ein Klick auf den
    Bibliotheksnamen bringt Ihnen weitere Informationen.</p>

<h2><a name="locate"></a>Auswählen und Bestellen</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/bestellen_klein.png') ?>"
         alt="Hilfe zum Bestellen">

    <p>Mit einem Klick auf einen Titel in der Trefferliste öffnet sich die Vollanzeige der bibliographischen Angaben
        (Titel, Autor, Ort, Verlag, Erscheinungsjahr, Seitenzahl, Auflage etc..). Im unteren Bereich sehen Sie zudem,
        welche Bibliotheken den Zugriff auf das Dokument ermöglichen. Ebenfalls haben Sie hier die Möglichkeit, durch
        einen Klick auf das kleine Herzsymbol <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_miniaction_favorite_add.gif') ?>"
            alt="add favourite"/> Ihre meistgenutzten Bibliotheken als <strong>Favoriten</strong> zu definieren, damit
        sie immer an erster Stelle erscheinen.</p>

    <p>Ein Klick auf den <strong>Bibliotheksnamen</strong> zeigt Ihnen Standort und Signatur an. Bei vielen Bibliotheken
        erfahren Sie zudem, ob das Dokument verfügbar <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_online.gif') ?>"
            alt="Available"/> oder schon ausgeliehen <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_notavailable.gif') ?>"
            alt="Not Available"/> ist.</p>

    <h3>Ausleihe/Bestellung</h3>
    <ul class="list">
        <!-- <li>Dokumente des IDS Basel/Bern können Sie <strong>direkt in jusbib</strong> bestellen oder reservieren.</li> -->
        <li>Die Dokumente <!-- aller anderen --> der Bibliotheken müssen Sie <strong>direkt über die jeweilige
                Bibliothek
                beziehen</strong>. Für den Zugriff bzw. die Bestellung/Reservation klicken Sie auf den Link <strong>zum
                Bestand</strong> und wechseln zur besitzenden Bibliothek und melden sich erneut an.
        </li>
    </ul>
</div>

<!-- <h2>Brauchen Sie weitere Informationen?</h2>
<p>Ausführlichere Informationen zur Benutzung von jusbib stehen Ihnen auf unserer erweiterten Hilfe-Seite zur
    Verfügung.</p>-->