<h2>About jusbib</h2>
<p>jusbib is a <b>metacatalogue</b> of data records from Swiss libraries of law and other relevant stock <b>of law
        literature</b>. The interface and search functions correspond to those of swissbib.</p>
<p>Data records can also be searched for by a standardised law classification system; it’s a multilingual, systematic <a
        href="http://isdc.ch/d2wfiles/document/5445/4018/0/Plan%20syst%20D(ISDC).pdf" target="_blank">classification of
        Swiss institutes of comparative law</a>.</p>
<p>The project Jusbib was started by the <a href="http://www.lawlibraries.ch/" target="_blank">association of legal
        libraries of Switzerland</a> and carried out in collaboration with the Swissbib team. It receives financial
    support from the <a href="http://www.bj.admin.ch/content/bj/en/home.html" target="_blank">federal office of
        justice</a> and the association <a href="http://www.svri.ch/index.html" target="_blank">eJustice.CH.</a></p>