<h2>Über jusbib</h2>
<p>Jusbib ist ein <b>Metakatalog</b> von Datensätzen aus Schweizer Rechtsbibliotheken und weiteren relevanten Beständen
    <b>der juristischen Literatur</b>. Das Interface und die Suchfunktionalitäten von Jusbib entsprechen jenen von
    Swissbib.</p>

<p>Zusätzlich können die Datensätze mittels einer einheitlichen Rechtsklassifikation abgefragt werden; es handelt sich
    um die mehrsprachige systematische <a href="http://isdc.ch/d2wfiles/document/5445/4018/0/Plan%20syst%20D(ISDC).pdf"
                                          target="_blank">Klassifikation des Schweizerischen Instituts für
        Rechtsvergleichung</a>.</p>

<p>Das Projekt Jusbib wurde von der <a href="http://www.lawlibraries.ch/" target="_blank">Vereinigung der juristischen
        Bibliotheken der Schweiz</a> gestartet und in enger
    Zusammenarbeit mit dem Team von Swissbib durchgeführt. Es erhält eine finanzielle Unterstützung des <a
        href="http://www.bj.admin.ch/content/bj/en/home.html" target="_blank">Bundesamtes für
        Justiz</a> und des Vereins <a href="http://www.svri.ch/index.html" target="_blank">eJustice.CH</a>.</p>
