<h3><?=$this->transEsc('helppage')?></h3>
<div class="subnavigation accountSidebar">
    <ul>
        <li>
            <a href="<?=$this->url('help-page', array('topic' => 'Myswissbib'))?>"><?=$this->transEsc('helppage.myswissbib')?></a>
        </li>
        <li>
            <a href="http://aleph.unibas.ch/F/?func=bor-new-0"><?=$this->transEsc('Create New Account')?></a>
        </li>
        <li>
            <a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE"><?=$this->transEsc('changeaddress')?></a>
        </li>
        <li>
            <a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE"><?=$this->transEsc('changepassword')?></a>
        </li>
    </ul>
</div>