<p>
    Falls Sie im Besitz eines in folgenden Verbünden gültigen Benutzerausweises sind, melden Sie sich mit Ihrem üblichen Login an:
</p>
<p>- IDS Basel Bern</p>
<p>- IDS Luzern</p>
<p>- NEBIS</p>
<p>- IDS St. Gallen</p>
<p>- St. Galler Bibliotheksnetz</p>
<p>
    <a href="http://aleph.unibas.ch/F/?func=bor-new-0" target="_blank" title="<?=$this->transEsc('Create New Account')?>"><?=$this->transEsc('Create New Account')?></a>
</p>
<!--<p>
    <a href="<?/*=$this->url('help-page', array('topic'=> 'myswissbib'))*/?>"><?/*=$this->transEsc('Help')*/?></a>
</p>-->