<?
    // Set page title.
    $this->headTitle($this->translate('Search Home'));
//
//    // Set default value if necessary:
//    if (!isset($this->searchClassId)) {
//        $this->searchClassId = 'Solr';
//    }

    // Load search actions and settings (if any):
//    $options = $this->searchOptions($this->searchClassId);
//    $basicSearch = $options->getSearchAction();
//    $advSearch = $options->getAdvancedSearchAction();
?>
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">
			<h1 class="hidden">Informationen zu swissbib</h1>
			<!-- begin: teaser -->
			<div class="teaser">
				<!-- col -->
				<div class="c50l">
					<div class="box h150 bmright">
						<h2>Über swissbib Basel Bern</h2>
						<p>
                            swissbib Basel Bern ist der neue Katalog des IDS Basel Bern. Sie können darin in den gedruckten und elektronischen Beständen aller Bibliotheken in Basel und Bern (inkl. Nationalbibliothek) recherchieren.
						</p>
						<ul class="actions">
							<li class="right">
								<a href="inhaltsseite.html" class="linkbutton primary icon_goto_primary" title="Mehr Infos"><span>Mehr Infos</span></a>
							</li>
						</ul>
					</div>
				</div>
				<!-- col -->
				<div class="c50l">
					<div class="box h150 bmleft">
						<h2>Aktueller Stand</h2>
						<p>
                            Der neue Katalog der Bibliotheken in Basel und Bern ist in Entwicklung. Goin' VuFind ...
						</p>
						<ul class="actions">
							<li class="right">
								<a href="inhaltsseite.html" class="linkbutton primary icon_goto_primary" title="Mehr Infos"><span>Mehr Infos</span></a>
							</li>
						</ul>
					</div>
				</div>
			</div><!-- end: teaser -->
		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>