<? $results = $this->recommend->getResults(); ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); ?>

<? if (isset($sideFacetSet['lists']) && !empty($sideFacetSet['lists']['list'])): ?>
	<h3 class="list"><?= $this->transEsc($sideFacetSet['lists']['label']) ?></h3>

	<div class="subnavigation favorites listWithCounter">
		<ul>
			<? foreach ($sideFacetSet['lists']['list'] as $current): ?>
				<li>
					<? if ($current['isApplied']): ?>
						<strong><?= $this->escapeHtml($current['displayText']) ?></strong>
					<? else: ?>
						<a href="<?= $this->url('userList', array('id' => $current['value'])) ?>"><?= $this->escapeHtml($current['displayText']) ?></a>
					<? endif; ?>
					<span class="counter">(<?= $this->escapeHtml($current['count']) ?>)</span>
				</li>
			<? endforeach; ?>
		</ul>
	</div>
<? endif; ?>

<? if (isset($sideFacetSet['tags']) && !empty($sideFacetSet['tags']['list'])): ?>
	<?php
		$filterList = $results->getParams()->getFilterList(true);
		$tagFilterList = isset($filterList[$sideFacetSet['tags']['label']]) ? $filterList[$sideFacetSet['tags']['label']] : null;
	?>
	<h3 class="tag"><?= $this->transEsc($sideFacetSet['tags']['label']) ?></h3>
	<?php if (!empty($tagFilterList)): ?>
		<strong><?= $this->transEsc('Remove Filters') ?></strong>
		<div class="subnavigation">
			<ul class="filters">
				<? $field = $sideFacetSet['tags']['label'];
				foreach ($tagFilterList as $filter): ?>
					<? $removeLink = $this->currentPath() . $results->getUrlQuery()->removeFacet($filter['field'], $filter['value']); ?>
					<li>
						<a href="<?= $removeLink ?>">
							<img src="<?= $this->imageLink('silk/delete.png') ?>" alt="<?= $this->transEsc('Delete') ?>"/>
						</a>
						<a href="<?= $removeLink ?>"><?= $this->transEsc($field) ?>: <?= $this->escapeHtml($filter['displayText']) ?></a>
					</li>
				<? endforeach; ?>
			</ul>
		</div>
	<? endif; ?>

	<div class="subnavigation tagList listWithCounter">
		<ul>
			<? foreach ($sideFacetSet['tags']['list'] as $thisFacet): ?>
				<li>
					<? if ($thisFacet['isApplied']): ?>
						<?= $this->escapeHtml($thisFacet['displayText']) ?>
						<img src="<?= $this->imageLink('silk/tick.png') ?>"	alt="<?= $this->transEsc('Selected') ?>"/>
					<? else: ?>
						<a href="<?= $this->currentPath() . $results->getUrlQuery()->addFacet('tags', $thisFacet['value']) ?>"><?= $this->escapeHtml($thisFacet['displayText']) ?></a>
						<span class="counter">(<?= $this->escapeHtml($thisFacet['count']) ?>)</span>
					<? endif; ?>
				</li>
			<? endforeach; ?>
		</ul>
	</div>

<? endif; ?>