<!-- Summons Database Recommendations -->
<?	/** @var	\VuFind\Search\Summon\Results	$results */
$summonDatabases = $results->getDatabaseRecommendations();
if (!empty($summonDatabases)): ?>
	<?php if(count($summonDatabases)>0): ?>
		<div class="authorbox summondbrecommendations">
		  <h2><?=$this->transEsc('summon_database_recommendations')?></h2>
		  <? foreach ($summonDatabases as $current): ?>
			<p>
				<a target="_blank" class="color singleLink" href="<?=$this->escapeHtml($current['link'])?>" title="<?=$this->escapeHtml($current['title'])?>">
					<?=$this->escapeHtml($current['title'])?>
				</a><br/>
				<?=$this->escapeHtml($current['description'])?>
			</p>
		  <? endforeach; ?>
		</div>
	<? endif; ?>
<?php endif; ?>