<h1>À propos de swissbib</h1>

<h3>Contact</h3>
<ul class="list">
    <li>Pour les questions concernant votre compte, adressez-vous à <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">votre bibliothèque</a>.</li>
    <li>Pour les questions concernant des oeuvres particulières, adressez-vous à <a href="<?= $this->url('libraries-index') ?>">la bibliothèque concernée</a></li>
    <li>Contacter swissbib Basel Bern: e-mail à <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> ou commentaire dans le <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.</li>
</ul>

<h3>Nouvelles</h3>
<p>Dans notre <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a></p>

<h1>Base de données</h1>

<h3>Livres &amp; plus</h3>
<ul class="list">
<li>Les bibliothèques scientifiques à <a href="<?= $this->url('libraries-index') ?>#nav_0">Bâle</a> et à <a href="<?= $this->url('libraries-index') ?>#nav_1">Berne</a></li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: revues scientifiques rétronumérisées 
</li>  
</ul>    
<h3>Articles &amp; plus</h3>
<ul class="list">
    <li>Content of e-journals, e-books and databases licenced by the university libraries of Basel and/or Bern. In most cases you have access to the full text if you are on campus of the university or logged in via VPN.</li>
    <li>Free online ressources.</li>
    <li>If the full text is not avaliable online you can order a copy using the <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>link to library services</i></li>
    <li>For more information see <a href="http://www.proquest.com/products-services/The-Summon-Service.html" target="_blank">the info site of ProQuest</a>.</li>
</ul>
