<h1>À propos de swissbib</h1>

<h2>Contact</h2>
<ul class="list">
<li>Via commentaire dans le <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>, via mail à <a
        href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> ou contactez <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</li>
<li>Pour les questions concernant votre compte, adressez-vous à <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">votre bibliothèque</a>.</li>
<li>Pour les questions concernant des oeuvres particulières, adressez-vous à <a href="../Libraries">la bibliothèque concernée</a>: cliquez
    sur le <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>" alt="Library Info"> situé
    près de la cote.</li>
</ul>

<h2>Nouvelles</h2>
<p>Dans notre <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a> et via <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>

<h1>Base de données</h1>

<h2>Livres &amp; plus</h2>
<ul class="list">
<li>Les bibliothèques scientifiques à <a href="../Libraries#nav_1">Bâle</a> et à <a href="../Libraries#nav2">Berne</a></li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: revues scientifiques rétronumérisées 
</li>  
</ul>    

<!--
<p><strong>Région Bâle</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, bibliothèques Bâle
        et Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Bibliothèques de l'université et du réseau IDS</a></li>
</ul>
<p><strong>Région Berne</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Banque nationale
            suisse</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Bibliothèque nationale suisse</a></li>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Bibliothèques de l'université et du réseau IDS</a></li>
    </ul>
-->

<h2>Articles &amp; plus</h2>
<ul class="list">
    <li>In <i>Artikel &amp; mehr</i> finden Sie die Inhalte von zahlreichen e-Journals, e-Books und Fachdatenbanken, die von den Universitätsbibliotheken Basel bzw. Bern lizenziert wurden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext (Journal-Artikel, e-Book-Kapitel etc.) zugegriffen werden.</li>
    <li>Zusätzlich enthält <i>Artikel &amp; mehr</i> elektronische Ressourcen, die frei im Internet zugänglich sind.</li>
    <li>Titel, zu denen kein direkter Volltextzugang besteht, können Sie via <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>Bibliotheksservice</i> bei der Universitätsbibliothek Basel oder Bern bestellen.<br/></li>
    <li>Für mehr Informationen zu den verzeichneten Ressourcen siehe <a href="http://www.serialssolutions.com/en/services/summon/content-and-coverage" target="_blank">SerialsSolutions</a>.</li>
  </ul>
