<h1>À propos de swissbib</h1>

<h2>Contact</h2>
<p>Via commentaire dans le <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>, via mail à <a
        href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> ou contactez <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>
<p>Pour les questions concernant votre compte, adressez-vous à <a href="http://www.swissbib.ch/libraries/placelist.html"
                                                                  target="_blank">votre bibliothèque</a>.</p>
<p>Pour les questions concernant des oeuvres particulières, adressez-vous à <a
        href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">la bibliothèque concernée</a>: cliquez
    sur le <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>" alt="Library Info"> situé
    près de la cote.</p>


<h2>Nouvelles</h2>
<p>Dans notre <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a> et via <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>

<h1>Base de données</h1>

<h2>Livres &amp; plus</h2>

<p><strong>Région Bâle</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, bibliothèques Bâle
        et Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Bibliothèques du réseau IDS</a></li>
</ul>
<p><strong>Région Berne</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Banque nationale
            suisse</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Bibliothèque nationale suisse</a></li>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Bibliothèques
            du réseau IDS</a></li>
    </ul>
<p><strong>retro.seals</strong></p>
<ul class="list">
    <li>Dans le cadre du projet <a href="http://retro.seals.ch" target="_blank">retro.seals.ch</a>, les revues
        scientifiques seront rétronumérisées et rendues accessibles online.
    </li>
</ul>


<h2>Articles &amp; plus</h2>
<ul class="list">
    <li>In <i>Artikel &amp; mehr</i> finden Sie die Inhalte von zahlreichen e-Journals, e-Books und Fachdatenbanken, die von den Universitätsbibliotheken Basel bzw. Bern lizenziert wurden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext (Journal-Artikel, e-Book-Kapitel etc.) zugegriffen werden.</li>
    <li>Zusätzlich enthält <i>Artikel &amp; mehr</i> elektronische Ressourcen, die frei im Internet zugänglich sind.</li>
    <li>Titel, zu denen kein direkter Volltextzugang besteht, können via <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>Bibliotheksservice</i> bei der Universitätsbibliothek Basel oder Bern per Fernleihe bestellt werden.<br/></li>
    <li>Für mehr Informationen zu den verzeichneten Ressourcen siehe <a href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">SerialsSolutions</a>.</li>
  </ul>