<h1>Recherche avancée</h1>
<h2>Livres &amp; plus</h2>
<h3>Avec tous les groupes de recherche</h3>
<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/advanced1.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/advanced1_small.png') ?>" alt="Zoom"> 
     </a>
       <p>
        Migration*/Migrant*/migrazion*<br/><strong>et</strong><br/>Gesundheit*/health/santé/salute<br/><strong>et</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*
    </p>
</div>

<h3>Sans le troisieme group de recherche</h3>
<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/advanced2.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/advanced2_small.png') ?>" alt="Zoom"> 
     </a>
    </a>

    <p>Migration*/Migrant*/migrazion*<br/><strong>et</strong><br/>Gesundheit*/health/santé/salute<br/><strong>mais pas</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*</p>
</div>

<h3>Affiner la recherche: Langue, Forme, Bibliothèque, Année de publication</h3>
<p>Instead of scrolling in the drop-down lists click somewhere in the list and write the word you want to scroll to, e.g.<i>English</i> in <i>Languages</i>.</p>

<h3>Répéter la recherche</h3>
<p><i>Modifier cette recherche</i> au dessus de la liste de résultats oubien sous <i>Mon swissbib - Recherches sauvegardées</i>.</p>

<h3>Sauvegarder la recherche</h3>
<p><i>Mon swissbib - Recherches sauvegardées</i>.</p>

<!--
<h3>Feed pour des nouveaux titres concernant votre recherche</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
        alt="S'inscrire au flux RSS"> Abonner</p>
-->

<h2>Articles &amp; plus</h2>
<p>Comme <i>Livres &amp; plus</i>, mais quelques champs/filtres sont différentes parce que <i>Articles &amp; plus</i> est un catalog séparé.</p>