<h1>FAQ</h1>
<h2>Rechercher, Recherche avancée</h2>
 <!--
<ul class="list">
    <li><strong>Comment chercher directement dans <i>Articles & plus</i>?</strong>
        <br/><a href="http://baselbern.swissbib.ch/Summon/Search" target="_blank">baselbern.swissbib.ch/Summon/Search</a>
    </li>
      <li><strong>La recherche avec parenthèses ne livre pas les résultats escomptés.</strong>
        <br/>Les recherches comme <i>a AND (b OR c)</i> ou <i>(a OR b) NOT c</i> ne sont pas valables. Utilisez plusieurs groupes de recherche dans la <i>Recherche avancée</i>.
    </li>
</ul>
<h2>Liste des résultats</h2>
-->
<ul class="list">
      <li><strong>Is <i>Refine search - Subject</i> the same as <i>Advanced search - Subject</i>?</strong>
        <br/>Search for <i>Subject</i> in advanced search includes special subjects of single libraries and classifications.<br/>The facet <i>Subject</i> only shows controlled vocabulary (GND, MeSH, terms BS/BE).</li>
    <li><strong>Trier par pertinance?</strong>
        <br/>Les concordances dans le titre, l'auteur et le thème sont affichées en prioritée. 
    </li>
</ul>

<h2>Commander</h2>
<ul class="list">
    <li><strong>Pouvez vous m'envoyer l'ouvrage xy?</strong>
        <br/>Sélectionnez la bibliothèque de votre choix. Cliquez sur <i>Commander</i>. Si
        l'envoi postal à votre adresse peut se faire, vous pouvez choisir cette option sous <i>Lieu de
            reprise/livraison</i>.
    </li>
</ul>

<div class="example">Vous ne trouvez pas la réponse à votre question? Contactez-nous via <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, <a
        href="mailto:swissbib-baselbern@unibas.ch">mail</a> ou <a href="https://twitter.com/swissbibBB"                                                                  target="_blank">@swissbibBB</a>.
</div>