<h1>FAQ</h1>
<h2>Rechercher, Recherche avancée</h2>
<ul class="list">
  <li><strong>Est-il possible d'effectuer une recherche dans le fonds d'une bibliothèque définie?</strong>
         <br/>Soit en sélectionant la bibliothèque en tant que favorit et en utilisant dans la liste de résultats <i>Affiner la recherche - Favoris</i> ou en utilisant <i>Recherche avancée - Affiner la recherche - Bibliothèque</i>.</li>   
    <li><strong>Trier par pertinance?</strong>
        <br/>Les concordances dans le titre, l'auteur et le thème sont affichées en prioritée. 
    </li>
</ul>


<h2>Commander</h2>
<ul class="list">
    <li><strong>Pouvez vous m'envoyer l'ouvrage xy?</strong>
        <br/>Sélectionnez la bibliothèque de votre choix. Cliquez sur <i>Commander</i>. Si
        l'envoi postal à votre adresse peut se faire, vous pouvez choisir cette option sous <i>Lieu de
            reprise/livraison</i>.
    </li>
</ul>

<h2>My swissbib</h2>
<ul class="list">
        <li><strong>Comment obtenir rapidement un aperçu de mes prêts?</strong>
            <br/>Connectez-vous, puis cliquez sur <i>Compte: votre nom</i>.<br> 
                   </li>
       </ul>       
              
       
<div class="example">Vous ne trouvez pas la réponse à votre question? Contactez-nous via <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, <a
        href="mailto:swissbib-baselbern@unibas.ch">mail</a> ou <a href="https://twitter.com/swissbibBB"                                                                  target="_blank">@swissbibBB</a>.
</div>