<h1>Se connecter</h1>

<p>Si vous avez une carte valable dans l'un des réseaux suivants vou spouvez vous connecter comme d'habitude:</p>
<ul class="list">
<li>IDS Basel Bern</li>
<li>IDS Luzern</li>
<li>IDS St. Gallen</li>
<li>NEBIS</li>
<li>St. Galler Bibliotheksnetz</li>
</ul>

<h3>Pas de compte?</h3>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0&CON_LNG=FRE" target="_blank">Ouvrir un nouveau compte</a></p>

<h3>Pourqoi se connecter?</h3>
<p>To use loan, favorite libraries, lists, saved searches and saved preferences.</p>

<h3>Oublié le mot de passe?</h3>
<p>Please contact <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">your library</a>.</p>

<h3>Profil</h3>
<p><a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE" target="_blank">Changer le mot de passe, l'adresse etc.</a></p>

<h3>Pourquoi se déconnecter?</h3>
<p>If you are using a public computer you should log out so nobody else can use your account.</p>

<h1>My swissbib</h1>
<h3>Recherches sauvegardées</h3>
<p>When you are not logged in, your searches are saved until you close the browser. You can repeat a search or - if you log in - save it permanently.</p>

<h3>Favoris</h3>
<p>To add a library to <i>Favorites</i> either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>" alt="Add to my favourites"> in the catalog.</p>

<h3>Listes</h3>
<ul class="list">
<li><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="Ajouter à une liste"> When you are logged in you can save titles on lists.</li>
<li>If you make a new list while saving a title you have to click <i>Save</i> twice.</li>
<li>Publique = Liste visible pour tout le monde qui connaît l'URL</li>
<li>Privé = Liste visible seulement pour vous</li>
</ul>   
       
<h3>Préférences</h3>
<p>Language of the catalog interface, number of titles per page</p>

<h3>Compte IDS Basel Bern</h3>
<p>Loan functions</p>
