<h1>Sauvegarder</h1>

<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="ajouter à une liste de sélection"></td>
		<td>Sauvegarder des titre dans votre <strong>listes de sélection</strong></td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
				 alt="S'inscrire aux flux RSS"></td>
		<td>Recevoir par <strong>feed</strong> les nouveaux titres correspondants à votre recherche</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>"
				 alt="Imprimer"></td>
		<td><strong>Imprimer</strong> les résultats</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>"
				 alt="Envoyer"></td>
		<td>Envoyer les résultats par <strong>mail</strong></td>
		</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>"
				 alt="Exporter ..."></td>
		<td><strong>Exporter</strong> les résultats sous différents formats</td>
	</tr>
	</tbody>
</table>

<h2>Commander</h2>

<div class="floatbox">
     <a href="<?= $this->basePath('/themes/swissbibmulti/images/HelpPage/fr/order.png') ?>">
     <img src="<?= $this->basePath('/themes/swissbibmulti/images/HelpPage/fr/order_small.png') ?>" alt="Screenshot"> 
     </a>
    
    
<ul class="list">
	<li>Cliquez sur le titre</li>
	<li>Choisissez une bibliothèque sous <i>Exemplaire</li>
	<li>Sous le nom de la bibliothèque cliquez sur <i>Se connecter</i></li> 
	<li>Cliquez sur <i>Commander</i> ou <i>Commander une copie</i></li>
	<li>Si aucune de ses options apparait, le document ne peut être commandé online. Un clic sur <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>" alt="Informations sur la bibliothèque"> à côté de la signature affiche les horaires d'ouverture et l'adresse de la bibliothèque.</li>
</ul>
    </div>
    
