<h1>Sauvegarder</h1>

<table>
	<tbody>
	<tr>
        <td><img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
                 alt="<?= $this->transEsc('memorizelistadd')?>"
                 title="<?= $this->transEsc('memorizelistadd')?>">
        </td>
		<td>Sauvegarder des titre dans votre <strong>listes de sélection</strong></td>
	</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_rss.gif') ?>"
                 alt="<?= $this->transEsc('Get RSS Feed')?>"
                 title="<?= $this->transEsc('Get RSS Feed')?>">
        </td>
		<td>Recevoir par <strong>feed</strong> les nouveaux titres correspondants à votre recherche</td>
	</tr>
    <tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_perma.gif') ?>"
                 alt="<?= $this->transEsc('Cite this')?>"
                 title="<?= $this->transEsc('Cite this')?>">
        </td>
        <td><strong>Citer</strong> les résultats</td>
    </tr>

    <tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_print.gif') ?>"
                 alt="<?= $this->transEsc('Print')?>"
                 title="<?= $this->transEsc('Print')?>"">
        </td>
		<td><strong>Imprimer</strong> les résultats</td>
	</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_send.gif') ?>"
                 alt="<?= $this->transEsc('Email this')?>"
                 title="<?= $this->transEsc('Email this')?>">
        </td>
		<td>Envoyer les résultats par <strong>mail</strong></td>
		</tr>
	<tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_save.gif') ?>"
                 alt="<?= $this->transEsc('Export Items')?>"
                 title="<?= $this->transEsc('Export Items')?>">
        </td>
		<td><strong>Exporter</strong> les résultats sous différents formats</td>
	</tr>
	</tbody>
</table>

<h2>Commander</h2>

<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/order.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/fr/order_small.png') ?>" alt="Zoom"> 
     </a>
    
    
<ul class="list">
	<li>Cliquez sur le titre.</li>
	<li>Choisissez une bibliothèque sous <i>Exemplaire</i>.</li>
	<li>Sous le nom de la bibliothèque cliquez sur <i>Se connecter</i>.</li> 
	<li>Cliquez sur <i>Commander</i> ou <i>Commander une copie</i>.</li>
	<li>Si aucune de ses options apparait, le document ne peut être commandé online. Un clic sur l'image <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Informations sur la bibliothèque"> sous Localisation affiche les horaires d'ouverture et l'adresse de la bibliothèque.</li>
</ul>
    </div>
    
