<h1>Rechercher</h1>

<h3>Combiner</h3>

<table>
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Les deux termes sont utilisés</td>
    </tr>
    <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Les deux termes sont utilisés dans le même champs</td>
    </tr>
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>Un seul des deux termes est utilisé</td>
    </tr>
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td><i>joyce</i> est utilisé, mais pas<i>ulysses</i></td>
    </tr>
    <tr>
        <td>Recherches plus complexes</td>
        <td>Voir <a href="<?= $this->url('help-page', array('topic' => 'Advanced')) ?>">Aide - Recherche avancée</a>.
        </td>
    </tr>
    </tbody>
</table>

<h3>Recherche avec guillemets</h3>

<table>
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>Les deux mots doivent se placer directement l'un après l'autre.</td>
    </tr>
    <tr>
        <td><i>"street art"~5</i></td>
        <td>Les deux mots doivent apparaître en l'espace de 5 mots.</td>
    </tr>
     <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>Cote</td>
    </tr>
    </tbody>
</table>

<h3>Truncature</h3>

<table>
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">remplace un nombre illimité de caractères</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>
      <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">remplace exactement un caractère</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc.</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist ecc.</td>
    </tr>
    <tr>
        <td>~</td>
        <td>si vous ignorez l'orthographe exacte</td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij etc.</td>
    </tr>
    </tbody>
</table>


<h2>Liste des résultats</h2>
<h3>Affiner la recherche</h3>
<p>Utilisez les filtres proposées dans la colonne de gauche de vos résultats ou la <i>Recherche avancée</i>.</p>

<h3>Répéter ou sauvegarder la recherche</h3>
<ul class="list">
    <li>Clic sur <i>Articles & plus</i> relance la recherche dans le catalogue de <a
            href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">Summon</a>.
    </li>
    <li><a href="<?= $this->url('search-history') ?>">My swissbib - Recherches sauvegardées</a></li>
</ul>

<!--
<h3>Feed pour des nouveaux titres concernant votre recherche</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
        alt="S'inscrire au flux RSS"> Abonner</p>
-->

<h2>Texte intégral</h2>
<p>Pour l'accès au texte intégral vous devez vous trouver sur le campus de l'université ou vous indetifier par VPN.</p>
        
<h3>Articles &amp; plus</h3>
<ul class="list">
    <li><i>get it</i> = Texte intégral</li>
    <li><img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>" alt="SFX Services"> = Texte intégral et/ou service sfx
    </li>
</ul>     
