<div class="offset" id="pagefunctions">
    <h3 class="hidden">Seitenfunktionen</h3>
    <ul>

        <li id="pagefunction_rss">
            <a href="http://www.swissbib.ch/TouchPoint/feed.do?q=-1+%3D+%22xml%22+IN+%5B3%5D&v=nose&l=de" target="_blank" title="Atom-Feed abonnieren">Atom-Feed abonnieren</a>
        </li>

        <li id="pagefunction_link">
            <a href="#display_permalink" class="inline cboxElement" title="Permanenter Link zu diesem/n Treffer(n)">Permanenter Link zu diesem/n Treffer(n)</a>
        </li>

        <li id="pagefunction_print">
            <a href="#" class="modal" title="Einträge drucken"></a>
        </li>
        <li id="pagefunction_send">
            <a href="#" class="modal" title="Einträge versenden"></a>
        </li>
        <li id="pagefunction_save">
            <a href="#" class="modal" title="Einträge lokal speichern"></a>
        </li>
    </ul>
    <div style='display:none'>
        <div id='display_permalink' style='padding:10px; background:#fff;'>
            <form action="#" class="form">
                <fieldset>
                  <div class="fieldbox">
                    <textarea id="advancedsearch_textarea_large" name="advancedsearch_textarea_large" class="textarea large">http://www.swissbib.ch/TouchPoint/perma.do?q=-1+%3D+%22xml%22+IN+%5B3%5D&v=nose&l=de</textarea>
                    </div>
                </fieldset>
                <fieldset>
                    <div class="fieldbox">

                        <div class="addthis_toolbox addthis_default_style addthis_32x32_style" >
                            <a class="addthis_button_favorites"></a>
                            <a class="addthis_button_facebook"></a>
                            <a class="addthis_button_pingfm"></a>
                            <a class="addthis_button_twitter"></a>
                            <a class="addthis_button_email"></a>
                            <a class="addthis_button_google"></a>
                            <a class="addthis_button_stumbleupon"></a>
                            <a class="addthis_button_compact"></a>
                        </div>
                        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=swissbib"></script>

                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>