
<div class="paging">
    <div class="paging_pages">
        <ul>
            <li><span>1</span></li>
            <li><a href="#" title="2">2</a></li>
            <li><a href="#" title="3">3</a></li>
            <li><a href="#" title="4">4</a></li>
            <li><a href="#" title="5">5</a></li>
        </ul>
    </div>
    <a href="#" title="weiter" class="paging_forward">weiter</a>
    <a href="#" title="3 Seiten weiter" class="paging_last">3 Seiten weiter</a>
    <a href="#" title="" class=""></a>
</div>
