

<!-- ich brauche etwas mit dem ich steuern kann, welche Elemente tools floatbox enthält
einmal top einmal bottom
-->

<div class="tools floatbox">

    <!--START of /nose/resultlist/sbToolsSort.jsp-->
    <h3 class="hidden">Einstellungen Suchresultat Anzeige</h3>
    <label for="selectedSorting">Sortieren nach:</label>
    <select id="selectedSorting" class="select mright"><option value="unsortiert">nach Relevanz</option>
            <option value="3_SORTING_2">Jahr (ältestes zuerst)</option>
            <option value="3_SORTING_3">Jahr (neustes zuerst)</option>
            <option value="3_SORTING_4">Autor (A-Z)</option>
            <option value="3_SORTING_5">Autor (Z-A)</option>
            <option value="3_SORTING_6">Titel (A-Z)</option>
            <option value="3_SORTING_7">Titel (Z-A)</option>
    </select>
    <input type="submit" name="change_sorting_3" value="Sortieren" id="changeSortingbutton" class="hidden" />
    <div class="hidden">
        <select name="selectedMemorizeList" id="hiddenMemorizeSelection" class="select">
            <option value="3_-1" selected="selected">Temporäre Merkliste</option>
        </select>
        <input type="submit" name="save_to_memorize_3" value="Speichern" id="hiddensaveToListbutton" />
    </div>

    <!--END of /nose/resultlist/sbToolsSort.jsp-->
    <!--START of /nose/resultlist/sbToolsDisplay.jsp-->
    <!-- display hit-amount -->
    <select name="selectedHitlistSize" id="searchresult_displaynb" class="select tiny"><option value="3_10" selected="selected">10</option>
      <option value="3_25">25</option>
      <option value="3_50">50</option>
      <option value="3_100">100</option>
    </select>
    <input type="submit" name="change_hitlistsize_3" value="Anzeigen" id="changeHitListSizebutton" class="hidden" />
    <!-- display long/short -->
    <label for="searchresult_display_listtype">Liste</label>
    <select  id="searchresult_display_listtype" name="selectedListType" class="select tiny" >
        <option selected value="long" >lang</option>
        <option  value="short">kurz</option>
    </select>
     <script type="text/javascript">
        jQuery("[name=selectedListType]").bind('change',function (event)
        {
                    $("#changeHitListSizebutton").click();
        });
    </script>
    <input type="submit" name="change_hitsize_3" value="Anzeigen" id="changeHitSizebutton" class="hidden" />
    <!--END of /nose/resultlist/sbToolsDisplay.jsp-->



    <?=$this->render("search/controls/paging.phtml")?>

</div>
