<?
    	// Set page title
    $this->headTitle($this->translate('Checked Out Items'));

//    	// Set up breadcrumbs
//    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
//        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
//        . $this->transEsc('Checked Out') . '</em>';
?>

<?=$this->myResearchSideBar('checkedout', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?=$this->transEsc('Your Checked Out Items')?></h1>
			<?=$this->flashmessages()?>

			<? if( !empty($this->transactions) ): ?>
				<? if( $this->renewForm ): ?>
					<form name="renewals" action="" method="post" id="renewals">
						<input type="submit" class="button renew" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" style="margin-bottom: 10px"/>
					<br>
				<? endif; ?>

				<?= $this->render('myresearch/checkedout/itemlist.phtml') ?>

				<? if( $this->renewForm ): ?>
					</form>
				<? endif; ?>

			<? else: ?>
				<p><?=$this->transEsc('You do not have any items checked out') ?>.</p>
			<? endif; ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->