<h3><?=$this->transEsc('confirm_delete') ?></h3>

<form action="<?=$this->url('myresearch-delete')?>" method="post" name="bulkDelete">
  <div id="popupMessages"><?=$this->flashmessages()?></div>
  <div id="popupDetails">
    <? if (!$this->list): ?>
      <div><?=$this->transEsc("fav_delete_warn") ?></div>
    <? else: ?>
      <h2><?=$this->transEsc("List") ?>: <?=$this->escapeHtml($this->list->title) ?></h2>
    <? endif; ?>
    
    <? foreach ($this->records as $favorite): ?>
      <strong><?=$this->translate('Title') ?>:</strong>
      <?=$this->escapeHtml($favorite->getBreadcrumb())?><br />
    <? endforeach; ?>
    <br />
    <input class="submit primary" type="submit" name="submit" value="<?=$this->transEsc('Delete')?>"/>
    <input class="close reset" type="button" name="close" value="<?= $this->transEsc('Cancel') ?>" />
    <? foreach ($this->deleteIDS as $deleteID): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtml($deleteID)?>" />
    <? endforeach; ?>
      <input type="hidden" name="listID" value="<?=$this->list?$this->escapeHtml($this->list->id):''?>" />
  </div>
</form>