<?
// Set up page title:
$pageTitle = empty($this->list->id) ? 'Create a List' : "edit_list";
$this->headTitle($this->translate($pageTitle));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
    . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
    . $this->transEsc($pageTitle) . '</em>';
?>
<h1><?= $this->transEsc($pageTitle); ?></h1>

<?= $this->flashmessages() ?>

<form class="form" method="post" name="<?= empty($this->list->id) ? 'newList' : 'editListForm' ?>" action="">
    <fieldset>
        <div class="fieldgroup">
            <div class="fieldbox">
                <label class="label" for="list_title"><?= $this->transEsc('List'); ?>:</label>
                <input id="list_title" type="text" name="title"
                       value="<?= isset($this->list['title']) ? $this->escapeHtml($this->list['title']) : '' ?>"
                       class="text large mainFocus <?= $this->jqueryValidation(array('required' => 'This field is required')) ?>"/>
            </div>
            <div class="fieldbox">
                <label class="label" for="list_desc"><?= $this->transEsc('Description') ?>:</label>
                <textarea id="list_desc" name="desc"
                          class="textarea large"><?= isset($this->list['description']) ? $this->escapeHtml($this->list['description']) : '' ?></textarea>
            </div>
            <div class="fieldbox">
                <label class="label"><?= $this->transEsc('Access') ?>:</label>
                <input class="checkbox" id="list_public_1" type="radio" name="public"
                       value="1"<? if ($this->list->isPublic()): ?> checked="checked"<? endif; ?>/> <label
                    for="list_public_1"><?= $this->transEsc('Public') ?></label>
                <input class="checkbox" id="list_public_0" type="radio" name="public"
                       value="0"<? if (!$this->list->isPublic()): ?> checked="checked"<? endif; ?>/> <label
                    for="list_public_0"><?= $this->transEsc('Private') ?></label>
            </div>
        </div>
    </fieldset>
    <fieldset class="actions">
        <input class="submit primary" type="submit" name="submit" value="<?= $this->transEsc('Save') ?>"/>
        <a class="linkbutton icon_backto"
           href="<?= $this->domainURL()->getRefererURL() ?>"><span><?= $this->transEsc('navigate_back') ?></span></a>
    </fieldset>
</form>

