<?
    	// Set page title
    $this->headTitle($this->translate('My Holds'));
//
//    	// Set up breadcrumbs
//    $this->layout()->breadcrumbs =
//		'<a href="' . $this->url('myresearch-home') . '">'
//	.	$this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
//	.	$this->transEsc('My Holds') . '</em>';

?>

<?=$this->myResearchSideBar('holds', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?=$this->translate('Your Holds and Recalls') ?></h1>

			<?=$this->flashmessages()?>

			<? if( !empty($this->recordList) ): ?>
				<? if( $this->cancelForm ): ?>
					<form name="cancelForm" action="" method="post" id="cancelHold">
					<input	type="submit" class="button holdCancel" name="cancelSelected"
						   value="<?=$this->translate("hold_cancel_selected") ?>"
						   onClick="return confirm('<?=$this->translate("confirm_hold_cancel_selected_text") ?>')"
						   style="margin-bottom: 10px"/>
					<br />
				<? endif; ?>

				<?=$this->render('myresearch/holds/itemlist.phtml')?>

				<? if( $this->cancelForm ): ?>
					</form>
				<? endif; ?>
			<? else: ?>
				<p><?= $this->transEsc('You do not have any holds or recalls placed') ?>.</p>
			<? endif; ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->