<?
    // Set up page title:
    $this->headTitle($this->translate('My Holds'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('My Holds') . '</em>';
?>
<?=$this->myResearchSideBar('holds');?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h2><?=$this->translate('Your Holds and Recalls') ?></h2>

			<?=$this->flashmessages()?>

			<? if( !empty($this->recordList) ): ?>
				<? if( $this->cancelForm ): ?>
					<form name="cancelForm" action="" method="post" id="cancelHold">
					<?=$this->render('myresearch/holds/cancelform.phtml')?>
				<? endif; ?>

				<?=$this->render('myresearch/holds/itemlist.phtml')?>

				<? if( $this->cancelForm ): ?>
					</form>
				<? endif; ?>
			<? else: ?>
				<?= $this->transEsc('You do not have any holds or recalls placed') ?>.
			<? endif; ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->











