<?
	// Set page title
$this->headTitle($this->translate('Login'));

	// If we're in AJAX mode, load some extra Javascript inline:
$lightBoxMode = $this->layout()->getTemplate() == 'layout/lightbox';

?>

<?php if ($lightBoxMode): ?>

	<?php $this->inlineScript()->appendFile("rc4.js"); ?>
	<?=$this->render('myresearch/login-form');?>

<?php else: ?>

	<!-- begin: col1 (sidebar)  -->
	<div id="col1" class="sidebar">
		<div id="col1_content" class="clearfix">
			<!-- begin: sidebar -->
			<div id="sidebar">
				<?=$this->render('myresearch/sidebar/login')?>
			</div>
			<!-- end: sidebar -->
		</div>
	</div>
	<!-- end: col1 (sidebar) -->
	<!-- begin: col3 (content) -->
	<div id="col3" class="content">
		<div id="col3_content" class="clearfix">
			<!-- begin: content -->
			<div id="content">

				<?=$this->render('myresearch/login-form');?>

			</div>
			<!-- end: content -->
		</div>
		<div id="ie_clearing">
			&nbsp;
		</div>
	</div>
	<!-- end: col3 (content) -->

<?php endif; ?>