<?php

	$this->headTitle($this->translate('Photocopies'));

?>

<?=$this->myResearchSideBar('photocopies', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">
			<h1><?=$this->transEsc('Photocopies')?></h1>

			<?=$this->flashmessages()?>

			<?php if( sizeof($this->photoCopies) ): ?>
				<p><?=$this->transEsc('Your photocopies') ?></p>
				<?=$this->render('myresearch/photocopies/itemlist.phtml')?>

			<?php else: ?>
				<p><?=$this->transEsc('No photocopies') ?></p>
			<?php endif; ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->