<?php

$this->headTitle($this->translate('Copy Jobs'));

?>
<?=$this->myResearchSideBar('copyjobs', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?=$this->transEsc('Copy Jobs')?></h1>

			<?=$this->flashmessages()?>

			<?php var_dump($this->photoCopies); ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->