<?
        // Set page title
    $this->headTitle($this->translate('My Profile'));
        // Only display home library form if we have multiple pickup locations
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);
        // Template for use by the renderArray helper
	$userDataMapping = array(
		$this->transEsc('First Name')       => 'firstname',
		$this->transEsc('Last Name')        => 'lastname',
		$this->transEsc('Address')          => 'address1',
		$this->transEsc('Zip')              => 'address2',
		//$this->transEsc('Zip')              => 'zip',
        $this->transEsc('Email')            => 'email',
		$this->transEsc('Phone Number')     => 'phone',
		//$this->transEsc('Group')            => 'group'
	);

?>

<?=$this->myResearchSideBar('profile', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">
			<h1><?=$this->transEsc('Your Profile')?></h1>
			<?=$this->flashmessages()?>

			<table>
				<tbody>
					<?php foreach($userDataMapping as $label => $key): ?>
						<tr>
							<th width="100"><?=$this->escapeHtml($label)?></th>
							<td><?=$this->escapeHtml($this->profile[$key])?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>

			<?php
				if( $showHomeLibForm ) {
					echo $this->render('myresearch/profile/pickupform.phtml', array(
						'pickup'				=> $this->pickup,
						'profile'				=> $this->profile,
						'defaultPickupLocation'	=> $this->defaultPickupLocation
					));
				}
            ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->