<?
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

//    // Set up breadcrumbs:
//    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
//        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
//        . $this->transEsc('Profile') . '</em>';

    // Only display home library form if we have multiple pickup locations:
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);

    // Template for use by the renderArray helper:
    $userDataTemplate	= '<span class="span-3"><strong>%%LABEL%%:</strong></span> %%VALUE%%<br class="clear"/>';
	$userData			= array(
		$this->transEsc('First Name') => 'firstname',
		$this->transEsc('Last Name') => 'lastname',
		$this->transEsc('Address') . ' 1' => 'address1',
		$this->transEsc('Address') . ' 2' => 'address2',
		$this->transEsc('Zip') => 'zip',
		$this->transEsc('Phone Number') => 'phone',
		$this->transEsc('Group') => 'group'
	);

?>
<?=$this->myResearchSideBar('profile', $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?=$this->transEsc('Your Profile')?></h1>

			<?=$this->flashmessages()?>

			<?=$this->renderArray($userDataTemplate, $this->profile, $userData)?>

			<?php
				if( $showHomeLibForm ) {
					echo $this->render('myresearch/profile/pickupform.phtml', array(
						'pickup'				=> $this->pickup,
						'profile'				=> $this->profile,
						'defaultPickupLocation'	=> $this->defaultPickupLocation
					));
				}
			?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->