<?
        // Set page title
    $this->headTitle($this->translate('My_Search_Settings'));

        // Only display home library form if we have multiple pickup locations
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);
    $active = $helper->getCurrent()->getTemplate() !== 'myresearch/searchsettings' ? 'profile' : 'searchsettings';

?>

<?=$this->myResearchSideBar($active, $this->location);?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">
			<h1><?=$this->transEsc('My_Search_Settings')?></h1>
			<?=$this->flashmessages()?><br/>

            <form name="form_useraccount" action="/vufind/MyResearch/Saveaccountlocal" method="get" id="save_account_submit">
                <h3><?= $this->transEsc('preferences.search') ?></h3>

                <label for="language"><?=$this->transEsc('Language')?>: </label>
                <select id="language" name="language">
                    <? foreach ($this->optsLanguage as $languageKey => $languageLabel): ?>
                        <option <? if($languageKey == $this->language): ?>selected="selected"<? endif; ?> value="<?= $languageKey ?>">
                            <?= $languageLabel ?>
                        </option>
                    <? endforeach; ?>
                </select>

                <br/><br/><br/>
                <h3><?= $this->transEsc('preferences.result') ?></h3>

                <label for="maxHits"><?=$this->transEsc('Max_Amount_Hits')?>: </label>
                <select id="maxHits" name="max_hits">
                    <? foreach ($this->optsMaxHits as $amountHits): ?>
                        <option <? if($amountHits == $this->maxHits): ?>selected="selected"<? endif; ?> value="<?= $amountHits ?>">
                            <?= $amountHits ?>
                        </option>
                    <? endforeach; ?>
                </select>

            </form>
		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->