<?php

/** @var	Swissbib\RecordDriver\SolrMarc	$resultItem  */
$resultItem	= $this->driver;
/** @var	VuFind\View\Helper\Root\Record		$record  */
$viewRecord	= $this->record($resultItem);

//$authors	= $this->Authors($resultItem->getDeduplicatedAuthors());

$mediumThumb= $viewRecord->getThumbnail('medium');
//$largeThumb	= $viewRecord->getThumbnail('large');
$thumbUrl	= $mediumThumb ? $mediumThumb : $this->url('cover-unavailable');

$subTitle				= $resultItem->getSubtitle(true);
$titleStatement			= $resultItem->getTitleStatement(true);
$secondaryAuthors		= $resultItem->getSecondaryAuthors();
$publishers				= $resultItem->getPublishers(true);
$physicalDescriptions	= $resultItem->getPhysicalDescriptions(true);
$edition				= $resultItem->getEdition();
$summary				= trim(implode($resultItem->getSummary()));
$groupID				= $resultItem->getGroup(true);

$publicationDate		= $this->publicationDateMarc($resultItem->getPublicationDates());

?>

<?/* Common parts of recordDriver's core.phtml templates*/?>
<!-- col -->
<div class="c25l">
	<a title="Zur Merkliste hinzufügen" class="icon_notepad_add_link" href="#">
		<img src="<?=$thumbUrl?>" class="dropshadow"/>
	</a>
</div>

<!-- col -->
<div class="c75l">
	<h2><?=$this->escapeHtml($resultItem->getShortTitle())?></h2>
	<?php if($subTitle): ?>
        <p><?=$this->escapeHtml($subTitle)?></p>
    <?php endif ?>
	<!-- details -->
	<div class="details">

		<?php if($titleStatement): ?>
		<h4><?=$this->transEsc('Author')?>:</h4>
		<p><?=$this->escapeHtml($titleStatement['title'])?></p>
		<?php endif; ?>

		<?php if($publishers): ?>
			<h4><?=$this->transEsc('Publication')?>:</h4>
			<p><?=$this->escapeHtml(implode(' | ', $publishers))?>, <?=$publicationDate?></p>
		<?php endif; ?>

        <?php if($physicalDescriptions): ?>
            <h4><?=$this->transEsc('Physical Description')?>:</h4>
                <p>
					<?php foreach($physicalDescriptions as $physicalDescription): ?>
						<?=$this->escapeHtml(implode(',', $physicalDescription['extent']))?>.
						<?php if( isset($physicalDescription['details']) ): ?>:
							<?=$this->escapeHtml(implode(',', $physicalDescription['details']))?>.
						<?php endif; ?>
						<?php if( isset($physicalDescription['dimensions']) ): ?>;
							<?=$this->escapeHtml(implode(',', $physicalDescription['dimensions']))?>
						<?php endif; ?>
						<?php if (isset($physicalDescription['company']) ): ?>+
							<?=$this->escapeHtml(implode(',', $physicalDescription['company']))?>.
						<?php endif; ?>
					<?php endforeach; ?>
                </p>
        <?php endif; ?>

		<h4><?=$this->transEsc('Format')?>:</h4>
		<p>
		<?php foreach($resultItem->getFormats() as $format): ?>
			<span class="icon_format_book"><?=$this->escapeHtml($format)?></span>
		<?php endforeach; ?>
		</p>

		<?php if($edition): ?>
		    <h4><?=$this->transEsc('Edition')?>:</h4>
		    <p><?=$this->escapeHtml($edition)?></p>
		<?php endif; ?>

		<?php if(!empty($summary)): ?>
		<h4>Inhalt:</h4>
		<p><?$this->escapeHtml($summary)?></p>
		<?php endif; ?>

	</div>

    <?php if(!empty($groupID)): ?>
	    <a href="#frbr.html" class="linkbutton icon_show" title="<?=$this->transEsc('FRBR_Button')?>">
			<span><?=$this->transEsc('FRBR_Button')?></span>
		</a>
    <?php endif; ?>

</div>