<table id="bookings-table">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th><?=$this->transEsc('Title')?></th>
			<th><?=$this->transEsc('date_from')?></th>
			<th><?=$this->transEsc('date_to')?></th>
			<th><?=$this->transEsc('Place of Delivery') ?></th>
		    <th><?=$this->transEsc('Library') ?></th>
			<th><?=$this->transEsc('Call Number') ?></th>
			<th><?=$this->transEsc('Note') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->bookings as $index => $booking): ?>
			<tr id="photocopy-<?=$index?>">
				<td><?=$index+1?></td>
				<td><?=$this->escapeHtml($booking['title'])?></td>
				<td><?=date('d/m/y H:i', $booking['dateStart'])?></td>
				<td><?=date('d/m/y H:i', $booking['dateEnd'])?></td>
				<td><?=$this->escapeHtml($booking['pickupLocation'])?></td>
		        <td><?=$this->escapeHtml($booking['library'])?></td>
				<td><?=$this->escapeHtml($booking['callNumber'])?></td>
				<td></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>