<div class="tabbed tabbed_selected tabbed_<?=$tabKey?>">
    <? if($tabHeadConfig['selected']): ?>
        <?=$this->render('global/sidebar/search/tabcontentinner.phtml')?>
    <? else: // Render placeholder for lazy-loaded inactive tab ?>
       <h3>Lade Filter</h3>
       <div class="filters">
            <div class="ajax_loading_spinner_transp" style="width:32px; height:32px;"></div>
       </div>
    <? endif; ?>
</div>