<?
    // Set page title.
    $this->headTitle($this->translate('Search History'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('History') . '</em>';
?>
<?=$this->myResearchSideBar('history');?>
<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<? if( !empty($this->saved) || !empty($this->unsaved) ): ?>

				<? if( !empty($this->saved) ): ?>
					<h1><?=$this->transEsc("history_saved_searches")?></h1>
					<?= $this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true)); ?>
				<? endif; ?>

				<? if( !empty($this->unsaved) ): ?>
					<h1><?=$this->transEsc("history_recent_searches")?></h1>
					<?= $this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false)); ?>
					<a href="?purge=true" class="delete"><?=$this->transEsc("history_purge")?></a>
				<? endif; ?>

			<? else: ?>

				<h1><?=$this->transEsc("history_recent_searches")?></h1>
				<?= $this->transEsc("history_no_searches") ?>

			<? endif; ?>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->