<table class="data" width="100%">
  <colgroup>
      <col width="25%">
      <col width="30%">
      <col width="30%">
      <col width="10%">
      <col width="5%">
  </colgroup>
  <thead>
      <tr>
           <th><?=$this->transEsc("history_time")?></th>
           <th><?=$this->transEsc("history_search")?></th>
           <th><?=$this->transEsc("history_limits")?></th>
           <th><?=$this->transEsc("history_results")?></th>
           <th><?=$this->transEsc($this->showSaved ? "history_delete" : "history_save")?></th>
      </tr>
  </thead>
  <tbody>
      <? foreach (($this->showSaved ? array_reverse($this->saved) : array_reverse($this->unsaved)) as $iteration => $info): ?>
          <tr>
              <td class="small left"><?=$this->escapeHtml(date("G:i, j.m.Y", $info->getStartTime()))?></td>
              <td>
                  <h3 class="nomargin">
                      <a class="color" href="<?=$this->url($info->getOptions()->getSearchAction()) . $info->getUrlQuery()->getParams()?>"><?
                          $desc = $info->getParams()->getDisplayQuery();
                          echo empty($desc) ? $this->transEsc("history_empty_search") : $this->escapeHtml($desc);
                          ?></a>
                  </h3>
                  <? if (method_exists($info,'getTarget')): ?>
                      <span class="meta"><?=$this->transEsc('tab.' . $info->getTarget())?></span>
                  <? endif; ?>
              </td>
              <td class="small left">
                  <? $info->getParams()->activateAllFacets(); foreach ($info->getParams()->getFilterList() as $field => $filters): ?>
                      <? foreach ($filters as $filter): ?>
                          <strong><?=$this->transEsc($field)?></strong>: <?=$this->escapeHtml($filter['displayText'])?><br/>
                      <? endforeach; ?>
                  <? endforeach; ?>
              </td>
              <td class="small left"><?=$this->escapeHtml(number_format($info->getResultTotal()))?></td>
              <td>
                  <? if ($this->showSaved): ?>
                      <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($info->getSearchId())?>&amp;mode=history" class="linkbutton icon_delete"><span><?=$this->transEsc("history_delete_link")?></span></a>
                  <? else: ?>
                      <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($info->getSearchId())?>&amp;mode=history" class="linkbutton add"><span><?=$this->transEsc("history_save_link")?></span></a>
                  <? endif; ?>
              </td>
          </tr>
      <? endforeach; ?>
  </tbody>

</table>
