<h1 class="hidden">Informationen zu swissbib</h1>
<!-- begin: teaser -->
<div class="teaser">
	<!-- col -->
	<div class="c50l">
		<div class="box h150 bmright">
			<h2>Über swissbib</h2>
			<p>
				SwissBib ist der Metakatalog der Schweizer Hochschulbibliotheken und der  Schweizerischen Nationalbibliothek. Er bietet einen raschen, einfachen und umfassenden Zugang zu wissenschaftlicher Information in der Schweiz an.
			</p>
			<ul class="actions">
				<li class="right">
					<a href="inhaltsseite.html" class="linkbutton primary icon_goto_primary" title="Mehr Infos"><span>Mehr Infos</span></a>
				</li>
			</ul>
		</div>
	</div>
	<!-- col -->
	<div class="c50l">
		<div class="box h150 bmleft">
			<h2>Leichter suchen - schneller finden</h2>
			<p>
				Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum.
			</p>
			<ul class="actions">
				<li class="right">
					<a href="inhaltsseite.html" class="linkbutton primary icon_goto_primary" title="Mehr Infos"><span>Mehr Infos</span></a>
				</li>
			</ul>
		</div>
	</div>
</div><!-- end: teaser -->