<table class="data">
	<colgroup>
		<col width="1%">
		<col width="1%">
		<col width="10%">
		<col width="*">
		<col width="11%">
		<col width="1%">
	</colgroup>
	<caption class="hidden">
        <?=$this->transEsc('Library Catalog Search Result')?>
	</caption>
	<thead class="hidden">
		<tr>
			<th><?=$this->transEsc('Number')?></th>
			<th>Merkliste</th>
			<th><?=$this->transEsc('Cover Image')?></th>
			<th><?=$this->transEsc('Description')?></th>
			<th><?=$this->transEsc('Library')?></th>
			<th><?=$this->transEsc('information')?></th>
		</tr>
	</thead>
	<tbody>

	<?php
	$this->startIndex	= $this->results->getStartRecord();

	foreach ($this->results->getResults() as $index => $result) {
		$this->recordIndex = $this->startIndex + $index;
		echo $this->record($result)->getSearchResult('list');
	}

	?>

	</tbody>
</table>