<h1><?=$this->transEsc('nohit_heading') ?></h1>
<div class="box">
<?
    $spellingSuggestions = $this->results->getSpellingSuggestions();
    if (sizeof($spellingSuggestions) > 0) {
?>
        <h4><?= $this->translate('nohit_spelling') ?></h4>
            <ul class="list">
            <?
            foreach ($spellingSuggestions as $oldTerm => $details) {
                foreach ($details['suggestions'] as $newWord => $data) {
                    $newUrl = $results->getUrlQuery()->replaceTerm($oldTerm,$data['new_term']);
            ?>
                    <li><a href="<?=$newUrl ?>"><?= $this->escapeHtml($newWord) ?></a></li>
            <?
                }
            }
            ?>
            </ul>
<?
    }
?>
<?=$this->translate('nohit_suggest') ?>
</div>


