<h1><?=$this->transEsc('nohit_heading') ?></h1>
<div class="box">
<?
    $spellingSuggestions = $this->results->getSpellingSuggestions();
    if (sizeof($spellingSuggestions) > 0) {
?>
        <h4><?= $this->translate('nohit_spelling') ?>: </h4>
            <ul class="list">
            <?
            foreach ($spellingSuggestions as $oldTerm => $details) {
                foreach ($details['suggestions'] as $newWord => $data) {
                    $newUrl = $results->getUrlQuery()->replaceTerm($oldTerm,$data['new_term']);
            ?>
                    <li><a href="<?=$newUrl ?>"><?= $this->escapeHtml($newWord) ?></a></li>
            <?
                }
            }
            ?>
            </ul>
<?
    }
?>
    <h4><?=$this->transEsc('nohit_suggest') ?></h4>
    <ul class="list">
        <li>Stimmt die Rechtschreibung?</li>
        <li>Wenn Sie mehrere Suchbegriffe eingegeben haben, reduzieren Sie die Menge.</li>
        <li>Können Sie die Suche mit anderen Suchbegriffen beschreiben?</li>
    </ul>
    <h4>Weitere Hilfe</h4>
    <ul class="list">
        <li>Siehe <em><a href="<?=$this->url('help-page')?>"><?=$this->transEsc('helppage')?></a> </em> für weitere Suchtipps</li>
        <li>Siehe <em><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></em> für zusätzliche Suchoptionen und Links zu weiteren Katalogen.</li>
    </ul>
</div>


