<?php

$bulkExportFormats = array('EndNote', 'MARC', 'RefWorks', 'MARCXML');

?>
<div id="pagefunctions" class="offset">
	<h3 class="hidden"><?=$this->transEsc('Search Tools')?></h3>
	<ul>

		<li id="pagefunction_rss">
			<a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>" title="<?=$this->transEsc('Get RSS Feed')?>"><?=$this->transEsc('Get RSS Feed')?></a>
		</li>

		<li id="pagefunction_print">
			<a href="#" title="<?=$this->transEsc('Print')?>"><?=$this->transEsc('Print')?></a>
		</li>

		<li id="pagefunction_send">
			<a href="<?=$this->url('search-email')?>" title="<?=$this->transEsc('Email this Search')?>"><?=$this->transEsc('Email this Search')?></a>
		</li>

		<li id="pagefunction_save" class="bulkExport">
			<a href="#" title="<?=$this->transEsc('Save')?>"><?=$this->transEsc('Save')?></a>
			<ul class="menu" id="exportMenu">
				<?php foreach ($bulkExportFormats as $format): ?>
					<li>
						<a href="<?=$this->url('cart-doexport')?>?f=<?=$format?>"><?= $this->transEsc('Export to') ?> <?= $this->escapeHtml($format) ?></a>
					</li>
				<?php endforeach; ?>
			</ul>
		</li>

	</ul>
</div>