<?php
 /*
  * @todo: make this array configurable?, keep list identical with [Export] in config_base.ini
  */
$bulkExportFormats = array('EndNote', 'MARCXML', 'BibTeX');

?>
<div id="pagefunctions" class="offset">
	<h3 class="hidden"><?=$this->transEsc('Search Tools')?></h3>
	<ul>

		<li id="pagefunction_rss">
			<a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>" title="<?=$this->transEsc('Get RSS Feed')?>"><?=$this->transEsc('Get RSS Feed')?></a>
		</li>

		<li id="pagefunction_print">
			<a href="#" title="<?=$this->transEsc('Print')?>"><?=$this->transEsc('Print')?></a>
		</li>

		<li id="pagefunction_send" class="sendResults">
			<a href="<?=$this->url('search-email')?>" title="<?=$this->transEsc('Email this Search')?>" class="mailSearch" id="mailSearch<?=$this->escapeHtml($this->results->getSearchId())?>"><?=$this->transEsc('Email this Search')?></a>
		</li>

		<li id="pagefunction_save" class="bulkExport">
			<a href="#" title="<?=$this->transEsc('Save')?>"><?=$this->transEsc('Save')?></a>
			<ul class="menu" id="exportMenu">
				<?php foreach ($bulkExportFormats as $format): ?>
					<li>
						<a href="<?=$this->url('cart-doexport')?>?f=<?=$format?>"><?= $this->transEsc('Export to') ?> <?= $this->escapeHtml($format) ?></a>
					</li>
				<?php endforeach; ?>
			</ul>
		</li>

	</ul>
</div>