




    <? if ($this->facetControl["hasfacets"]): ?>

        <h3>Ihre Suche</h3>
        <div class="filters">
            <p><cite>Alle Felder = ???</cite></p>
            <? $filterList = $this->results->getParams()->getFilterList(true); if (!empty($filterList)): ?>
                <? foreach ($filterList as $field => $filters): ?>
                  <? foreach ($filters as $filter): ?>
                    <?
                        $removeLink = $this->url().$this->results->getUrl()->removeFacet($filter['field'], $filter['value']);
                        if ($filter['displayText'] == '[* TO *]') $filter['displayText'] = $this->translate('filter_wildcard');
                    ?>
                    <div class="filter" id="filter_<?=$this->transEsc($field)?>">
                        <h5><?=$this->transEsc($field)?>: <?=$this->escape($filter['displayText'])?></h5>
                        <ul><li><a href="<?=$removeLink?>" class="filter_remove" title="Suchfilter <?=$this->transEsc($filter['field'])?> entfernen"><?=$this->transEsc($field)?>: <?=$this->escape($filter['displayText'])?></a></li></ul>
                    </div> <!-- end filter: tempFilterLabel -->
                  <? endforeach; ?>
                <? endforeach; ?>
            <? endif; ?>
        </div> <!-- end: <div class="filters" -->




        <h3>Treffer eingrenzen</h3>
        <div class="facets">

            <? $recommend = $this->facetControl["recommend"];   $sideFacetSet = $recommend->getFacetSet(); $dateFacets = $recommend->getDateFacets(); ?>
            <? if (!empty($sideFacetSet) && $this->results->getResultTotal() > 0): ?>


            <? foreach ($sideFacetSet as $title => $cluster): ?>
              <? if (isset($dateFacets[$title])): ?>
                <? /* das muss noch in einer Art und Weise dargestellt werden, dass es fuer uns passt */ ?>
                <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
                <form action="<?=$this->url()?>" name="<?=$this->escape($title)?>Filter" id="<?=$this->escape($title)?>Filter">
                  <?=$this->results->getUrl()->asHiddenFields(array('filter' => "/^{$title}:.*/"))?>
                  <input type="hidden" name="daterange[]" value="<?=$this->escape($title)?>"/>
                  <fieldset class="publishDateLimit" id="<?=$this->escape($title)?>">
                    <legend><?=$this->transEsc($cluster['label'])?></legend>
                    <label for="<?=$this->escape($title)?>from"><?=$this->transEsc('date_from')?>:</label>
                    <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escape($title)?>from" id="<?=$this->escape($title)?>from" value="<?=isset($dateFacets[$title][0])?$this->escape($dateFacets[$title][0]):''?>" />
                    <label for="<?=$this->escape($title)?>to"><?=$this->transEsc('date_to')?>:</label>
                    <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escape($title)?>to" id="<?=$this->escape($title)?>to" value="<?=isset($dateFacets[$title][1])?$this->escape($dateFacets[$title][1]):''?>" />
                    <div id="<?=$this->escape($title)?>Slider" class="dateSlider"></div>
                    <input type="submit" value="<?=$this->transEsc('Set')?>" id="<?=$this->escape($title)?>goButton"/>
                  </fieldset>
                </form>
              <? else: ?>
                    <div class="facet" id="facet_Thema">
                        <h5 class="toggler persist" id="facet_toggler_<?=$title?>"><?=$title?></h5>
                        <ul class="facet_toggler_<?=$title?>" >

                            <? $i=0; ?>
                            <? foreach ($cluster['list'] as $thisFacet): ?>
                                <? if ($thisFacet['isApplied']): ?>
                                    <? continue ?>
                                <? endif; ?>
                                <? ++$i;?>

                                <li>

                                    <!--
                                    guenterh local - in Bearbeitung
                                    Problem mit geänderten Methodenaufrufen
                                    nach Umbau des search objects

                                     -->

                                </li>

                            <? endforeach; ?>

                        </ul>
                    </div>


              <? endif; ?>


            <? endforeach; ?>

            <? endif;?>

        </div>

    <?endif;?>

