<?php

	/** @var \VuFind\Search\Solr\Results	$results  */
	$results	= $this->results;
	/** @var \VuFind\Search\Solr\Params		$params  */
	$params		= $this->params;

	$recordTotal= $results->getResultTotal();
	$lookFor	= $params->getDisplayQuery();

?>

    <h1>
        <?=$this->number($recordTotal)?> Treffer für ihre Suchanfrage
        <cite><?=$this->escapeHtml($lookFor)?></cite>
    </h1>

	<?php if($recordTotal): ?>
		<!-- begin: tools -->
		<div class="tools floatbox">
			<!-- sort -->
			<h3 class="hidden">Einstellungen Suchresultat Anzeige</h3>
			<?=$this->render('search/controls/sort.phtml')?>
			<!-- display -->
			<?=$this->render('search/controls/limit.phtml')?>
			<!-- paging -->
			<?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $results))?>
		</div>
		<!-- end: tools -->
	<?php endif; ?>

	<!-- data -->
	<?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml')?>

	<?php if($recordTotal): ?>
		<!-- begin: tools -->
		<div class="tools floatbox">
			<!-- paging -->
			<?=$this->partial('search/controls/view.phtml')?>
		</div><!-- end: tools -->
	<?php endif; ?>