<?
// Set page title.
$this->headTitle($this->translate('Email Record'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
		$this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('Email Record') . '</em>';
?>
<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
	<div id="col1_content" class="clearfix">
		<!-- begin: sidebar -->
		<?= $this->render('record/sidebar') ?>
		<!-- end: sidebar -->
	</div>
</div>
<!-- end: col1 (sidebar) -->

<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?= $this->transEsc('Email Record') ?></h1>

			<?= $this->flashmessages() ?>

			<form action="" method="post" name="emailRecord">
				<input type="hidden" name="id" value="<?= $this->escapeHtml($this->driver->getUniqueId()) ?>"/>
				<input type="hidden" name="source" value="<?= $this->escapeHtml($this->driver->getResourceSource()) ?>"/>

				<label class="displayBlock" for="email_to"><?= $this->transEsc('To') ?>:</label>
				<input id="email_to" type="text" name="to" value="<?= isset($this->to) ? $this->to : '' ?>" size="40"
					   class="displayBlock mainFocus <?= $this->jqueryValidation(array('required' => 'This field is required', 'email' => 'Email address is invalid')) ?>"/>
				<br>
				<label class="displayBlock" for="email_from"><?= $this->transEsc('From') ?>:</label>
				<input id="email_from" type="text" name="from" value="<?= isset($this->from) ? $this->from : '' ?>"
					   size="40"
					   class="displayBlock  <?= $this->jqueryValidation(array('required' => 'This field is required', 'email' => 'Email address is invalid')) ?>"/>
				<br>
				<label class="displayBlock" for="email_message"><?= $this->transEsc('Message') ?>:</label>
				<textarea id="email_message" name="message" rows="3" class="displayBlock "
						  cols="40"><?= isset($this->message) ? $this->message : '' ?></textarea>
				<br/>
				<input class="button" type="submit" name="submit" value="<?= $this->transEsc('Send') ?>"/>
			</form>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->
