<?php

$isAvailable= isset($item['isAvailable']) && $item['isAvailable'];
$actions	= array();

	// Build item links
	// @todo Move into holdings helper or view helper as soon as the feature set is clear
if( isset($item['userActions']) ) {
	if( $item['userActions']['hold'] ) {
		$actions[] = array(
			'label'	=> 'ausleihen',
			'action'=> $this->recordLink()->getHoldUrl($item['holdLink'])
		);
	}
	if( $item['userActions']['shortLoan'] ) {
		$actions[] = array(
			'label'	=> 'Kurzausleihe',
			'action'=> 'javascript:alert(\'Not implemented yet\')'
		);
	}
	if( $item['userActions']['photocopyRequest'] ) {
		$actions[] = array(
			'label'	=> 'Kopie bestellen',
			'action'=> $item['userActions']['photocopyRequestLink']
		);
	}
	if( $item['userActions']['bookingRequest'] ) {
		$actions[] = array(
			'label'	=> 'Booking Request',
			'action'=> 'javascript:alert(\'Not implemented yet\')'
		);
	}
} elseif( isset($item['holdLink']) ) {
	$actions[] = array(
		'label'	=> 'ausleihen',
		'action'=> $this->recordLink()->getHoldUrl($item['holdLink'])
	);
}

?>
<tr>
	<td><?=$this->escapeHtml($item['location_expanded'])?></td>
	<td><?=$this->escapeHtml($item['signature'])?></td>
	<td><?php if($isAvailable):?>ausleihbar<?php else: ?>nicht ausleihbar<?php endif; ?></td>
	<td>erhältlich</td>
	<td><?=$this->escapeHtml($item['opac_note'])?></td>
	<td>
		<ul>
			<?php foreach($actions as $action): ?>
                <li><a href="<?=$this->escapeHtml($action['action'])?>" ><?=$this->escapeHtml($action['label'])?></a></li>
			<?php endforeach; ?>
		</ul>
	</td>
</tr>