<?
    	// Set page title
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

    	// Set up breadcrumbs
//  $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
//  $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('request_place_text') . '</em>';

?>

<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
	<div id="col1_content" class="clearfix">
		<!-- begin: sidebar -->
		Sidebar für Bestellungen
		<!-- end: sidebar -->
	</div>
</div>
<!-- end: col1 (sidebar) -->

<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<h1><?=$this->transEsc('request_place_text')?></h1>
			
			<?=$this->flashmessages()?>

			<div class="hold-form">
				<form class="form" action="" method="post">
                    <fieldset>
                        <?php if( in_array("pickUpLocation", $this->extraHoldFields) ): ?>
                            <div class="fieldbox">
                                <?php if( count($this->pickup) > 1 ): ?>
                                    <?
                                    if( isset($this->gatheredDetails['pickUpLocation']) && !empty($this->gatheredDetails['pickUpLocation']) ) {
                                        $selected = $this->gatheredDetails['pickUpLocation'];
                                    }
                                    elseif( isset($this->homeLibrary) ) {
                                        $selected = $this->homeLibrary;
                                    }
                                    else {
                                        $selected = $this->defaultPickup;
                                    }
                                    ?>
                                    <label class="label" for="gatheredDetails[pickUpLocation]"><?=$this->transEsc('pick_up_location')?>:</label>
                                    <select class="select" name="gatheredDetails[pickUpLocation]">
                                        <?php foreach($this->pickup as $lib): ?>
                                            <option value="<?=$this->escapeHtml($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
                                                <?=$this->escapeHtml($lib['locationDisplay'])?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php else: ?>
                                    <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtml($this->defaultPickup)?>"/>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>

                        <?php if( in_array("comments", $this->extraHoldFields) ): ?>
                            <div class="fieldbox">
                                <label class="label" for="gatheredDetails[comment]"><?=$this->transEsc('Comments')?>:</label>
                                <textarea class="textarea large"
                                          name="gatheredDetails[comment]"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
                            </div>
                        <?php endif; ?>

                        <?php if (in_array("requiredByDate", $this->extraHoldFields)): ?>
                            <div class="fieldbox">
                                <label class="label" for="gatheredDetails[requiredBy]"><?= $this->transEsc("hold_required_by") ?> (<?= $this->dateTime()->getDisplayDateFormat() ?>): </label>
                                <input class="text small" id="requiredByDate" type="text"
                                                                  name="gatheredDetails[requiredBy]"
                                                                  value="<?= (isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtml($this->gatheredDetails['requiredBy']) : $this->escapeHtml($this->defaultRequiredDate) ?>"
                                                                  size="8"/>
                            </div>
                        <? endif; ?>
                    </fieldset>
                    <fieldset class="actions">
                        <input class="submit primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>

                    </fieldset>
				</form>
			</div>

		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->