<?php

$exportFormats = $this->export()->getFormatsForRecord($this->driver);
$controllerClass = 'controller' . $this->record($this->driver)->getController();

?>
<div id="pagefunctions" class="offset">
	<h3 class="hidden"><?=$this->transEsc('Search Tools')?></h3>
	<ul>

		<? if (count($this->driver->getCitationFormats()) > 0): ?>
			<li id="pagefunction_link">
				<a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" class="citeRecord cite <?=$controllerClass?>" id="citeRecord" title="<?=$this->transEsc('Cite this')?>"><?=$this->transEsc('Cite this')?></a>
			</li>
		<? endif; ?>

		<li id="pagefunction_print">
			<a href="#" title="<?=$this->transEsc('Print')?>"><?=$this->transEsc('Print')?></a>
		</li>

		<li id="pagefunction_send" class="sendRecord">
			<a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" class="mailRecord controllerRecord" title="<?=$this->transEsc('Email this')?>"><?=$this->transEsc('Email this')?></a>
		</li>

		<?php if (count($exportFormats) > 0): ?>
			<li id="pagefunction_save">
				<a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" title="<?=$this->transEsc('Save')?>"><?=$this->transEsc('Save')?></a>
				<ul class="menu" id="exportMenu">
					<?php foreach ($exportFormats as $exportFormat): ?>
						<?php
							$needsRedirect	= $this->export()->needsRedirect($exportFormat);
							$targetAttr		= $needsRedirect ? 'target=' . $this->escapeHtml($exportFormat) . 'Main' : '';
							$exportLink		= $this->recordLink()->getActionUrl($this->driver, 'Export') . '?style=' . $this->escapeHtml($exportFormat);
						?>
						<li>
							<a <?=$targetAttr?> href="<?=$exportLink?>"><?= $this->transEsc('Export to') ?> <?= $this->escapeHtml($exportFormat) ?></a>
						</li>
					<?php endforeach; ?>
				</ul>
			</li>
		<?php endif; ?>

	</ul>
</div>