<?php
$pagingRequired = isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord']);
if($pagingRequired) {
    $previousUrl	= $this->scrollData['previousRecord'] ? $this->recordLink()->getUrl($this->scrollData['previousRecord']) : false;
    $nextUrl		= $this->scrollData['nextRecord'] ? $this->recordLink()->getUrl($this->scrollData['nextRecord']) : false;
    $currentPosition= $this->scrollData['currentPosition'];
    $totalResults	= $this->scrollData['resultTotal'];
}
?>
<div class="paging">
	<?php if($pagingRequired): ?>
		<?php if($previousUrl): ?>
			<a href="<?=$previousUrl?>" title="<?= $this->transEsc('navigate_back') ?>" class="paging_back"><?= $this->transEsc('navigate_back') ?></a>
		<?php endif; ?>
		<div class="paging_pages">
			<ul>
				<li>
					<span><?=$currentPosition?>/<?=$totalResults?></span>
				</li>
			</ul>
		</div>
		<?php if($nextUrl): ?>
			<a href="<?=$nextUrl?>" title="<?= $this->transEsc('Next') ?>" class="paging_forward"><?= $this->transEsc('Next') ?></a>
		<?php endif; ?>
	<?php endif; ?>
</div>