<div id="sidebar">

	<?php /** MORE LIKE THIS BREAKS AT THE MOMENT  ?>
	  <? foreach ($this->driver->getRelated() as $current): ?>
	    <?=$this->related($current)?>
	  <? endforeach; */?>


	<!-- begin: subnavigation todo -->
	<h3><?=$this->transEsc('Related Subjects')?></h3>
	<div class="subnavigation">
		<ul>
			<li>
				<a href="#" title="Anzeigen">Thema1</a>
			</li>
			<li>
				<a href="#" title="Aussortieren">Thema2</a>
			</li>
			<li>
				<a href="#" title="Im Gesamtbestand suchen">Thema3</a>
			</li>
		</ul>
	</div>
    <h3><?=$this->transEsc('Similar Items')?></h3>
    <div class="subnavigation">
        <ul>
            <li>
                <a href="#" title="hallihallo">hallihallo</a>
            </li>
            <li>
                <a href="#" title="undtsch&uuml;ss">undtsch&uuml;ss</a>
            </li>
        </ul>
    </div>
    <!-- end: subnavigation -->

</div>