<div id="sidebar">

	<?php /** MORE LIKE THIS BREAKS AT THE MOMENT
	  <? foreach ($this->driver->getRelated() as $current): ?>
	    <?=$this->related($current)?>
	  <? endforeach; ?>
	 */ ?>

	<!-- begin: subnavigation -->
	<h3>Ähnliche Dokumente</h3>
	<div class="subnavigation">
		<ul>
			<li>
				<a href="#" title="Anzeigen">Anzeigen</a>
			</li>
			<li>
				<a href="#" title="Aussortieren">Aussortieren</a>
			</li>
			<li>
				<a href="#" title="Im Gesamtbestand suchen">Im Gesamtbestand suchen</a>
			</li>
		</ul>
	</div><!-- end: subnavigation -->

</div>