<?php
/** @var  VuFind\View\Helper\Root\Record $viewRecord  */
$viewRecord	= $this->record($this->driver);
?>
<div class="tabs">
	<h3 class="hidden">Tabnavigation</h3>

	<ul>
		<?php foreach($this->tabs as $tabKey => $tabObject): ?>
			<?php /** @var	\VuFind\RecordTab\TabInterface $tabObject */ ?>
			<li>
				<a href="#tab-<?=strtolower($tabKey)?>"><?=$this->transEsc($tabObject->getDescription())?></a>
			</li>
		<?php endforeach; ?>
	</ul>

	<?php foreach($this->tabs as $tabKey => $tabObject): ?>
		<!-- begin: tab <?=$tabKey?> -->
		<div id="tab-<?=strtolower($tabKey)?>" class="tab">
			<?=$viewRecord->getTab($tabObject)?>
		</div>
		<!-- end: tab <?=$tabKey?> -->
	<?php endforeach; ?>

</div>