<div class="tabs">
	<h3 class="hidden">Tabnavigation</h3>
	<ul>
		<li>
			<a href="#tab-library">Bibliotheken</a>
		</li>
		<li>
			<a href="#tab-review">Rezension</a>
		</li>
		<li>
			<a href="#tab-tags">Tags</a>
		</li>
	</ul>

	<!-- begin: tab library -->
	<div id="tab-library" class="tab">

		<!-- begin: innerbox meine bibliotheken -->
		<div class="innerbox grey">
			<h3 class="toggler persist collapsed" id="library_toggler_meine-bibliotheken"><span class="icon_favorit_library">Meine Bibliotheken</span></h3>
			<div class="library_toggler_meine-bibliotheken">

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Historisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_meine-bibliotheken_historisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_remove">
							<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://aleph.unibas.ch" class="externallink" title="Historisches Seminar">http://aleph.unibas.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_meine-bibliotheken_historisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

			</div>
		</div><!-- end: innerbox meine bibliotheken -->

		<!-- begin: innerbox basel -->
		<div class="innerbox grey">
			<h3 class="toggler persist collapsed" id="library_toggler_ids-basel">IDS Basel / Bern</h3>
			<div class="library_toggler_ids-basel">

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Historisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_historisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_remove">
							<a href="#" title="Bibliothek aus Favoriten entfernen">Bibliothek aus Favoriten entfernen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Historisches Seminar">http://aleph.unibas.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-basel_historisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Altägyptisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_aegyptisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_add">
							<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Altägyptisches Seminar">http://aleph.unibas.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-basel_aegyptisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Slavisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-basel_slavisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_add">
							<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://aleph.unibas.ch" class="externallink" title="Bibliothek Slavisches Seminar">http://aleph.unibas.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-basel_slavisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

			</div>
		</div><!-- end: innerbox basel -->

		<!-- begin: innerbox basel -->
		<div class="innerbox grey">
			<h3 class="toggler persist collapsed" id="library_toggler_ids-zurich">IDS Zürich Universität</h3>
			<div class="library_toggler_ids-zurich">

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Historisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_historisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_add">
							<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Historisches Seminar">http://biblio.unizh.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-zurich_historisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Altägyptisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_aegyptisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_add">
							<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Altägyptisches Seminar">http://biblio.unizh.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-zurich_aegyptisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

				<!-- begin: innerbox -->
				<div class="innerbox">
					<h4>Slavisches Seminar</h4>
					<ul class="actions">
						<li>
							<a href="#" class="linkbutton primary icon_link_primary" title="Zum Bestand"><span>Zum Bestand</span></a>
						</li>
						<li>
							<a href="#" class="linkbutton icon_show toggler collapsed" title="Informationen zum Bestand" id="stock_toggler_ids-zurich_slavisches-seminar"><span>Informationen zum Bestand</span></a>
						</li>
					</ul>
					<ul class="miniactions boxed">
						<li class="miniaction_favorite_add">
							<a href="#" title="Bibliothek zu Favoriten hinzufügen">Bibliothek zu Favoriten hinzufügen</a>
						</li>
						<li class="miniaction_link">
							<a href="http://biblio.unizh.ch" class="externallink" title="Bibliothek Slavisches Seminar">http://biblio.unizh.ch</a>
						</li>
					</ul>

					<div class="stock_toggler_ids-zurich_slavisches-seminar">
						<table>
							<thead>
								<tr>
									<th>Standort</th>
									<th>Signatur</th>
									<th>Exemplarstatus</th>
									<th>Ausleihstatus</th>
									<th>Bechreibung</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>-</td>
									<td>Gd XIII 3836</td>
									<td>ausleihbar</td>
									<td>erhältlich</td>
									<td>Diest ist ein Beschreibungstext.</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div><!-- end: innerbox -->

			</div>
		</div><!-- end: innerbox basel -->

	</div><!-- end: tab library -->

	<!-- begin: tab review -->
	<div id="tab-review" class="tab">

		<h3 class="metatitle"><a name="rezensionen">Rezensionen (3)</a><span class="rating rating_4"></span><span class="meta">Durchschnittliche Bewertung</span></h3>

		<!-- begin: items review -->
		<ul class="items">

			<!-- review -->
			<li>
				<h4><a name="review_03">Marken als Botschafter</a><span class="rating rating_5">Bewertung 5/5</span><span class="meta">Hunter S. / 01.09.2009</span></h4>
				<p>
					Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<p>
					Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.
				</p>
				<!-- edit -->
				<ul class="actions">
					<li>
						<a href="#" class="linkbutton" title="Ihre Rezension löschen"><span>Löschen</span></a>
					</li>
					<li>
						<a href="#" class="linkbutton" title="Ihre Rezension bearbeiten"><span>Bearbeiten</span></a>
					</li>
				</ul>
			</li>

			<!-- review -->
			<li>
				<h4><a name="review_02">Marken verkaufen kein schlechtes Produkt</a><span class="rating rating_2">Bewertung 2/5</span><span class="meta">picasso / 12.08.2009</span></h4>
				<p>
					Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
				</p>
			</li>

			<!-- review -->
			<li>
				<h4><a name="review_01">Markenstrategie als Investition in die Zukunft</a><span class="rating rating_4">Bewertung 4/5</span><span class="meta">pablo / 27.06.2009</span></h4>
				<p>
					Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
				</p>
				<p>
					Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
				</p>
			</li>

		</ul><!-- end: items review -->

		<!-- begin: editor_rezensionen -->
		<form action="#" name="form_rezension" id="form_rezension" class="form">
			<h3 class="toggler persist collapsed" id="editor_toggler_rezension">Rezension verfassen</h3>
			<div class="editor_toggler_rezension">

				<!-- begin: status -->
				<div class="status information">
					<p>
						Verfassen Sie eine Rezension zu diesem Titel und teilen Sie uns und anderen Nutzern Ihre Meinung mit. Ihr Kommentar sollte sich ausschließlich auf diesen Titel beziehen. Für weitere Informationen lesen Sie unseren <a href="#">Leitfaden</a>.
					</p>
				</div><!-- end: status -->

				<fieldset>
					<div class="fieldbox">
						<label for="rezension_rating" class="label">Bewerten sie diesen Titel</label>
						<select id="rezension_rating" name="rezension_rating" class="select">
							<option selected="selected" value="0">Bitte auswählen…</option>
							<option value="1">Schlecht</option>
							<option value="2">Mittelmäßig</option>
							<option value="3">Gut</option>
							<option value="4">Sehr gut</option>
							<option value="5">Ausgezeichnet</option>
						</select>
					</div>
					<div class="fieldbox">
						<label for="rezension_language" class="label">Sprache der Rezension</label>
						<select id="rezension_language" name="rezension_rating" class="select">
							<option selected="selected" value="">Bitte auswählen…</option>
							<option value="en">Englisch</option>
							<option value="de">Deutsch</option>
							<option value="fr">Französisch</option>
							<option value="nl">Niederländisch</option>
						</select>
					</div>
				</fieldset>
				<fieldset>
					<label for="rezension_rezension" class="label">Ihre Rezension</label>
					<textarea id="rezension_rezension" name="rezension_rezension" class="textarea large"></textarea>
				</fieldset>
				<fieldset class="actions">
					<label for="rezension_publish" class="hidden">Rezension speichern und publizieren</label>
					<input id="rezension_publish" name="rezension_publish" type="submit" class="submit primary" value="Rezension veröffentlichen"/>
					<label for="rezension_draft" class="hidden">Rezension als Entwurf speichern</label>
					<input id="rezension_draft" name="rezension_draft" type="submit" class="submit" value="Als Entwurf speichern"/>
					<label for="rezension_reset" class="hidden">Entwurf zurücksetzen</label>
					<input id="rezension_reset" name="rezension_reset" type="reset" class="reset" value="Zurücksetzen"/>
					<a class="linkbutton" id="rezension_reset" href="#">Abbrechen</a>
				</fieldset>
			</div>
		</form>
		<!-- end: editor_rezensionen -->

	</div><!-- end: tab review -->

	<!-- begin: tab tags -->
	<div id="tab-tags" class="tab">

		<h3>Meine Tags (3)</h3>
		<ul class="listing">
			<li class="first">
				<a href="#" title="Picasso">Picasso</a>
			</li>
			<li>
				<a href="#" title="Marke">Marke</a>
			</li>
			<li>
				<a href="#" title="Werte">Werte</a>
			</li>
		</ul>

		<h3>Tags (12)</h3>
		<ul class="listing">
			<li class="first">
				<a href="#" title="Picasso">Picasso</a>
			</li>
			<li>
				<a href="#" title="Marke">Marke</a>
			</li>
			<li>
				<a href="#" title="Werte">Werte</a>
			</li></li>
			<li>
				<a href="#" title="NOSE">NOSE</a>
			</li></li>
			<li>
				<a href="#" title="Design">Design</a>
			</li></li>
			<li>
				<a href="#" title="Brand">Brand</a>
			</li></li>
			<li>
				<a href="#" title="Experience">Experience</a>
			</li></li>
			<li>
				<a href="#" title="Melinda Lini">Melinda Lini</a>
			</li>
			<li>
				<a href="#" title="Photoshop Queen">Photoshop Queen</a>
			</li>
			<li>
				<a href="#" title="Stefan Tan">Stefan Tan</a>
			</li>
			<li>
				<a href="#" title="Prinz Tan">Prinz  Tan</a>
			</li>
			<li>
				<a href="#" title="Gschmois">Gschmois</a>
			</li>
		</ul>

		<!-- begin: editor_tags -->
		<form action="#" name="form_tag" id="form_tag" class="form">
			<h3 class="toggler persist collapsed" id="editor_toggler_tag">Tags hinzufügen</h3>
			<div class="editor_toggler_tag">
				<fieldset>
					<div class="fieldbox">
						<label for="tag_tags" class="label">Tags hinzufügen (kommagetrennt)</label>
						<input id="tag_tags" name="tag_tags" type="text" class="text large"/>
					</div>
				</fieldset>
				<fieldset class="actions">
					<label for="tag_save" class="hidden">Tag speichern</label>
					<input id="tag_save" name="tag_save" type="submit" class="submit primary" value="Tags speichern"/>
				</fieldset>
			</div>
		</form>
		<!-- end: editor_tags -->

	</div><!-- end: tab tags -->

</div>