<?
/**
 * Record detail view
 */

    // Set up standard record scripts
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");

    // Add RDF header link if applicable
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
	$this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

$lastSearchUrl = VuFind\Search\Memory::retrieve();

?>
<!-- begin: col1 (sidebar)  -->
<div id="col1" class="sidebar">
	<div id="col1_content" class="clearfix">
		<!-- begin: sidebar -->
		<?=$this->render('record/sidebar.phtml')?>
		<!-- end: sidebar -->
	</div>
</div>
<!-- end: col1 (sidebar) -->

<!-- begin: col3 (content) -->
<div id="col3" class="content">
	<div id="col3_content" class="clearfix">
		<!-- begin: content -->
		<div id="content">

			<div id="inlay">
				<?=$this->render('global/notepad.phtml')?>
			</div>

			<?=$this->flashmessages()?>

			<input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />

			<!-- title -->
			<h1 class="invisible">Details</h1>

			<div class="tools floatbox">
				<?php if($lastSearchUrl): ?>
					<a href="<?=$this->escapeHtml($lastSearchUrl)?>" title="Zurück zur swissbib Resultatsliste" class="linkbutton icon_backto">
                        <span>swissbib Resultatsliste</span>
                    </a>
				<?php endif; ?>

				<?=$this->render('record/paging.phtml')?>
			</div>

			<!-- begin: box -->
			<div class="box">
				<?=$this->record($this->driver)->getCoreMetadata()?>
			</div>
			<!-- end: box -->

			<?=$this->render('record/tabs.phtml')?>

			<span class="Z3988" title="<?=$this->escapeHtml($this->driver->getOpenURL())?>"></span>

			<div class="tools floatbox">
				<?php if($lastSearchUrl): ?>
					<a href="<?=$this->escapeHtml($lastSearchUrl)?>" title="Zurück zur swissbib Resultatsliste" class="linkbutton icon_backto">
                        <span>swissbib Resultatsliste</span>
                    </a>
				<?php endif; ?>
			</div>

			<!-- begin: pagefunctions -->
			<?=$this->pageFunctions($this->driver)?>
			<!-- end: pagefunctions -->
		</div>
		<!-- end: content -->
	</div>
	<div id="ie_clearing">
		&nbsp;
	</div>
</div>
<!-- end: col3 (content) -->