<h1>About swissbib</h1>
<h2>Search centrally - order locally</h2>
<p>Search centrally in the libraries of all Swiss universities, universities for applied science, federal research
    stations, the Swiss national library, and many more.</p>
<p>swissbib can be used for finding media and informing yourself about the holding libraries. For ordering the book you
    have to switch to the local library.</p>

<h2>What does swissbib contain?</h2>
<p>swissbib lets you search in 19.8 million documents from <a href="../libraries/index.html"><b>823 libraries, media
            centers and archives</b></a> from all parts of the country within one user interface.</p>
<p>This covers books, journals, theses, ebooks, digitized materials, movies (from VHS to Bluray), music (from sheets,
    partitions and LPs to DVDs) audiobooks, photos, learning materials and many more...</p>

<p>These library networks take part in swissbib:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22sbt%22') ?>" target="_blank">Sistema
            bibliotecario ticinese (32 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idsbb%22') ?>" target="_blank">IDS Basel/Bern
            (193 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idslu%22') ?>" target="_blank">IDS Luzern (30
            libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22snl%22') ?>" target="_blank">Schweizerische
            Nationalbibliothek (1 library)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idss*%22') ?>" target="_blank">IDS St. Gallen (36
            libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22nebis%22') ?>" target="_blank">NEBIS (172
            libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22rero%22') ?>" target="_blank">RERO Westschweizer
            Bibliotheksverbund (236 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22sgbn%22') ?>" target="_blank">St. Galler
            Bibliotheksnetz (52 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22bgr%22') ?>" target="_blank">Bibliotheksverbund
            Graubünden (26 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22abn%22') ?>" target="_blank">Aargauer
            Bibliotheksnetz (25 libraries)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22alex%22') ?>" target="_blank">Alexandria library
            network (20 libraries)</a></li>
</ul>

<p>2013 more networks are included:</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek (25 libraries)</li>
</ul>

<p>Additionally swissbib includes these repositories:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ccsa%22') ?>" target="_blank">Catalogue collectif
            suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22charch02%22') ?>" target="_blank">Digitized
            materials of the Swiss Literary Archives</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22charch01%22') ?>" target="_blank">Digitized
            materials of the Federal Archives of historic monuments</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22retros%22') ?>"
           target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22zora%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>2013 these repositories are added:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>serval</li>
</ul>

<h2>How up to date is swissbib?</h2>
<p>swissbib updates daily.</p>

<h2>Your opinion matters</h2>
<p>swissbib is continually developed. To make swissbib more perfect we depend on your tips and opinion. On each page is
    a feedback button that leads you to an external service - please use it!</p>


<h2>What to come in 2013?</h2>
<p>We work on the following functionality during 2013:</p>

<ul class="list">
    <li>ordering directly out of swissbib</li>
    <li>a centralized user account for Swiss libraries</li>
    <li>data quality and search efficiency</li>
</ul>

<h2>project swissbib</h2>
<p>swissbib is a cooperative project of the Swiss university libraries, the Swiss national library under the lead of the
    Universitätsbibliothek Basel and is a part of the infrastructure project &raquo;e-lib.ch - Swiss electronic library&laquo;.
    From 2008 to 2013 it is funded by SUC - Swiss University Conference.</p>