<h2>swissbib changes the search interface and updates its data</h2>
<h3>Which current services stop working as expected?</h3>
<p>The update is very extensive and leads to three profound changes that affect your personal data in swissbib:
</p>
<ol class="list">
    <li>The user preferences do not survive the update. Private users have to sign in anew.
    </li>
    <li>The personal lists as part of the old user account are deleted.</li>
    <li>The short-links to the old swissbib are no longer valid.</li>
</ol>
<h3>What changes?</h3>
<p>On the whole there are only small changes. If you look closer there are many notable details:
</p>
<ul class="list">
    <li>The filter on local networks is moved from the start page to the facets of the result page.</li>
    <li>The &raquo;extended search&laquo; is completely revamped.</li>
    <li>New sign-in-mechanism for private individuals <a href="<?= $this->url('myresearch-home'); ?>"
                                                         title="<?= $this->transEsc('Your Account') ?>"><img alt="Info"
                                                                                                 src="/themes/swissbib/images/icon_info.gif"></a>
    </li>
    <li>result list
        <ul>
            <li>New facets to filter by year</li>
            <li>Improvements for export and printing</li>
        </ul>
    </li>
    <li>hit page
        <ul>
            <li>Tweaked library display</li>
            <li>Better display of multivolume works <a
                    href="/Record/295089423/HierarchyTree?hierarchy=295089423"><img alt="Info"
                                                                                    src="/themes/swissbib/images/icon_info.gif"></a>
            </li>
            <li>Improvements for export and printing</li>
            <li>More information on the single record if present in the data</li>
        </ul>
    </li>
</ul>
