<h2>Login</h2>
<div class="floatbox">
    <img class="small right"
         src="<?= $this->basePath('themes/swissbibsingle/images/Help/de/myswissbib/switch_Anmelden.png') ?>">

    <p>swissbib is a <strong>supra-regional service</strong> and therefore provides a library-independent login.</p>

    <p>There are two possibilities:</p>
    <ul class="list">
        <li><strong>switchAAI</strong> for students and staff of universities, polytechnics and other institutions. <a
                href="http://www.switch.ch/aai/participants/homeorgs.html" target="_blank">switch</a> provides more
            information.
        </li>
        <li>A login for <strong>private individuals</strong> caters all those users that cannot use switchAAI. It is
            provided by switch as well.
        </li>
    </ul>
</div>

<h3>Why log in?</h3>
<p>The login allows you to use swissbib more efficiently.</p>
<ul class="list">
    <li>You can reuse all your saved searches</li>
    <li>You only have to define favorite libraries once and use them afterwards in different search sessions.</li>
    <li>You save list and keep them as long as you need them.</li>
    <li>You're allowed to configure the search interface</li>
    <!--<li>You can save library logins for loan functionalities</li>-->
</ul>
<p>If you choose <strong>not</strong> to login, you use all preferences the moment you close your browser.</p>

<h3>Forgot your password?</h3>
<ul class="list">
    <li>If you use <strong>switchAAI</strong> contact the appropriate services of your home organization.</li>
    <li>If you logged in as <strong>private individuals</strong> use the switch service to reset your password.</li>
</ul>

<h3>Why log out?</h3>
<p>If you use swissbib on a public computer you always have to log out <strong> and close the browser
        completely</strong>. Otherwise it is possible that someone else reuses your credentials!</p>

<!--<h3>Ausleihfunktionen</h3>
<h4>Konto IDS Basel Bern</h4>
<div class="floatbox">
    <img class="small right"
         src="<?= $this->basePath('themes/swissbibsingle/images/Help/de/myswissbib/Anmelden_IDS-BaselBern.png') ?>">

    <p>Online ausleihbare Bestände des IDS Basel/Bern können direkt in swissbib bestellt oder vorgemerkt werden.
        Voraussetzung ist, dass der für die Bestellung benötigte Nutzername und das Passwort im swissbib-Account
        hinterlegt werden.</p>

    <p>Dies geschieht nach der ersten Anmeldung mit switchAAI oder dem switch Gastzugang im <strong>Konto IDS
            Basel/Bern</strong>.</p>

    <p>Die Benutzerdaten werden im swissbib-Account verschlüsselt gespeichert und sicher an das Bibliothekssystem
        übertragen. Schliessen Sie an öffentlichen Stationen nach der Abmeldung immer den Browser, damit niemand
        versehentlich mit Ihren Daten bestellt.</p>
</div> -->