<h2 style="padding-top:30px;">search box to include swissbib on your web page</h2>
<p>With this box you can include a direct search in swissbib in your web page. The search is configurable - more hints
    are directly in the code. Most likely are filters on materials, libraries or networks.</p>
<p>Here you can load the code <a href="http://www.swissbib.org/doc/swissbib-box/swissbib-box.html">for the search
        box</a> directly.<p>
<h3>For example a filter on map material</h3>
<!-- Start: swissbib search box with format filter-->
<!-- change background color -->
<div style="background: #32CD0F  bottom no-repeat; width: 430px; height:80px;">
    <script type="text/javascript">
        function search_swissbib() {
            var basic_url = "https://test.swissbib.ch/Search/Results";
            <!-- change swissbib language and swissbib appearance -->
            var first_fix_part = "?lng=de&sort=relevance&lookfor=";
            var search_value = encodeURIComponent(document.getElementById('INPUT_SWISSBIB_SEARCH').value);
            <!-- change the media filter argument by replacing MP01* -->
            <!-- change the media filter to a library-filter by replacing "format" by "institution" and then apply the swissbib library code -->
            var filter_restriction = "";
            if (document.getElementById("filterMaps").checked) {
                filter_restriction = '&filter[]=format%3A%22MP01*%22';
            }
            var query_parameter = first_fix_part + search_value + filter_restriction;
            var search_all_url = basic_url + query_parameter;
            window.open(search_all_url);
            return false;
        }
    </script>
    <!-- change background color of the icon -->
    <div
        style="margin:5px 0 0 15px; background: #32CD0F  url(https://test.swissbib.ch/themes/swissbib/images/logo_swissbib.png) no-repeat; height: 55px; padding-left:130px;">
        <form style="padding:10px 0 0 40px; " onsubmit="return search_swissbib();">
            <fieldset style="margin: 0; padding: 0; border: none;">
                <input style="display:block;float:left;width:230px;" name="SEARCH_ALL" id="INPUT_SWISSBIB_SEARCH"
                       type="text"/>
                <input style="height:25px; width:80px;  margin-top:5px; display:block;float:left;" type="submit"
                       value="Suchen"/>

                <!--if you don't want the checkbox checked leave the option "checked" empty -->
                <input id="filterMaps" style="margin:5px 0 0 10px; padding-left:10px; display:block; float:left;"
                       type="checkbox" value="Search" checked="checked"/>
                <!-- change color of filter label and label text-->
                <label
                    style="margin-top:5px; color:#2F333C;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.1538em;margin:0 10px 0 0;"
                    for=filtermaps>&nbsp;nur Kartenmaterial</label>
            </fieldset>
        </form>
    </div>
</div>
<!-- End: swissbib search box-->

<p style="padding-top:30px;">You can change some elements in order</p>
<ul class="list">
    <li>to change the color of the interface:
        <ul>
            <li>Replace "#32CD0F" through "#8D919D"</li>
        </ul>
    </li>
    <li>to adapt the search mode:
        <ul>
            <li>change the filter from &raquo;format&laquo; to &raquo;library&laquo;. In order to do this adapt
                "filter_restriction" from &raquo;format&laquo; to &raquo;institution&laquo; </li>
            <li>The values for &raquo;format&laquo; as well as &raquo;library&laquo; are coded. The main categories
                for &raquo;format&laquo; are listed in the <a
                    href="http://www.swissbib.org/wiki/index.php?title=Filtering">swissbib wiki</a> and the codes of
                the &raquo;libraries&laquo; in <a href="../Libraries"
                                                  target="_blank">https://www.swissbib.ch/Libraries</a>.
            </li>
        </ul>
    </li>
</ul>