<h2>Project swissbib</h2>
<p>swissbib is a cooperation between the Swiss university libraries and the Swiss national library under the lead of the
    Universitätsbibliothek Basel under the auspices of &raquo;e-lib.ch - Swiss electronic library&laquo;.</p>

<p>swissbib is financed by from 2008 to 2013 by SUC - Swiss University Conference.</p>

<h2>What does cooperation mean in swissbib?</h2>
<p>The following libraries and networks contributed significantly to swissbib in different areas. Without them swissbib
    would not have been realized:</p>

<h3>Data delivery</h3>
<ul class="list">
    <li>All local networks of IDS - Informationsverbund Deutschschweiz</li>
    <li>Swiss national library</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>sbt - Sistema bibliotecario ticinese and the majority of the IDS partners</li>
    <li>Alexandria library network</li>
</ul>

<h3>Testing of functionality</h3>
<p>The functionality testing was organized and led by a team of the UB Basel. The following networks and libraries
    participated:</p>
<ul class="list">
    <li>Information librarians and catalogers of IDS Luzern, IDS St. Gallen, IDS Basel/Bern, IDS Zürich Universität and
        IDS Zürich Zentralbibliothek
    </li>
    <li>Information librarians and catalogers of the Swiss national library</li>
    <li>Members of COPAC and catalogers from RERO centrale</li>
    <li>Biblioteca Universitaria di Lugano</li>
</ul>

<h3>Usability Testing</h3>
<p>The usability of the interface was evaluated by two focus groups as well as by experts. This was done by two e-lib.ch
    projects <a href="http://www.e-lib.ch/accept.html" target="_blank">ACCEPT</a> and <a
        href="http://www.e-lib.ch/eval.html" target="_blank">ElibEval</a>.</p>

<h3>Translation</h3>
<p>The French and Italian version of the interface was adapted to Swiss standards.</p>
<ul class="list">
    <li>French interface: members of RERO COPAC</li>
    <li>French texts: UB Basel</li>
    <li>Italian interface and texts: Biblioteca Universitaria Lugano</li>
</ul>

<h2>Design and concept of the web site</h2>
<p>The design and concept of the web site was developed by <a href="http://www.nose.ch" target="_blank">Nose Design
        AG</a>.</p>

<p>The swissbib software solution consists of three components:
<ul class="list">
    <li>data preparation: <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS - Metadata management
            solution</a> of OCLC.
    </li>
    <li>search engine: <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr/Lucene</a> (Open Source)
    </li>
    <li>user interface: <a href="http://www.vufind.org" target="_blank">vufind</a> (Open Source)</li>
    <li>single components of the whole solution: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>
</ul>
</p>