<h1>About swissbib</h1>
<h2>Search centrally - order locally</h2>
<p>Search centrally in the libraries of all Swiss universities, universities for applied science, federal research
    stations, the Swiss national library, and many more.</p>
<p>swissbib can be used for finding media and informing yourself about the holding libraries. For ordering the book you
    have to switch to the local library.</p>

<h2>What does swissbib contain?</h2>
<p>swissbib lets you search in 20 million documents of <a href="../Libraries"><b>900 libraries, media
            centers and archives</b></a> from all parts of the country within one user interface.</p>
<p>This covers books, journals, theses, ebooks, digitized materials, movies (from VHS to Bluray), music (from sheets,
    partitions and LPs to DVDs) audiobooks, photos, learning materials and many more...</p>

<p>These library networks take part in swissbib:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SBT%22') ?>" target="_blank">Sistema
            bibliotecario ticinese</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSBB%22') ?>" target="_blank">IDS Basel/Bern</a>
    </li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSLU%22') ?>" target="_blank">IDS Luzern</a>
    </li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SNL%22') ?>" target="_blank">Schweizerische
            Nationalbibliothek</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSS*%22') ?>" target="_blank">IDS St. Gallen</a>
    </li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22NEBIS%22') ?>" target="_blank">NEBIS</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RERO%22') ?>" target="_blank">RERO Westschweizer
            Bibliotheksverbund</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SGBN%22') ?>" target="_blank">St. Galler
            Bibliotheksnetz</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22BGR%22') ?>" target="_blank">Bibliotheksverbund
            Graubünden</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ABN%22') ?>" target="_blank">Aargauer
            Bibliotheksnetz</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ALEX%22') ?>" target="_blank">Alexandria library
            network</a></li>
</ul>

<p>2014 more networks are included:</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek</li>
</ul>

<p>Additionally swissbib includes these repositories:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CCSA%22') ?>" target="_blank">Catalogue collectif
            suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH02%22') ?>" target="_blank">Digitized
            materials of the Swiss Literary Archives</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH01%22') ?>" target="_blank">Digitized
            materials of the Federal Archives of historic monuments</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RETROS%22') ?>"
           target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ZORA%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>2014 these repositories are added:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>serval</li>
</ul>

<h2>How up to date is swissbib?</h2>
<p>swissbib updates daily.</p>

<h2>Your opinion matters</h2>
<p>swissbib is continually developed. To make swissbib more perfect we depend on your tips and opinion. On each page is
    a feedback button that leads you to an external service - please use it!</p>


<h2>What to come in 2014?</h2>
<p>We work on the following functionality during 2014:</p>

<ul class="list">
    <li>ordering directly out of swissbib - currently tested internally</li>
    <li>a centralized user account for Swiss libraries - currently tested internally</li>
    <li>data quality and search efficiency</li>
</ul>

<h2>project swissbib</h2>
<p>swissbib is a cooperative project of the Swiss university libraries, the Swiss national library under the lead of the
    Universitätsbibliothek Basel. Between 2008 and 2013 it was a part of the infrastructure project &raquo;e-lib.ch -
    Swiss electronic library&laquo;, which ended 2013.
    Since 2014 it is now part of CRUS Program 2. From 2008 to 2014 it is funded by SUC - Swiss University
    Conference.</p>