<div id="col3" class="content">
<?/* In der View zur Verfügung stehende Werte: vollständige Inhalte aus data/cache/libadmin_all.json
unvollständige Beispiele, für Vollständigkeit siehe in der Datei:
$group = array(
    'id'   => 13,
    'code' => 'RegioBS',
    'label' => array(
        'de' => 'Region Basel',
        'fr' => 'Région Bâle',
        'it' => 'Regione di Basilea',
        'en' => 'Region Basel'
    ),
);
$institution = array(
    'id' => 2471,
    'code'     => 'A253',
    'sys_code' => 'A253',
    'position' => '2',
    'favorite' => true,
    'address' => array(
        'address' => 'Petersgraben 11',
        'zip'     => '4051',
        'city'    => 'Basel',
    ),
    'label' => array(
        'de' => 'Archäologische Bodenforschung Basel-Stadt',
        'fr' => 'Archäologische Bodenforschung Basel-Stadt',
        'it' => 'Archäologische Bodenforschung Basel-Stadt',
        'en' => 'Archäologische Bodenforschung Basel-Stadt'
        ),
    'url' => array(
        'de'=> 'http://aleph.unibas.ch/F/?func=library&sub_library=A253',
        'fr'=> 'http://aleph.unibas.ch/F/?func=library&sub_library=A253',
        'it'=> 'http://aleph.unibas.ch/F/?func=library&sub_library=A253',
        'en'=> 'http://aleph.unibas.ch/F/?func=library&sub_library=A253'
    ),
)
*/?>
    <div id="col3_content" class="clearfix">
        <div id="content" class="libraries">

            <?= $this->render('global/logo') ?>

            <div class="navigation">
                <ul>
                    <? $arrayLength = count($this->groupedInstitutions);
                    for ($i = 0; $i < $arrayLength; $i++): ?>
                        <li class="color">
                            <a href="#nav_<?= $i ?>" class="color"><?= $this->groupedInstitutions[$i]['group']['label'][$this->layout()->userLang] ?></a>
                            <span><? if($i!==$arrayLength-1) echo '&Iota;&nbsp;'; ?></span>
                        </li>
                    <? endfor; ?>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="all_groups">
                <? $i = 0; ?>
                <? foreach ($this->groupedInstitutions as $institutionGroup): ?>
                    <?=
                    $this->render(
                        'libraries/group',
                        array(
                             'group'        => $institutionGroup['group'],
                             'institutions' => $institutionGroup['institutions'],
                             'nr'           => $i++
                        )
                    ) ?>
                <? endforeach; ?>
            </div>

        </div>
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>