<div id="nav_<?= $nr ?>" class="group">
    <h2><?= $group['label'][$this->layout()->userLang] ?></h2>
    <div class="institutions">
        <? foreach($institutions as $institution): ?>
            <?= $this->render(
                'libraries/institution',
                array(
                     'institution' => $institution
                )
            ) ?>
        <? endforeach; ?>
    </div>
</div>