<div class="institution">
    <h4><?= $institution['label'][$this->layout()->userLang] ?></h4>
    <div>
        <? if(!empty($institution['address'])): ?>
            <p><?= $institution['address'] ?></p>
        <? endif; ?>
        <? if(!empty($institution['city']) && !empty($institution['zip'])): ?>
            <p><?= $institution['city'] ?> <?= $institution['zip'] ?></p>
        <? endif; ?>
        <? if(!empty($institution['website'])): ?>
            <p><a href="<?= $institution['website']?>" class="color" target="_blank"><?=$this->transEsc('libraries.website')?></a></p>
        <? endif; ?>
    </div>
</div>