<?= $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?= $this->layout()->userLang ?>" xml:lang="en">
<head>
    <?= $this->partial('global/head.phtml') ?>
    <?= $this->headLink()->appendStylesheet('libraries/styles.css') ?>
</head>
<body>
<div class="page_margins">
    <div class="page">
        <div id="main">
            <?= $this->render('libraries/content') ?>
        </div>
    </div>
</div>
</body>
</html>
