<?php

/** @var $results VuFind\Search\Solr\Results */
$results    = $this->results;
$facetList	= $results->getFacetList();

/** @var $options VuFind\Search\Solr\Options  */
$options	= $this->searchOptions($this->searchClassId);
$basicSearch= $options->getSearchAction();

    // Facet results settings: settings for items limit per facet
$facetResultsSettings   = $this->facetsConfig->get('Results_Settings');
$facetItemsMaxAmount	= $facetResultsSettings->get('facet_limit');               // full
$facetItemsLimitDefault = $facetResultsSettings->get('facet_limit_default');    // initially shown

?>

<h3><?=$this->transEsc('Narrow Search')?></h3>

<div class="facets">
	<?php foreach($facetList as $facetGroup => $facetGroupData): /* Iterate over facet groups (topic, author, language, ... */ ?>
		<?php
			$facetId		= strtolower($facetGroup);
			$facetGroupLabel= $facetGroupData['label'];
			$facetGroupItems= $this->SortAndPrepareFacetList($results, $facetGroup, $facetGroupData['list'], $basicSearch);
		?>
		<!-- facet start: <?=$facetGroup?> -->
		<div class="facet" id="facet_<?=$facetId?>">
			<h5 class="toggler persist expanded" id="facet_toggler_<?=$facetId?>"><?=$this->escapeHtml($facetGroupLabel)?></h5>
			<ul class="facet_toggler_<?=$facetId?>">

<?php
        // Get limit of initially shown items per facet
    $amountItems        = count($facetGroupItems);
    $amountItemsShown   = intval($facetResultsSettings->get('facet_limit_' . $facetGroup));
    if( $amountItemsShown === 0 ) {
        $amountItemsShown = $facetItemsLimitDefault;
    }
    $itemsCount = 0;
?>		    <?php foreach($facetGroupItems as $facet): ?>
                <?php if($itemsCount >= $amountItemsShown) break; /* Limit initially shown items per facet*/ ?>
                <?php $itemsCount++; ?>
                <?= $this->facetItem($facet, $facetGroup) ?>
            <?php endforeach; ?>
            <? if($amountItems > $amountItemsShown): /* Show "more facets" link if there are more */ ?>
                <?php $amountMore = $amountItems - $amountItemsShown ?>
                    <li id="more<?=$facetId?>" class="facet_more">
                        <a href="#" onclick="moreFacets('<?=$facetId?>'); return false" title="<?=$this->transEsc('more_info_toggle')?>"><?=$this->transEsc('more_info_toggle')?> (<?= $amountMore ?>)</a>
                    </li>
            <div id="narrowGroupHidden_<?=$facetId?>" class="offscreen">
                <?php while($itemsCount < $amountItems) {
                    $facet  = $facetGroupItems[$itemsCount];
                ?>
                    <?= $this->facetItem($facet, $facetGroup) ?>
                    <?php $itemsCount++; ?>
                <?php } ?>
                <li id="less<?=$facetId?>" class="facet_more">
                    <a href="#" onclick="lessFacets('<?=$facetId?>'); return false" title="<?=$this->transEsc('more_info_toggle')?>"><?=$this->transEsc('more_info_toggle')?> (<?= $amountMore ?>)</a>
                </li>
            </div>
            <? endif; ?>
            </ul>
		</div>
		<!-- facet -->
	<?php endforeach; ?>


	<!-- Slider widget: Range of publication date  -->
	<?php
		$this->headScript()->appendFile('pubdate_slider.js');
		$title = 'Erscheinungsjahr';
	?>
	<div id="facet_pubdate_slider" class="facet">
		<h5 id="facet_toggler_publishdate" class="toggler persist expanded" title="adv_search_year">Erscheinungsjahr</h5>

		<form action="" name="<?=$this->escapeHtml($title)?>Filter" id="<?=$this->escapeHtml($title)?>Filter">
			<?=$results->getUrlQuery()->asHiddenFields(array('filter' => "/^{$title}:.*/"))?>
			<input type="hidden" name="daterange[]" value="<?=$this->escapeHtml($title)?>"/>

			<fieldset class="publishDateLimit facet_toggler_publishdate" id="publishDateSlider">
				<div class="values">
					<div>
						<label for="<?=$this->escapeHtml($title)?>from"><?=$this->transEsc('date_from')?>:</label>
						<input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtml($title)?>from" id="<?=$this->escapeHtml($title)?>from" value="<?=isset($dateFacets[$title][0])?$this->escapeHtml($dateFacets[$title][0]):''?>" />
					</div>
					<div>
						<label for="<?=$this->escapeHtml($title)?>to"><?=$this->transEsc('date_to')?>:</label>
						<input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtml($title)?>to" id="<?=$this->escapeHtml($title)?>to" value="<?=isset($dateFacets[$title][1])?$this->escapeHtml($dateFacets[$title][1]):''?>" />
					</div>
				</div>

				<div id="<?=$this->escapeHtml($title)?>Slider" class="dateSlider"></div>

				<input type="submit" value="<?=$this->transEsc('Set')?>" id="<?=$this->escapeHtml($title)?>goButton"/>
			</fieldset>
		</form>
	</div>

</div>