<?php
/** @var $results VuFind\Search\Solr\Results */
$results    = $this->results;
$facetList	= $results->getFacetList();

/** @var $options VuFind\Search\Solr\Options  */
$options	= $this->searchOptions($this->searchClassId);
$basicSearch= $options->getSearchAction();

    // Facet results settings: settings for items limit per facet
$configReader           = new \VuFind\Config\Reader();
$facetResultsSettings   = $configReader->getConfig('facets')->get('Results_Settings');
$facetItemsMaxAmount = $facetResultsSettings->get('facet_limit');               // full
$facetItemsLimitDefault = $facetResultsSettings->get('facet_limit_default');    // initially shown
?>

<h3>Treffer eingrenzen</h3>

<div class="facets">
	<?php foreach($facetList as $facetGroup => $facetGroupData): ?>
		<?php
			$facetId		= strtolower($facetGroup);
			$facetGroupLabel= $facetGroupData['label'];
			$facetGroupItems= $this->SortAndPrepareFacetList($results, $facetGroup, $facetGroupData['list'], $basicSearch);
		?>
		<!-- facet start: <?=$facetGroup?> -->
		<div class="facet" id="facet_<?=$facetId?>">
			<h5 class="toggler persist expanded" id="facet_toggler_<?=$facetId?>"><?=$this->escapeHtml($facetGroupLabel)?></h5>
			<ul class="facet_toggler_<?=$facetId?>">

<?php
        // Get limit of initially shown items per facet
    $amountItems        = count($facetGroupItems);
    $amountItemsShown   = intval($facetResultsSettings->get('facet_limit_' . $facetGroup));
    if( $amountItemsShown === 0 ) {
        $amountItemsShown = $facetItemsLimitDefault;
    }
    $itemsCount = 0;
?>		    <?php foreach($facetGroupItems as $facet): ?>
                <?php if($itemsCount >= $amountItemsShown) break; /* Limit initially shown items per facet*/ ?>
                <?php $itemsCount++; ?>
                <?= $this->facetItem($facet) ?>
            <?php endforeach; ?>
            <? if($amountItems > $amountItemsShown): /* Show "more facets" link if there are more */ ?>
                <?php $amountMore = $amountItems - $amountItemsShown ?>
                    <li id="more<?=$facetId?>" class="facet_more">
                        <a href="#" onclick="moreFacets('<?=$facetId?>'); return false" title="Mehr anzeigen">Mehr anzeigen (<?= $amountMore ?>)</a>
                    </li>
            <div id="narrowGroupHidden_<?=$facetId?>" class="offscreen">
                <?php while($itemsCount < $amountItems) {
                    $facet  = $facetGroupItems[$itemsCount];
                ?>
                    <?= $this->facetItem($facet) ?>
                    <?php $itemsCount++; ?>
                <?php } ?>
                <li id="less<?=$facetId?>" class="facet_more">
                    <a href="#" onclick="lessFacets('<?=$facetId?>'); return false" title="Weniger anzeigen">Weniger anzeigen (<?= $amountMore ?>)</a>
                </li>
            </div>
            <? endif; ?>
            </ul>
		</div>
		<!-- facet -->
	<?php endforeach; ?>
</div>