<h3>Ihre Suche</h3>
<div class="filters">
	<p>
		Freie Suche:
		<br/>
		<cite>Marke</cite>
	</p>
	<h4 class="filters_indicator"><span>Suchfilter B&uuml;cher</span></h4>
	<!-- filter -->
	<div class="filter" id="filter_autor">
		<h5>Autor</h5>
		<ul>
			<li>
				<a href="#" title="Filter entfernen: Armin Bregy" class="filter_remove">Armin Bregy</a>
			</li>
			<li>
				<a href="#" title="Filter entfernen: David Riedrich-Karl" class="filter_remove">David Riedrich-Karl</a>
			</li>
		</ul>
	</div>
	<!-- filter -->
	<div class="filter" id="filter_language">
		<h5>Sprache</h5>
		<ul>
			<li>
				<a href="#" title="Filter entfernen: Englisch" class="filter_remove">Englisch</a>
			</li>
		</ul>
	</div>

</div>