<h1>About swissbib</h1>

<h2>Contact</h2>
<p>Write a comment in our <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>, an email to
    <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> or contact
    <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>
<p>For questions about your account please contact <a href="http://www.swissbib.ch/libraries/placelist.html"
                                                      target="_blank">your library</a>.</p>
<p>For questions about a certain work please contact the <a href="http://www.swissbib.ch/libraries/placelist.html"
                                                            target="_blank">owning library</a> directly. Link from the
    catalog: click on the <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>"
                               alt="Library Info"> next to the call number.</p>


<h2>News</h2>
<p>Follow our <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a> or <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>

<h1>Data</h1>
<p>swissbib Basel Bern consists of two separate catalogs:</p>

<h2>Books &amp; more</h2>
<p><strong>Region Basel</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, libraries in Basel
        and Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Universitäts- und Verbundbibliotheken</a></li>
</ul>
<p><strong>Region Bern</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Schweizerische
            Nationalbank</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Schweizerische Nationalbibliothek</a></li>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Universitäts- und Verbundbibliotheken</a></li>
   </ul>


<p><strong>retro.seals</strong></p>
<ul class="list">
    <li>Within the framework of the project <a href="http://retro.seals.ch" target="_blank">retro.seals.ch</a>,
        scientific journals are retrodigitized and made available via internet.
    </li>
</ul>

<h2>Articles &amp; more</h2>
<ul class="list">
    <li>Content of e-journals, e-books and databases licenced by the university libraries of Basel and/or Bern. In most cases you have access to the full text if you're on campus of the university or logged in via VPN.</li>
    <li>Free online ressources.</li>
    <li>If the full text isn't avaliable online you can order a copy using the <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>link to library services</i></li>
    <li>For more information see <a href="http://www.serialssolutions.com/en/services/summon/content-and-coverage" target="_blank">SerialsSolutions</a>.</li>
  </ul>
