<h1>About swissbib</h1>

<h3>Contact</h3>
<ul class="list">
    <li>For questions about your account please contact <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">your library</a>.</li>
    <li>For questions about a certain work please contact the <a href="<?= $this->url('libraries-index') ?>">owning library</a> directly.</li>
    <li>To contact swissbib Basel Bern write to <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> or post a comment in our <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.</li>
</ul>

<h3>News</h3>
<p>Follow our <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a></p>

<h1>Data</h1>
<p>swissbib Basel Bern consists of two separate catalogs:</p>

<h3>Books &amp; more</h3>
<ul class="list">
<li>The scientific libraries in <a href="<?= $this->url('libraries-index') ?>#nav_0">Basel</a> and <a href="<?= $this->url('libraries-index') ?>#nav_1">Bern</a></li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: retrodigitized scientific journals
</li>  
</ul>    

<!--
<p><strong>Region Basel</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, libraries in Basel
        and Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Universitäts- und Verbundbibliotheken</a></li>
</ul>
<p><strong>Region Bern</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Schweizerische
            Nationalbank</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Schweizerische Nationalbibliothek</a></li>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Universitäts- und Verbundbibliotheken</a></li>
   </ul>
-->

<h3>Articles &amp; more</h3>
<ul class="list">
    <li>Content of e-journals, e-books and databases licenced by the university libraries of Basel and/or Bern. In most cases you have access to the full text if you're on campus of the university or logged in via VPN.</li>
    <li>Free online ressources.</li>
    <li>If the full text isn't avaliable online you can order a copy using the <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>link to library services</i></li>
    <li>For more information see <a href="http://www.serialssolutions.com/en/services/summon/content-and-coverage" target="_blank">SerialsSolutions</a>.</li>
</ul>
