<h1>Advanced search</h1>
<h2>Books &amp; more</h2>
<h3>With all search groups</h3>
<div class="floatbox">
    <a href="/themes/swissbibmulti/images/HelpPage/de/advanced1.png" class="help">
        <img class="image magnify" src="/themes/swissbibmulti/images/HelpPage/de/advanced1_small.png"
             alt="Screenshot"/>
    </a>

    <p>
        Migration*/Migrant*/migrazion*<br/><strong>and</strong><br/>Gesundheit*/health/santé/salute<br/><strong>and</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*
    </p>
</div>

<h3>Without the third search group</h3>
<div class="floatbox">
    <a href="/themes/swissbibmulti/images/HelpPage/de/advanced2.png" class="help">
        <img class="image magnify" src="/themes/swissbibmulti/images/HelpPage/de/advanced2_small.png"
             alt="Screenshot"/>
    </a>

    <p>Migration*/Migrant*/migrazion*<br/><strong>and</strong><br/>Gesundheit*/health/santé/salute<br/><strong>but not</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*</p>
</div>

<h3>Refine search: Language, Format, Library, Year of publication</h3>
<p>Instead of scrolling in the drop-down lists click somewhere in the list and write the word you want to scroll to, e.g.<i>English</i> in <i>Languages</i>.</p>

<h3>Repeat search</h3>
<p>Either use <i>Edit this Advanced Search</i> above the list of results or <i>My swissbib - Saved searches</i>.</p>

<h3>Save search</h3>
<p><i>My swissbib - Saved searches</i>.</p>

<h2>Articles &amp; more</h2>
<p>As <i>Books &amp; mehr</i>, but some of the fields/facets are different, as <i>Articles &amp; more</i> is a separate catalog.</p>
       
