<h1>FAQ</h1>
<h2>Search, Advanced search</h2>
<ul class="list">
    <li>
       <li><strong>Can I search within a certain library?</strong>
         <br/>Either mark the library as favorite and filter your search results with <i>Refine search - Favorites</i> or use <i>Advanced search - Refine search - Library</i>.</li>   
         <li><strong>What is Sort by Relevance?</strong>
        <br/>Hits in main title, author name and subjects rank higher than hits in other fields.</li>
 </ul>

<h2>Order</h2>
<ul class="list">
        <li><strong>Could you send me the following book: ...?</strong>
            <br/>Choose the library you'd like to order from. Click on <i>Order</i>. If getting the book sent to your home address is possible you see it as one of the options under <i>Pickup/delivery location</i>. 
                   </li>
       </ul>

   <h2>My swissbib</h2>
<ul class="list">
        <li><strong>Is there a shortcut to see what I have checked out?</strong>
            <br/><i>Log in</i>, then click on <i>Account: Your name</i>.<br> 
                   </li>
       </ul>       
       
<div class="example">Is your question not covered? Ask us in the <a
        href="http://swissbib-baselbern.blogspot.com" target="_blank">blog</a>, by <a href="mailto:swissbib-baselbern@unibas.ch">email</a> or <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.
</div>