<h1>FAQ</h1>
<h2>Search, Advanced search</h2>
<ul class="list">
    <li>
        <strong>Can I search within a certain library?</strong>
        <br/>Either mark the library as favorite and filter your search results with <i>Refine search - Favorites</i> or use <i>Advanced search - Refine search - Library</i>.
    </li>
    <li>
        <strong>Why can't I always see the full text of e-books, articles, etc.?</strong>
        <br/>Access to full text is often only possible from the university having licenced the content. Log in via VPN if you're not on campus.
    </li>
</ul>

<h2>Order</h2>
<ul class="list">
    <li>
        <strong>Could you send me a certain book?</strong>
        <br/>Choose the library you'd like to order from. Click on <i>Order</i>. If getting the book sent to your home address is possible you see it as one of the options under <i>Pickup/delivery location</i>.
   </li>
</ul>

<h2>My swissbib</h2>
<ul class="list">
    <li>
        <strong>Which is the fastest way to see what I have checked out?</strong>
        <br/><i>Log in</i>, then click on <i>Account: Your name</i>
    </li>
</ul>
       
<h2>Is your question not covered?</h2>
<ul class="list">
    <li>
        For questions about your account please contact <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">your library</a>.
    </li>
    <li>
        For questions about a certain work please contact the <a href="<?= $this->url('libraries-index') ?>">owning library</a> directly.
        <br/>Link from the catalog: click on the Icon <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Library Info"> under location.
    </li>
    <li>
        To contact swissbib Basel Bern write to <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> or post a comment in our <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.
    </li>
</ul>
