<h1>Log in, My swissbib</h1>
<h2>Log in</h2>

<p>Use your <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis" target="_blank">IDS account</a> for logging in.</p>

<h3>Why log in?</h3>
<p>To use loan, favorite libraries, lists, saved searches and saved preferences.</p>

<h3>Forgot your password?</h3>
<p>Please contact <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">your library</a>.</p>


<h3>Why log out?</h3>
<p>If you are using a public computer you should log out so nobody else can use your account.</p>

<h2>My swissbib</h2>
<h3>Saved searches</h3>
<p>When you are not logged in, your searches are saved until you close the browser. You can repeat a search or - if you log in - save it permanently.</p>

<h3>Favorites</h3>
<p>To mark a library as favorite, either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>" alt="Add to my favourites"> in the catalog.</p>

<h3>Lists</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="Add to list"> When you are logged in you can save titles on lists. 
<br/>Attention: if you make a new list while saving a title you have to click <i>Save</i> twice.</p>
            
<h3>Preferences</h3>
<p>Language of the catalog interface, number of titles per page</p>

<h3>Konto IDS Basel Bern</h3>
<p>Loan functions</p>
