<h1>Log in</h1>
<p>If you have a valid library card for IDS Basel Bern, log in as usual.</p>
<!--
<p>If you have a valid library card for any one of the following partner libraries, log in as usual:</p>
<ul class="list">
    <li>IDS Basel Bern</li>
    <li>IDS Luzern</li>
    <li>IDS St. Gallen</li>
    <li>NEBIS</li>
    <li>St. Galler Bibliotheksnetz</li>
</ul>
-->
<h3>No account yet?</h3>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0&CON_LNG=ENG"
      target="_blank"><?= $this->transEsc('Create New Account') ?></a></p>

<h3>Why log in?</h3>
<p>To use loan functions and lists and to save searches, favorites and preferences.</p>

<h3>Forgot your password?</h3>
<p>Please contact <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">your library</a>.
</p>

<h3>Profile</h3>
<p><a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE" target="_blank">Change password, address etc.</a></p>

<h3>Why log out?</h3>
<p>If you are using a public computer you should log out so nobody else can use your account.</p>

<h1>My swissbib</h1>
<h3>Saved searches</h3>
<p>When you are not logged in, your searches are saved until you close the browser. You can repeat a search or - if you
    log in - save it permanently.</p>

<h3>Favorites</h3>
<p>To mark a library as favorite, either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?= $this->basePath('themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="<?= $this->transEsc('mylibraries.add')?>"
        title="<?= $this->transEsc('mylibraries.add')?>"> in the catalog. In your search results, these libraries are marked with a <img
        src="<?= $this->basePath('/themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="Favorit"> and can be used as filters.</p>

<h3>Lists</h3>
<ul class="list">
    <li>When you are logged in you can save titles on lists by clicking on this sign: <br />
        <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
             alt="<?= $this->transEsc('memorizelistadd')?>"
             title="<?= $this->transEsc('memorizelistadd')?>">
    </li>
    <li>If you make a new list while saving a title you have to click <i>Save</i> twice.</li>
    <li>Public = List visible for everybody who knows the URL</li>
    <li>Private = List visible only for you</li>
</ul>

<h3>Preferences</h3>
<p>Language of the catalog interface, number of titles per page</p>

<h3>Account IDS Basel Bern</h3>
<p>Loan functions</p>
