<h1>My swissbib</h1>
<h2>Login</h2>

<p>Use your <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis" target="_blank">IDS account</a> for logging in.</p>


<h3>Why log in?</h3>
<p>To use loan, favorite libraries, lists, saved searches and saved preferences.</p>

<h3>Why log out?</h3>
<p>If you are using a public computer you should log out before you leave so nobody else can use your account.</p>


<h3>Forgot your password?</h3>
<p>Please contact <a href="http://www.swissbib.ch/libraries/index.html" target="_blank">your library</a>.</p>



<h2>Favorites</h2>
<p>To add a library to <i>Favorites</i> either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>" alt="Add to my favourites"> next to <i>Library Information</i>.
    <!--
	<br>Titles in those libraries and are marked with a <img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>">, score
	higher in relevancy and can be used as facets.
	-->
</p>