<h1>Save</h1>

<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="add to list"></td>
		<td>Add result/s to one of your <strong>lists</strong></td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
				 alt="get feed of new items matching this search"></td>
		<td><strong>Feed</strong> notification about new titles that match your search</td>
	</tr>
    <tr>
        <td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_perma.gif') ?>" alt="Cite"></td>
        <td><strong>Cite</strong> result/s</td>
    </tr>

    <tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>"
				 alt="Print"></td>
		<td><strong>Print</strong> result/s</td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>"
				 alt="Email this"></td>
		<td><strong>Email</strong> result/s</td>
		</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>"
				 alt="Export to ..."></td>
		<td><strong>Export</strong> result/s in different formats</td>
	</tr>
	</tbody>
</table>

<h2>Order</h2>

<div class="floatbox">
          
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/en/order.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/en/order_small.png') ?>" alt="Zoom"> 
     </a>
    
<ul class="list">
	<li>Click on the title.</li>
	<li>Choose a library.</li>
	<li>Click <i>Log in</i> below the library's name.</li> 
	<li>Click <i>Order</i> or <i>Order copy</i>.</li>
	<li>If you don't see these options the work can't be ordered online. A click on the Icon <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Library Info"> under Location shows you the opening times and address of the library.</li>
</ul>
    </div>


