<h1>Search</h1>

<h3>Combine</h3>

<table>
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Both terms are present</td>
    </tr>
    <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Both terms are present in the same field</td>
    </tr>
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>One of the terms is present</td>
    </tr>
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td><i>joyce</i> is present, but not <i>ulysses</i></td>
    </tr>
    <tr>
        <td>More complex searches</td>
        <td>See <a href="<?= $this->url('help-page', array('topic' => 'Advanced')) ?>">Help - Advanced search</a>.</td>
    </tr>
    </tbody>
</table>

<h3>Phrase search, using quotation marks</h3>

<table>
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>The words must be adjacent.</td>
    </tr>

    <tr>
        <td><i>"street art"~5</i></td>
        <td>Both terms must be present within 5 words.</td>
    </tr>
      <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>Call numbers</td>
    </tr>

    </tbody>
</table>

<h3>Truncation</h3>

<table>
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">replaces any number of letters</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>
      <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">replaces exactly one letter</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc.</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist ecc.</td>
    </tr>
    <tr>
        <td>~</td>
        <td>fuzzy search</td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij etc.</td>
    </tr>
    </tbody>
</table>

<h2>Results</h2>

<h3>Refine search</h3>
<p>Use the filters in the left hand column of your result list or <i>Advanced search</i>.</p>

<h3>Repeat or save search</h3>
<ul class="list">
    <li>Clicking on <i>Articles & more</i> will repeat your search in <a
            href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">Summon</a>.
    </li>
    <li><a href="<?= $this->url('search-history') ?>">My swissbib - Saved searches</a></li>
</ul>

<!--
<h3>Feed notification about new titles that match your search</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
        alt="get feed of new items matching this search"> Subscribe to feed</p>
-->

<h2>Full text</h2>
<p>Access to full text is often only possible from the university having licenced the content. Log in via VPN if you're not on campus.</p></p>

<h3>Articles &amp; more</h3>
<ul class="list">
    <li><i>get it</i> = link to full text</li>
    <li><img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>" alt="SFX Services"> = link to full text
        and/or other sfx services
    </li>
</ul>         
         
      