<h1>Search</h1>

<h3>Combine</h3>

<table>
    <tbody>
    <tr>
        <td>AND / OR / NOT</td>
        <td><i>art* OR kunst*</i></td>
        <td>The operators must be written in capital letters, default is AND</td>
    </tr>
    </tbody>
</table>


<h3>Phrase search, using quotation marks</h3>

<table>
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>= the words must be adjacent</td>
        </tr>
    
    <tr>
        <td><i>"street art"~5</i></td>
        <td>= must be present within 5 words</td>
           </tr>
    <tr>
        <td><i>"Sackville-West"</i></td>
        <td>also use quotation marks for double names and other hyphenated words</td>
    </tr>
    <tr>
        <td>"PZB E 62 2:6"</td>
        <td>in basic search, use quotation marks to search for call numbers</td>
    </tr>
    
    </tbody>
</table>


<h3>Truncation</h3>
<table>
    <tbody>
    <tr>
        <td>*</td>
        <td>replaces any number of letters</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>

    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">replaces exactly one letter</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc. **</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist etc. **</td>
    </tr>


    <tr>
        <td>~</td>
        <td>fuzzy search</td>
        <td><i>Copenhagen~</i></td>
        <td>Copenhagen, København, Kopenhagen etc. **</td>
    </tr>
    
      <tr>
        <td>~</td>
        <td>range search</td>
        <td><i>weather [2010 TO 2013]</i></td>
        <td>instead of <i>weather [2010 OR 2011 OR 2012 OR 2013]</i> **</td>
    </tr>
    
    </tbody>
</table>


<p> ** only for <i>Books & more</i>
</p>


<h2>Found too much?</h2>
<p>Use the facets in the left hand column and/or the <a href="<?=$this->url('search-advanced')?>">advanced search</a>.</p>

<h2>Found too little?</h2>
<ul class="list">
    <li>Clicking on <i>Articles & more</i> will repeat your search in <a href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">Summon</a>.</li>
    <li><a href="http://www.swissbib.ch" target="_blank">swissbib.ch</a> metacatalog of Swiss university libraries and the Swiss National Library</li>
    <li>Contact the information desk / interlibrary loan of <a href="http://www.swissbib.ch/libraries/index.html" target="_blank">your library</a>.</li>
</ul>

<h2>Don't know where to start?</h2>
<p>Try a null search (a search with no text in the searchbox), then use the facets to filter the results.</p>