<h1>Über swissbib</h1>

<p>swissbib Basel Bern ist der neue Katalog der Bibliotheken in Basel und Bern. Das Projekt wird getragen vom Verbund IDS Basel Bern und nutzt Infrastruktur und Know-How des gesamtschweizerischen Metakatalogs
    <a href="http://www.swissbib.ch" target="_blank">swissbib</a>.
</p>

<h3>Kontakt</h3>
<ul class="list">
    <li>Für Fragen zu Ihrem Konto wenden Sie sich bitte an <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">Ihre Bibliothek</a>.</li>
    <li>Für Fragen zu bestimmten Werken wenden Sie sich bitte an die <a href="<?= $this->url('libraries-index') ?>">besitzende Bibliothek</a>.</li>
    <li>Kontakt swissbib Basel Bern: E-Mail an <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oder Kommentar im <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a>.</li>
</ul>
                                
<h3>News</h3>
<p>In unserem <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a></p>

<h1>Datenbestand</h1>
<p>swissbib Basel Bern besteht aus zwei separaten Katalogen:</p>
<h3>Bücher &amp; mehr</h3>
<ul class="list">
<li>Bestände aller wissenschaftlichen Bibliotheken in <a href="<?= $this->url('libraries-index') ?>#nav_0">Basel</a> und <a href="<?= $this->url('libraries-index') ?>#nav_1">Bern</a> inkl. Nationalbibliothek sowie
    Fachhochschulbibliotheken</li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: retrodigitalisierte wissenschaftliche Zeitschriften
</li>  
</ul>    
<h3>Artikel &amp; mehr</h3>
<ul class="list">
    <li>In <i>Artikel &amp; mehr</i> finden Sie die Inhalte von zahlreichen e-Journals, e-Books und Fachdatenbanken, die von den Universitätsbibliotheken Basel bzw. Bern lizenziert wurden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext (Journal-Artikel, e-Book-Kapitel etc.) zugegriffen werden.</li>
    <li>Zusätzlich enthält <i>Artikel &amp; mehr</i> elektronische Ressourcen, die frei im Internet zugänglich sind.</li>
    <li>Titel, zu denen kein direkter Volltextzugang besteht, können Sie via <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>Bibliotheksservice</i> bei der Universitätsbibliothek Basel oder Bern bestellen.</li>
    <li>Für mehr Informationen siehe die <a href="http://www.proquest.com/products-services/The-Summon-Service.html" target="_blank">Seite des Anbieters ProQuest</a>.</li>
</ul>
