<h1>Über swissbib</h1>

<p>swissbib Basel Bern ist der neue Katalog der Bibliotheken in Basel und Bern. Das Projekt wird getragen vom Verbund
    IDS Basel Bern und nutzt Infrastruktur und Know-How des gesamtschweizerischen Metakatalogs <a
        href="http://www.swissbib.ch" target="_blank">swissbib</a>.
</p>

<h2>Kontakt</h2>
<p>Via Kommentar im <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a>, Mail an
    <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oder
    <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>
<p>Für Fragen zu Ihrem Konto wenden Sie sich bitte an <a href="http://www.swissbib.ch/libraries/placelist.html"
                                                         target="_blank">Ihre Bibliothek</a>.</p>
<p>Für Fragen zu bestimmten Werken wenden Sie sich bitte an die <a
        href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">besitzende Bibliothek</a>. Link aus dem
    Katalog: Klick auf das <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_info.gif') ?>"
                                alt="Bibliotheksinformation"> neben der Signatur.</p>

<h2>News</h2>
<p>In unserem <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a> und via <a
        href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a></p>

<h1>Datenbestand</h1>
<p>swissbib Basel Bern besteht aus zwei separaten Katalogen:</p>
<h2>Bücher &amp; mehr</h2>
<p>Bestände aller wissenschaftlichen Bibliotheken in Basel und Bern inkl. Nationalbibliothek sowie
    Fachhochschulbibliotheken.</p>
<p><strong>Region Basel</strong></p>
<ul class="list">
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a>, Bibliotheken Basel
        und Muttenz
    </li>
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken"
           target="_blank">Verbundbibliotheken
            IDS</a></li>
</ul>
<p><strong>Region Bern</strong></p>
<ul class="list">
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften</a></li>
    <li><a href="http://www.snb.ch/de/iabout/snb/address/id/snb_addresses_libraries" target="_blank">Schweizerische
            Nationalbank</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Schweizerische Nationalbibliothek</a>
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Verbundbibliotheken
            IDS</a></li>
    </li>
</ul>

<p><strong>retro.seals</strong></p>
<ul class="list">
    <li>Im Rahmen des Projekts <a href="http://retro.seals.ch" target="_blank">retro.seals.ch</a> werden
        wissenschaftliche Zeitschriften retrodigitalisiert und online zugänglich gemacht.
    </li>
</ul>


<h2>Artikel &amp; mehr</h2>
<ul class="list">
    <li>Wenn Sie ein Häkchen setzen bei <i>auch Artikel ohne Volltext</i> und <i>auch Zeitungsartikel</i>, durchsuchen Sie den gesamten Inhalt von <a href="http://www.serialssolutions.com/en/services/summon/content-and-coverage" target="_blank">Summon von
            SerialsSolutions</a>.
    </li>
    <li>Wenn Sie kein Häkchen setzen und sich im Netz der Universität Basel befinden - entweder auf dem Campus oder via VPN - sehen Sie die Inhalte aus Summon, die die Universität Basel lizenziert hat. Analog dazu für die Universität Bern. 
    </li>
    </ul>