<h1>Über swissbib</h1>

<h2>Kontakt</h2>
<p>Via Kommentar im <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a>, Mail an
    <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oder
    <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a>.</p>
<p>Für Fragen zu bestimmten Werken wenden Sie sich bitte an die <a href="http://www.swissbib.ch/libraries/index.html" target="_blank">besitzende Bibliothek</a> (Link <i>Bibliotheksinformation</i> im Katalog).</p>
<p>Für Fragen zu Ihrem Benutzerkonto wenden Sie sich bitte an <a href="http://www.swissbib.ch/libraries/index.html" target="_blank">Ihre Bibliothek</a>.</p>

<h2>News</h2>
<p>In unserem <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a> und via <a href="https://twitter.com/swissbibBB" target="_blank">@swissbibBB</a></p>

<h2>Datenbestand Bücher &amp; mehr</h2>
<!--
<p>Ausführlichere Informationen im <a
href="http://swissbib-baselbern.blogspot.com/2012/05/bucher-mehr-zwischen-ids-basel-bern-und.html">Blog</a>.
</p>
-->
<h3>Region Basel</h3>
<ul class="list">
    <li><a href="http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken" target="_blank">Verbundbibliotheken
        IDS</a></li>
    <li><a href="http://www.fhnw.ch/bibliothek" target="_blank">Fachhochschule Nordwestschweiz</a></li>
</ul>
<h3>Region Bern</h3>
<ul class="list">
    <li><a href="http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken" target="_blank">Verbundbibliotheken
        IDS</a></li>
    <li><a href="http://www.nb.admin.ch" target="_blank">Schweizerische Nationalbibliothek</a>
    </li>
    <li><a href="http://www.bewi.unibe.ch" target="_blank">Bibliothek exakte Wissenschaften Bern</a></li>
    <li><a href="http://www.bfh.ch/service/bibliotheken.html" target="_blank">Berner Fachhochschule</a></li>
    <!--
       <li><a href="http://www.swissbib.ch/libraries/placelist.html">Weitere Bibliotheken in Bern und Umgebung</a></li>
   -->

</ul>

<h3>Volltext online</h3>
<ul class="list">
    <li><a href="http://retro.seals.ch" target="_blank">RetroSeals</a>: <a
            href="http://baselbern.swissbib.ch/TouchPoint/start.do?Language=de&amp;View=bb&amp;Query=1810=%22retros%22 ">fast
        300'000 Artikel</a> aus digitalisierten Zeitschriften
    </li>
</ul>

<!-- 
<h3>IDS-Kurier</h3>
<ul class="list">
    <li><a href="http://www.ub.unibas.ch/ids-basel-bern/ids-kurierbibliotheken">IDS-Kurierbibliotheken</a> in Luzern, St. Gallen und Zürich</li>
  </ul>
-->

<h2>Datenbestand Artikel &amp; mehr</h2>
<ul class="list">
    <li><a href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">Summon von SerialsSolutions</a>
        <!--
<br />Wenn Sie nicht im Netz der Universität Basel oder Bern angemeldet sind, werden Ihnen davon nur die open
access Inhalte angezeigt.
-->
    </li>
</ul>