<h1>Erweiterte Suche</h1>
<h2>Wozu?</p>
<p>Komplexe Abfragen lassen sich nicht über die einfachen Suche formulieren.</p>
 
<p>Migration/Migrant*/migrazione + Gesundheit/health/santé/salute + Schweiz/Switzerland/Suisse/Svizzera:</p>

<p><img src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced1.png') ?>" alt="Screenshot Hilfeseite"></p>




<p>Migration/Migrant*/migrazione + Gesundheit/health/santé/salute, <strong>aber nicht</strong> Schweiz/Switzerland/Suisse/Svizzera:</p>

<p><img src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced2.png') ?>" alt="Screenshot Hilfeseite"></p>


<h2>Suche verfeinern: Sprache, Format, Bibliothek, Erscheinungsjahr</h2>
<h3>Anstatt Scrollen in den Pulldown-Listen</h3>
     <p>Klicken Sie in die Liste und schreiben Sie das Wort, zu dem Sie scrollen wollen, also z.B. <i>Englisch</i> im Pulldown <i>Sprachen</i>.</p>
