<h1>Erweiterte Suche</h1>
 <h2>Bücher &amp; mehr</h2>
 <p><strong>Mit allen Suchgruppen</strong><br/>
   Migration/Migrant*/migrazione + Gesundheit*/health/santé/salute + Schweiz*/Switzerland/swiss/Suisse/Svizzer*</p>
 <div class="floatbox">
    <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced1.png') ?>" class="help"><img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced1_small.png') ?>" alt="Screenshot Hilfeseite"/></a>
    <p>Klick aufs Bild für grössere Version</p>
    </div>

 <p><strong>Ohne die dritte Suchgruppe</strong><br/>
  Migration/Migrant*/migrazione + Gesundheit*/health/santé/salute, <strong>aber nicht</strong> Schweiz*/Switzerland/swiss/Suisse/Svizzer*</p>
<div class="floatbox">
    <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced2.png') ?>" class="help"><img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced2_small.png') ?>" alt="Screenshot Hilfeseite"/></a>
    <p>Klick aufs Bild für grössere Version</p>
    </div>

<h3>Suche verfeinern: Sprache, Format, Bibliothek, Erscheinungsjahr</h3>
<p>Anstatt Scrollen in den Pulldown-Listen: klicken Sie in die Liste und schreiben Sie das Wort, zu dem Sie scrollen wollen, also z.B. <i>Englisch</i> im Pulldown <i>Sprachen</i>.</p>

<h3>Suche wiederholen</h3>
     <p>Entweder mit <i>Suche verfeinern</i> über der Trefferliste oder über <i>My swissbib - Gespeicherte Suchen</i>.</p>
     
     <h3>Suche speichern</h3>
     <p><i>My swissbib - Gespeicherte Suchen</i>.</p>
     
     <h2>Artikel &amp; mehr</h2>
     <p>Wie <i>Bücher &amp; mehr</i>, aber z.T. stehen andere Felder/Facetten zur Auswahl, da <i>Artikel &amp; mehr</i> ein separater Datenbestand ist.</p> 