<h1>Erweiterte Suche</h1>
<h2>Bücher &amp; mehr</h2>
<h3>Mit allen Suchgruppen</h3>
<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced1.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced1_small.png') ?>" alt="Zoom"> 
     </a>
     <p>
        Migration*/Migrant*/migrazion*<br/><strong>und</strong><br/>Gesundheit*/health/santé/salute<br/><strong>und</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*
    </p>
</div>

<h3>Ohne die dritte Suchgruppe</h3>
<div class="floatbox">
     <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced2.png') ?>" class="help">
     <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/advanced2_small.png') ?>" alt="Zoom"> 
     </a>
     <p>Migration*/Migrant*/migrazion*<br/><strong>und</strong><br/>Gesundheit*/health/santé/salute<br/><strong>aber
            nicht</strong><br/>Schweiz*/Switzerland/swiss/Suisse*/Svizzer*</p>
</div>

<h3>Suche verfeinern: Sprache, Format, Bibliothek, Erscheinungsjahr</h3>
<p>Anstatt zu scrollen in den Pulldown-Listen: klicken Sie in die Liste und schreiben Sie das Wort, zu dem Sie scrollen
    wollen, also z.B. <i>Englisch</i> im Pulldown <i>Sprachen</i>.</p>

<h3>Suche wiederholen</h3>
<p>Entweder mit <i>Erweiterte Suche bearbeiten</i> über der Trefferliste oder über <i>My swissbib - Gespeicherte Suchen</i>.</p>

<h3>Suche speichern</h3>
<p><i>My swissbib - Gespeicherte Suchen</i>.</p>

<!--
<h3>Neue Einträge zu Ihrer Suche per Feed gemeldet bekommen</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>"
        alt="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"> Feed abonnieren</p>
-->
<h2>Artikel &amp; mehr</h2>
<p>Wie <i>Bücher &amp; mehr</i>, aber z.T. stehen andere Felder/Filter zur Auswahl, da <i>Artikel &amp; mehr</i> ein
    separater Datenbestand ist.</p>