<h1>FAQ</h1>

<h2>Suchen, Erweiterte Suche</h2>
<ul class="list">
      <li><strong>Suche mit Klammern liefert nicht das erwartete Resultat</strong>
        <br/>Suchen wie <i>a AND (b OR c)</i> bzw. <i>(a OR b) NOT c</i> werden nicht unterstützt. Benutzen Sie für solche Kombinationen mehrere Suchgruppen in der <i>Erweiterten Suche</i>.
    </li>
    </ul>

<h2>Trefferliste</h2>
<ul class="list">
    <li><strong>Was ist Sortieren nach Relevanz?</strong>
        <br/>Treffer in Haupttitel, Verfasser und Thema kommen vor solchen in anderen Feldern. Neue Publikationen werden vor älteren angezeigt.</li>
  <!--
  <li><strong>Der gesuchte Titel kommt viel zu weit unten bei der Sortierung nach Relevanz</strong>
        <br/>Wenn Sie wissen, dass es ein neues Werk ist, können Sie in der linken Spalte zuunterst auf Erscheinungsjahr 2000-2014 oder 2010-2014 einschränken oder hinter die Suchbegriffe <i>20??</i> bzw. <i>201?</i> schreiben (das ist etwas ungenauer als die Facette Erscheinungsjahr).<br/>Sie können uns den Fall auch gerne melden, Kontakt siehe unten. Die Sortierung in <i>Artikel &amp; mehr</i> ist von SerialsSolutions festgelegt und kann von uns nicht geändert werden.
    </li>
    -->
  </ul>

<h2>Bestellen</h2>
<ul class="list">
        <li><strong>Können Sie mir Werk xy senden?</strong>
            <br/>Wählen Sie die Bibliothek, bei der Sie bestellen möchten. Klicken Sie auf <i>Bestellen</i>. Wenn Postversand an Ihre Adresse möglich ist, können Sie die Option bei <i>Abholort</i> wählen.<br> 
                   </li>
       </ul>

<div class="example">Ist Ihre Frage nicht dabei? Melden Sie sich via <a href="http://swissbib-baselbern.blogspot.com" target="_blank">Blog</a>,
    <a href="mailto:swissbib-baselbern@unibas.ch">Email</a> oder <a href="https://twitter.com/swissbibBB">@swissbibBB</a>.
</div>
