<h1>FAQ</h1>
<h2>Suchen, Erweiterte Suche</h2>
<ul class="list">
    <li>
        <strong>Kann ich im Bestand einer bestimmten Bibliothek suchen?</strong>
        <br/>Entweder die gewünschte Bibliothek als Favorit markieren und in der Trefferliste <i>Suche verfeinern - Favoriten</i> benutzen oder <i>Erweiterte Suche - Suche verfeinern - Bibliothek</i>.
    </li>
    <li>
        <strong>Warum funktioniert der Link zum Volltext bei E-Books und Artikeln nicht immer?</strong>
        <br/>Der Zugang zum Volltext funktioniert oft nur aus dem Netz der Universität, die den Inhalt lizenziert hat. Melden Sie sich deshalb über VPN an, wenn Sie sich nicht auf dem Campus befinden.
    </li>
</ul>

<h2>Bestellen</h2>
<ul class="list">
    <li>
        <strong>Können Sie mir ein bestimmtes Werk per Post senden?</strong>
        <br/>Wählen Sie die Bibliothek, bei der Sie bestellen möchten. Klicken Sie auf <i>Bestellen</i>. Wenn Postversand an Ihre Adresse möglich ist, können Sie die Option bei <i>Abholort/Lieferadresse</i> wählen.
    </li>
</ul>

<h2>My swissbib</h2>
<ul class="list">
    <li>
        <strong>Was ist der kürzeste Weg zur Übersicht meiner Ausleihen?</strong>
        <br/><i>Anmelden</i>, dann auf <i>Konto: Ihr Name</i> klicken.
    </li>
</ul>

<h2>Ist Ihre Frage nicht dabei?</h2>
<ul class="list">
    <li>
        Für Fragen zu Ihrem Konto wenden Sie sich bitte an <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">Ihre Bibliothek</a>.
    </li>
    <li>
        Für Fragen zu bestimmten Werken wenden Sie sich bitte an die <a href="<?= $this->url('libraries-index') ?>">besitzende Bibliothek</a>.
        <br/>Link aus dem Katalog: Klicken Sie auf das Icon <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Bibliotheksinformation"> bei Standort.
    </li>
    <li>
        Kontakt swissbib Basel Bern: E-Mail an <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oder Kommentar im <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a>.
    </li>
</ul>