<h1>FAQ</h1>

<h2>Suchen, Erweiterte Suche</h2>
<ul class="list">
        <li><strong>Suche mit Klammern liefert nicht das erwartete Resultat</strong>
        <br/>Suchen wie <i>a AND (b OR c)</i> bzw. <i>(a OR b) NOT c</i> werden nicht unterstützt. Benutzen Sie für solche Kombinationen mehrere Suchgruppen in der <i>Erweiterten Suche</i>.
    </li>
    <!--
       <li><strong>Wie kann ich direkt in <i>Artikel & mehr</i> suchen?</strong>
        <br/><a href="http://baselbern.swissbib.ch/Summon/Search" target="_blank">baselbern.swissbib.ch/Summon/Search</a>
    </li>
    -->
 </ul>

<h2>Trefferliste</h2>
<ul class="list">
     <li><strong>Ist <i>Suche verfeinern - Thema</i> das selbe wie <i>Erweiterte Suche - Thema</i>?</strong>
        <br/>Suche nach <i>Thema</i> in der erweiterten Suche durchsucht alle Themenfelder, auch Spezialschlagworte einzelner Bibliotheken und Klassifikationen.<br/>Die Facette <i>Thema</i> zeigt nur kontrolliertes Vokabular (GND, MeSH, Thema BS/BE).</li>
    <li><strong>Was ist Sortieren nach Relevanz?</strong>
        <br/>Treffer in Haupttitel, Verfasser und Thema kommen vor solchen in anderen Feldern.</li>
   </ul>

<h2>Bestellen</h2>
<ul class="list">
        <li><strong>Können Sie mir Werk xy senden?</strong>
            <br/>Wählen Sie die Bibliothek, bei der Sie bestellen möchten. Klicken Sie auf <i>Bestellen</i>. Wenn Postversand an Ihre Adresse möglich ist, können Sie die Option bei <i>Abholort/Lieferadresse</i> wählen.<br> 
                   </li>
       </ul>

<div class="example">Ist Ihre Frage nicht dabei? Melden Sie sich via <a href="http://swissbib-baselbern.blogspot.com" target="_blank">Blog</a>,
    <a href="mailto:swissbib-baselbern@unibas.ch">Email</a> oder <a href="https://twitter.com/swissbibBB">@swissbibBB</a>.
</div>
