<h1>Anmelden, My swissbib</h1>
<h2>Anmelden</h2>
<p>Melden Sie sich mit Ihrer <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis" target="_blank">IDS-Kennung</a> an, die Sie auch bisher bereits für Bestellungen aus dem Katalog benutzen.</p>

<h3>Wozu anmelden?</h3>
<p>Ausleihfunktionen, Favoritbibliotheken, Merklisten, gespeicherte Suchen und gespeicherte Einstellungen stehen Ihnen nur zur Verfügung, wenn Sie sich anmelden.</p>

<h3>Passwort vergessen?</h3>
<p>Bitte von <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">Ihrer Bibliothek</a> zurücksetzen lassen.</p>

<h3>Wozu abmelden?</h3>
<p>An öffentlichen Computern sollten Sie sich abmelden, damit ausser Ihnen niemand Ihr Konto benutzen kann.</p>


<h2>My swissbib</h2>
<h3>Suchhistorie</h3>
<p>Wenn Sie nicht angemeldet sind, werden Ihre Suchen gespeichert, bis Sie den Browser schliessen. Sie können eine Suche nochmal ausführen oder - wenn Sie sich anmelden - längerfristig speichern.</p>

<h3>Favoriten</h3>
<p>Um eine Bibliothek als Favorit zu markieren, gehen Sie entweder über <i>My swissbib - Favoriten</i> oder Sie klicken auf das <img
            src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"
            alt="in meinen Favoriten anzeigen"> im Katalog.</p>

<h3>Merklisten</h3>
<p>Wenn Sie sich anmelden, können Sie Titel auf Merklisten speichern: <img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="in die Merkliste"><br/>
Achtung: wenn Sie einen Titel speichern und gleichzeitig eine neue Merkliste anlegen, müssen Sie zwei Mal <i>Speichern</i> klicken.</p>
            
<h3>Einstellungen</h3>
<p>Sprache der Katalogoberfläche, Anzahl Treffer pro Seite</p>

<h3>Konto IDS Basel Bern</h3>
<p>Ausleihfunktionen</p>

