<h1>Anmelden, My swissbib</h1>
<h2>Anmelden</h2>
<p>Melden Sie sich mit Ihrer <a href="http://www.ub.unibas.ch/ids-basel-bern/anmeldung-benutzerausweis" target="_blank">IDS-Kennung</a> an, die Sie auch bisher bereits für Bestellungen aus dem Katalog benutzen.</p>

<h3>Wozu anmelden?</h3>
<p>Ausleihfunktionen, Favoritbibliotheken, Merklisten, gespeicherte Suchen und gespeicherte Sucheinstellungen stehen Ihnen nur zur Verfügung, wenn Sie sich anmelden.</p>

<h3>Passwort vergessen?</h3>
<p>Bitte von <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">Ihrer Bibliothek</a> zurücksetzen lassen.</p>

<h3>Wozu abmelden?</h3>
<p>An öffentlichen Computern sollten Sie sich abmelden, damit ausser Ihnen niemand Ihr Konto benutzen kann.</p>


<h2>My swissbib</h2>
<h3>Suchhistorie</h3>
<p>...</p>

<h3>Merkliste</h3>
<p>...</p>

<h3>Favoriten</h3>
<p>Um eine Bibliothek als Favorit zu markieren, gehen Sie entweder über <i>My swissbib - Favoriten</i> oder Sie klicken auf das <img
            src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"
            alt="in meinen Favoriten anzeigen"> im Katalog.</p>

<h3>Sucheinstellungen</h3>
<p>...</p>

<h3>Konto Basel Bern</h3>
<p>...</p>

