<h1>Anmelden, My swissbib</h1>
<h2>Anmelden</h2>
<p>Wenn Sie im Besitz eines in folgenden Verbünden gültigen Benutzerausweises sind, melden Sie sich mit Ihrem üblichen Login an:</p>
<ul>
<li>IDS Basel Bern</li>
<li>IDS Luzern</li>
<li>IDS St. Gallen</li>
<li>NEBIS</li>
<li>St. Galler Bibliotheksnetz</li>
</ul>

<h3>Wozu anmelden?</h3>
<p>Ausleihfunktionen, Favoritbibliotheken, Merklisten, gespeicherte Suchen und gespeicherte Einstellungen stehen Ihnen nur zur Verfügung, wenn Sie sich anmelden.</p>

<h3>Passwort vergessen?</h3>
<p>Bitte von <a href="http://www.swissbib.ch/libraries/placelist.html" target="_blank">Ihrer Bibliothek</a> zurücksetzen lassen.</p>

<h3>Noch kein Konto?</h3>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0" target="_blank">Neues Konto anlegen</a></p>

<h3>Wozu abmelden?</h3>
<p>An öffentlichen Computern sollten Sie sich abmelden, damit ausser Ihnen niemand Ihr Konto benutzen kann.</p>


<h2>My swissbib</h2>
<h3>Gespeicherte Suchen</h3>
<p>Wenn Sie nicht angemeldet sind, werden Ihre Suchen gespeichert, bis Sie den Browser schliessen. Sie können eine Suche nochmal ausführen oder - wenn Sie sich anmelden - längerfristig speichern.</p>

<h3>Favoriten</h3>
<p>Um eine Bibliothek als Favorit zu markieren, benutzen Sie entweder <i>My swissbib - Favoriten</i> oder Sie klicken auf das <img
            src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_favorit.gif') ?>"
            alt="in meinen Favoriten anzeigen"> im Katalog.</p>

<h3>Merklisten</h3>
<p><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="Auf Merkliste speichern"> Wenn Sie sich anmelden, können Sie Titel auf Merklisten speichern.<br/>
Achtung: wenn Sie einen Titel speichern und gleichzeitig eine neue Merkliste anlegen, müssen Sie zwei Mal <i>Speichern</i> klicken.</p>
            
<h3>Einstellungen</h3>
<p>Sprache der Katalogoberfläche, Anzahl Treffer pro Seite</p>

<h3>Konto IDS Basel Bern</h3>
<p>Ausleihfunktionen</p>


