<h1>Speichern</h1>
<table>
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_notepad_add.gif') ?>" alt="in die Merkliste"></td>
		<td>Titel in einer Ihrer <strong>Merklisten</strong> speichern</td>
	</tr>
    <tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_rss.gif') ?>" alt="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"></td>
		<td>Neue Einträge zu Ihrer Suche per <strong>Feed</strong> gemeldet bekommen</td>
	</tr>
    <tr>
        <td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_perma.gif') ?>" alt="Zitieren"></td>
        <td>Treffer <strong>zitieren</strong></td>
    </tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_print.gif') ?>" alt="Drucken"></td>
		<td>Treffer <strong>drucken</strong></td>
	</tr>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_send.gif') ?>" alt="per Email versenden"></td>
		<td>Treffer als <strong>Email</strong> versenden</td>
	</tr>

	<tr>
		<td><img src="<?= $this->basePath('themes/swissbib/css/themes/orange/img/icon_pagefunctions_save.gif') ?>" alt="Exportieren nach ..."></td>
		<td>Treffer in verschiedenen Formaten <strong>exportieren</strong></td>
	</tr>
	</tbody>
</table>

<h2>Bestellen</h2>
<div class="floatbox">
    <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/order.png') ?>" class="help">
    <img class="image magnify" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/order_small.png') ?>" alt="Zoom">
     </a>
    <ul class="list">
        <li>Klicken Sie auf den Titel.</li>
	<li>Wählen Sie unter <i>Exemplare</i> eine Bibliothek aus.</li>
	<li>Klicken Sie <i>Anmelden</i> unter dem Bibliotheksnamen.</li>
	<li>Wählen Sie <i>Bestellen</i> oder <i>Kopie bestellen</i>.</li>
	<li>Wenn keine dieser Optionen angezeigt wird, kann das Werk nicht online bestellt werden. Klick auf das Icon
	<img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Bibliotheksinformation"> unterhalb Standort zeigt Öffnungszeiten und Adresse der Bibliothek.</li>
</ul>
    </div>