<h1>Suchen</h1>

<h3>Kombinieren</h3>

<table>
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Beide Begriffe kommen vor</td>
    </tr>
      <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Beide Begriffe kommen im selben Feld vor</td>
    </tr>  
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>Einer der beiden Begriffe kommt vor</td>
    </tr>  
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td><i>joyce</i> kommt vor, <i>ulysses</i> nicht</td>
    </tr>
    <tr>
        <td>Komplexere Kombinationen</td>
        <td>Siehe <a href="<?=$this->url('help-page', array('topic' => 'Advanced'))?>">Hilfe - Erweiterte Suche</a>.</td>
    </tr>
    </tbody>
</table>


<h3>Phrasensuche mit Anführungszeichen</h3>

<table>
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>Die beiden Wörter müssen direkt hintereinander stehen.</td>
    </tr>

    <tr>
        <td><i>"street art"~5</i></td>
        <td>Die beiden Wörter müssen innerhalb von 5 Wörtern Abstand vorkommen.</td>
    </tr>
    <tr>
        <td><i>"978-386-56619-6-8"</i></td>
        <td>In der einfachen Suche: ISBN, ISSN etc. in Anführungszeichen [folgt]</td>
    </tr>
    <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>In der einfachen Suche: Signatur in Anführungszeichen</td>
    </tr>

    </tbody>
</table>

<h3>Platzhalter</h3>
<table>
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">ersetzt beliebig viele Zeichen</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>


    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">ersetzt genau ein Zeichen</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc. **</td>
    </tr>
      <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist ecc. **</td>
    </tr>
  
    <tr>
        <td>~</td>
        <td>wenn Sie die genaue<br/>Schreibweise nicht kennen</td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij etc. **</td>
    </tr>

    <tr>
        <td>[ ]</td>
        <td>Bereichssuche</td>
        <td><i>Wetter [2010 TO 2013]</i></td>
        <td>anstatt <i>Wetter (2010 OR 2011 OR 2012 OR 2013)</i> **</td>
    </tr>
    </tbody>

</table>

<p>** nur für <i>Bücher & mehr</i>
</p>

<h2>Suche verfeinern</h2>
<p>Benutzen Sie die Facetten in der linken Spalte Ihrer Trefferliste.</p>

<h2>Suche wiederholen oder speichern</h2>
       <p><a href="<?=$this->url('search-history')?>">My swissbib - Gespeicherte Suchen</a></p>

<h2>Zu wenig gefunden?</h2>
<ul class="list">
    <li>Klick auf <i>Artikel & mehr</i> führt Ihre Suche im Bestand von <a href="http://www.serialssolutions.com/en/services/summon/content" target="_blank">Summon</a> aus.</li>
    <li><a href="http://www.swissbib.ch">swissbib.ch</a> Metakatalog der Schweizer Hochschulbibliotheken und der Schweizerischen Nationalbibliothek</li>
    <li>Wenden Sie sich an die Info/Fernleihe <a href="http://www.swissbib.ch/libraries/index.html" target="_blank">Ihrer Bibliothek</a>.</li>
</ul>
