<h1>Über swissbib</h1>
<h2>Zentral suchen - lokal bestellen</h2>
<p>Swissbib gibt Ihnen die Möglichkeit, die Bibliotheken der Schweizer Universitäten, Fachhochschulen, Forschungsanstalten und die Schweizerische Nationalbibliothek zentral zu durchsuchen.</p>

<p>Sie benutzen swissbib für die Suche und die Trefferanzeige. Weiter informiert sie swissbib, in welchen Bibliotheken das von Ihnen gefundene Werk vorhanden ist. Die Bestellung erfolgt dann direkt bei den Bibliotheken.</p>


<h2>Was ist enthalten?</h2>
<p>swissbib macht mit <b>19.4 Mio. Dokumenten</b> die Sammlungen von <a href="../libraries/index.html"><b>823 Bibliotheken, Mediotheken und Archiven</b></a> aus allen Landesteilen der Schweiz unter einer Oberfläche suchbar.</p>
<p>Das umfasst Bücher, Zeitschriften, Dissertationen, eBooks, Digitalisiertes, Filme (von VHS über DVDs zu Bluray), Musik (vom Notenblatt über Partituren, zu Schallplatten, CDs, DVDs), Hörbücher, Photos, Dias, Unterrichtsmaterialien, Sprachkurse und vieles mehr...</p>

<p>Folgende Verbünde und Bibliotheken sind bereits in swissbib enthalten:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22sbt%22') ?>" target="_blank">Sistema bibliotecario ticinese (32 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idsbb%22') ?>" target="_blank">IDS Basel/Bern (193 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idslu%22') ?>" target="_blank">IDS Luzern (30 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22snl%22') ?>" target="_blank">Schweizerische Nationalbibliothek (1 Bibliothek)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22idss*%22') ?>" target="_blank">IDS St. Gallen (36 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22nebis%22') ?>" target="_blank">NEBIS (172 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22rero%22') ?>" target="_blank">RERO Westschweizer Bibliotheksverbund (236 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22sgbn%22') ?>" target="_blank">St. Galler Bibliotheksnetz (52 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22bgr%22') ?>" target="_blank">Bibliotheksverbund Graubünden (26 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22abn%22') ?>" target="_blank">Aargauer Bibliotheksnetz (25 Bibliotheken)</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22alex%22') ?>" target="_blank">Bibliotheksverbund Alexandria (20 Bibliotheken)</a></li>
</ul>

<p>2013 werden weitere Verbünde und Bibliotheken in swissbib verfügbar werden:</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek (25 Bibliotheken)</li>
</ul>

<p>Ausserdem bietet swissbib weitere Datenquellen an:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ccsa%22') ?>" target="_blank">Catalogue collectif suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22charch02%22') ?>" target="_blank">Digitalisate des Schweizerischen Literaturarchives</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22charch01%22') ?>" target="_blank">Digitalisate des Eidgenössischen Archivs für Denkmalpflege</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22retros%22') ?>" target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22zora%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>2013 werden folgende Datenquellen hinzukommen:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>serval</li>
</ul>

<h2>Wie aktuell ist swissbib?</h2>
<p>Die Daten in swissbib werden täglich aktualisiert.</p>

<h2>Feedback erwünscht</h2>
<p>Swissbib wird laufend weiterentwickelt. Um swissbib zu verbessern und perfekter zu machen, sind wir auf Hinweise und Vorschläge angewiesen. Auf jeder Seite finden Sie im Menü den Bereich Feedback, dahinter verbirgt sich ein Forum, wo Sie ihre Vorschläge einbringen oder auch mit Ihrer Stimme einer bereits bestehenden Idee mehr Gewicht verleihen können.</p>


<h2>Was wird 2013 verbessert?</h2>
<p>Folgende Bereiche werden im Laufe von 2013 überarbeitet und verbessert werden. Die Aufzählung ist keinesfalls abschliessend:</p>

<ul class="list">
    <li>Die Bestellung direkt in swissbib</li>
    <li>Ein Benutzerkonto für die Schweizer Bibliotheken</li>
    <li>Bessere Datenaufbereitung zur weiteren Vereinfachung der Suche</li>
    <li>Einbinden weiterer Wörterbücher für eine komfortablere Suche</li>
</ul>

<h2>Projekt swissbib</h2>
<p>swissbib ist ein Kooperationsprojekt der Schweizer Universitätsbibliotheken und der Nationalbibliothek unter der Federführung der Universitätsbibliothek Basel im Rahmen des Innovations- und Kooperationsprojekts der Schweizer Hochschulen &raquo;E-lib.ch: Elektronische Bibliothek Schweiz&laquo;.</p>

<p>Gefördert wird swissbib während seiner Laufzeit von 2008 bis 2013 durch die Schweizerische Universitätskonferenz (SUK).</p>