<h1>Über swissbib</h1>
<h2>Zentral suchen - lokal bestellen</h2>
<p>Swissbib gibt Ihnen die Möglichkeit, die Bibliotheken der Schweizer Universitäten, Fachhochschulen,
    Forschungsanstalten und die Schweizerische Nationalbibliothek zentral zu durchsuchen.</p>

<p>Sie benutzen swissbib für die Suche und die Trefferanzeige. Weiter informiert sie swissbib, in welchen Bibliotheken
    das von Ihnen gefundene Werk vorhanden ist. Die Bestellung erfolgt dann direkt bei den Bibliotheken.</p>


<h2>Was ist enthalten?</h2>
<p>swissbib macht mit <b>20 Mio. Dokumenten</b> die Sammlungen von <a href="../Libraries"><b>900
            Bibliotheken, Mediotheken und Archiven</b></a> aus allen Landesteilen der Schweiz unter einer Oberfläche
    suchbar.</p>
<p>Das umfasst Bücher, Zeitschriften, Dissertationen, eBooks, Digitalisiertes, Filme (von VHS über DVDs zu Bluray),
    Musik (vom Notenblatt über Partituren, zu Schallplatten, CDs, DVDs), Hörbücher, Photos, Dias,
    Unterrichtsmaterialien, Sprachkurse und vieles mehr...</p>

<p>Folgende Verbünde und Bibliotheken sind bereits in swissbib enthalten:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SBT%22') ?>" target="_blank">Sistema
            bibliotecario ticinese </a></li>
    <!-- (32 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSBB%22') ?>" target="_blank">IDS Basel/Bern</a>
    </li>
    <!-- (193 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSLU%22') ?>" target="_blank">IDS Luzern</a>
    </li>
    <!-- (30  Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SNL%22') ?>" target="_blank">Schweizerische
            Nationalbibliothek</a></li>
    <!-- (1 Bibliothek) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSS*%22') ?>" target="_blank">IDS St. Gallen</a>
    </li>
    <!-- (36 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22NEBIS%22') ?>" target="_blank">NEBIS</a></li>
    <!-- (172 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RERO%22') ?>" target="_blank">RERO Westschweizer
            Bibliotheksverbund</a></li>
    <!--  (236 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SGBN%22') ?>" target="_blank">St. Galler
            Bibliotheksnetz</a></li>
    <!--  (52 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22BGR%22') ?>" target="_blank">Bibliotheksverbund
            Graubünden</a></li>
    <!-- (26 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ABN%22') ?>" target="_blank">Aargauer
            Bibliotheksnetz</a></li>
    <!-- (25 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ALEX%22') ?>" target="_blank">Bibliotheksverbund
            Alexandria</a></li>
    <!-- (20 Bibliotheken) -->
</ul>

<p>2014 werden weitere Verbünde und Bibliotheken in swissbib verfügbar werden:</p>
<ul class="list">
    <li>Liechtensteinische Landesbibliothek</li>
    <!-- (25 Bibliotheken) -->
</ul>

<p>Ausserdem bietet swissbib weitere Datenquellen an:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CCSA%22') ?>" target="_blank">Catalogue collectif
            suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH02%22') ?>" target="_blank">Digitalisate
            des Schweizerischen Literaturarchives</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CHARCH01%22') ?>" target="_blank">Digitalisate
            des Eidgenössischen Archivs für Denkmalpflege</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RETROS%22') ?>"
           target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ZORA%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>2014 werden folgende Datenquellen hinzukommen:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>serval</li>
</ul>

<h2>Wie aktuell ist swissbib?</h2>
<p>Die Daten in swissbib werden täglich aktualisiert.</p>

<h2>Feedback erwünscht</h2>
<p>Swissbib wird laufend weiterentwickelt. Um swissbib zu verbessern und perfekter zu machen, sind wir auf Hinweise und
    Vorschläge angewiesen. Auf jeder Seite finden Sie im Menü den Bereich Feedback, dahinter verbirgt sich ein Forum, wo
    Sie ihre Vorschläge einbringen oder auch mit Ihrer Stimme einer bereits bestehenden Idee mehr Gewicht verleihen
    können.</p>


<h2>Was wird 2014 verbessert?</h2>
<p>Folgende Bereiche werden im Laufe von 2014 überarbeitet und verbessert werden. Die Aufzählung ist keinesfalls
    abschliessend:</p>

<ul class="list">
    <li>Die Bestellung direkt in swissbib - aktuell im internen Test</li>
    <li>Ein Benutzerkonto für die Schweizer Bibliotheken - aktuell im internen Test</li>
    <li>Einbinden weiterer Wörterbücher für eine komfortablere Suche</li>
</ul>

<h2>Projekt swissbib</h2>
<p>swissbib ist ein Kooperationsprojekt der Schweizer Universitätsbibliotheken und der Nationalbibliothek unter der
    Federführung der Universitätsbibliothek Basel. Es lief von 2008 bis 2013 im Rahmen des Innovations- und
    Kooperationsprojekts der Schweizer
    Hochschulen &raquo;E-lib.ch: Elektronische Bibliothek Schweiz&laquo;. Ab 2014 läuft swissbib unter dem
    Rahmenprogramm 2 der CRUS.</p>

<p>Gefördert wird swissbib während seiner Laufzeit von 2008 bis 2013 durch die Schweizerische Universitätskonferenz
    (SUK).</p>