<h2>Projekt swissbib</h2>
<p>swissbib ist ein Kooperationsprojekt der Schweizer Universitätsbibliotheken und der Nationalbibliothek unter der Federführung der Universitätsbibliothek Basel im Rahmen des Innovations- und Kooperationsprojekts der Schweizer Hochschulen &raquo;E-lib.ch: Elektronische Bibliothek Schweiz&laquo;.</p>

<p>Gefördert wird swissbib während seiner Laufzeit von 2008 bis 2013 durch die Schweizerische Universitätskonferenz (SUK).</p>

<h2>Was heisst nun Kooperationsprojekt?</h2>
<p>Die folgenden Bibliotheken und Verbünde haben sich massgeblich auf verschiedenen Ebenen an swissbib beteiligt. Ohne sie wäre swissbib nicht möglich:</p>

<h3>Datenlieferung</h3>
<ul class="list">
    <li>Alle Teilverbünde des IDS - Informationsverbund Deutschschweiz</li>
    <li>Schweizerische Nationalbibliothek</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>sbt - Sistema bibliotecario ticinese</li>
    <li>Bibliotheksverbund Alexandria</li>
</ul>

<h3>Funktionstests</h3>
<p>Die Funktionstests wurden durch ein Team der UB Basel organisiert und geleitet. Folgende Verbünde und Bibliotheken haben daran teilgenommen:</p>
<ul class="list">
    <li>Bibliothekarinnen und Bibliothekare aus dem Bereich Benutzung und Katalogisierung der IDS Verbünde Luzern, St. Gallen, Basel/Bern, Zürich Universität und Zürich Zentralbibliothek</li>
    <li>Bibliothekarinnen und Bibliothekare aus dem Bereich Benutzung und Katalogisierung der Schweizerische Nationalbibliothek</li>
    <li>Mitglieder der COPAC und Katalogisierung von RERO centrale</li>
    <li>Biblioteca Universitaria di Lugano</li>
</ul>

<h3>Usability-Tests</h3>
<p>Die Usability der Oberfläche wurde durch zwei Fokusgruppen und eine Expertengruppe evaluiert. Dies geschah im Rahmen der E-Lib.ch-Projekte <a href="http://www.e-lib.ch/accept.html" target="_blank">ACCEPT</a> und <a href="http://www.e-lib.ch/eval.html" target="_blank">ElibEval</a>.</p>

<h3>Übersetzung</h3>
<p>Die französische und italienische Version der Oberfläche wurde den Schweizer Erfordernissen angepasst. Ebenso werden die Inhalte auf swissbib übersetzt.</p>
<ul class="list">
    <li>Französische Oberfläche: Mitglieder der COPAC von RERO</li>
    <li>Französische Inhaltselemente: UB Basel</li>
    <li>Italienische Oberfläche und Inhaltselemente: Biblioteca Universitaria Lugano</li>
</ul>

<h2>Design und Konzept der Webseite</h2>
<p>Das Design und Konzept der Webseite wurde durch <a href="http://www.nose.ch" target="_blank">Nose Design AG</a> erstellt.</p>

<h2>Die Software-Lösung hinter swissbib</h2>
<p>Die Software-Lösung für swissbib wird von <a href="http://www.oclc.org/" target="_blank">OCLC</a> bereitgestellt und besteht aus den drei Komponenten <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS</a>, <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr</a> und <a href="http://www.oclc.org/de/de/touchpoint/default.htm" target="_blank">TouchPoint</a>.</p>