<?
// Set page title
$this->headTitle($this->translate('Search Home'));

// Set default value if necessary
//    if (!isset($this->searchClassId)) {
//        $this->searchClassId = 'Solr';
//    }

// Load search actions and settings (if any)
//    $options = $this->searchOptions($this->searchClassId);
//    $basicSearch = $options->getSearchAction();
//    $advSearch = $options->getAdvancedSearchAction();

?>

<div id="col3" class="content">
    <div id="col3_content" class="clearfix">
        <!-- begin: content -->
        <div id="content">
            <h1 class="hidden"><?= $this->transEsc('start.teaser.description.chb') ?></h1>
            <!-- begin: teaser -->
            <div class="teaser">
                <!-- col -->
                <div class="c50l">
                    <div class="box h150 bmright">
                        <?= $this->translate('start.teaser.left.jus') ?>
                        <ul class="actions">
                            <li class="right">
                                <a href="<?= $this->url('help-page', array('topic' => 'jusbib')); ?>"
                                   class="linkbutton primary icon_goto_primary"
                                   title="<?= $this->transEsc('more') ?>"><span><?= $this->transEsc('start.teaser.more') ?></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- col -->
                <div class="c50l">
                    <div class="box h150 bmleft">
                        <?= $this->translate('start.teaser.right.jus') ?>
                        <ul class="actions">
                            <li class="right">
                                <a href="<?= $this->url('help-page', array('topic' => 'jus_3steps')); ?>"
                                   class="linkbutton primary icon_goto_primary"
                                   title="<?= $this->transEsc('more') ?>"><span><?= $this->transEsc('start.teaser.more') ?></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- end: teaser -->
            <div style="position: absolute; bottom: 0px; right: 0px;" class="teaser">
                <a target="_blank" href="http://www.urz.unibas.ch/"><img
                        src="<?= $this->basePath('themes/swissbib/images/poweredby_unibasel.gif') ?>"></a>
            </div>
        </div>
        <!-- end: content -->
    </div>
    <div id="ie_clearing">
        &nbsp;
    </div>
</div>