<h2>Jusbib in tre mosse</h2>
<p>Jusbib offre un accesso rapido, semplice e completo all’informazione scientifica in Svizzera, tanto sotto forma di
    libri, riviste, giornali, musica, immagini e carte geografiche che in formato elettronico.</p>
<p>Jusbib permette di effettuare una ricerca simultanea nei cataloghi delle biblioteche universitarie svizzere e della
    Biblioteca nazionale.
</p>

<p>Noi vi assistiamo nella ricerca di informazioni e facilitiamo l’accesso ai documenti di cui avete bisogno.</p>

<ol class="list">
    <li><a href="#search">Cercare</a></li>
    <li><a href="#refine">Trovare</a></li>
    <li><a href="#locate">Scegliere e accedere</a></li>
</ol>

<h2><a name="search"></a>Cercare</h2>
<div class="floatbox">
    <img class="small nb" src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/suche_klein.png') ?>"
         alt="Suchen"/>

    <p>Inserite una o più parole nella maschera di ricerca.</p>

    <p><em>Usando il segno di asterisco <strong>*</strong>, è possibile troncare o sostituire <strong>un numero
                qualsiasi</strong> di caratteri, ad esempio per la ricerca di termini con differenti terminazioni (oper*
            per 'Oper', 'Opern', 'opéra', 'opéras', 'opera', 'opere' ecc.).</em></p>

    <p><em>Il punto di domanda <strong>?</strong> sostituisce <strong>un singolo</strong> carattere e permette di
            ricercare parole la cui ortografia varia (es. wom?n per 'woman' e per 'women').</em></p>

    <p><em>Inserendo i termini tra virgolette <strong>“...“</strong>, è possibile ricercarli nell’ordine esatto
            dell’inserimento (es. “Don Giovanni“).</em></p>
</div>

<h2><a name="refine"></a>Trovare</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/anpassung_klein.png') ?>"
         alt="Approfondire"/>

    <h3>Filtri</h3>

    <p>Approfondire la ricerca utilizzando i filtri sulla sinistra della lista dei risultati.</p>

    <p>Alla ricerca di <strong>un determinato autore</strong>? <br/>La ricerca di un nome di persona darà come risultato
        una lista di documenti che lo hanno come autore, ma pure di documenti che ne trattano. Allo scopo di ottenere
        unicamente gli scritti dell’autore cercato, è opportuno selezionare il suo nome nella lista del filtro <strong>Autore</strong>.
    </p>

    <p>Alla ricerca di <strong>un determinato soggetto</strong>?<br/>E’ opportuno selezionare un termine <strong>che
            descrive l'argomento</strong> della ricerca nella lista del filtro <strong>Soggetto</strong>.</p>
</div>

<h3>Ordinare i risultati</h3>
<p>L’ordinamento per <strong>anno (dal più recente)</strong> non vi mostra quanto cercato? Modificate l’ordine di
    apparizione dei
    risultati - p.e. &raquo;pertinenza&laquo;.</p>

<h3>Dove si trova il documento?</h3>
<p>Il punto interrogativo <img src="<?= $this->basePath('themes/jusbib/images/icon_info.gif') ?>" alt="Info"/> a
    destra di ciascun titolo permette di vedere quale biblioteca è in possesso dell’esemplare. Cliccando sul nome della
    biblioteca, vi si accede direttamente.</p>

<h2><a name="locate"></a>Scegliere e accedere</h2>
<div class="floatbox">
    <img class="small nb"
         src="<?= $this->basePath('themes/jusbib/images/Help/de/3_steps/bestellen_klein.png') ?>"
         alt="Scegliere e accedere">

    <p>Cliccando sul titolo desiderato, si ottiene la visualizzazione completa di tutti i dati bibliografici. Al di
        sotto della notizia bibliografica si trova l’elenco delle biblioteche che rendono possibile l'accesso al
        documento. Cliccando sul simbolo del cuore <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_miniaction_favorite_add.gif') ?>"
            alt="add favourite"/>, è anche possibile definire alcune biblioteche come <strong>preferite</strong>, in
        modo che appaiano in cima alla lista per le successive ricerche.</p>

    <p>Cliccando sul nome della biblioteca consente di visualizzare localizzazione e segnatura del documento. Nel caso
        di molte biblioteche, è anche possibile sapere se è disponibile <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_online.gif') ?>"
            alt="Available"/> oppure già in prestito <img
            src="<?= $this->basePath('themes/jusbib/images/Help/icn/icon_lending_notavailable.gif') ?>"
            alt="Not Available"/>.</p>

    <h3>Prenotazione</h3>
    <ul class="list">
        <!-- <li>Dokumente des IDS Basel/Bern können Sie <strong>direkt in jusbib</strong> bestellen oder reservieren.</li>
        <li>Die Dokumente aller anderen Bibliotheken müssen Sie <strong>direkt über die jeweilige
                Bibliothek
                beziehen</strong>. Für den Zugriff bzw. die Bestellung/Reservation klicken Sie auf den Link <strong>zum
                Bestand</strong> und wechseln zur besitzenden Bibliothek und melden sich erneut an.
        </li> -->
        <li>
            jusbib non consente di ordinare o direttamente prendere in prestito un titolo. Per accedere a un
            documento, oppure richiederlo o prenotarlo, occorre utilizzare il collegamento &raquo;al catalogo&laquo; e
            identificarsi presso la biblioteca attraverso il catalogo locale.
        </li>
    </ul>
</div>

<!-- <h2>Brauchen Sie weitere Informationen?</h2>
<p>Ausführlichere Informationen zur Benutzung von jusbib stehen Ihnen auf unserer erweiterten Hilfe-Seite zur
    Verfügung.</p>-->
