<h2>Jusbib</h2>

<p>Jusbib è un meta-catalogo di dati bibliografici provenienti da biblioteche giuridiche svizzere ed altre collezioni di
    dati giuridici. L'interfaccia e le funzionalità di ricerca di Jusbib corrispondono a quelle di Swissbib.</p>

<p>Inoltre, i dati possono essere consultati tramite una classificazione per materia di diritto; la classificazione
    scelta è il <a href="http://www.isdc.ch/d2wfiles/document/5441/4018/0/Plan%20syst%20I(ISDC).pdf" target="_blank">piano
        sistematico plurilingue dell'Istituto svizzero di diritto comparato</a>.</p>

<p>Il progetto Jusbib è stato iniziato dall'Associazione delle biblioteche giuridiche svizzere ed è realizzato in
    stretta collaborazione con il gruppo di progetti Swissbib. Viene sostenuto con un contributo finanziario
    dall'Ufficio federale della Giustizia e dall'associazione <a href="http://www.svri.ch/index.html" target="_blank">eJustice.CH
        (sito internet in tedesco solo)</a>.</p>
